### ISSUE TITLE
Error messages comparing objects

### ISSUE THREAD

**Issue by DanielHeath** [facebook/flow#2256] opened 2016-08-16 02:01 UTC
I'm trying to typecheck some react-redux code (using the flow-typed repo definitions).

Somehow the props aren't lining up correctly (I'm fairly sure that's my mistake.

However, the resulting error message is:

```
102: const Foo: Class<React.Component<*, BaseProps, *>> = connect(mapStateToProps, mapDispatchToProps)(SignInFormContainer);
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ type parameter `P` of function call. This type is incompatible with
102: const Foo: Class<React.Component<*, BaseProps, *>> = connect(mapStateToProps, mapDispatchToProps)(SignInFormContainer);
                                         ^^^^^^^^^ object type
```

which gives no information about _how_ those types are incompatible, or what `P` has been inferred as in this case. 
Worse yet, `connect` has an intersection type across a number of definitions, and most of them have a type parameter named `P` (no indication which one has been used).

**Comment by thejameskyle** [comment] 2016-08-18 16:48
Sorry about that @DanielHeath, that error message definitely sucks.

I've run into a handful of those. I debug them in similar fashion I do with Babel issues. Basically create a new branch and slowly chunk away at the irrelevant bits until all you're left with is a tiny reproduction case which you can then think about abstractly and should be much easier to fix.

If you want to share the reduced case with us it would be helpful for improving error messages for everyone in the future.

**Comment by samwgoldman** [comment] 2017-09-19 23:28
Unfortunately, there is no repro so I can't show you what the current error looks like, but we've recently added a lot of context to these error messages. Going to close this, but reopen if you have a repro with a bad error message.

**Closed by samwgoldman** 2017-09-19 23:28 UTC
Labels: error messages
