### ISSUE TITLE
mixed type in props of React Element. Number is incompatible with string

### ISSUE THREAD

**Issue by n06rin** [facebook/flow#4575] opened 2017-08-11 09:53 UTC
when we set one props to number | string I'm get error.

[react element example on try flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjYqfOLMAcn0pqYG50q4A7AZ2IBlAI4BXCqzABeMAAoA3ggwATQgAsZzAIwAGHAA8mAGjA94+LUwDm+CgE8TYQfZhlTVGBX78AchSwyAF8ALjAFVDAwZTV1AH4wwXwMXmswAB8wXjEsACMyfGNIszgLBOdCZNSiqM9vPwCycqSU6xqK1yawhSCioIBKGQA+eWKAHhUMADdi2q8ff0DpBTqFxqDZjrdliKi96NUNdv31MgxrdUIwmKPNqNzqAGtbODFeFQBhUoIw8wJjvYAOmBLjcAKCGyiwCGqH6XFQZAMeCIYBUZCgFDEMGE4kkZC4QA)

But with one simple [function](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzHwFMCAxAV2wzAF4wAKAQwC4wCAnAS2wHMwAPmGwUAtgCNiHAJRsAbnC4ATOgD4wAb1QBfdCXJUMDAORNj0gNyp9+StQYAmS6iA) it works correctly.

Maybe I'm doing something wrong?

**Comment by jcready** [comment] 2017-08-11 14:56
Oddly enough [this works](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjYqfOLMAcn0pqYG50q4A7AZ2IBlAI4BXCqzABeMAAoc9HPwBcYAN6owYBBgAmhABYB+NYPwZeAczAAfMLzFYARmXwAaLWB7x8psOaWVp7aVDAU-PwAchRYZP6B1iEBhACeMPFq6gC+qNkAlDIAfBpePALE6jr6RjLMAIwADDgAHkzu3nC+dUxW+BSp7SnpZB1hEdGxZGDZdYpwyl6shGL4vPJe2gA8ehgAbpva3uGRMXHS6uOnU7lHR4IjF5p3d7oGhmpvRskvYIZkGCshkInxqhh+L2c1AA1n04GJeHoAMJdAhqHwECF3AB0uIeGSxM1uR2ARS8+Ty6DILTwRDAejIUAoYhgwnEkjIHCAA):

```js
/* @flow */

import React from 'react';

const Square = (props: {
  width?: string | number,
  color?: string,
  className?: string,
  style?: {}
}) => {
  const { width = '10px', color = 'gray', style, className } = props
  return (
    <div
      className={className}
      style={{
        width: width,
        height: width,
        backgroundColor: color,
        ...style,
      }}
    />
  )
}

export default Square;
```

**Comment by mwalkerwells** [comment] 2017-08-14 01:45
This should be titled, "**Unable to set a subtype default value (function input object destructure)**".

Here is a more simple example:

```js
const foo = ({ bar = 'a' }: { bar: number | string }): void => {}
```
```js
1: const foo = ({ bar = 'a' }: { bar: number | string }): void => {}
                  ^ number. This type is incompatible with
1: const foo = ({ bar = 'a' }: { bar: number | string }): void => {}
                  ^ string
1: const foo = ({ bar = 'a' }: { bar: number | string }): void => {}
                  ^ string. This type is incompatible with
1: const foo = ({ bar = 'a' }: { bar: number | string }): void => {}
                  ^ number
1: const foo = ({ bar = 'a' }: { bar: number | string }): void => {}
                        ^ string. This type is incompatible with
1: const foo = ({ bar = 'a' }: { bar: number | string }): void => {}
                  ^ number
```

**Comment by mwalkerwells** [comment] 2017-08-14 01:50
It seems to only be an issue for union subtypes (``string`` <: ``string | number``) & not classes and intersections.

```js
const fooUnionExample = ({ bar = 'a' }: { bar: number | string }): void => {}

declare class Animal {}
declare class Dog extends Animal {}

const fooClassExample = ({ bar = new Dog() }: { bar: Animal }): void => {}

declare var numberAndString: number & string
const fooIntersectionExample = ({ bar = numberAndString }: { bar: number }): void => {}
```

**Comment by mwalkerwells** [comment] 2017-08-14 01:54
https://github.com/facebook/flow/issues/4569

**Comment by goodmind** [comment] 2019-05-29 07:07
Duplicate of #2093

**Closed by goodmind** 2019-05-29 07:07 UTC
Labels: Typing: unions/intersections, destructuring
