### ISSUE TITLE
How to: Object property chaining 

### ISSUE THREAD

**Issue by shanemileham** [facebook/flow#2020] opened 2016-06-30 21:49 UTC
I'm trying to use Flow, but I keep getting the "Not covered by Flow" warning, so my code is mostly underlined. I checked the Flow documentation, but it wasn't helpful regarding object property chaining, so **how do you get something like this to work?**

![image](https://cloud.githubusercontent.com/assets/3304303/16505429/c9201144-3ed1-11e6-8a83-4f93ce559c39.png)

**Comment by shanemileham** [comment] 2016-06-30 21:54
And if there's a better place to ask such a question, please let me know. I couldn't find any tutorials or other articles online from preliminary searches.

**Comment by vkurchatkin** [comment] 2016-06-30 23:39
You shouldn't use `Object` type if you want flow coverage, use concrete types

**Comment by shanemileham** [comment] 2016-07-01 00:19
A few follow up questions then:
- If I don't know what sails.models is (because it's part of the framework), do I just leave it as an `Object`?
- How do I write the top line then?
- Flow knows `users` is `Object[]`, and it knows `waiting` is a `Number`, so why is that not covered?
- What's wrong with the `retData` line? Or am I not supposed to use `Object` in that case too?

Here is what I modified after your comment, but there are still quite a few underlines:
![image](https://cloud.githubusercontent.com/assets/3304303/16508326/b7021be6-3ee6-11e6-9c4d-b3382c372413.png)

**Comment by vkurchatkin** [comment] 2016-07-01 00:33
> do I just leave it as an Object

You can, but it's better to cast it's property to concrete type as soon as possible:

```js
const User: Model<UserType> = sails.modules.user;
```

If you provide proper declaration for `Model` type, the whole callback will be covered and won't need any annotations

> Flow knows users is Object[], and it knows waiting is a Number, so why is that not covered

Not sure, might be a bug

**Comment by calebmer** [comment] 2017-07-27 15:41
Closing since this issue hasn’t seen a lot of activity. Sorry about that 😣

Please reopen with a reproduction on https://flow.org/try if you are still having issues!

**Closed by calebmer** 2017-07-27 15:41 UTC
