### ISSUE TITLE
Disjoint unions and destructurization of functions' arguments 

### ISSUE THREAD

**Issue by apsavin** [facebook/flow#5420] opened 2017-11-28 09:23 UTC
```
type ArgType = {| a: string, b?: void |} | {| b: number, a?: void |};

function a({ a, b }: ArgType): string {
  return typeof a === 'string' ? a : b.toString();
}
```

**Expected result**
no errors

**Actual result**
```
3: function a({ a, b }: ArgType): string {
                ^ string. This type is incompatible with
3: function a({ a, b }: ArgType): string {
                ^ undefined
3: function a({ a, b }: ArgType): string {
                ^ undefined. This type is incompatible with
3: function a({ a, b }: ArgType): string {
                ^ string
3: function a({ a, b }: ArgType): string {
                   ^ number. This type is incompatible with
3: function a({ a, b }: ArgType): string {
                   ^ undefined
3: function a({ a, b }: ArgType): string {
                   ^ undefined. This type is incompatible with
3: function a({ a, b }: ArgType): string {
                   ^ number
```

Try [here](https://flow.org/try/#0C4TwDgpgBAggTgcwCrmgXigbwD5QIYBcUAzsHAJYB2CANFAEYD8RAbgPbkAmU2Avj1lz0ilAK4BbehDh08zKOy49eAbgBQagGajKAY2Dk2lfAApM+OvSi8i8ZKgCURUhWpY1UKHAjBRcY6CQbJr4UGjhUADkLlQIkVCMoUT0AHTAbADKZLEmDuq8akA)

**Comment by goodmind** [comment] 2019-05-24 03:31
Duplicate of https://github.com/facebook/flow/issues/2093

**Closed by goodmind** 2019-05-24 03:31 UTC
Labels: destructuring
