### ISSUE TITLE
Importing React as a namespace causes warnings

### ISSUE THREAD

**Issue by DaniyarJakupov** [facebook/flow#4870] opened 2017-09-13 09:42 UTC
## Version
"flow-bin": "0.52.0",
"react": "16.0.0-alpha.12",
"react-native": "0.47.0"

##
When I import React as a namespace:
`import * as React from 'react';`
I'm getting `checkPropTypes has been moved to a separate package` warning
**Terminal output:**

<img width="1026" alt="screen shot 2017-09-13 at 11 31 09" src="https://user-images.githubusercontent.com/17025967/30370394-bcdadd46-9877-11e7-959a-2e0ec6ea5c8c.png">

**And 2 more warnings via console output:**

<img width="1434" alt="screen shot 2017-09-13 at 11 06 01" src="https://user-images.githubusercontent.com/17025967/30370383-b6ff4cf4-9877-11e7-8070-7e3c9a37a3e2.png">

Warnings disappear when named type imports are used:
`import React, { type Node } from 'react'`

**Comment by AugustinLF** [comment] 2017-09-13 09:59
Yep, it's a know bug, duplicate of #4673

**Closed** 2017-09-13 14:32 UTC
