### ISSUE TITLE
System hangs sometimes when using command flow even I have only one or two files with @flow annotation

### ISSUE THREAD

**Issue by prashen** [facebook/flow#7742] opened 2019-05-20 05:56 UTC
![Screen Shot 2019-05-20 at 11 33 33 AM](https://user-images.githubusercontent.com/5449548/57999528-54ceee80-7af3-11e9-9734-2c1edaf6599f.png)
See this image when enabling the `flow-language-support` from `vscode` or typed flow
see the flow server `showing 1290` or more files reading and right side activity monitor showing too many commands of flow services in memory.

I have not many files with `@flow` annotation and sometimes when running flow command on terminal it takes too much time and when I saw in activity monitor after the system hangs, I saw that there are too many flow services running in Memory tab and it's recursive and after closing one another process fires and it make the whole system hangs badly.

Please fix the issues and it's the main type checking for React and if it has so many problems then how the users will start with it.
I had a plan to start with the flow in my existing project and I am fixing the type checking on basis of flow warnings and if it's not working as expected then how I will finish the project with type checking.

I am using flow with react native and these are my system and project details:

` React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-3330S CPU @ 2.70GHz
      Memory: 2.16 GB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.2.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 24.0.0, 25.0.0, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.0, 28.0.3
        System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.57.8 => 0.57.8 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2
      react-native-git-upgrade: 0.2.7
      react-native-rename: 2.4.0`

`React-native` already has so many issues whenever a new version comes, but why these testing and type checking has so many issues. 

It's being such a difficult thing to tell our client that `react-native's` some specific version has some issues that is why the `dependent plugin` is not working, giving always excuses to the client is not possible. 

It's somehow looking like our client will give up on `React-native` and with its relevant tools.

Flow version: ^0.96.0

using `vscode`

## Expected behavior
Should not slow

## Actual behavior
making `Mac` hang and after seeing `Activity monitor` there are services called flow and when closing one it's coming again and making the whole system not workable.

## Flow config file
![Screen Shot 2019-05-20 at 11 25 26 AM](https://user-images.githubusercontent.com/5449548/57999157-02410280-7af2-11e9-8af2-ce94c156a109.png)

@mislav

**Comment by vicapow** [comment] 2019-05-29 15:08
@prashen thanks for reporting. 

To help debug can you provide the log output from the flow server as well as the monitor file?

To isolate this as a flow issue and not a  vscode issue, can you run flow from the command line instead of from the editor?

At one point you mentioned there are too many flow servers but flow runs many flow servers to take advantage of multi cpu cores, similar to Chrome, do this is expected.

Lastly, I’ve seen issues before with users not being able to run flow if they’re syncing their repo with iCloud. Be sure to check that’s not the case here.

**Comment by Brianzchen** [comment] 2020-10-10 23:42
Flow has made performance improvements in the past year, especially with types-first. Closing this issue as it looks abandoned and unless you feel the issue is still present on recent versions of flow.

**Closed by Brianzchen** 2020-10-10 23:42 UTC
Labels: bug, needs triage, nontermination / perf
