### ISSUE TITLE
Unable to create new type by spreading imported types

### ISSUE THREAD

**Issue by bgonp** [facebook/flow#8506] opened 2020-10-14 10:33 UTC
Flow version: 0.135.0 

## Expected behavior
Create and use a new type by spreading two exact types (declared in other files) in a React project.

## Actual behavior
App compiled succesfully but Browser throws an error because 'undefined is not iterable'. But actually imported types are not undefined, I'm using them in other parts of the same file with no errors.

### This works:
main.js
```javascript
type FooT = {| foo: string |};
type BarT = {| bar: number |};

type FooBarT = {| ...FooT, ...BarT |};

const fooBar: FooBarT = { foo: '123', bar: 12 };
```
### This doesn't:
atomic-types.js
```javascript
export type FooT = {| foo: string |};
export type BarT = {| bar: number |};
```
main.js
```javascript
import type { FooT, BarT } from './atomic-types';

type FooBarT = {| ...FooT, ...BarT |};

const fooBar: FooBarT = { foo: '123', bar: 12 };
```

* Link to Try-Flow (works): https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AMVrACqgC8oA3gD6iQEBcoAzigE4CWAdgOaiUC+AblSYcAIQCGLYmSqgARpIYcArgFs5WFr0HJ02PAQlTSFagDoL+IgBpQFs0eL8hiAMawOzGocUHYjk3JvWAYAcgBGACYAZlDbBRYGKNBBIA

**Comment by Brianzchen** [comment] 2020-10-14 21:08
Firstly I've tested this in my app and no flow errors are thrown when your types are defined in a separate file.

But when you say it throws errors in the browser I don't think this is a consequence of flow. Flow does not impact what runs in your browser, it is only a static analysis tool that should be stripped during runtime. Are you sure this is a flow problem?

**Comment by bgonp** [comment] 2020-10-15 08:16
I think Flow actually impact what is running in the browser. Webpack is loading flow-runtime when compile the application in order to check type errors at runtime. And then it throws that error after compiling without errors.

**Comment by Brianzchen** [comment] 2020-10-15 09:43
That wouldn't be an issue with Flow and you should probably open an issue with [flow-runtime](https://github.com/gajus/flow-runtime). Have you tried removing usage of that lib to see if it resolves?

**Comment by Brianzchen** [comment] 2020-11-01 20:38
@gajus Any thoughts on this? Since you own that project and probably have a better idea. Otherwise I'll close this issue given the problem is unrelated to flow itself.

**Comment by gajus** [comment] 2020-11-01 23:36
This seems like an issue with flow-runtime.

**Closed** 2020-11-01 23:46 UTC
Labels: bug, needs triage
