### ISSUE TITLE
Import from Buffer (how do native imports work?)

### ISSUE THREAD

**Issue by CMCDragonkai** [facebook/flow#5133] opened 2017-10-18 11:57 UTC
On my project, I have declarations like these:

```
import { Buffer } from 'buffer';
```

This is so that rollup will know to either leave it alone and let it be equivalent to `var Buffer = require('buffer').Buffer;` or to inline an actual buffer polyfill package.

However flow complains about this:

```
^^^^^^ Named import from module `buffer`.
```

The native buffer module and buffer polyfill really does provide `Buffer` as an exported property.

**Comment by EugeneZ** [comment] 2017-10-18 15:53
For this to work, there needs to be a [declararion somewhere around here](https://github.com/facebook/flow/blob/master/lib/node.js#L116). It's supposed to be a global in Node, though, and though the docs acknowledge that its also a named export, it might not be a good idea to rely on that. You can simply do this yourself though in your flow `libs`:

```
declare module "buffer" {
  declare var Buffer = Buffer; //<----
  declare var kMaxLength: number;
  declare var INSPECT_MAX_BYTES: number;
  declare function transcode(source: Buffer, fromEnc: buffer$Encoding, toEnc: buffer$Encoding): Buffer;
}
```

**Comment by CMCDragonkai** [comment] 2017-10-19 01:46
Why do you say it might not be a good idea to rely on it?

Ok so should I send a PR?

What do you mean by "flow `libs`"? Do you mean `.flowconfig` somewhere? How would that work?

**Comment by EugeneZ** [comment] 2017-10-19 18:05
That makes sense. Sure, try a PR. I'm not part of the flow org, just passing through.

[If you add the following to your `.flowconfig`:](https://flow.org/en/docs/config/libs/)

```
[libs]
path/to/somewhere
```

Then in that folder, you have a .js file with Flow definitions in it, it makes for a nice home for definitions that aren't in the default flow libs or included with dependencies already. This is a good use case for it. Though I've never tried to declare a module that already was declared by flow's libs, so I'm not sure which one takes precedence. Perhaps they somehow merge. But I think it's more likely that the new one will override the old one. So I've included the other, non-relevant lines above.

I hope it works!

**Comment by CMCDragonkai** [comment] 2017-10-20 04:21
https://github.com/facebook/flow/pull/5153

**Comment by mroch** [comment] 2017-10-23 07:30
Duplicate of #3723

**Closed by mroch** 2017-10-23 07:30 UTC
