### ISSUE TITLE
Bug: No errors when using covariant field and `+=`

### ISSUE THREAD

**Issue by Bannerets** [facebook/flow#6693] opened 2018-08-04 12:56 UTC
If you use `+=` (or `-=`, `^=`, etc) Flow doesn't detect any error:

```js
class Number0 {
  +value: number = 0
  add(n: number) {
    this.value += n // no error?
  }
}
```

^ [try flow](https://flow.org/try/#0FAkYwGwQwZxgCAcgVwLYCMCmAnADPAb2HngGoA3KCZTALngDs0tt4BeeXY+KAE14AUDekww4AlIW4kALgAsAljAB0lapjIcG3AL7AdQA)

With `=` everything works correctly:

```js
class Number0 {
  +value: number = 0
  add(n: number) {
    this.value = this.value + n // error, as expected
  }
}
```

**Comment by goodmind** [comment] 2019-04-24 15:38
Duplicate of https://github.com/facebook/flow/issues/7195

**Closed** 2019-04-24 15:38 UTC
