### ISSUE TITLE
flow/lib types usage

### ISSUE THREAD

**Issue by gyzerok** [facebook/flow#332] opened 2015-03-19 11:29 UTC
Is there a way to use types declared in [flow/lib](https://github.com/facebook/flow/tree/master/lib)?
For example [node](https://github.com/facebook/flow/blob/master/lib/node.js) [dgram$Socket](https://github.com/facebook/flow/blob/master/lib/node.js#L272)?

Also is there possible to override [flow/lib](https://github.com/facebook/flow/blob/master/lib/node.js) modules implementation? Do i have to name interfaces file same as the original?

**Comment by gyzerok** [comment] 2015-03-20 12:17
It seems that types in flow are not overridable. So you may take this as a bug request.

**Comment by unknownexception** [comment] 2015-03-20 14:17
For the second question I use following workaround: 

- Copy `flow/lib/*` files to local project, 
- override needed declarations, 
- run `flow` with a flag `--no-flowlib`, 
- at the same time you could create pull request with fixes 
- wait until it (if) will be accepted in the master. 
- After that, you probably could obtain latest `flow/lib` again.

**Comment by gyzerok** [comment] 2015-03-20 14:41
@unknownexception yes, i understand that it is the solution, but its extremly ugly.

I dont know OCaml at all, so cant add a PR with this feature. But i have another solution for this feature. Gonna show it in a few days. Let this issue be open to discuss my solution later.

**Comment by henridf** [comment] 2015-12-23 03:22
This seems like a near-dupe of the later #922

**Closed** 2017-03-04 04:23 UTC
