### ISSUE TITLE
node module can not be found when on windows 10, works fine on osx

### ISSUE THREAD

**Issue by aeneasr** [facebook/flow#2373] opened 2016-08-31 19:52 UTC
```
npm i --save react-css-modules
```

with

```
import cssModules from 'react-css-modules'
```

works fine on osx, but on windows I get:

```
src/editor/plugins/content/placeholder/Component/index.js:3
  3: import cssModules from 'react-css-modules'
                            ^^^^^^^^^^^^^^^^^^^ react-css-modules. Required module not found
```

I removed node_modules several times and tried different things but did not manage to make that message go away.

**Comment by jrajav** [comment] 2016-08-31 21:15
Confirmed, getting the same issue with the same module.

**Comment by gabelevi** [comment] 2016-09-01 13:43
Could it be a long file path thing? How many characters is the path to node_modules/react-css-modules? Does `flow check` give a warning about long file paths?

**Comment by jrajav** [comment] 2016-09-01 14:24
It does, it gives many, which is another issue it would be really nice to get resolved, since it results in thousands of flow warnings even when the files are ignored. That's issue #2187.

However, that doesn't appear to affect this issue at all - or at least if it does, it's not warning about the react-css-modules path. Here is the full output I get including long file paths:

https://gist.githubusercontent.com/jrajav/6d32b718505967ac5cc79260b6725f1d/raw/dcfd8c84bc321a06c03f74a96dc6a47f4209505a/flow%2520check%2520output.txt

**Comment by arekkas** [comment] 2016-09-01 20:31
> Could it be a long file path thing? How many characters is the path to node_modules/react-css-modules? Does flow check give a warning about long file paths?

I'm currently on the road but I'll get back on my windows machine next week. Long filenames shouldn't be the culprit as `react-css-modules` is directly placed under `node_modules/` and there are a lot more dependencies much deeper down the tree which don't cause any troubles. Additionally it would be weird if both me and @jrajav would run into the same long file path issues on different systems.

**Comment by jrajav** [comment] 2016-09-13 02:41
Just a note that this happens even with npm3 which maximally flattens dependencies. After installing my project's dependencies with npm3 and running `flow check`, it returns no long path errors where it returned many before, but still comes up with these react-css-modules error.

**Comment by jrajav** [comment] 2016-10-25 21:12
Any update on this?

**Comment by arekkas** [comment] 2016-11-07 21:31
Not really, I'm still experiencing the same issues. I tried adding the following declaration but it didn't help either:

```
declare module 'react-css-modules' {
  declare type CssOptions = {
    allowMultiple?: boolean,
    errorWhenNotFound?: boolean,
  };

  declare type FunctionComponent<P> = (props: P) => ?React$Element<any>;
  declare type ClassComponent<D, P, S> = Class<React$Component<D, P, S>>;

  declare function exports<D, P, S, C: ClassComponent<D, P, S> | FunctionComponent<P>>(reactClass: C, styles: Object, cssOptions?: CssOptions): C;
}
```

**Comment by arekkas** [comment] 2016-11-07 21:33
Oh and sorry, flow check does not give any long path errors! But I see this error:

```
Skipping D:\workspace\js\editor\NODE_PATH=.: No such file or directory
```

**Comment by arekkas** [comment] 2016-11-17 18:04
This is still an issue unfortunately.

**Comment by jrajav** [comment] 2017-01-16 16:01
@arekkas Perhaps check if it's related to the current issue with case sensitivity on Windows? #3189

**Comment by arekkas** [comment] 2017-01-17 13:04
I no longer use react-css-modules but I ran the flow check command from `cmd.exe` not git bash so I'm not sure those are related

**Comment by jrajav** [comment] 2017-02-27 22:11
This issue just reared its head again for my project after going away for a while.

**Comment by mroch** [comment] 2022-09-30 15:11
we've fixed a lot of Windows issues this year. I'm going to close this, please file new issues for anything that still crops up on recent versions (e.g. v0.185+). thanks!

**Closed by mroch** 2022-09-30 15:11 UTC
Labels: Windows support
