### ISSUE TITLE
Object spread copies class methods

### ISSUE THREAD

**Issue by jesseschalken** [facebook/flow#3846] opened 2017-05-01 02:17 UTC
Flow treats object spread as copying class methods, but at runtime only own properties are copied.

Example:

```js
interface Bar {
  x(): void;
}

class Foo implements Bar {
  x(): void {}
}

let x: Bar = new Foo();
x.x(); // types: ok, runtime: ok
x = {...x}; // types: ok, runtime: ok
x.x(); // types: ok, runtime: error "x.x is not a function"
```

[Try Flow](https://flow.org/try/#0FASwdgLgpgTgZgQwMZQAQCEE1Qb2K1ADwAoBKALlQDcB7EAEwG5gBfYYJAGwQGcfUAYjRqoQAWwAOnKGKiR+mbHgIkK1OvVxs2waRCKVFqALyowUAO6DhZZoQB0qxqgD0L1DQDWwQidz2AwhY7R1tXdxgAV0hxNFgYGhhgIA)

**Comment by goodmind** [comment] 2019-06-20 22:28
Duplicate of #3197

**Closed by goodmind** 2019-06-20 22:28 UTC

**Comment by jesseschalken** [comment] 2019-06-21 13:21
@goodmind Duplicate of my own bug! I didn't even realize. 😅
