### ISSUE TITLE
Symbol.asyncIterator undefined

### ISSUE THREAD

**Issue by maury91** [facebook/flow#3940] opened 2017-05-15 15:33 UTC
I get 
`property `asyncIterator`. Property not found in statics of Symbol`
even if `import 'babel-polyfill' creates it

**Comment by sbking** [comment] 2018-02-27 18:14
Any news on this? Async iteration is basically impossible to use in Flow without this.

**Comment by goodmind** [comment] 2019-05-30 06:06
Duplicate of #810

**Closed by goodmind** 2019-05-30 06:06 UTC
