### ISSUE TITLE
Improve Flow for Redux

### ISSUE THREAD

**Issue by k15a** [facebook/flow#5039] opened 2017-10-05 15:04 UTC
After the great improvements for React support in Flow, it would be great the Redux support could be improved as well.

Currently, I think there are a few things which have to be improved until developing Redux apps with Flow is truly enjoyable.

# Reducers

A common reducer looks like the following:
```js
// @flow

type Action =
	| { type: 'add_account', name: string }
	| { type: 'remove_account', id: string }

type Account = {
	id: string,
	name: string,
}

type Accounts = Account[]

function reducer(state: Accounts = [], action: Action): Accounts {
	switch (action.type) {
		case 'remove_account':
			return state.filter(account => account.id !== action.id)
		case 'add_account':
			return [
				...state,
				{
					id: String(Math.random()),
					name: action.name,
				},
			]
		case 'change_account':
			return state.map(account => {
				if (account.id === action.id) {
					return {
						...account,
						name: action.name,
					}
				}

				return account
			})
	}
}
```
[Playground](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AQQMYoCWsAdqALyKg2gA+oA3qOtgFygDkAhgCa8B9bvnywArqRScANKFLcAtlg4BnFACcipAOagAvtVoNmrZV3VYFsAG5YhI8ZJmgivVRq26DqTDgKiJFEomQxpXd00daVC5RTM1SO1o71M8B0CVYP9HFABtAF1kSAlCEnILXjF8LHUACjVuFDNsjOCC2WFiMg4CLtIASh70yUzGGJV4IhR8AAtQWs6ygDpTfpDaDdB8bhUcTgsrW3sApzYYzdoLFDF1cgampcgiaCa64ROgigA+UHecpdcoAAhBQKL9SmQAbx+udaNtdlw+II-oFOGcLhcrjdyLlYRjaEtCfcsNF8fixmTKS43KAAMoeHS1ACyjRmS3U3FIvFgClq-X6pKp+PkSg4i0hIpJeLJekFlMK+Phe1mnO0dhRp2lGyxt1AxKWCm4GAWw0+PwpQtoREg8w1KChlFB4L6ULWFstlyw1117o9m0JSztcr9G0lYohpCWkuDHoMIbjlq1mx15DtSZoehhGwM3hAoAAjEsXAoMNAiPhnuhQCmsLxQBJeFgtJBa4g8wAmIsYdSwbDqKuA0iwIKQRy8NtgADMRYAcsO5MPy54WDNGlwVTp1abOC5Mo3WVtYI2gA)

## 1. Problem
The first problem is that flow doesn't recognize that all possible cases of this switch statement are covered and that the `change_account` case is actually dead code because it can never be reached. This has already been reported a couple of times: https://github.com/facebook/flow/issues/3032, https://github.com/facebook/flow/issues/2400 https://github.com/facebook/flow/issues/2399

## 2. Problem
The second problem with this reducer and Flow is in the 'remove_account' case.

```
case 'remove_account':
	return state.filter(account => account.id !== action.id)

// Flow Error:
// 17:             return state.filter(account => account.id !== action.id)
//                                                                      ^ property `id`. Property not found in
// 17:             return state.filter(account => account.id !== action.id)
//                                                               ^ object type
```

The problem here is that flow will handle every function call very pessimistic. It's not really obvious but on runtime, the filter function could mutate the action object and remove the id field. In my opinion, this behavior is a bug of Flow. In my definition of the Action type, I specifically say that the id is a required field. This means that the property is always there and Flow should not error.

Flow should only error in this case if the id field is optional.

**Comment by asolove-stripe** [comment] 2017-10-05 15:23
Regarding your problem 1, this is a known but tricky issue. I have heard that there is some hope of getting knowledge of exhaustiveness in, but I think it'll be a little while. It's not an easy fix!

As for your problem 2, it is not a bug, though it is certainly quite confusing. The error is caused by [Refinement Invalidation](https://flow.org/en/docs/lang/refinements/#toc-refinement-invalidations). Even though you've refined `action` to one specific action type in the `switch`, Flow doesn't know that the value won't have changed to an `add_account` action by the time the closure passed to `filter` is called. There is a proposal (can't find the issue) to add some kind of annotation to tell Flow that a function's callback is called synchronously and another one to tell Flow that a variable is immutable. Either of those would make it possible for Flow to type the code as-is. But in the mean-time, you can solve this by just adding a line like:

```
const removeAccountAction: RemoveAccountAction = action;
return state.filter(account => account.id !== removeAccountAction.id)
```

Because that variable can only ever have the remove action type, Flow knows it can't be reset to something without an `id`, and the code will type-check.

**Comment by CharlesStover** [comment] 2017-10-05 16:00
I don't agree with #1. Every reducer handles every action. There is no way for Flow, or any type checker, to know that every possible action has been covered. If you have two reducers, they are each receiving every action, even actions that are only handled by the other reducer. It is possible for one action to be handled by two reducers for two separate state changes. The entire point of Flow is that the developer might be wrong -- just because the developer said "these are the only actions for this reducer" does not mean that is true. For example, all of your reducers are receiving the "@@redux/INIT" action type.

You _said_ action is of type Action, but you could be wrong. In fact, you _are_ wrong, because as I said, @@redux/INIT is an action that you are receiving. Any action can be dispatched, regardless of if you listed it in your list of actions for this reducer.

**Comment by k15a** [comment] 2017-10-05 16:27
@asolove-stripe Thank you got the explanation of the problem 2 and good point. Haven't thought that I can change the action type as well and therefore remove the requirement of the id property.

For problem 1:
I am curious if this is harder with the type checking approach of flow in comparison of the AST type checking of typescript because they already have this feature.

@CharlesStover This is not really true. Because reducers are nothing else than functions they should be handled like functions and therefore flow should trust me that my type annotations are correct.

Let's take for example this little function:
```
// @flow

type Object = {
  type: 'a',
  value: string
}

function func(param: Object): string {
  return param.value
}
```
In this example, Flow will not error but you can still call this function with no arguments at runtime which will result in a runtime error. Flow and every other static type checker will be pretty useless if it requires that you handle every possible way a function could be called.

**Comment by asolove-stripe** [comment] 2017-10-05 17:17
There are two separate questions. One is, should the redux typings introduce some extra requirements where a store has to declare all its allowed actions, and enforce that in `dispatch` and in every reducer. That would probably be useful for safety, thought it might be a bit of a pain to get working.

But separate from that, exhaustiveness doesn't work in any function, even one not used as a reducer. I don't actually understand why it doesn't work. It seems like the machinery is present, since Flow does know that if you get past the `if` or `switch`, the type of the argument has been narrowed down to `empty`. But I have heard that it isn't trivial to fix, so I dunno.

**Comment by vkurchatkin** [comment] 2017-10-05 17:40
I'm going to close this. Both issues are not really specific to redux and are already filed separately.

**Closed by vkurchatkin** 2017-10-05 17:40 UTC

**Comment by CharlesStover** [comment] 2017-10-05 20:18
>therefore flow should trust me that my type annotations are correct.

But your type annotations aren't correct. I already pointed out how `{ type: '@@redux/INIT' }` is being passed to your reducer.
