### ISSUE TITLE
Flow type check fails when using Polymorphic Intersection types

### ISSUE THREAD

**Issue by homam** [facebook/flow#2565] opened 2016-10-03 08:20 UTC
The last line of this snippet must be a type error:

``` javascript
// @flow
declare type Map = <T, R>(f: (x: T) => R, xs: Array<T>) => Array<R>;

declare var map : Map;

declare type CurriedFunction2<T1, T2, R> = ((t1: T1, t2: T2) => R) 
 & ((t1: T1) => (t2: T2) => R);

declare type Curry = <T1, T2, R>(f: (a: T1, b: T2) => R) => CurriedFunction2<T1,T2, R>;

declare var curry: Curry;

curry(map)(x => x.foo())([1,2,3])
```

But Flow only correctly detects the error if we remove `((t1: T1, t2: T2) => R)` from `CurriedFunction2<T1, T2, R>` declaration.

Another similar case is discussed in [SO 39805174](http://stackoverflow.com/questions/39805174/dead-code-ramda-type-decelration-breaks-flow)

**Comment by calebmer** [comment] 2017-08-02 15:15
Closing since this issue hasn’t seen a lot of activity. Sorry about that 😣

Please reopen with a reproduction on https://flow.org/try if you are still having issues!

**Closed by calebmer** 2017-08-02 15:15 UTC
