### ISSUE TITLE
JSON typechecking only possible with `flow check --all`

### ISSUE THREAD

**Issue by erydo** [facebook/flow#1714] opened 2016-04-27 01:36 UTC
Valid JSON files cannot have the required `/* @flow */` pragma, and there is no way in `.flowconfig` to opt those files in. As a result, Flow does not have a way to typecheck imported JSON files except when running `flow check --all`, which can perform extremely poorly on some codebases.

**Comment by calebmer** [comment] 2017-07-26 21:44
Closing since this issue hasn’t seen a lot of activity. Sorry about that 😣

Please reopen with a reproduction on https://flow.org/try if you are still having issues!

**Closed by calebmer** 2017-07-26 21:44 UTC

**Comment by STRML** [comment] 2017-08-05 17:31
This shouldn't be closed, it is still an issue.
