### ISSUE TITLE
The parameter passed to require() must be a literal string.

### ISSUE THREAD

**Issue by mhaddon** [facebook/flow#2946] opened 2016-12-05 17:50 UTC
I am having this problem, i assume caused by using a backtick string template in the webpack require function:

```
  3: const Vue = require(`vue/dist/vue.min`);
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^ The parameter passed to require() must be a literal string.

```

I dont understand why this should be a problem.
I would rather not swap the backticks with apostrophes as i am using eslint to force backticks in my project.

**Comment by vkurchatkin** [comment] 2016-12-05 20:44
Duplicate of https://github.com/facebook/flow/issues/2692

**Closed by vkurchatkin** 2016-12-05 20:44 UTC
