### ISSUE TITLE
Flow cannot infer union type based on nested value in object

### ISSUE THREAD

**Issue by houshuang** [facebook/flow#4505] opened 2017-08-02 09:26 UTC
If you have a union of two object types, distinguished by one of the object keys having a different specified value, and you test for that value, Flow can narrow down which of the object types in the union you are referring to. However, if they are distinguished by a key that is in a nested object, Flow cannot infer/distinguish the objects. Sorry if my explanation is not very clear, here is a minimal example:

```js
// doesn't work
type objecta = {meta: {type: 'a', onlyA: number}}
type objectb = {meta: {type: 'b'}}
type object = objecta | objectb

const trythis = (x: object) => {
  if (x.meta.type === 'a') { console.log(x.onlyA) }
}

// -----
// does work

type objecta1 = {type: 'a', onlyA: number}
type objectb1 = {type: 'b'}
type object1 = objecta1 | objectb1

const trythis1 = (x: object1) => {
  if (x.type === 'a') { console.log(x.onlyA) }
}
```

[Flow try](https://flow.org/try/#0PTAEBMHsFMGcDsDkAXUB3SAnA1gKGQJ4AO0okARgFbQDGyAhqALygDeAttAwFxuEm9E9RABoy8ADYEAgr3gBXduWiYAvqvzFSFanXLM2nHny2DyidZpJkqtVCx13GAHxu7k5XLhqR4sVMiYBMgAFgCWsAYAFAAevI50AJTMAHxsuKCgYQBmoLEAdEb0+fykTOWgQojJrKA+fpAS0PkSkADmBb5S0skaGrggoAC0IyMDYFBw6Fh4Vtq2dPQAjAaspYLCYl0ycorKanNuduQrLGumleYapUd0p7cMK64JHkte9f6ggcHhsPex8QWyCWySYaVYGSyuQKN3KLCqNTqvlgjWarQ6MXy2x6oD6QA)

This is not an unrealistic example, but led to a rewrite of our API to satisfy Flow - [PR](https://github.com/chili-epfl/FROG/pull/369)

**Comment by vkurchatkin** [comment] 2017-08-02 13:08
Duplicate of https://github.com/facebook/flow/issues/1931

**Closed by vkurchatkin** 2017-08-02 13:08 UTC
