### ISSUE TITLE
Can reference arbitrary properties on functions

### ISSUE THREAD

**Issue by decentralion** [facebook/flow#6490] opened 2018-06-19 21:00 UTC
As seen on [this flow.org/try]:
```js
/* @flow */

const f = () => 3;
f.foo().bar()
```

Why is this not a type error? `f` clearly does not have a `foo` property.

[this flow.org/try]:https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzCjAF4wAKASlID4wBmAblSgDoo44rWAjAQwBOVIA

**Comment by goodmind** [comment] 2019-06-22 19:49
Duplicate of #106

**Closed by goodmind** 2019-06-22 19:49 UTC
Labels: Typing: soundness, bug
