### ISSUE TITLE
How to cover React-Redux Connect()

### ISSUE THREAD

**Issue by knyzorg** [facebook/flow#6681] opened 2018-08-02 17:14 UTC
I have the following code:

    const mapStateToFilterProps = (state:DataExplorerState, props) => ({ loading: state.loading, filters: state.filters });
    
    const actionCreators: ActionCreators<string, Action> = { updateLoadState, updateFilters, updateChartData};
    
    const mapDispatchToProps = (dispatch: Dispatch<Action>) => bindActionCreators(actionCreators, dispatch)
    
    // TODO: Fix typing issue
    export const FilterBoxConnect = connect(
        mapStateToFilterProps, 
        mapDispatchToProps
    )(FilterBox)

The code below the "TODO" says it is uncovered. How can I cover it?

**Comment by jasonLaster** [comment] 2018-08-07 12:44
We cover it here: http://github.com/devtools-html/debugger.html/  with this flow-type [def][d]

here is a sample connected component [sample][s]

[s]: https://github.com/bomsy/debugger.html/blob/types-wasm/src/components/Editor/Preview/index.js#L173-L188
[d]: https://github.com/bomsy/debugger.html/blob/types-wasm/flow-typed/npm/react-redux_v5.x.x.js#L1

**Comment by knyzorg** [comment] 2018-08-07 14:15
I am looking at it and am not understanding why my typings fall through. Is your def different than the flow-typed one?

Otherwise, is there a more minimal sample?

**Comment by avilapedro** [comment] 2018-08-07 21:15
I'm facing the same issue.

I created a minimal sample with steps to reproduce: https://github.com/avilapedro/react-redux-connect-flow-coverage

Also related to this issue:
- https://stackoverflow.com/questions/51659042/covering-react-redux-connect-using-flowtype
- https://stackoverflow.com/questions/48762132/flow-uncovered-code-warning-when-exporting-react-redux-connect

**Comment by villesau** [comment] 2019-03-02 19:32
react-redux libdefs have been rewritten since the issue so I assume it's not longer an issue with more recent versions of Flow. I'm going to close this. Feel free to reopen if you encounter this with up-to-date Flow versions.

**Closed by villesau** 2019-03-02 19:32 UTC
