### ISSUE TITLE
`typeof x === "object"` shouldn't re-add `null` if `null` has already been refined away

### ISSUE THREAD

**Issue by samwgoldman** [facebook/flow#1430] opened 2016-02-21 05:48 UTC
```js
function mixedToObject(x: mixed): Object {
  if (x === null) {
    return {};
  } else if (typeof x === "object") {
    return x;
  } else {
    return {};
  }
}
```

```
 5:     return x;
               ^ null. This type is incompatible with
 1: function mixedToObject(x: mixed): Object {
                                      ^^^^^^ object type
```

/cc @mroch

**Comment by mroch** [comment] 2016-02-29 22:59
dupe of #1416

**Closed by mroch** 2016-02-29 22:59 UTC
