### ISSUE TITLE
Array.filter to more generic type fails

### ISSUE THREAD

**Issue by nielsmadan** [facebook/flow#7200] opened 2018-11-21 14:00 UTC
```
type Foo = {
  prop1: number,
}

type FooArray = Array<Foo>;

type Bar = {
  prop1: number,
  prop2: number,
}

type BarArray = Array<Bar>;

function testArrayFilter(bars: BarArray): FooArray {
  return bars.filter(e => true);
}

function testArrayMap(bars: BarArray): FooArray {
  return bars.map(e => e);
}
```

Both `map` and `filter` return a new array, but flow seems to treat them differently (`filter` produces an error, `map` doesn't).

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiccYAvGAN6phg4BOcOAjAFxgB2ArgLYBGeegBpUAX3TZ8REgEF69AIZZyYOYqwAeYnAB8Abgm4CAIQX0V1WgyZtOvAcJp1GOAEztu-QSPGYjYU3o1JRVgzUD9dCguDgBjDABLOA4wDDwAZwwwwgSYNPoACj4zdPZAsIBKdm0wqid6PAwuehTi+nSAOihc-IKCMh1U+i48CoNfaLjE5NSMrPklAFkFHCKSsrNK6tkF5UswBqaWsDbOnhW+8kHR8aiY+KSUtMyAZQSOAHMYPABRb548BwMGt6Bt6FVpKR9odmq0zOMgA

**Comment by lll000111** [comment] 2018-11-21 14:20
I think the minimum example of the issue [is this one](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiccYAvGAN6phg4BOcOAjAFxgB2ArgLYBGeegBpUAX3TZ8YAEIBDeuSo06jFu279BI2gyYAmdbwHCx6KFw4BjDAEs4HMBjwBnDAGUbHAOYw8AUV8ePA4MAAo+eXY5egBKdmJSalp6PAwuegcI+gBuUyA).

It seems to me this is a [variance](https://flow.org/en/docs/lang/variance/) issue and "works as intended" "More specific outputs — Good"?

**Comment by nielsmadan** [comment] 2018-11-21 14:30
No, I am not expecting an error. And I figure if `map` doesn't produce one then `filter` also shouldn't.

**Comment by lll000111** [comment] 2018-11-21 14:36
You don't need `filter` for your example, you get the same behavior with only `return bars;` already.

**Comment by nielsmadan** [comment] 2018-11-21 15:57
You get the same error, but it's not exactly the same because filter creates a new list. If you return `bars` directly, you will end up with two references to the same list, but if with different types. You can argue that that should also work, but it's a different issue.

**Comment by lll000111** [comment] 2018-11-21 16:09
New object or not should not be a type difference. Immutability/mutability is not expressed in Flow (apart from $ReadOnly and the "+" for covariance), and the object is whatever it is.

Anyway, [here are a few more variants](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiccAggE7kCGWYAvGBdVgDwDeqYYO5cOAjAC4wAOwCuAWwBGecgBpUAXwB8AbnTZ8YAEJVyTGvUaUa7Tt14Dh46bIVcefAEzXJM+UrXooYkQGMMAEs4ETAMPABnDAMsAAopPQjhXX0TLABKYWIyNLAOLnI8DDFyUITyCPVFb18A4NDwqJiAYT448qSdPRjMohIYvPNC4tLjZgA6KF4JeMT0qpr-IJCwyOi01pwsJ1mK5O603uyB-LBhktCAbXGbjoBdBdQfJfrVprTCQJhw8l3OlJ6WX6uVO51GHUmXx+sW0JBgeCoInmSkWdRWjXWzAAslQcH99qlmEdgcxBgUihcwBCJLjYgQ6MowHhkdUgA), following your line of thought.

**Comment by nielsmadan** [comment] 2018-11-21 18:46
Fair enough.

I guess since flow is happy with this:

```
const barArray = [{ prop1: 0, prop2: 1}];

const fooArray: FooArray = barArray;
```

There's no reason that wrapping it in a function that returns `FooArray` shouldn't.

**Comment by SamChou19815** [comment] 2023-08-08 16:28
Should be fixed by local type inference. You can also use type guards now

**Closed by SamChou19815** 2023-08-08 16:28 UTC
Labels: Typing: refinements
