### ISSUE TITLE
Incorrect type inferred after instanceof/Array.isArray checks?

### ISSUE THREAD

**Issue by sampeka** [facebook/flow#2379] opened 2016-09-01 15:35 UTC
I'm using `flow-bin@0.31.1` and I think below an incorrect type is being inferred for the default case in the if statement.

```
/* @flow */

import _ from 'lodash';

declare function encodeURIComponent(uriComponent: string | number) : string;

type NonNullJSONType = {[key: string]: NonNullJSONType}| Array<NonNullJSONType> | string | number;

/**
* Formats a facebook querystring recursively:
* - Arrays are formatted as comma-delimited values.
* - Object keys and values are formatted as k1=v1&k2=v2
* - Scalar values are encoded with encodeURIComponent
*/
export default function facebookQs(v: NonNullJSONType) : string {
  if (Array.isArray(v)) {
    return _(v).map(facebookQs).join(',');
  } else if (v instanceof Object) {
    return _(v).toPairs().map(([k,v]) => `${k}=${facebookQs(v)}`).join('&');
  } else {
    return encodeURIComponent(v);
  }
}
```

Running a flow check on this, I'm given the following errors:

```
src/util/facebookQs.js:19
 19:     return encodeURIComponent(v);
                                   ^ object type. This type is incompatible with
  5: declare function encodeURIComponent(uriComponent: string | number) : string;
                                                       ^^^^^^^^^^^^^^^ union: string | number
  Member 1:
    5: declare function encodeURIComponent(uriComponent: string | number) : string;
                                                         ^^^^^^ string
  Error:
   19:     return encodeURIComponent(v);
                                     ^ object type. This type is incompatible with
    5: declare function encodeURIComponent(uriComponent: string | number) : string;
                                                         ^^^^^^ string
  Member 2:
    5: declare function encodeURIComponent(uriComponent: string | number) : string;
                                                                  ^^^^^^ number
  Error:
   19:     return encodeURIComponent(v);
                                     ^ object type. This type is incompatible with
    5: declare function encodeURIComponent(uriComponent: string | number) : string;
                                                                  ^^^^^^ number
```

In the final clause of the if statement, shouldn't `v` be deduced as `string | number`? As a different issue I also had to redeclare `encodeURIComponent` since it should be able to take a number as an input.

**Comment by rpominov** [comment] 2016-09-01 21:05
Seems like a duplicate of https://github.com/facebook/flow/issues/2132

**Comment by sampeka** [comment] 2016-09-02 08:50
Thanks for that, definitely is a duplicate. If anyone reads this: `typeof v === 'object'` is a workaround.

**Comment by avikchaudhuri** [comment] 2016-09-02 18:06
Merging with #2132

**Closed by avikchaudhuri** 2016-09-02 18:06 UTC
