### ISSUE TITLE
Flow for RN doesn't resolve ".ios" / ".android" dependencies correctly 

### ISSUE THREAD

**Issue by 7ynk3r** [facebook/flow#1685] opened 2016-04-19 21:15 UTC
Small bug here. If I have a file with name "SOMETHING.ios.js" and import it like 

    import SOMETHING from './src/components/SOMETHING'

Flow gives me the following error

    ./src/components/SOMETHING: ~/dev/macaron/index.ios.js:165
    Required module not found

The apps works perfect.

I'm using 

    "dependencies": {
      "react": "^0.14.7",
      "react-native": "^0.23.1"
    },
    "devDependencies": {
      "flow-bin": "^0.22.1"
    }

**Comment by abalhier** [comment] 2016-04-25 13:47
Hello

I don't think you need to specifiy .ios (or .android) when requiring a module. React Native should resolve this for you depending on the platform it runs on. See https://github.com/fbsamples/f8app and the use of F8TabsView for example : https://github.com/fbsamples/f8app/search?utf8=%E2%9C%93&q=F8TabsView&type=Code

**Comment by 7ynk3r** [comment] 2016-04-25 17:15
@abalhier, i know i don't need to specify .ios (or android) when requiring a module, but flow gives me an error (it can find the module). it doesn't have the logic to look for .ios / .android suffixes.

**Comment by alexanderjarvis** [comment] 2016-05-18 16:59
Worse than this, the flow errors only show for files with an ios extension. The same code with an android.js extension doesn't show any flow errors.

**Comment by mroch** [comment] 2016-05-31 23:18
duplicate of #945

**Closed by mroch** 2016-05-31 23:18 UTC
Labels: module resolution
