### ISSUE TITLE
property `children` not found in props of React element ...

### ISSUE THREAD

**Issue by MoOx** [facebook/flow#1964] opened 2016-06-17 07:47 UTC
This issue showed when I upgraded from 0.25 to 0.27...

I think I am still having issue.

Here is a component

``` js
// @flow

import React from "react"
import { StyleSheet, View } from "react-native"

type Props = {
  children: ReactElement,
}

const NavigationBar = (props: Props): ReactElement => {
  return (
    <View
      accessibilityRole={ "menubar" }
      style={ styles.bar }
    >
      <View style={ styles.center }>
        { props.children }
      </View>
    </View>
  )
}

NavigationBar.defaultProps = {
  children: null,
}

const styles = StyleSheet.create({
  // ...
})

export default NavigationBar
```

And here is a place where it is throwing errors

``` js
// ...
const Header = (props: Props): ReactElement => {
  const { user } = props

  return (
    <NavigationBar> // <- HERE I AM THE ERROR: property `children` not found in props of React element `NavigationBar`
      <View style={ styles.left }>
// ...
```

Looks like a bug. Or maybe I am doing something wrong?

**Comment by Kerumen** [comment] 2016-06-22 15:18
Dupe of https://github.com/facebook/flow/issues/1934

**Comment by ctrlplusb** [comment] 2016-07-12 15:19
For now I have had to resort to the following:

```typescript
type Props = {
  children?: $react$Children,
  other: number,
};

function Foo({ children, other } : Props) {
  return (
     <div>...</div>
  );
}
```

**Comment by szagi3891** [comment] 2016-07-25 04:26
fast offtopic :
ReactElement is the proper way to describe output type from function render ?
where it is defined by this definition ?

**Comment by jedwards1211** [comment] 2016-07-29 16:17
@ctrlplusb you can workaround without using a maybe prop:

```js
<div children={<span>flow bug</span>}>
  <span>This is the actual children which overrides the children prop above</span>
</div>
```

**Comment by jedwards1211** [comment] 2016-07-29 16:19
@szagi3891 It's here: https://github.com/facebook/flow/blob/master/lib/react.js#L32

I thought it has to be `React.Element` in recent versions of flow though?

**Comment by MoOx** [comment] 2016-09-20 10:23
My real poor workaround is to always do `children?: React$Element<any>`.

**Comment by wildeyes** [comment] 2016-09-23 09:40
@MoOx Hey, why do you write the dollar sign between `React` and `Element`?

**Comment by gcanti** [comment] 2016-09-23 10:26
@wildeyes `React$Element` and `import type { Element } from 'react'` are equivalent https://github.com/facebook/flow/blob/master/lib/react.js#L226

**Comment by mqklin** [comment] 2016-10-08 07:44
My workaroud, works nice:

```
type Props = {
  children: React$Element<*>,
};

class Div extends Component {
  props: Props;
  render() {
    const { props } = this; // don't do 'const { chidlren } = this.props', because flow can't check children this way
    return (
      <div>{props.children}</div>  
    );
  }
}
```

Usage:

```
  <Div
    children={(
      <span>Works nicely</span>
    )} 
  />
```

**Comment by Ehesp** [comment] 2016-10-19 13:27
Hitting this issue... bread and butter React syntax.  Work arounds feel a bit stinky :(

**Comment by rosskevin** [comment] 2016-10-19 13:54
This syntax works for me and I believe was the recommended change when upgrading from 0.25.0

```javascript
// @flow
import React, {Element} from 'react'

type Props = {
  children: Element<any>
}
```

And the signature for render is 

```javascript
render (): Element<any> 
```

Am I missing something in the question/problem? I made this change quite some time ago and it is working well.  This doesn't seem like a workaround.

**Comment by Ehesp** [comment] 2016-10-19 14:04
@rosskevin Well I'm fairly new to Flow at the moment, so maybe I'm not understanding correctly! Here's my example:

```
/**
 * @providesModule Button
 * @flow
 */

import React, { PropTypes } from 'react';
import { TouchableHighlight, Text } from 'react-native';

function Button({ onPress, children }: { onPress: () => void, children: string }) {
  return (
    <TouchableHighlight
      onPress={onPress}
    >
      <Text>
        {children}
      </Text>
    </TouchableHighlight>
  );
}

Button.propTypes = {
  onPress: PropTypes.func,
  children: PropTypes.string.isRequired,
};

export default Button;
```

So in this, I'm saying by `Button` must always have children which must always be a `string`. When I implement this in another component like so...

```
<Button onPress={this.someFunc}>
    Click Me
</Button>
```

... I get a Flow error of `Flow children: Property not found in props of React element "Button"`.

The only "fix" I can see right now is changing `children: string` to `children?: string`, which is removing the error, but now Flow thinks a `children` **prop** maybe has to be set (which it isn't), when in fact I always want to have `children`, just not as a direct prop, rather than in-between my `<Button>` component.

**Comment by rosskevin** [comment] 2016-10-19 14:30
@ehesp - two things

- use `Element<any>` for children
- stop doing propTypes separately and use [flow-react-proptypes](https://github.com/brigand/babel-plugin-flow-react-proptypes) (before your babel entry for `transform-flow-strip-types`.  Here's my [.babelrc](https://gist.github.com/rosskevin/442196fb3accdcfe6477f9fb3fcfa1f0)

Here's how I would refactor your component:

```javascript
// @flow
import React from 'react'
import pure from 'recompose/pure'
import { TouchableHighlight, Text } from 'react-native'

type Props = {
  onPress: Function,
  children: Element<any>
}

export default pure((props: Props): Element<any> => {
  const { onPress, children, ...rest } = props
  return (
    <TouchableHighlight onPress={onPress}>
      <Text>
        {children}
      </Text>
    </TouchableHighlight>
  )
})
```

This is untested but I think it should work for you.

**Comment by AsaAyers** [comment] 2016-10-19 14:31
JSX converts to something like this:

```
React.createElement(
    Button,
    { onPress: thissomeFunc },
    "Click Me"
);
```

Flow recognizes that the 2nd parameter is where props come from, but it doesn't seem to recognize that the 3rd parameter gets mixed into props under the key `children`.

This workaround works because you're moving children from the 3rd parameter into the 2nd parameter

```jsx
  <Div
    children={(
      <span>Works nicely</span>
    )} 
  />
```

becomes

```js
React.createElement(Div, {
  children: React.createElement(
    "span",
    null,
    "Works nicely"
  )
});
```

If you use `children?: React$Element<any>.` the error goes away. Flow still thinks `children` is always missing, but now that it's marked optional it doesn't complain.

**Comment by AsaAyers** [comment] 2016-10-19 14:38
@rosskevin I corrected your untested code [here](https://flowtype.org/try/#0JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wChRJY4wBXIubXAotXSAZyQHpaiyLo8AN5wAKhBpoAFigBGAGyQAJYAHMp8tVJgAaMUgAe8AL4MceQsRgBaAHYoYwAG5IypGAE8wSOAAUcYOxwALxwQqRwcBC2-kjs7ABccABiNLYYwNE6EXDSwPIAJkS2SQCiiiBItjAAPCi2HgB8pMakpKy27PC+dD6hABT9YAGJfiMAlCGNYTkdXWFRMUTxenmFxXoAdNvLJiHUIzlEMHS2cP05kTXikjIKylqa6vDRsfHBQq-L7MbNkf9wa6GGB-AH-IRrIpVVpgwFcUTA0FXeESaRyRQqdRPbSg8YtPFtOYQRSbeQQVQXK49ehfOLsD79SbBaa2GjyeS-S5wJRIdkQOAAdWghRyNS41KQzXGQA). You can see that at the bottom I am passing children to `pure` but Flow just doesn't see it.

I dumped the `: Element<any>` part because it was just giving me errors I didn't need to fix.

**Comment by rosskevin** [comment] 2016-10-19 14:52
@AsaAyers - I corrected your correction ;) with imports [here](https://flowtype.org/try/#0JYWwDg9gTgLgBAJQKYEMDGMA0cDeBRAGyRCQDsYBfOAMyghDgHIpUNGAoUSWXOAFQgBXNAAsUAIyIAJYAHMRBOSKz8kAD3hVa9Ji3QwAtKRQxgANyQd2MAJ5gkcAAp0wAZzgBeXOzhwIpZyRXVwAuOAAxQVIMYH9MHzhRYAIAExZSMMJiMhgAHhRSGwA+dgp2djR-V3hHQRZPOAAKMBdQp1aASk8i719K0mref0Dg7CTU9OwAOhmWQaovFog3BJYYOtImhN9cgWExSSQZeUV5eGG51w8cC6DXChLfJ7hd9RhH56eccbSyMs+XgB6PhvD47YFCUQSaRKU7KD4dUrlCpVCBEKYECCyRoJXK1eq3YLXRpdDw9UiCAgEB7bOBSJBUiBwADq0FSuMB+KQJQ6QA)

I haven't seen this problem but it **does** seem that you have to make `Element<any>` optional.

[Here is a reduced test case](https://flowtype.org/try/#0JYWwDg9gTgLgBAJQKYEMDGMA0cDeBRAGyRCQDsYBfOAMyghDgHIpUNGAodmATzCTgAKdMAGc4AXlzs4cCKQDCBYGgDWALjgAxAK6kMwOZmlw0AC2AEAJi1IbCxMjAA8KUtwB87CpzRyR8AGVQMCIJOAAKMGERDSEIUQBKCXcpGV9Sf1xZBSVVbDMLazJsADoylkyqSSj4kWMWGG0oUgjjGSdLYAA3bMVlFXEcOT7VCk8ZCdwCqxtvSacAek6u8bgEr052dJEIIhKCCABzcOMnIPBQ4dyBnHCk8RTt3aR9o-DGAHVoK0YEsba4AAJJAEA6nBbnEJITwJIA) that seems to prove either this is a bug (or my misunderstanding).

**Comment by AgentME** [comment] 2016-10-19 20:23
That doesn't work for elements that actually require children.

[react-motion specifically requires a function](https://github.com/chenglou/react-motion/blob/446a8d0130072c4a59fec1ab788bfc2cc5c5b788/src/Motion.js#L29) to be passed as the children prop.

**Comment by ismay** [comment] 2016-11-04 10:14
So apparently the fix: https://github.com/facebook/flow/commit/a7878ebb678252ba50c36bc2d33ab75efd43a04c was reverted in https://github.com/facebook/flow/commit/0185892b806c259b07b6d10109cc0faa0b7f3e7a, which means that flow currently can't check whether the children prop has been set in jsx.

From the revert: 

> We don't have a way to declare the type of a React element "nominally" based on it's type. Without this, it's arguably better to be ignorant than support JSX children.

Still, eventually supporting jsx children would be nice, it's a pretty crucial part of using react. Any feedback on whether there will be support for this in the future?

**Comment by AsaAyers** [comment] 2016-11-04 14:56
Every few months I come back and try Flow to see if it's ready. When trying to add Flow to my codebase it never takes me long to find the show stoppers. It seems I can only use flow if I significantly change the style of my code to avoid JS features where Flow is buggy. I guess I'd need to drop JSX to avoid this.

If this were the only problem I might consider one of the workarounds here. But for now I'm back to subscribing to issues and I'll try again in a few months when some of them close.

**Comment by steida** [comment] 2016-11-29 16:10
@AsaAyers I recently flowtyped my relatively huge project. You can check it. https://github.com/este/este

**Comment by steida** [comment] 2016-11-29 16:13
@AsaAyers If you are not sure what to use, use any. Even /* @flow weak */ is immensely useful. Or check how I flowtyped Fela https://github.com/rofrischmann/fela/pull/134

**Comment by Spy-Seth** [comment] 2016-12-29 13:53
I'm facing the same issue with flow 0.37.4. Any update on this?

**Comment by faceyspacey** [comment] 2017-01-17 12:46
same here, this is a pretty serious issue, given the significance of `children`.

**Comment by cjke** [comment] 2017-01-18 15:11
Also on 0.37.4, and still happening. 

I've been using the following: 

```
import type { Children } from 'react';

type PropsType = {
    children?:Children,
};
```

**Comment by echenley** [comment] 2017-01-18 17:27
@cjke I believe `Children` is currently defined as `any`: https://github.com/facebook/flow/blob/master/lib/react.js#L159

**Comment by cjke** [comment] 2017-01-18 17:36
It absolutely is - but I figure it explains my intention more naturally (for me, flow definitions act as a touch of documentation as well) than just a generic `any`, and if later down the line they choose to define a more fleshed declaration, all the better.

**Comment by gre** [comment] 2017-01-18 18:16
except I don't think `Children` refers to what you think (the children prop). It's probably for that [React.Children](https://facebook.github.io/react/docs/react-api.html#react.children) object utilities right?

**Comment by cjke** [comment] 2017-01-19 01:10
I actually don't know either way - it's not clear for which it applies. I was basing it off this cheat sheet of types: http://www.saltycrane.com/blog/2016/06/flow-type-cheat-sheet/

I've just looked through the various declarations here: https://github.com/facebook/flow/tree/master/lib and it seems `any` is the most common way to refer to children in this context

**Comment by kellyrmilligan** [comment] 2017-03-01 19:50
so what is considered the proper way on this issue then?

**Comment by amilajack** [comment] 2017-03-11 21:28
@kellyrmilligan @cjke 's [answer](https://github.com/facebook/flow/issues/1964#issuecomment-273501378) worked for me

**Comment by deecewan** [comment] 2017-04-12 22:15
I can't believe we still don't have a decent solution for this. Sure, you can mark it optional. But then how do you enforce components that *need* children, as opposed to components that can optionally take children?

**Comment by onehorsetown** [comment] 2017-04-12 22:25
@deecewan 

It's hardly ideal, but I just enforce an invariant in the constructor or render method:

```
var invariant = require('invariant');
 
render() {
    invariant(!this.props.children, 'Must have children');
```

**Comment by deecewan** [comment] 2017-04-12 22:26
That's actually not too bad. At least it provides an error.

Hardly static compile-time analysis, tho.

**Comment by onehorsetown** [comment] 2017-04-12 22:28
@deecewan - Ah yes... static analysis.  Ignore my answer.  Its stupid.

**Comment by jedwards1211** [comment] 2017-04-12 23:19
@AsaAyers yes, flow typing a big project is painful at first, but I believe it's already worth the effort; once you learn how to handle the quirks, it can catch a lot of bugs for you.

**Comment by jedwards1211** [comment] 2017-04-12 23:24
@deecewan as I mentioned before, here is a workaround for required children:
[Try flow link](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjYqfOLMAcn0pqfUIE8cywAFejgDOYALxgA3qjBgqACwwwAJqwB2ALlJtCAOgCiMMljJrCAHgpquAPlQBfdFThrhxALJdDx08QkAKSQUlVVN7LUE4EQBKcRswc2UMADcbIMUVdXtzYCTUpxc3MAxXQisqPgCZBM9vEzM5DNC1MUl-NQBXGBgtKy5o+ztZWUSUmwAVeTJhPgpWMEIpsGpCDooYRpD1HLyh4dHUybIuMDhksnx8DGU+Rb5gzNMwHCFitQWlsoBzHbHqnNqRnqhDs0VQQA)

```js
import React from 'react'

type Props = {
  children: React.Element<any>
}

const MyElement = ({children}: Props) => <div>{children}</div>

const instance = (
  <MyElement children={(null: any)}>
    <div>These are the actual children</div>
    <div>They override the children prop in the tag</div>
  </MyElement>
)
```

**Comment by deecewan** [comment] 2017-04-12 23:25
@jedwards1211 that doesn't seem like a good workaround, tho. That's a dirty hack. `children` is a pretty fundamental part of React.

**Comment by jedwards1211** [comment] 2017-04-12 23:44
@deecewan I mean yeah, it's ugly as f, but you were asking "But then how do you enforce components that need children", I was just providing an example of the only way I know how.

**Comment by comerc** [comment] 2017-04-15 20:50
```jsx
type Props = {
  children?: typeof React.Element,
}
```
My original way :)

**Comment by daltones** [comment] 2017-04-15 21:49
@comerc I guess every solution involving `children?` is not related to this issue.

The real problem is:
```jsx
// Flow supports this:
<Component children={someChildren} />

// But doesn't support this:
<Component>{someChildren}</Component>
```

**Comment by cjke** [comment] 2017-04-16 01:15
They seem very tightly aligned though, but I understand what you are saying. 

Under the hood, your first line becomes:
`React.createElement(Component, { children: someChildren });`

And you second variation becomes:
`React.createElement(Component, null, someChildren);`

Within the createElement, if children are provided as an argument (your second variation), they simply override the props version. As per the lines below:
https://github.com/facebook/react/blob/master/src/isomorphic/classic/element/ReactElement.js#L219

It feels like a proper solution to this requires flow "knowing" too much about React - but in reality it shouldn't  know that a property of the second argument is identical in implementation to the third argument of createElement.

**Comment by suchipi** [comment] 2017-04-16 02:54
Except that in practice, if you're using flow and react together, you want this to work... it seems like something for jsx in .flowconfig would be a good compromise (similar to how jsx pragmas work)

**Comment by cjke** [comment] 2017-04-16 03:00
I _do_ agree - and it is painful. Especially considering they come from the same parent. 

However, I do feel that it is a rabbit hole. Unless they can define the relationship between an argument and a property on another argument abstractly, **or** we are provided a mechanism to define required `props.children` and `children` in ours components separately, I don't see how this could be added without bloating flow to handle specific library use cases (in this case React).

In saying this, I am no Facebook engineer, I'm a pleb with a laptop - so I'm sure they will figure out something that avoids tightly coupling flow to react while resolving this issue.

**Comment by suchipi** [comment] 2017-04-16 03:20
Off the top of my head, here's some places where different uses of JSX differ:
* Is the third argument used as an attribute called `children`?
* When there is only one child JSX element, is it passed as a single-item array to the factory function, or a bare item?
* How are uppercase/lowercase element type names treated? (React uses identifiers for uppercase and strings for lowercase)

You could theoretically make configuration for each of these in .flowconfig:
```
[options]
jsx.useChildrenAttribute=true
jsx.singleChildWrappedInArray=false
jsx.identifierTypeMatcher=^[A-Z]\w+
```

But in practice, most people just want
```
[options]
jsx.react=true
```

**Comment by aaronjensen** [comment] 2017-04-16 05:30
Could it be typed something like this?

```js
/* @flow */

type Props = {
  foo: string,
  children: number
}

type RC<P> = (props: P) => void

declare var Foo: RC<Props>
 
declare function createElement<C, P: { children: C }>(component: RC<P>, props: $Diff<P, {children: C}> & {children?: void}, children: C): void
declare function createElement<P>(component: RC<P>, props: P, children: void): void

createElement(Foo, {foo: 'hi', children: 3})
createElement(Foo, {foo: 'hi'}, 3)
```

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAKATnDgM5gC8YA3qmGFHHAFxjkbECWAdgOYAaBmADGAC24wAJsTy92vAK4BbAEZ5iqAL7ps+MACUAwgB5CAPmpgAFDlIV2hAJTUrANzjdp6aXlEwAIZyYO7BYABiLOwm5g7kFgyofgHBBFBKvKIY3HC8YnKBGHgAojB4KvIYpsaCROy0YpIycgpgxmDaFjaicCo4eVUxZpZ19mTk7AAkACLcUFDmdbQSUrLy7MZdYABkdKst8gD87J7e2nUH623GzqdePilBIRlZOXkFeEWl5ZW81ZYen0BrwhkYRhYxvEnJdmtd7t47qEHuhRIVimUKlUbFE4MtmGwwABySRE2FrVrsADM2mcqDRXwxv2xuPx0WJpIuYCpziAA

**Comment by daltones** [comment] 2017-04-16 21:39
@aaronjensen seems like a good start. But Flow still doesn't “understand” that *JSX* children would be the third argument of `createElement`.

Besides that, these declarations don't handle multi-element children the way `React.createElement` is.
```jsx
<Foo>
  <i />
  <i />
  <i />
</Foo>

// equals to:
createElement(Foo, null, createElement('i'), createElement('i'), createElement('i'));

// and not:
createElement(Foo, null, [createElement('i'), createElement('i'), createElement('i')]);
```

**Comment by aaronjensen** [comment] 2017-04-17 04:42
@daltones 

> But Flow still doesn't “understand” that JSX children would be the third argument of createElement.

Really? What does it do with JSX then? I was assuming that it translated it into a React.createElement call (if you use the default pragma). How else would it type proptypes or the children prop? [Babel certainly "understands" it.](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3&targets=&browsers=&builtIns=false&debug=false&experimental=true&loose=true&spec=false&code=%0Aconst%20x%20%3D%20%3CFoo%3E%0A%20%20%3CBar%2F%3E%0A%3C%2FFoo%3E%0A%20%20)

As for the multiple children, I think you can [handle that too](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAKATnDgM5gC8YA3qmGFHHAFxjkbECWAdgOYAaBmADGAC24wAJsTy92vAK4BbAEZ5iqAL4jMuAgCEAhsRJlKNeo2ZsOXPkJESps+ewCCxYsawAeZXVNAD4ddGx8MAAlAGE-QmDqMAAKHFIKdkIASmpEgDc4bml0aTxRGFMCPNMwADEWdlj49PJQ0vLKsGriMBNiRrjzClDUdoq5JiVeUQxuOF4xOWMMPABRGDwVeQw-GMEidloxSRk5BTAYsG1g5NE4FRx57YH44P20i3YAEgARbigoPF9rQXKd3BdrmAAGR0UFuXgAfnYBSK2n2cLO7BiWWRhWKY06UCmMzmC1ESxW602212+0Ih2OrkxFyuNzuDyevAwLwS7xa3z+AKBsJO8KxkJhINFZyRXTxaLAADplRjwdjcUVRmVxgQidNZvNFnhlmsNlsua9bvdHrxntFBm8wB8MkR0dLwSjpDi5ZrUOTjZSzdtkvU4MDbOwAOSSSNupnggDM2iyfoppupXJDLHDDTA0e4kYVCZT-pNVPNGGSfRzdnzhf2CYbDayQA):

```js
/* @flow */

type Props = {
  foo: string,
  children: number
}
  
type BarProps = {
  foo: string,
  children: Array<number>
}

type RC<P> = (props: P) => void

declare var Foo: RC<Props>
declare var Bar: RC<Props>

declare function createElement<C, P: { children: C }>(component: RC<P>, props: $Diff<P, {children: C}> & {children?: void}, children: C): void
declare function createElement<C, P: { children: C }>(component: RC<P>, props: $Diff<P, {children: C}> & {children?: void}, ...children: C): void
declare function createElement<P>(component: RC<P>, props: P, children: void): void

createElement(Foo, {foo: 'hi', children: 3})
createElement(Foo, {foo: 'hi'}, 3)
createElement(Bar, {foo: 'hi'}, 3, 3, 3)
```

**Comment by daltones** [comment] 2017-04-17 05:15
@aaronjensen Yeah! And I guess _this_ is the main bug here: Flow can only handle normal JSX props (`name={value}`), but cannot handle element children (`<Foo>{children}</Foo>`).

You can see the issue using your example [adding the same elements in JSX syntax](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAKATnDgM5gC8YA3qmGFHHAFxjkbECWAdgOYAaBmADGAC24wAJsTy92vAK4BbAEZ5iqAL4jMuAgCEAhsRJlKNeo2ZsOXPkJESps+ewCCxYsawAeZXVNAD4ddGx8MAAlAGE-QmDqMAAKHFIKdkIASmpEgDc4bml0aTxRGFMCPNMwADEWdlj49PJQ0vLKsGriMBNiRrjzClDUdoq5JiVeUQxuOF4xOWMMPABRGDwVeQw-GMEidloxSRk5BTAYsG1g5NE4FRx57YH44P20i3YAEgARbigoPF9rQXKd3BdrmAAGR0UFuXgAfnYBSK2n2cLO7BiWWRhWKY06UCmMzmC1ESxW602212+0Ih2OrkxFyuNzuDyevAwLwS7xa3z+AKBsJO8KxkJhINFZyRXTxaLAADplRjwdjcUVRmVxgQidNZvNFnhlmsNlsua9bvdHrxntFBm8wB8MkR0dLwSjpDi5ZrUOTjZSzdtkvU4MDbOwAOSSSNupnggDM2iyfoppupXJDLHDDTA0e4kYVCZT-pNVPNGGSfRzdnzhf2CYbDZTqG6YAAVuQAB4ARiSflDTBYVAARJIR4ywbwqLQk2BgKE252uwAmfuD2yj8fBWfaPzAUOLmrLhPrlhDuBb7gjndJ3e7-eHoA).

**Comment by SEAPUNK** [comment] 2017-04-17 05:19
Considering how Facebook & Co. uses React and (I would assume) also use Flow, I wonder how they handle this problem themselves... 🤔

**Comment by aaronjensen** [comment] 2017-04-17 15:13
> Flow can only handle normal JSX props (name={value}), but cannot handle element children (<Foo>{children}</Foo>).

Right, which is what we're discussing in this thread. They cannot handle it *now*, but I'm wondering if one way for them to handle it is with a better signature of React.createElement.

The example you linked doesn't really prove anything because it's still using the built-in React.createElement jsx pragma. Unfortunately, `// @jsx` doesn't work on flowtype.org for some reason, so I built this: https://github.com/aaronjensen/type-create-element

Try loading that up and changing the children types.

The only thing the signature doesn't handle right now afaik is JSXIntrinsics because I'm not entirely sure how to type those ([and maybe they aren't either](https://github.com/facebook/flow/blob/19fb6fc954f1ed8e90058ae46fbfa1985ce55bfe/src/typing/type_normalizer.ml#L247))

**Comment by aaronjensen** [comment] 2017-04-21 17:13
Typescript just merged support for this: https://github.com/Microsoft/TypeScript/pull/15160

**Comment by Hypnosphi** [comment] 2017-05-04 00:55
React flow typing [excludes](https://github.com/facebook/flow/blob/5fe47b750cdfc4dcb149b5462c5291f34b14f3b7/lib/react.js) defaultProps from the config of props that need to be specified. Maybe it should also exclude `children`, like this:
```js
Config: $Diff<$Diff<Props, DefaultProps>, {children: any}>
```

**Comment by AgentME** [comment] 2017-05-04 01:13
@Hypnosphi Sometimes you want to enforce the type of children; I don't want the type just ignored.

**Comment by Hypnosphi** [comment] 2017-05-04 01:42
@AgentME yes, but normally children are provided separately from props. `$PropertyType<Props, 'children'>` can be used for their validation.

**Comment by karlhorky** [comment] 2017-06-06 15:51
Just tried @rosskevin 's example again with Flow `0.47.0` and it is not throwing errors currently:

[Try Flow Link](https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDGMA0cDeBRAGyRCQDsYBfOAMyghDgHIpUNGAodmATzCTgAKdMAGc4AXlzs4cCKQDCBYGgDWALjgAxAK6kMwOZmlw0AC2AEAJi1IbCxMjAA8KUtwB87CpzRyR8AGVQMCIJOAAKMGERDSEIUQBKCXcpGV9Sf1xZBSVVbDMLazJsADoylkyqSSj4kWMWGG0oUgjjGSdLYAA3bMVlFXEcOT7VCk8ZCdwCqxtvSacAek6u8bgEr052dJEIIhKCCABzcOMnIPBQ4dyBnHCk8RTt3aR9o-DGAHVoK0YEsba4AAJJAEA6nBbnEJITwJIA)

![screen shot 2017-06-06 at 17 47 33](https://user-images.githubusercontent.com/1935696/26838520-a6a8b316-4ae0-11e7-9555-e6fac54e104d.png)

Is this intentional or actually a bug currently in Flow?

---

Strangely enough, it doesn't appear to be actually checking the type of the children:

[Try Flow - children with type `boolean`](https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDGMA0cDeBRAGyRCQDsYBfOAMyghDgHIpUNGAodmATzCTgAKdMAGc4AXlzs4cCKQDCBYGgDWALjgAxAK6kMwOZmlw0AC2AEAJi1IaARhAhEUpdhU5o5I+AGVQYIgk4AAowYRENIQhRAEoJAD4pGU9Sb1xZBSVVbDMLazJsADpiljSqSTDokWMWGG0oUhDjGQAeS2AANwzFZRVxHDke1Qp45plcXKsbd3G4FoB6do7RmRi3TnYUkSckQoIIAHNg4xa-cEDBrL6cYLjxRK2dvcPgxgB1aCtGGJGxgAkkAR9id5mcAkhRjEgA)

**Comment by echenley** [comment] 2017-06-06 16:25
@karlhorky I may be mistaken, but wouldn't you have to do this?

```js
import React, { type Element } from 'react'
```

Otherwise, you could use the global `React$Element` type and avoid the import altogether.

**Comment by karlhorky** [comment] 2017-06-06 16:36
Hm, this [doesn't make a difference for the result](https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wChRJY4YBPMJOAbwFEAbJEJAOxgF85suAkXQwypWvTgAFHGADOcALxNScOBC4BhVsDQBrAFxwAYgFcuGYJoA0auGgAWwVgBMiXY2w7cYAHhQuGgA+Ul5SUjRNeXgAZQp2ZTgACjA5eWNZCAUASmVg1XUorhimDW1dAxsHZzcPaoA6JqJS-hU07Pl7IhgzKC4U+3U-V2AAN3KdPX0lRk0pg15Q9RWmJxd3bnDVvwB6UbHluBywiMjoiHYG1ggAc2T7P3jwRPnKmcZkvKUC4vlLpDXO7JfAAdWgbnwOSWQzgAAkkKwbo9ds8wOxQjkgA).

**Comment by suchipi** [comment] 2017-06-13 00:18
Ooo, does that mean this is fixed?

**Comment by SEAPUNK** [comment] 2017-06-13 00:30
I hope so, even though nobody on the dev team said anything about it. My cynical side expects this to break again in the next releases.

**Comment by gaastonsr** [comment] 2017-06-13 00:37
Almost, it checks for the presence of children but it doesn't do type checking yet.

**Comment by suchipi** [comment] 2017-06-13 00:58
You're right: https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wChRJY4YBPMJOAbwFEAbJEJAOxgF85suAkXQwypWvTgAFHGADOcALxNScOBC4BhVsDQBrAFxwAYgFcuGYJoA0auGgAWwVgBMiXY2w7cYAHgAqAD5SXlJSNE15eABlCnZlOAAKMDl5Y1kIBQBKZSDVdUiuaKYNbV0DGwdnNw8qgDpGohL+FVSs+XsiGDMoLmT7dT9XYAA3Mp09fSVGTUmDXhD1ZaYnF3duMJW-AHoR0aW4bNDw0h2duHkzNDQkJFdFFEUkAA96DHuAfgioiHZ61gQADmSXsfji4AScwq00YSVySnyRXkfyQAOBSXwAHVoG58NlFoMmABWLZwXYQsDsELHM4XTAoFyPZ5vJAfVzfZGo9EgsGUqHlKYzeF5By-f6AkHY3GufG8HY0oA

**Comment by agrcrobles** [comment] 2017-08-16 18:51
Flow v0.53 supports children out of the box!!
```
import * as React from 'react';

type Props = {
  children?: React.Node,
};
```
More info: https://flow.org/en/docs/react/children/

**Comment by asolove** [comment] 2017-08-22 02:21
Now that Flow v0.53 has improved the Component type and made `children` work, I think this issue can be closed. (/cc @calebmer)

**Closed** 2017-08-22 05:55 UTC
Labels: react
