### ISSUE TITLE
[declarations] not working as expected

### ISSUE THREAD

**Issue by nishant-dani** [facebook/flow#7803] opened 2019-06-07 17:55 UTC
Flow version:
"flow-bin": "^0.100.0",

## Expected behavior
I have the following declarations tag in .flowconfig
[declarations]
.*/node_modules/.*
.*/graphql-iso-date/.*
I am expecting to see no flow type errors in the following file:
node_modules/graphql-iso-date/dist/time/index.js.flow

## Actual behavior
Flow throws a lot of errors in that file, disregarding the declarations tag.  I was unable to setup a repro on flow try because there appeared to be no way to setup a .flowconfig file.

* Link to Try-Flow or Github repo:

**Comment by nishant-dani** [comment] 2019-06-07 18:23
I had to add a line feed after
.*/graphql-iso-date/.*

**Comment by nishant-dani** [comment] 2019-06-07 18:42
The problem is still occuring.  The line -feed did not help, it only went away temporarily but the problem has surfaced again.

**Comment by FezVrasta** [comment] 2019-06-15 16:45
I can confirm `[declarations]` seems to be completely broken on 0.100.0

**Comment by mroch** [comment] 2019-06-16 16:11
@FezVrasta does it work on previous versions?

**Comment by mroch** [comment] 2019-06-16 16:13
wondering if it could be the same as https://github.com/facebook/flow/issues/6717

**Comment by FezVrasta** [comment] 2019-06-16 18:12
No it's definitely a different issue. I didn't have time to test a previous version, I'll give it a shot tomorrow

**Comment by FezVrasta** [comment] 2019-06-19 11:38
@mroch please try this repro out:

```bash
git clone git@github.com:FezVrasta/flow-issue-repro-7803.git
cd flow-issue-repro-7803
yarn --frozen-lockfile
$(yarn bin)/flow
```

You should see errors coming from `@emotion/core` even if the Flow configuration is:

```ini
[declarations]
<PROJECT_ROOT>/node_modules/.*
```

**Comment by FezVrasta** [comment] 2019-08-02 15:11
@mroch did you ever find time to take a look at my repro?

**Comment by FezVrasta** [comment] 2019-09-25 10:22
This bug still affects Flow (version 0.108.0).

Does anyone know of any workaround to suppress these errors while maintaining the `[declarations]` behavior?

**Comment by FezVrasta** [comment] 2019-09-27 10:52
@mroch I just realized this issue is a dupe of #6717 as you suggested, I thought it was different because I didn't see `$FlowFixMe` comments in the Flow output, but actually they are just truncated from the Flow report but are there if you look at the source code that is throwing it.

I guess we can close it and focus on #6717

**Comment by evbo** [comment] 2021-02-28 03:21
I see this issue still with:

```
npm run flow --version
5.8.0
```

I create .flow files in the same directory as .js files, but unless I add types to the .js file it still complains even though the .flow file is getting used correctly

**Comment by SamChou19815** [comment] 2023-10-09 16:43
`<PROJECT_ROOT>` needs to be included

**Closed by SamChou19815** 2023-10-09 16:43 UTC
Labels: bug, declarations
