### ISSUE TITLE
Out of retries, exiting!

### ISSUE THREAD

**Issue by mcandre** [facebook/flow#390] opened 2015-04-14 21:39 UTC
**Summary**

When I try to initialize and run flow, it quits with `Out of retries, exiting!`

**Trace**

```
$ flow init
$ cat .flowconfig
[ignore]

[include]

[libs]

[options]

$ flow
Flow server launched for /Users/apennebaker
Spawned flow server (child pid=67099)
Logs will go to /var/folders/_9/shv02r4n1nx9ksvx6w_nd4pw0000gp/T/flow_apennebaker/apennebaker-zSUserszSapennebaker.log
The flow server will be ready in a moment.
Error: flow server is busyzing. If it was just started this can take some time. Retrying... |
Error: flow server is busyzing. If it was just started this can take some time. Retrying... -
Error: flow server is busyzing. If it was just started this can take some time. Retrying... |
Out of retries, exiting!lizing. If it was just started this can take some time. Retrying... -
```

**System**

```
$ specs flow os
Specs:

specs 0.14
https://github.com/mcandre/specs#readme

flow --version
Flow, a static type checker for JavaScript, version 0.7.0

system_profiler SPSoftwareDataType | grep 'System Version'
      System Version: OS X 10.10.2 (14C1514)
```

**Comment by gabelevi** [comment] 2015-04-14 22:13
Yeah this has been happening to me too and is pretty annoying. Here's what's happening:

1. You run `flow` (aka `flow status`)
2. `flow` starts a flow client.
3. The flow client sees that no flow server is running and starts one up
4. The flow client keeps asking the flow server "are you done yet are you done yet are you done yet"
5. Sometimes the flow server is too busy thinking and doesn't respond
6. The flow client doesn't like being ignored, and counts each missed response as an error that consumes a retry

I think this should be fixable by just making the flow client a little bit more patient

**Comment by mcandre** [comment] 2015-04-14 22:52
Yeah, it just needs to be patient. Maybe:

* Add a 2-3 second delay before attempting to contact the server
* Increase the delay between retries
* Multiply the maximum number of retries by a factor of 2 or 3
* Increase the TCP timeout

?

**Comment by Kureev** [comment] 2015-04-15 15:24
so, any solution? It's really annoying when you're debugging react-native applications. Every refresh ~ 5-7 secs because of this.

**Comment by clauderic** [comment] 2015-04-17 18:06
I'm also running into this problem when working on react-native applications, any input on this would be helpful

**Comment by Kureev** [comment] 2015-04-17 18:47
@clauderic I think I solved the problem for myself:
- Get sure that you have .flowconfig in the directory you run `flow`
- Make sure you excluded all unnecessary stuff (like `node_modules` etc)
After that it started working for me

**Comment by clark800** [comment] 2015-06-15 19:24
Ignoring `node_modules` does not seem to work because it creates many errors like:
`Failure("internal error: package /home/user/node_modules/lodash/package.json not found")`

**Comment by clark800** [comment] 2015-06-18 22:20
I think the solution is to either run `flow check` or use the `--timeout` command line option.

**Comment by samwgoldman** [comment] 2015-06-24 00:56
@gabelevi IIUC, the [facepalm] commit fixes this? If so, please tag as willfix next release and I'll close this out once that commit is released.

**Comment by armish** [comment] 2015-07-02 23:38
also running into this problem and since this doesn't exit with status 0, it makes harder to rely on this within a Bash script. Would be great to see this fixed with the upcoming version ;)

**Comment by raould** [comment] 2015-09-28 05:42
I guess I have something similar. I just cloned yesterday and built today.
$ flow --version
Flow, a static type checker for JavaScript, version 0.7.0

```
$ bin/flow
Flow server launched for /home/xyzpdq/Dev/flow
Spawned flow server (child pid=6458)
Logs will go to /tmp/flow/zShomezSxyzpdqzSDevzSflow.log
The Flow server will be ready in a moment.
Flow server launched for /home/xyzpdq/Dev/flow
Spawned flow server (child pid=6475)
Logs will go to /tmp/flow/zShomezSxyzpdqzSDevzSflow.log
The Flow server will be ready in a moment.
Flow server launched for /home/xyzpdq/Dev/flow
Spawned flow server (child pid=6492)
Logs will go to /tmp/flow/zShomezSxyzpdqzSDevzSflow.log
The Flow server will be ready in a moment.
Flow server launched for /home/xyzpdq/Dev/flow
Spawned flow server (child pid=6509)
Logs will go to /tmp/flow/zShomezSxyzpdqzSDevzSflow.log
Out of retries, exiting!
```

**Comment by nmn** [comment] 2017-03-04 04:27
Pretty sure this is fixed now.

**Closed by nmn** 2017-03-04 04:27 UTC
Labels: bug

**Comment by Infonautica** [comment] 2017-09-08 08:52
Issue isn't gone. I have a project, and from start of it's developing 1 of 3 flow runs is failing with error
**Out of retries, exiting!**

On second run it always success. Version 0.54.0. Tried it on create-react-app and custom boilerplate.

**Comment by FezVrasta** [comment] 2018-03-05 15:29
Still happening with 0.66

**Comment by TrySound** [comment] 2018-03-05 15:33
@FezVrasta It happens when another instance with different version of flow is run. Just run `killall flow && flow`

**Comment by FezVrasta** [comment] 2018-03-05 15:41
It doesn't help, as soon I run `flow` again it will return the same error. I can run `flow` just once before I start getting errors.

**Comment by TrySound** [comment] 2018-03-05 15:44
@FezVrasta It may doesn't help when your ide tries to run flow before you.

**Comment by FezVrasta** [comment] 2018-03-05 15:45
So what could the solution be like?

**Comment by ardok** [comment] 2018-03-06 21:30
Happening to me too. 0.65.0

**Comment by mirek** [comment] 2018-03-14 06:08
Still happens on 0.67.1

**Comment by caiogondim** [comment] 2018-03-23 15:29
Having the same issue with `"flow-bin": "0.68.0"`.

**Comment by TrySound** [comment] 2018-03-23 15:30
@caiogondim If you have mac os and yarn run `killall flow && yarn flow`.

**Comment by caiogondim** [comment] 2018-03-23 15:31
Just tried. Same issue 😢 
I'm on macOS.

**Comment by FezVrasta** [comment] 2018-03-23 15:45
The problem seem to happen when you have a global flow-bin and a local one, your editor is most likely going to run the global one and your shell is going to call the local one, and this makes Flow go mad.

The solution is to never have flow-bin installed globally.

**Comment by yutingkuang** [comment] 2018-04-03 05:49
It conflicts with the vscode's kit (Flow Language Support).
I stop the kit and resolved.

**Comment by dshinzie** [comment] 2018-04-16 22:05
@FezVrasta I can confirm that deleting flow-bin globally resolved this specific issue for me

**Comment by luiguild** [comment] 2019-08-18 17:51
I not having flow-bin installed globally and I get this error ever that I open Atom and try edit some file... I not installed nothing related (directly) with Flow in Atom, just added `eslint-plugin-flowtype-errors` locally in my project... I'm trying using Flow with Vue Single File Components, someone already make it?

**Comment by aghh1504** [comment] 2019-09-30 16:06
rm -rf node_modules works for me
