### ISSUE TITLE
Predicate function does not work when it's a property of an object.

### ISSUE THREAD

**Issue by newtang** [facebook/flow#5051] opened 2017-10-06 22:18 UTC
Since this works:

https://flow.org/try/#0PTACDMBsHsHcCgBEBXAzgUwASoC4CcBLAYx0QG555xkA7Eg6GzAQ2RwAtpCAvdAEwAU0AEYArAFwBRAB4AHPOlSoAyotQMaASnHDo0SOmZMApEXboiAa1QBveJgU5keJgEJXQsZgBk3zCNEAOjR0PABJPk0KAF9KPgtIZgVMHABPWSwZeTVVJQ1MAF5MG0x4AEgQ8L4AfnFsfAIaAHMAGnLKmmYAW3Ra3EJmtrLURKsAYUYaCxx+WsxdfUMaIZHmKwB9aFYOddxmGbn+xtby1Y2ttnZdnH30db5bvobB8oUm9Cm8W-FqOhwNIbxfrQVI-Wj0RjwaJAA

I would expect this to work:
https://flow.org/try/#0PTACDMBsHsHcCgBEBXAzgUwASoC4CcBLAYx0QG554A3AQz02gCMArTAXkwG95NMbkcAC2iEAXugAmALnDIAdiQLQ5ACibMpAUQAeABzzpUqAMqHUSuQEopjaNEjoaczAFIig9EQDWqbgEhMAxxkPGcAQjC1FkwAMhiGFgA6NHQ8AEkJSwpeAF94HIp4CU9IOiwcAE9dLB19M1MjC3YuTHg-FPSJAH4pbHwCOQBzABo2jrkaAFt0HtxCIdG-VFLvAGFlOU8cSR7MW3tHOUXlmm8AfWh+ITPcGm3duYGRtpPzy4FBG5w79DOJH9m-QWbQMg3QmzwPxk8kUykWxTm0Aq0IUOAs+SAA

**Comment by jcready** [comment] 2017-10-07 01:30
Duplicate: #4254

**Comment by goodmind** [comment] 2019-05-18 13:10
Duplicate of #4254

**Closed by goodmind** 2019-05-18 13:10 UTC
