### ISSUE TITLE
Flow LSP hover has `empty` placeholders until types are used

### ISSUE THREAD

**Issue by lyleunderwood** [facebook/flow#7522] opened 2019-03-02 13:59 UTC
Flow version: 0.91-0.93

## Expected behavior

Types are fully resolved when examined via LSP hover.

## Actual behavior

Types have `empty` placeholders until they are actually used, at which point the types are fully resolved and reflect their actual behavior.

[Link to Try-Flow](https://flow.org/try/#0C4TwDgpgBAKgFgSwHYHMoF4oG8oFsK4BGEATgFxQDOwJyaAvgNwBQokUAsgcSQEICuCADYATUgB4ACgD4MUABSSAlBlnVaqFm2jw6A4WJJTZmRSvSzdm5gGMA9kmpRgiVHPn4ipCurpKKVmgWCjiePFD0Siz2jsDOrij6oqRyUgA0nLwUXF58gslGMtIe3KRJhtm8-rAJ5RIyqsxQCmAAhiStuBTKAQmq8XQluXUk8m0duEpRzMwA9LNQAGZCdgDuUEKUYFBwdgBuKSQQYHYkwJTx0It2QiurdM7g0K0XgSPiBGCg0hmrcBBIKAIOIIC5iRbIYEQIQgGp6fKGcRIfi5aS2BxOXAgN4IlKYFzwgykeTyYAUZG5cyyYAAOmAdgAyjRBlMWHMFghFkCoPwkPZcPgkHECRchMgIBllmsNlsdvtDsdTuc8NjariSFAXnDUO8KTw0fMgXFKBACKKEABrK53KAiOwQShIADkcUIdhcKXpUCOlBuB0uj3Ydi5WJxRI1vOAwiNTourRswH4rVusP4JpE7JimNVD0wobV4fkAEZpuyVWGCraIBCkFCYVBiHBWgc43HtYl1UiUfqMlrefzBVG3CKoPdblBSCRTmR2fnCQV5C6HcAnaXDSPk76JyQpyRKDP5h4czr1b154jfKhpGuFhvNnY8K0rRcPYHoMHywXKzEbEdgNBkBlbZdgOEgMgrRE9VIA1ZiPCDvHbXVu2g6YgA)

**Comment by jbrown215** [comment] 2019-03-03 15:36
This is a symptom of a larger problem we have with polymorphism. Fixing this is on our roadmap :)

The issue is that the polymorphic type variables don't receive lower bounds from the call, which is what Flow uses to give a type for type-at-pos.

**Comment by goodmind** [comment] 2019-08-14 04:15
@jbrown215 is is `type-at-pos` related or general problem?

**Comment by SamChou19815** [comment] 2023-01-20 06:33
This would finally be fixed with https://medium.com/flow-type

**Closed by SamChou19815** 2023-01-20 06:33 UTC
Labels: bug, Typing: polymorphism
