### ISSUE TITLE
((()=>1:()=>number):interface{a:{}}) passes type check

### ISSUE THREAD

**Issue by aatatuzov** [facebook/flow#7503] opened 2019-02-22 21:29 UTC
Flow version: up to 0.93.0

## Expected behavior

Flow should give an error when I forget to put brackets after a function name.
```
interface IFoo {
  a: {}
}
class Foo {
  a: {}
}
type FooMaker = ()=>IFoo
let fooMaker: FooMaker = ()=> new Foo()
let foo: IFoo = fooMaker
```

I found a shorter example for which Flow does not give an error: `((()=>1:()=>number):interface{a:{}})`.

## Actual behavior

No errors.

Please note that Flow gives errors if the function type is not explicitly declared.
* `let foo: IFoo = ()=>new Foo()`
* `(()=>1:interface{a:{}})`
> Cannot cast function to interface type because property `a` is missing in function [1] but exists in interface type [2].

References: 
* [((()=>1:()=>number):interface{a:{}}) vs (()=>1:interface{a:{}})](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAFJglAXgHwCMAXOrngHYCuAtgEYCmATlkQJbkAuTUAhgMb0A3jyKCAvmKwBuDKXzF2XRrwHDRE6UA)
* [foo = fooMaker](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgOwC4FMBOUAhgMa5gCSAYnHGAN6phhEBcDAvqlyTEQM78wNOo2ZtO3VNgCeAB3IiAskQDWBMAF4wACgCUmgHzVaqGLmxgotFevztlajdv1GwmXEhH6zFq7XYTOm1rOFsCVCA)

**Comment by wchargin** [comment] 2019-03-02 18:25
Duplicate of #6490; the problem is that `((() => 1).a: {});`.

**Closed** 2019-03-02 18:26 UTC
Labels: bug

**Comment by wchargin** [comment] 2019-03-02 18:27
Duplicate of #6490
