### ISSUE TITLE
Union type doesn't work when containing an imported type from another module which is dependent on the current module

### ISSUE THREAD

**Issue by jddxf** [facebook/flow#3368] opened 2017-02-11 14:35 UTC
Consider the following two modules:
```
/**
 * @providesModule ModuleA
 * @flow
 */

var ModuleB = require('./ModuleB');
export type A = number;
```
```
/**
 * @providesModule ModuleB
 * @flow
 */

import type { A } from './ModuleA';
module.exports = function () {
  var a: A | null = 's';
}
```
Flow is expected to report an error but it doesn't.It only does when I change the type annotation on `a` from `A | null` to `A` or when type `A` is declared in ModuleB.

**Comment by asolove** [comment] 2017-08-22 03:53
I tried to narrow this down and found that the `module.exports = function()` but isn't necessary. Just saying `let a: A|null = "a"` inside that module is sufficient for the error to not show up.

But two things are necessary:

- the two modules have to have a circular dependency
- the type that ought to fail has to be a union between a type imported from the other module and some other type that should not match the value

It looks like this:

ModuleA.js: 

```js
// @flow
var ModuleB = require('./ModuleB');
export type A = number;
```

ModuleB.js:

```js
// @flow
import type { A } from './ModuleA';

let wrong: A | null = "s"; // succeeds but should error
let wrong2: A | {} = "s"; // succeeds but should error

let right1: ?A = "s"; // errors as it should
let right2: A = "s" // errors as it should
let right3: Array<A> = ["s"]; // errors as it should
let right4: {a: A} = {a: "s"}; // errors as it should
```

**Comment by asolove** [comment] 2017-08-22 04:20
Ah, this is a duplicate of #3249, and is also being discussed in #3522, so I think this issue can be closed. (/cc @calebmer)

**Comment by calebmer** [comment] 2017-08-27 20:04
I’m going to close this as a duplicate, but thanks for reporting the bug! I’ll take a look into it.

**Closed by calebmer** 2017-08-27 20:04 UTC
