### ISSUE TITLE
React children accepts function when explicitly typed

### ISSUE THREAD

**Issue by arahansen** [facebook/flow#6889] opened 2018-09-13 20:43 UTC
[this flow.org/try example](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQFA24QB2qhAro7nALxwAUAlNwB85ADYRRtGgHppcAsmCjU9JizgNw3OAB4AJsABuQgN4F2uAL47pB4zTiOnq5vAgwAFligAxCwC4+QS4RFihgRgBzbQFhci8ATzhGCAB3KVlkiHlFUVZKF3V3LygAYRIwbX0jU2LvPw5rWxq6OiA) demonstrates the same input to react children being treated differently by flow.

My understanding is that for built in html elements, children should be `React.Node`. However, React.Nodes should not be functions. The first example shows this behavior. However, if the function is explicitly typed, flow will not error on the react element.

Code:
```js
import * as React from 'react'

const func = () => 'lol'

// fails
const comp = <div>{func}</div>
      
const otherFunc: () => string = () => 'hey now'

// no failure
const otherComp = <div>{otherFunc}</div>
```

**Comment by avikchaudhuri** [comment] 2019-03-28 22:38
@samwgoldman I suspect the root cause is the same as an issue you're working on already: statics of a function type being different than statics of a function.

**Comment by samwgoldman** [comment] 2019-03-28 22:39
Yes, that's right. A callable object (which has well-defined statics) also exhibits the expected error. Fix is in the works.

**Comment by goodmind** [comment] 2019-05-31 06:10
[This is still an issue for methods](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQFA24QB2qhAro7nALxwAUAlNwB85ADYRRtGgHppcAsmCjU9JizgNw3OAB4AJsABuQgN4F2uAL47pB4zTiOnq5vAgwAFligAxCwC4+QS4RFihgRgBzbQFhci8ATzhGCAB3KVl5RWUXdXcvKABhEjBtfSNTfO8-DmtbCocnR3pRNHQfOBNGlmQYYE4CWK6myhhWKEZ4rCSU9MbLGgWZORSspVYYSlz4H2KtHnLjEx8AOgI6uyE6OiA)

**Comment by SamChou19815** [comment] 2024-01-10 02:22
This now errors

**Closed by SamChou19815** 2024-01-10 02:22 UTC
Labels: bug, Typing: object model
