### ISSUE TITLE
Dynamic Type Tests with external libraries

### ISSUE THREAD

**Issue by bolismauro** [facebook/flow#1680] opened 2016-04-19 14:06 UTC
Hi everyone,
I was wondering if there is a way to refine a type with the result of an external function.

I'll try to explain myself with an example

``` js
const testFN = (val: string|Array<string>): void => {
  let arr: Array<string>;

  if (_.isArray(val) {
    arr = val;
  } else {
    arr = [val];
  }
}
```

This is just a toy example, but the point is that flow can't understand that `_.isArray` returns true when val is an array and therefore in that branch val is an array and can be assigned.

I can achieve the result I want with `Array.isArray` but I wonder if there are ways to tell flow about this behaviour or at least force the type inside the if branch.

Thank you!

**Comment by sebinsua** [comment] 2016-07-12 23:38
I had this same problem using `ramda#isArrayLike`, too. I switched to `Array.isArray` obviously, but it would be nice to be able to fix it properly.

**Comment by jsdnxx** [comment] 2016-12-15 03:05
I would love this as well- consider this a feature request. For comparison, this is supported in TypeScript under the name "[user-defined type guards](https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards)", where you can declaratively annotate a predicate function that will be used for the refinement.

For example, you might be able to do something like
```js
import { isArray} from 'lodash'
declare function isArray: (val: any): val is Array

function doStuff (foo: any): boolean {
  // here foo is an any
  if (isArray(foo)) {
    // here foo is refined to Array
    foo.forEach(otherStuff)
  }
  // here foo is an any
  return true
}
```

and importantly, you would be able to do this to declare refinements for *any type*, which are statically type checked and run-time executable without erasure.

**Comment by mroch** [comment] 2016-12-15 03:08
this is a duplicate of https://github.com/facebook/flow/issues/34, lots of discussion there!

**Closed by mroch** 2016-12-15 03:08 UTC
