### ISSUE TITLE
exact empty object not working

### ISSUE THREAD

**Issue by villesau** [facebook/flow#4681] opened 2017-08-22 13:29 UTC
following code fails:

```
/* @flow */

type Empty = {||};
const huh = (ob: Empty) => ob;
huh({});
```

to this:
```
5: huh({});
       ^ object literal. Inexact type is incompatible with exact type
4: const huh = (ob: Empty) => ob;
                    ^ exact type: object type
```
see: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCiAtjtmALxgDeAPrQL4DcqAxnAHYDOGYAFgFc+lMAAo4AIwBcRUtgCUlAHxhJLQX1HUG8pkA

when following works just fine:

```
/* @flow */

type NotEmpty = {|lol: number|};
const huh = (ob: NotEmpty) => ob;
huh({lol: 1});
```

see: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBycGAogLY7ZgC8YA3gD7wwBcYAdgK7kBGeAJ0YBfANyoAxnA4BnDGAAWXBbTAAKOL3bEylbAEpaAPjCbxShWvot2ARmH7RQA

**Comment by jcready** [comment] 2017-08-22 13:31
Duplicate of #4582

**Closed** 2017-08-22 16:11 UTC
