### ISSUE TITLE
Build a custom type for `Object.entries`

### ISSUE THREAD

**Issue by jeffmo** [facebook/flow#3310] opened 2017-01-31 22:13 UTC
Currently `Object.entries` is typed as `(object: any) => Array<[string, mixed]>`. This is the best we can do for inexact objects really, but for exact objects we could be more precise.

Let's build a custom type for `Object.entries` that returns a proper union of all the fields' values given an exact object type (and falls back to this `[string, mixed]` behavior for inexact object types).

**Comment by samwgoldman** [comment] 2017-01-31 22:16
Dupe of #2174. I am working on this already.

**Closed by samwgoldman** 2017-01-31 22:16 UTC
Labels: enhancement
