### ISSUE TITLE
`$FlowIssue`. Could not resolve name

### ISSUE THREAD

**Issue by ashee** [facebook/flow#1895] opened 2016-06-05 00:23 UTC
```
$ flow version
Flow, a static type checker for JavaScript, version 0.22.1

$ flow
node_modules/fbjs/lib/shallowEqual.js.flow:29
 29:     return x !== 0 || 1 / (x: $FlowIssue) === 1 / (y: $FlowIssue);
                                   ^^^^^^^^^^ identifier `$FlowIssue`. Could not resolve name


Found 1 error
```

**Comment by samwgoldman** [comment] 2016-06-06 05:49
Ack! This is happening because Flow is pulling in the fbjs type definitions, which is cool, but fbjs apparently depends on a configuration that is now required in your own project. If you add `suppress_type=$FlowIssue` to the `[options]` section of your `.flowconfig` the error will go away.

Going to leave this open, because we need to fix the root cause of this issue once and for all. 3rd party library dependencies shouldn't introduce errors in your project like this.

**Comment by calebmer** [comment] 2017-07-27 15:17
Closing since this issue has been resolved. Thanks for reporting! 😊

**Closed by calebmer** 2017-07-27 15:17 UTC
