### ISSUE TITLE
Dynamic object keys question

### ISSUE THREAD

**Issue by chrisblossom** [facebook/flow#2368] opened 2016-08-30 14:02 UTC
I am trying to figure out the correct way to declare an object that has both static and dynamic properties. Am I doing this correctly? Or is there a different / better way?

``` ts
type ObjectTypes = {
  exists: string;
  sometimesExists?: string;

  // If any other keys exist, they should follow this pattern:
  [field: string]: {
    some: number;
  };
};

const passes_flow1 = (): ObjectTypes => {
  return {
    exists: 'some string',
    other: {
      some: 123,
    },
  };
};

const passes_flow2 = (): ObjectTypes => {
  return {
    exists: 'some string',
  };
};

const fails_flow1 = (): ObjectTypes => {
  return {
    exists: 'some string',
    sometimesExists: 'other string',
    other: {
      some: 'should be a number',
    },
  };
};

console.log(passes_flow1());
console.log(passes_flow2());
console.log(fails_flow1());
```

(Linking issue https://github.com/gcanti/babel-plugin-tcomb/issues/100)

**Comment by calebmer** [comment] 2017-07-31 15:34
Closing since this issue hasn’t seen a lot of activity. Sorry about that 😣

Please reopen with a reproduction on https://flow.org/try if you are still having issues!

**Closed by calebmer** 2017-07-31 15:34 UTC

**Comment by SkylerRogers** [comment] 2018-07-11 19:18
+1 - an example use case for dynamic keys could be a basic key/value store:

```
{
   id2342343: "ensure I'm a string",
   id3243424: "ensure I'm a string",
   id4232333: "ensure I'm a string"
}

```
