### ISSUE TITLE
Flow incorrectly parses export default async functions as FunctionExpression instead of FunctionDeclaration

### ISSUE THREAD

**Issue by vjeux** [facebook/flow#3891] opened 2017-05-05 23:34 UTC
```js
export default async function foo() {}
export default (async function foo() {})
```

Flow parses both as FunctionExpression but only the second one should be (babylon does it fine).

It makes prettier add parenthesis because it's an expression instead of a declaration :(

http://astexplorer.net/#/gist/13b558367e825b316764c410daf9c45d/cee8ab46f39769211d361c3f06ac88f05c151bf2

**Comment by vkurchatkin** [comment] 2017-05-05 23:38
Duplicate of https://github.com/facebook/flow/issues/3264

**Closed by vkurchatkin** 2017-05-05 23:38 UTC

**Comment by vjeux** [comment] 2017-05-06 02:18
Thanks! cc @mroch  :)
