### ISSUE TITLE
Destructuring + Default Parameter on Union Type throws error

### ISSUE THREAD

**Issue by FermiDirak** [facebook/flow#7715] opened 2019-05-10 23:42 UTC
Flow version: 0.98.1

## Expected behavior

When destructuring an object with a default parameter, the following should be type safe:
```jsx
type Props = {
  val?: number | string,
};

function func({val = 3}: Props) {};
```

Default parameter `3` is of type `number | string`, therefore no error should be thrown.

## Actual behavior

https://flow.org/try/#0C4TwDgpgBACgTgezAZygXigbwFBSgNwEMAbAfgC4oA7AVwFsAjCOKAHymWDgEsqBzADTYAvgG5s2AGY0qAY2DcEVKNLkAKTEWLooAZmGV4SZAEosYoA

An incompatibility error is thrown:
```
5: function func({val = 3}: Props) {};
                  ^ string [1] is incompatible with number [2].
```

**Comment by goodmind** [comment] 2019-05-11 08:21
This is 3 year old bug, please use search https://github.com/facebook/flow/issues/2093

**Comment by goodmind** [comment] 2019-05-11 08:21
Duplicate of #2093

**Closed by goodmind** 2019-05-11 08:21 UTC
Labels: bug, needs triage
