### ISSUE TITLE
[BUG] Flow fails to check interface statics on implementing classes

### ISSUE THREAD

**Issue by mike-marcacci** [facebook/flow#4290] opened 2017-06-30 20:12 UTC
This is based on [my comment here](https://github.com/facebook/flow/pull/3994#issuecomment-312361590).

It appears that interface statics enjoy partial support, but in quite a dangerous way. In [the example below](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWA7ALgUwE6QIYDGWoAyrALZYCSmuBxoA3oqKANQDOlNanG+NMQCyWDAAtYAEwBcoABQBKUAF4AfKH450AcwDcrTQIwpCmnqWOnRE6XKWqNW3QYC+yQtHydOoAMKwODhYhBigKBQADtBYVJi+5FS02HhEJCxs3El8AkJYNpJSCsoZbKDBGACuOGigAOQSKL5NoILhOYKMVLZSdQZs7myG-PgmZllYlqPWYoXFzIZsFdW1DeItLfhG02bdhX2G7u6Int6+tISBwaHhUTFxGAk8yfRpC5nPHXkF0vOlS2IVvVGs1fG10CM8qA9tIDgNEMdLjlQABBOR+Lw+AA8iV4KQYWA0Kn8VxCGAMKIAdBMpmMflIlAYTrBkQAhdGYzg4z74tJE0AXUmhAys6kWKyEemMjws-itOS4l6pRjEtBYeAkoJk6X4SlIrSVUKBMVUWkzHrS5nIgBGCp5rxVoDVGsFWtC0utetlGBwhowxppEqligMQA) you can see that the static method defined in `SomeInterface` is present on `Class<SomeInterface>` and `SomeInterface.constructor`. However, the static method isn't defined on the class `Incorrect`, and flow doesn't error.

```typescript
// @flow

interface SomeInterface {
  +someInstanceMethod: () => string;
  static someStaticMethod: () => string;
}

class Correct implements SomeInterface {
  someInstanceMethod () {
    return 'this is an instance method';
  }
  
  static someStaticMethod () {
    return 'this is a static method';
  }
}

// this should error!!
class Incorrect implements SomeInterface {
  someInstanceMethod () {
    return 'this is an instance method';
  }
}

const A: Class<SomeInterface> = Correct;
A.someStaticMethod();

const B: Class<SomeInterface> = Incorrect;
B.someStaticMethod();

const a: SomeInterface = new Correct();
a.constructor.someStaticMethod();

const b: SomeInterface = new Incorrect();
b.constructor.someStaticMethod();
```

**Comment by vkurchatkin** [comment] 2017-06-30 20:28
Duplicate of https://github.com/facebook/flow/issues/803

**Closed by vkurchatkin** 2017-06-30 20:28 UTC
