### ISSUE TITLE
Type refinement failing with instanceof

### ISSUE THREAD

**Issue by MarkKahn** [facebook/flow#5969] opened 2018-03-16 06:15 UTC
[try flow](https://flow.org/try/#0G4QwTgBAZg9jBcEC2BLAHgUwCYG4BQeKUEAFLDBCgHYDOALiFQMYYzECiYYMYAlBAG88EaHHwBfIA)

```js
1: var foo: mixed;
2: 
3: if (foo instanceof Error) {
4:   foo;
5: }
```

`foo` on line 4 is of type `empty`, not `Error` as expected.  I can't seem to get `instanceof` to refine `mixed` or `any` types no matter what I try.

**Comment by vkurchatkin** [comment] 2018-03-16 12:00
Duplicate of https://github.com/facebook/flow/issues/2282

**Closed by vkurchatkin** 2018-03-16 12:00 UTC
