### ISSUE TITLE
Flow doesn't catch type errors in JSX if component is a member expression

### ISSUE THREAD

**Issue by philippotto** [facebook/flow#3853] opened 2017-05-01 19:56 UTC
Flow doesn't catch type errors in JSX usages like this:

```js
<Component.Subcomponent value={obj.wrongProp} />
```

Complete example:

```js
/* @flow */

type t = {
  a: string;
}


function component(a: t) {
  const Component = {
    subcomponent: () => {},
  };
  const SubComponent = Component.subcomponent;
  return <div>
    <div value={a.b} />
    <Component.subcomponent value={a.b} />
    <SubComponent value={a.b} />
  </div>;
}
```

[Try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgZgC8YA3qmGAIYBcYAzhgE4CWAdgOYDcqAvulRQAruwDGGVnHZgxcALY5pedhgAUdQgEpylWdKZgAwgqXsVRUhSpUGwgEZzFy1fTU7iAPnJ8ANHr5eKjl2QwBlBxNnc1USY1MXDAA6O0cEmIwgsGY8DGFmGQAeABNWADdPPSoS8rAy6hhhPGIyaiT7PjBgSpswQqizCxSHJ0HY+sbm1vbO7qq+iPsBxLqGppa2jq6evuBSit4+IA)

**Comment by vkurchatkin** [comment] 2017-05-01 20:02
Duplicate of https://github.com/facebook/flow/issues/1113

**Closed by vkurchatkin** 2017-05-01 20:02 UTC
