### ISSUE TITLE
parametric types evaluation

### ISSUE THREAD

**Issue by coot** [facebook/flow#1525] opened 2016-03-11 09:53 UTC
Currently this is impossible:

```
/* @flow */
declare type get<T> =  () => T;
declare type ID<T> = T;

// flow complains here, that it does not expect any parameters for the T type
declare type X<T> = T<string>;

let x: X<ID> = 'abc';
let f: X<get> = () => 'abc';
```

I also tried `declare type X<T<U>>` but  this syntax is not allowed.

**Comment by TrySound** [comment] 2019-02-04 23:38
Duplicate of https://github.com/facebook/flow/issues/30

**Closed by TrySound** 2019-02-04 23:38 UTC
Labels: Typing: polymorphism
