### ISSUE TITLE
Flow doesn't recognize this disjoint union refinement

### ISSUE THREAD

**Issue by mruzekw** [facebook/flow#4685] opened 2017-08-22 18:03 UTC
Flow doesn't seem to recognize this refinement.

```
export type A = {
  id: string;
  name: string;
  
  legacyId?: number;
};

export type B = {
  id: number;
  title: string;
};

export type unionType = A | B;

function normalizeToA(item: unionType): A {
	if (typeof item.id === 'string') {
		return { id: item.id, legacyId: item.legacyId, name: item.name };
	} else {
		return { id: '', legacyId: item.id, name: item.title };
	}
}
```

flow.org/try [here](https://flow.org/try/#0C4TwDgpgBAygrgYwRAziqBeKBvKLHJoBcUwATnBADRQBuAhgDaUkBGA9u4xPQHZQBfANwAoUJCgAxegEtuAEyiYceAqhQkAZkxTUoEMmXZkSKcjN4BzQaLHhoAJVRh2vXcvhJ1UAD5TZCraacLwIwDKuUAAWfPLcTigubhAAFGTOrrokCUm6AJQ4IkoymlBpGckAdPheaAXYRUp09GTNzBBsnNx8yumJmRCVDO1CUAD0Y1AA6sYA1igAhI0C+ozuDU3NrQZGJnjmVr0VupU7xqMT03OLyyICIiKXALQvr2-vH58vEw8QAB4uMjAUj2KAAQWUGygMnkpgOllESl49AAth19mQLAjGo1uJZ6AgQABJeQAfhIvDgKNYBlEwl+AOMwPE0AAQpDGjCKVSaWREaQZMBuHDMVY6bZ-oDmaCQhFeAAVUFYCF+VlBEJhOVQXjGFFMGQALwg8vYYJSgogKJIstcisgeRIEIaAEgSmUWexShaUZUYZgMFgAORmUWWQP1ETO53pYBwMj8XBc6HAS2++Q0PEE4mw5OpzOEkk0ZFokjeyrF6D050rCBraAu6MQWPxlRJwOBjMQfEFnNlmFF1HosvhIWV0TVu5AA)

**Comment by asolove** [comment] 2017-08-23 02:59
There are already a number of issues reporting similar cases that boil down to the same thing.

For now, when I need to distinguish different cases in a union, I add a clearly distinguishing feature, often a `type` tag with a string literal value. This is also helpful for debugging and logging, since at run-time the Flow types aren't available. So something like this does work:

```js
export type A = {
  id: string;
  name: string;
  type: "A",
  
  legacyId?: number;
};

export type B = {
  id: number;
  title: string;
  type: "B"
};

export type unionType = A | B;

function normalizeToA(item: unionType): A {
	if (item.type === "A") {
		return { id: item.id, legacyId: item.legacyId, name: item.name, type: "A" };
	} else {
		return { id: '', legacyId: item.id, name: item.title, type: "A" };
	}
}
```

In the mean time, since this issue is a duplicate of other similar issues, I think we can close it.

**Comment by lll000111** [comment] 2017-08-23 08:25
As @asolove says. I would not say this is a bug but a feature request to extend how disjoint unions operate.

Furthermore, personally I would consider a union of types where a property of the same name has different types an anti-pattern, especially if that is the property you use to create the disjoint union (won't matter if it's any other property).

**Comment by jcready** [comment] 2017-08-23 12:34
> You are supposed to have a concrete value that identifies a given type that is part of the disjoint union, not a type.

This is not specified in the docs.

**Comment by mruzekw** [comment] 2017-08-23 13:16
Thanks for responding everyone.

It would be nice to have a specific note in the docs about the need for a concrete value. That wasn't apparent to me at the first glance, but looking at it now I see the requirement.

**Comment by pulli23** [comment] 2019-03-25 23:40
@lll000111 I "agree" that is is an anti-pattern, however we are dealing with an immense chain of libraries on npm. Many of which use this as a "feature".

Take for example "sails": the ORM loads data. If the data contains a reference to another table, the "value" is an integer - the id of the other data.

However one can also call "populate(propertyname)", in which case the property is replace with the actual referred object.

**Comment by goodmind** [comment] 2019-03-26 06:21
TypeScript supports this since 3.2, so I guess this is feature request
https://devblogs.microsoft.com/typescript/announcing-typescript-3-2/#improved-narrowing-for-tagged-unions

**Comment by goodmind** [comment] 2019-03-26 06:25
I'm not sure if this possible, then every key would be discriminant property on unions

**Comment by goodmind** [comment] 2019-03-26 07:08
Yeah, I was wrong about TypeScript, it supports it if you write your type like this
```ts
type User =
    | { id: string, name: string, title: null }
    | { id: number, title: string, name: null }

function unwrap<T>(result: User) {
    if (typeof result.id === 'string') {
        // Here 'name' is string
        result.id
        return result.name;
    }
    // Now 'title' is string
    result.id
    return result.title;
}
```

**Comment by leplatrem** [comment] 2019-06-11 14:12
About @asolove example, note that using triple equals is necessary for the type check to work (ie. if you do `if (item.type == "A") {`, it won't be enough to distinguish cases)

**Comment by SamChou19815** [comment] 2023-02-22 20:23
Closing this, since we only support sentinel refinement with sentinel properties.

**Closed by SamChou19815** 2023-02-22 20:23 UTC
Labels: feature request
