### ISSUE TITLE
Flow stuck in seemingly infinite loop while initializing.

### ISSUE THREAD

**Issue by JoshMcCullough** [facebook/flow#3528] opened 2017-03-16 20:31 UTC
Testing out flow on an existing (large) project, but have only marked one file with `/* @flow */`, and have excluded npm and jspm module directories:

**.flowconfig**

```
[ignore]
./node_modules/
./jspm_packages/

[include]
./src/account/account-constants.js

[libs]

[options]
```

Here is what I'm seeing:

>$ flow
>Launching Flow server for C:\Projects\MyProject
>Spawned flow server (pid=10124)
>Logs will go to C:\Users\Josh\AppData\Local\Temp\flow\CzCzBProjectszBMyProject.log
>Launching Flow server for C:\Projects\MyProject
>Spawned flow server (pid=9008)
>Logs will go to C:\Users\Josh\AppData\Local\Temp\flow\CzCzBProjectszBMyProject.log
>Launching Flow server for C:\Projects\MyProject
>Spawned flow server (pid=18292)
>Logs will go to C:\Users\Josh\AppData\Local\Temp\flow\CzCzBProjectszBMyProject.log
>Launching Flow server for C:\Projects\MyProject
>Spawned flow server (pid=8232)
>Logs will go to C:\Users\Josh\AppData\Local\Temp\flow\CzCzBProjectszBMyProject.log
>Launching Flow server for C:\Projects\MyProject
>Spawned flow server (pid=8352)
>Logs will go to C:\Users\Josh\AppData\Local\Temp\flow\CzCzBProjectszBMyProject.log
>flow is still initializing; this can take some time. [merging inference] -

The log is mostly empty:

>[2017-03-16 16:24:47] Initializing Server (This might take some time)
>[2017-03-16 16:24:47] executable=C:\Users\Josh\AppData\Roaming\npm\node_modules\flow-bin\flow-win64-v0.41.0\flow.exe
>[2017-03-16 16:24:47] version=0.41.0
>[2017-03-16 16:24:47] Parsing

Not sure how to debug this further.

**Comment by philikon** [comment] 2017-03-16 20:48
I suspect this is related to the multiflow change regarding rest args introduced in 0.39. I'm seeing something similar. See #3370 and #3443 for a very minimal reproduction.

If you're using `...args` without type declarations anywhere in your code, try adding them and see if the problem goes away.

**Comment by lll000111** [comment] 2017-03-22 18:52
May be related, may be not - I had this endless spawn loop when I had an invalid `.flowconfig` that included directories that didn't exist (I had changed the project structure and forgot to change the Flow config file).

**Comment by andrejs-sisojevs-accenture** [comment] 2017-04-19 14:18
Hello. Is there a way to determine what causes hanging flow?
We had flow-bin v0.30. 
At some moment running `flow` just resulted in infinite initialization wit high CPU load:
```
Launching Flow server for /Users/dev/Transient/ws/project
Spawned flow server (pid=66740)
Logs will go to /private/tmp/flow/zSUserszSdevzSTransientzSwszSproject.log
flow is still initializing; this can take some time. [parsing] \
```
Logs contain:
```
[2017-04-19 17:02:26] Initializing Server (This might take some time)
[2017-04-19 17:02:26] executable=/Users/dev/Transient/ws/project/node_modules/flow-bin/flow-osx-v0.44.2/flow
[2017-04-19 17:02:26] version=0.30.0
[2017-04-19 17:02:26] Parsing
```
I have updated to 0.44.1 - same hanging.

**Comment by lll000111** [comment] 2017-04-19 14:20
@andrejs-sisojevs-accenture Have a look at the log?

**Comment by lll000111** [comment] 2017-04-19 14:24
How long did you wait? How much source code is there? It appears to be busy parsing, how do you know it hangs?

**Comment by andrejs-sisojevs-accenture** [comment] 2017-04-19 14:31
@lll000111 it used to initialise in a second.
Now it hangs for 5 minutes with overheating CPU until I kill process.
Project is not big - 10k lines of code.

**Comment by andrejs-sisojevs-accenture** [comment] 2017-04-19 14:44
I'm sorry - I guess it was some corruption on my side.
I've erased flow-bin, then fully reinstalled it - now it works properly.

**Comment by nadav-dav** [comment] 2017-04-27 21:24
Hey guys,
I also faced this issue, and after few (really) frustrating night, I was able to create a file that always fails (Now we can start debugging 👍  !)

Running this on the flow 0.44.2 gets stuck with `flow is still initializing; this can take some time. [local inference]`

Notice something interesting - it only gets stuck with 4 of these methods -> 3 and it works fine!  

```
// @flow

type Iface = {
  fn1: (arg: string) => Iface,
  fn2: (arg: string) => Iface,
  fn3: (arg: string) => Iface,
  fn4: (arg: string) => Iface
};

function t(): Iface {

    const context = function (...args): any {
    };


    context.fn1 = (arg: string) => {
      return context;
    };

    context.fn2 = (arg: string) => {
      return context;
    };

    context.fn3 = (arg: string) => {
      return context;
    };

    context.fn4 = (arg: string) => {
      return context;
    };

    return context;
}
```

**Comment by nadav-dav** [comment] 2017-04-27 21:28
I forgot to say that i am using OSX.

AND (fun fact) I was able to cause flow's website to stackoverflow with this code!

https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1ASUgIYDGOAvKAN6KiiQB2AjAFygAUBATgOYsDOKHAJZ0uASlCkAfHkIkANNVp0ATC3bc+A4WInT8xLApr0AzGs49Q-ISPFSZBo0oAs5jVa23dDkogC+ANzIkACudEQogrB0oCisoiz6JJTINDRE0fygGXQoWAAeKBK0YRFRMawAdNUWvAmgBHRoKWmggciK6dF5hZX0DMXqltbadtJUrTQcWCghHDE5PShBre2d2d0FKH0qgxaaNjr2E5PTs-MbuVsraWuti1s7JnvuI17H61MzcwubhTc0O5pB69ejOF7DTxHcafUBnH6XJYAtpBdbwi4g5b+IA

**Comment by avikchaudhuri** [comment] 2017-04-28 19:48
A workaround is to use `interface`:

```
interface Iface {
  fn1: (arg: string) => Iface,
  fn2: (arg: string) => Iface,
  fn3: (arg: string) => Iface,
  fn4: (arg: string) => Iface
}
```

Some checks are blowing up in the original version but are optimized with interfaces. Bringing those optimizations back to vanilla object types will take a while.

**Comment by samwgoldman** [comment] 2017-05-01 16:41
@nadav-dav We've identified the cause of your issue. I created a separate issue to in #3849, which you can subscribe to if you want to be notified when a fix lands. Thanks for sharing a small repro case! I'm sorry we caused you to burn so much time. The repro made it much easier to find the underlying cause.

**Comment by nadav-dav** [comment] 2017-05-01 18:53
Thanks @sam for the response! Rock on:)

**Comment by andrejs-sisojevs-accenture** [comment] 2017-05-02 09:45
@samwgoldman I wonder if you could add some kind of guard-construction, which would detect hanged parsing and log where it failed?

**Comment by TimothyKrell** [comment] 2017-05-03 18:00
I'm getting the same kind of behavior when type checking this code:

```js
let createRelationshipPaths = (path = "", rels = []) => {
  return rels.length
    ? rels.reduce((acc, [name, nested]) => {
        return [
          ...acc,
          ...createRelationshipPaths(path ? `${path}.${name}` : name, nested)
        ];
      }, path ? [path] : [])
    : [path];
};
```

```js
let createRelationshipPaths = (path = "", rels = []): string[] => {
// This fixes it --------------------------------------^
  return rels.length
    ? rels.reduce((acc, [name, nested]) => {
        return [
          ...acc,
          ...createRelationshipPaths(path ? `${path}.${name}` : name, nested)
        ];
      }, path ? [path] : [])
    : [path];
};
```

**Comment by cainvommars** [comment] 2017-05-28 11:55
@JoshMcCullough is your issue gone with 0.47?

**Comment by echenley** [comment] 2017-06-02 19:57
Another repro taken from some production code: 

https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1ARQK5YBOaA8higJawB2AzqALygDeiooA2gNZZoBcoOiiKUaAcwC6g4aImgAPqBr4AtgCNii0OtixoWAIY1tbDhx58ZIsVOtzx2lRq1KAgkSKG0AHlm2nNU0iAD4AGnZQAF8IqORIfBoAYypaUHEsFAAxSmgUYjos2CIcrGgAEwAKSEoy8oA5Q1UsMNAauoA1Q2hCVpq84kbmugBKVkiiTPwiE378oiGsOgA6SfL8JKxK6tqKtySkvtz5xbHGEPHzUCTaYVAAN27CJjbd8q6erE45waasSUiHBu9BQrwGRAAyjZ5MwAAYAfXhABIWD8Fn8orDAddbqDHp8oQ4Xh4vGhlpQ6CTvJV8YQxgB+B5PLDLABWsDElQA5GEuWNBLSsMgrpRIKBKgBCQWE2xjMxXUCTFDTWZvfZJbFxbFKlVcbEcZaG9p7A4RBWgWEo40NDFW47EGUSKKMFFYZKwcpYACqACUAJIAYVgqgwtDdKEqjvENOZUZGI0xZvMAI4MS4khGiC1wLuAEdCCQoy9KvniAI8AWyBRqPQXiwomcLvKc6DrQxmKR1KysCllrw0HQS5XMxwQIqsKpYPcAlTfP4JBd4LloNdDPg6DgYAhQChYKAABbGRyVdREBAbog7wzqUBL6ArpJeOj7kc4kFg+azl5t1ZYdabbY0ToQRZz8aFxHCV46kbS5zBbKCKg+Z5mFLEhvjeAFsVFcV0GwWAxWtJCcAlRhmC5WAux7FA+Vgq4dRmLhDWWIDWktVE3mdV13U9X1A2DUMaHDSNwJ2TpmXjTEU3MLUrngtFFnbUBO27Xt+0HQjxOxOT7SIQpilKCoXgybIdL0ko3lEiojjEz4jnBBTM21KYGM4JiWNANzTKKcy6iktNOAzYVx2VBi0VnZYDAkFB91ARlYXpO1wXC9lOS5AAyPlMVAQQuS5LNkCAA

**Comment by nahuelhds** [comment] 2017-07-13 23:59
Folks, in my case (I'm on Windows 10) the issue were resolved by running `watchman watch-del-all` and then uninstalling watchman (or removing it from the PATH). It seems just weird but anytime I install watchman flow doesn't work.

**Comment by silvenon** [comment] 2017-10-08 20:51
I was getting the infinite loop problem on Flow 0.56.0. Downgrading to 0.55.0 worked.

**Comment by trevordmiller** [comment] 2017-11-03 15:54
I'm getting this infinite loop as well. I've tried killing and reinstalling the Flow server and wiping and reinstalling `node_modules` without success. Here are my logs:

```
[2017-11-03 09:49:30] Initializing Server (This might take some time)
[2017-11-03 09:49:30] executable=/Users/trevordmiller/repos/snout/apps/snout_web/assets/node_modules/flow-bin/flow-osx-v0.50.0/flow
[2017-11-03 09:49:30] version=0.50.0
[2017-11-03 09:49:30] Parsing
[2017-11-03 09:49:37] Building package heap
[2017-11-03 09:49:37] Loading libraries
[2017-11-03 09:49:40] Resolving dependencies
[2017-11-03 09:49:41] Running local inference
[2017-11-03 09:49:42] Calculating dependencies
[2017-11-03 09:49:42] Merging
```

**Comment by trevordmiller** [comment] 2017-11-07 17:56
Per [my last comment](https://github.com/facebook/flow/issues/3528#issuecomment-341744946), I finally found the file causing the infinite "merging inference" by removing `/* @flow */` comments directory by directory, then file by file until finding which file was causing flow to hang. The culprit looked like this:

```javascript
const getJsonFields = (parsedBody: any, prefix: string = '') =>
  Object.keys(parsedBody).reduce((memo, key) => {
    const value = parsedBody[key]

    if (Array.isArray(value)) {
      return memo
    } else if (value !== null && typeof value === 'object') {
      return [...memo, ...getJsonFields(value, prefix + key + '.')]
    } else {
      return [...memo, prefix + key]
    }
  }, [])
```

Adding explicit types on the `reduce` arguments (`(memo: Array<string>, key: string)` fixed the problem for me:

```javascript
const getJsonFields = (parsedBody: any, prefix: string = '') =>
  Object.keys(parsedBody).reduce((memo: Array<string>, key: string) => {
    const value = parsedBody[key]

    if (Array.isArray(value)) {
      return memo
    } else if (value !== null && typeof value === 'object') {
      return [...memo, ...getJsonFields(value, prefix + key + '.')]
    } else {
      return [...memo, prefix + key]
    }
  }, [])
```

**Comment by jomi-se** [comment] 2018-02-08 12:49
I got the same issue as @trevordmiller. Infinite loop on OS X but not in CI running Linux.

How is that even possible ? 😂 

The culprit was also a reduce function that returned arrays using the spread operator. Fixed by adding types to the arguments of the arrow function.

```
z$ ./node_modules/.bin/flow version
Flow, a static type checker for JavaScript, version 0.57.3
```

**Comment by TrySound** [comment] 2018-02-08 13:15
@jomi-se Try to update to the latest 65 version and run `killall flow`

**Comment by jomi-se** [comment] 2018-02-08 15:04
I tried out version `0.65.0`, flow still gets stuck in the same file on OS X

```
Please wait. Server is initializing (merged files 215/237 (90.7%)): |
```

Adding type to all reduce functions arguments in this file fixes it though. I also was able to reproduce it locally with a single file containing

```javascript
// @flow
const getJsonFields = (parsedBody: any, prefix: string = '') =>
  Object.keys(parsedBody).reduce((memo, key) => {
    const value = parsedBody[key]

    if (Array.isArray(value)) {
      return memo
    } else if (value !== null && typeof value === 'object') {
      return [...memo, ...getJsonFields(value, prefix + key + '.')]
    } else {
      return [...memo, prefix + key]
    }
  }, [])
```

**Comment by sibelius** [comment] 2018-02-11 21:24
reduce is pretty common in javascript, this is a really big deal

any plans to fix this?

**Comment by TrySound** [comment] 2018-02-11 21:36
@sibelius It's not about reduce itself. Just about recursion with it.

**Comment by pashka** [comment] 2018-03-13 13:09
Had the same issue, the reason was dist folder, which was created after 'npm run build'.

**Comment by debel88** [comment] 2018-04-06 08:57
I got the same problem with `reduce`. Adding type annotations to the functions did the trick.

**Closed** 2023-04-18 16:03 UTC
Labels: nontermination / perf
