### ISSUE TITLE
Error message incorrectly disregards branch if declaration occurs after usage

### ISSUE THREAD

**Issue by jzhou-stripe** [facebook/flow#8097] opened 2019-09-20 00:44 UTC
Flow version: 0.108.0

## Expected behavior
The try-flow link below should have three errors with the same message:

```
10:   useFoo(foo);
             ^ Cannot call `useFoo` with `foo` bound to `foo` because null [1] is incompatible with string [2].
References:
4: type Props = {foo: null} & {};
                      ^ [1]
2: declare function useFoo(foo: string): void;
                                ^ [2]
```

## Actual behavior
Two of the errors have a different and very misleading message:

```
14:   const {foo} = after;
             ^ property `foo` is missing in object type [1].
References:
4: type Props = {foo: null} & {};
                              ^ [1]
```

* Link to Try-Flow or Github repo:
https://flow.org/try/#0PTAEAEDMBsHsHcBQATApgY2gQwE6tJAK4B26ALgJazGiEDOqAYrLABSQsBcodZOFxAOYBKbgDdYFZAG5EiMgE8ADvgAKOWErqgAvKADeHWN2KFo0AL6gAZAYuyUGbHlBjcoAEaoOebus10DqzCugB8BoigoOjUvAZGVnpePqiyUfRMLOwswrL2csFhEVExxHGGLImgWJBkqDhptAzMbEa5iPmOmLj4bjjVtfV+GloO3XTaACKE-ELFoEojdMMBDlHIMwKChfqRUdGxZPGVuqDEqPCg07PbwgB0i6t76c1ZbY0WHUA

**Comment by SamChou19815** [comment] 2023-02-17 16:14
The issue is now fixed.

**Closed by SamChou19815** 2023-02-17 16:14 UTC
Labels: bug, error messages, needs triage
