### ISSUE TITLE
union types within interfaces seem to be interpreted as section

### ISSUE THREAD

**Issue by danrot** [facebook/flow#6186] opened 2018-04-23 12:14 UTC
We are using mobx, and we are getting the following error since recently: 

```
Cannot call `configure` with object literal bound to `options` because string [1] is incompatible with boolean [2] in
property `enforceActions`.

   src/Sulu/Bundle/AdminBundle/Resources/js/index.js:45:11
   45| configure({enforceActions: 'strict'});
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^

References:
   src/Sulu/Bundle/AdminBundle/Resources/js/index.js:45:28
   45| configure({enforceActions: 'strict'});
                                  ^^^^^^^^ [1]
   node_modules/mobx/lib/mobx.js.flow:6:22
    6|     enforceActions?: boolean | "strict",
                            ^^^^^^^ [2]
```

You can also see [our CI build](https://circleci.com/gh/sulu/sulu/1005) for the full output.

IMO everything is correct here, but flow doesn't read that correctly. Have also made a small reproducible example here: https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAdgFwKYCdIEMBjTUAeQAd1lZUBnUAb0VFE1UlmyIEEDLqaAXKABGsWNEx5UoAD6gA5DXTZkveYgC+iRJACuqXlWkFqkZAHNd2TAApYwgFZDyfWgEoGWxCbYWrt+lZ2TkweV0FQZV1MDTcAbiA

The thing is that now nothing works, neither `'strict'` nor `true` are acceptable values now. I would expect for both of them to be valid.

This only seems to occur within interfaces, if this is defined with an object it works without any problems.

**Comment by mrkev** [comment] 2018-04-23 16:04
Duplicate of https://github.com/facebook/flow/issues/3876

**Closed by mrkev** 2018-04-23 16:04 UTC
