### ISSUE TITLE
an optional property is giving an error when undefined (sealed, covariant object)

### ISSUE THREAD

**Issue by gajus** [facebook/flow#3692] opened 2017-04-10 14:49 UTC
```js
type RequestResponseType = {|
  
|};

type ResponseType = {|
  +encoding?: string
|};

const request = (): RequestResponseType => {
  return {};
};

const respond = (response: ResponseType) => {};

respond(request());

```

```
10:   return {};
             ^ object literal. Inexact type is incompatible with exact type
9: const request = (): RequestResponseType => {
                       ^ exact type: object type
13: const respond = (response: ResponseType) => {};
                               ^ property `encoding`. Property not found in
15: respond(request());
            ^ object type

```

https://goo.gl/iKKzI6

**Comment by gabelevi** [comment] 2017-04-10 14:56
@samwgoldman - this is another report of that thing I asked you about last week. Special casing the empty object bites us once again! I wonder if there's some way for us to seal the empty object when it's obviously not being modified.

@gajus - A possible workaround is `return {encoding: undefined};`

**Comment by vkurchatkin** [comment] 2017-04-10 15:36
Duplicate of https://github.com/facebook/flow/issues/2977

**Closed** 2017-04-10 15:39 UTC
