### ISSUE TITLE
flow doesn't follow `export * from`

### ISSUE THREAD

**Issue by alexfedoseev** [facebook/flow#2743] opened 2016-11-03 06:03 UTC
When I use `export * from` I got `Property not found in` error.

```
flow-bin@0.34.0
```

**Comment by jsdnxx** [comment] 2016-12-15 02:01
duplicate of #940

**Comment by alexfedoseev** [comment] 2016-12-22 09:34
@jsdnxx No, it's not. `export * from` is in specs. The issue you linked is about proposed non-standard syntax.

**Comment by TrySound** [comment] 2018-03-12 13:07
This is probably fixed. I don't have problems with `export *` statements this time.

/cc @vkurchatkin

**Closed** 2019-01-31 17:35 UTC
