### ISSUE TITLE
Cannot use optional chaining with esproposal.optional_chaining=enable

### ISSUE THREAD

**Issue by RastislavMirek** [facebook/flow#6990] opened 2018-10-12 00:30 UTC
With this  .flowconfig:

```[ignore]
.*/build

[include]

[libs]

[options]
suppress_type=$FlowFixMe
suppress_comment= \\(.\\|\n\\)*\\$FlowFixMe
include_warnings=true
esproposal.class_static_fields=enable
esproposal.class_instance_fields=enable
esproposal.optional_chaining=enable
esproposal.nullish_coalescing=enable

[lints]
all=error
unclear-type=warn
sketchy-null=off
sketchy-number-and=off
```

I still get `Error:(5, 13) Flow does not yet support method or property calls in optional chains.` error from in this code:

```
// @flow

function test() {
  const a: ?string = ''
  const b = a?.trim()
}
```

Expected behaviour: Optional chains should yield no such errors with `esproposal.optional_chaining=enable`.

**Comment by villesau** [comment] 2018-10-29 22:02
AFAIK that's known issue and a reason why this is still open: https://github.com/facebook/flow/issues/4303

**Comment by goodmind** [comment] 2019-05-31 00:38
Duplicate of #4303

**Closed by goodmind** 2019-05-31 00:38 UTC
