### ISSUE TITLE
%checks refinement works via "import {}" but not with "import * as"

### ISSUE THREAD

**Issue by UnsungHero97** [facebook/flow#8374] opened 2020-05-13 18:23 UTC
Flow v0.124.0

### Expected behavior
I expect type refinement for a possibly `null` / `undefined` value to work when using a helper validation function.

### Actual behavior
It seems that type refinement is working only when the validation function is imported directly, but not if it's used via dot notation. Example:

```
// Utils.js
function isValid(value :any) :boolean %checks {
  return value && /valid/.test(value);
}
export { isValid };

// direct import
import { isValid } from './Utils';
function test1(id :?string) :string {
  if (!isValid(id)) return '';
  return 'test/:id'.replace(':id', id); // ok
}

// module import
import * as Utils from './Utils';
function test2(id :?string) :string {
  if (!Utils.isValid(id)) return '';
  return 'test/:id'.replace(':id', id); // error: either null or undefined is incompatible with string
}
```

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5sxCBnANQEMZCATACgDdbMBTMALmuwE8AlNwBGcODHa8wAUlwALdrgDW5MAG90YMACd2+TNtKsYHMADIzYYMYbAAdPnbl8LNuwEBuVAF90wYDrsAA665OzY+KrUYFCEEmAIhPhyYAowQezaMTgExNjkqLgkzmCYRDCqALzqqFoUNHT0Pl6o-mQAtkFw2vjqZFS0DGDeMdpw7WAA5HbAAKrl5JNeWHhEJGCOzgCMjENcAPzO2oTYAOZCXEcnpzW1ZFBgjACE9YNMDAJCGlpauvqGUyWd18WjufwMpEmm3wwC4DGmuiCMGouHYjEmcPokwANGR6J4fH4AoROt1emU4qooGMJtM5gsgStcutoQAmXb0biHfDHM4XK5nW51B7PCkVOyvRocz41H6Bf6QoFaEFgMF6CFTaGw+F2RHI1HozE4vEE7xAA

**Comment by jcready** [comment] 2020-05-16 00:48
Duplicate of https://github.com/facebook/flow/issues/8322

**Closed** 2023-03-31 00:20 UTC
Labels: bug, needs triage
