### ISSUE TITLE
Flowtype for ES6 Map.prototype.has does not validate optional response from Map.prototype.get

### ISSUE THREAD

**Issue by benderTheCrime** [facebook/flow#2876] opened 2016-11-22 20:27 UTC
Consider the following code:

```javascript
const store: Map<string, any> = new Map();

function getStoreValue(key: string): string {
    if (store.has(key)) {
        return store.get(key);
    }

    /* perhaps some code to fetch the value that did not exist */

    return null;
}
```

This is great in theory, however, the potential value of the key in the store is not validated, similar to how a check for a property or "hasOwnProperty" would work. Instead I get the following error:

```javascript
 17:         return store.get(key);
                    ^^^^^^^^^^^^^^^^^^^^^ undefined. This type is incompatible with the expected return type of ...
```

So, instead, I've had to do this:

```javascript
const store: Map<string, any> = new Map();

function getStoreValue(key: string): string {
    const value = store.get(key);

    if (value) {
        return value;
    }

    /* perhaps some code to fetch the value that did not exist */

    return null;
}
```

Which is not ideal. Is there a right way to be doing this while still utilizing Map.prototype.has instead of attempting to Map.prototype.get they key and then validating it in a condition?

**Comment by gcanti** [comment] 2016-11-22 22:46
Seems a dupe of https://github.com/facebook/flow/issues/2751

**Closed** 2016-11-23 04:35 UTC
Labels: Closed: duplicate

**Comment by benderTheCrime** [comment] 2016-11-23 04:53
@vkurchatkin So, this was a duplicate, but the original seems to have been prematurely closed by its author without a proper solution or suitable fix. I recommend that we reopen either this issue or the original because it is still an issue.

I think the point that @steambap made in that issue is right on the money: Flow should understand Map.prototype.has in the same way that it understands Object.prototype.hasOwnProperty, whether that invariance is handled by magic in the library or not.

I don't believe using a library or using "get" en lieu of "has" is a suitable solution.

**Comment by vkurchatkin** [comment] 2016-11-23 04:56
@benderTheCrime sure, let's continue the discussion there

**Comment by gcanti** [comment] 2016-11-23 07:50
> Flow should understand Map.prototype.has in the same way that **it understands Object.prototype.hasOwnProperty**

@benderTheCrime What do you mean? Flow doesn't seem to handle `hasOwnProperty` in a special way

```js
declare var x: { name?: string };

if (x.hasOwnProperty('name')) {
  x.name.trim() // <= error: call of method `trim`. Method cannot be called on possibly undefined value
}

if (typeof x.name !== 'undefined') {
  x.name.trim() // ok
}
```

**Comment by benderTheCrime** [comment] 2016-11-23 12:23
Applying the example I used earlier:

```
const store: Map<string, any> = new Map();

function getStoreValue(key: string): string {
    const value = store.get(key);

    if (value) {
        return value;
    }

    /* perhaps some code to fetch the value that did not exist */

    return null;
}
```

If we instead use an Object type:

```
const store: Object<any> = {};

function getStoreValue(key: string): string {
    if (store.hasOwnProperty(key)) {
        return value[key];
    }

    /* perhaps some code to fetch the value that did not exist */

    return null;
}
```

We're still unsure of whether `value[key]` is a string (We could access any key for a potentially undefined value) or a falsy value, but somehow flow knows that checking `hasOwnProperty` validates the string return of `value[key]` without knowing that store.hasOwnProperty(key) is a check for the existence of the property key on store. 

 Virtually the same code checking the existence of the key on store will result in the above ever, even when taking advantage of polymorphism.

**Comment by gcanti** [comment] 2016-11-23 12:44
That is because `Object` is unsafe

```js
const store: Object = {}

function getStoreValue(key: string): string {
  return store[key] // <= no errors
}
```

**Comment by benderTheCrime** [comment] 2016-11-23 12:57
Ok, I mean perhaps the supertype object is not a great corollary (the idea that there is a supertype that just returns 👍 for any type is pretty crazy in my book, but another can of worms altogether). Nevertheless, you are correct. It seems as though the only reason my example works for Object and not for Map is because flow is just not validating the return value of the function at all. 

This does not immediately invalidate this issue. I understand that the static typing has no real way of knowing that the check for the existence of the key is in any way connected to the maybe-type return value of Map.prototype.has, but I'm not sure that the error this presents should be altogether ignored.
