### ISSUE TITLE
Calling non-existent static method does not produce an error

### ISSUE THREAD

**Issue by danvk** [facebook/flow#410] opened 2015-04-23 17:19 UTC
This code shouldn't type check, since `goodbye` isn't declared as a static method on `C`:

```javascript
/** @flow */
class C {
  static hello(): string {
    return 'hello';
  }
}

function foo() {
  var hello = C.goodbye();
}
```

However, it type-checks with no errors under Flow 0.9.2.

**Comment by gabelevi** [comment] 2015-04-24 20:13
@avikchaudhuri wrote
> Static properties are only checked for consistency. So currently you won't get an error if a static property doesn't exist, but you should get an error if you set it to something and use it like something else.

> We do this because we find people adding static properties to classes on the fly, so we can't make the set of static properties fixed at class definition time.

Hmm, ok, so this is currently the expected behavior. It would be nice to figure out some other compromise, like the one we have for object types, where you can add properties initially, but not after it is "sealed". Or maybe there should be some way to declare a class "sealed" or something like that.

**Comment by popham** [comment] 2015-04-28 06:28
I'm not sure that this is expected behavior.  I think that static *properties* are the outlier because ES6 classes do not admit inline static properties:

```
class D {
  static ngProperty = 5; // Error under ES6 classes
}
D.okProperty = 5; // This is ok under ES6 classes
```

Static methods are written inline, so I don't think that the static properties caveat applies.  At least I don't think that it should apply.

(I expect that my code fragment will fail under Flow without an explicit `static okProperty: number` in the body of `D`.  A `D.someFn = function () { ... }` case is kind of interesting:  maybe it warrants a warning, since Flow does a better job with `static someFn...` implemented in the class body?)

**Comment by avikchaudhuri** [comment] 2015-06-19 01:16
This has been fixed, closing.

**Closed by avikchaudhuri** 2015-06-19 01:16 UTC
