### ISSUE TITLE
Computed properties - expecting a flow error, but there is none.

### ISSUE THREAD

**Issue by mkellyclare** [facebook/flow#2928] opened 2016-12-01 17:32 UTC
I'm trying to type check a computed property and was expecting an error but am not seeing one. 

```
function create(key: string): {[key:string]: number} {
  return {
      [key]: 'Not a number' // Does not cause a flow error
  }
}
```
[Try Flow Link](https://flowtype.org/try/#0GYVwdgxgLglg9mABBATgUwIZTQCgNZoCeAXIgM5QoxgDmAlKQN4DaBJFVtAuqWCALYAjNCgC+iRgCgAkOiggUSKYhWrWRHogDkAOThREGRHyEitiAPQXEAEThoyx-cgwgyaQ4mAAbOAHdEERQ4FElVRFFJUSA)

Is it possible to enforce the {[key:string]:number} type when using computed properties?

Thanks.

**Comment by gabelevi** [comment] 2016-12-01 18:01
Oh weird! That's definitely a bug! I'll check in with @samwgoldman and we'll get this fixed. Thanks for the report!

**Comment by gabelevi** [comment] 2016-12-01 18:39
Oh I think I see what's happening. Since Flow doesn't know the exact value of `key`, I'm guessing the type of the object literal doesn't reflect the computed prop. If you change the code to

```
function create(key: 'foo'): {[key:string]: number} {
  return {
      [key]: 'Not a number' // Now causes an error
  }
}
```

now it causes an error, since Flow knows the value of `key` and the object type now contains a property `foo` with the type `string`.

I suppose the solution will be to automatically create an indexer for object properties when they have unknown computed properties, or something like that!

**Comment by gcanti** [comment] 2016-12-01 19:10
Seems a dupe of https://github.com/facebook/flow/issues/1971

**Comment by samwgoldman** [comment] 2016-12-01 19:11
Yup. Will fix.

**Comment by mkellyclare** [comment] 2017-01-31 11:35
Just wondering if this is on the roadmap anytime soon? 
Obviously you're providing this tool to the community for free (and it's a fantastic tool), so don't want to seem too ungrateful. I haven't used OCaml before, but if you could point out where and what needs to be done, I could make an attempt at it.
Thanks.

**Comment by adamterlson** [comment] 2017-08-17 17:13
This would be a lovely fix to have.  My use case is that of using Redux, where using computed keys is common.  This bug prevents meaningful type safety on the store.

```javascript
type State = {
    [id:number]: { id: number, foo: string }
}

type Action = {
    payload: { id: number, bar: string }
}

function myReducer(state: State, action: Action): State {
    return {
        ...state,
        byId: {
            ...state.byId,
            [payload.id]: payload, // <-- Expected type mismatch
        }
    }
}
```

**Comment by augusto-altman** [comment] 2018-03-22 07:51
I am also facing this issue, it would be nice to have a fix soon :)

**Comment by nedp** [comment] 2018-08-27 03:55
I've been bitten by this a few times now.

**Comment by maartenschumacher** [comment] 2021-03-24 09:26
@samwgoldman @gcanti Any update on this? It's still an issue, and especially painful for those of us using redux. Does Flow have product pains or similar so we can upvote this issue? 🙏  There is also no easy workaround afaik.

**Closed** 2024-12-17 22:18 UTC
Labels: bug, Typing: object model
