### ISSUE TITLE
$ElementType does not typecheck 

### ISSUE THREAD

**Issue by sparlampe** [facebook/flow#5296] opened 2017-11-08 16:44 UTC
The [following](https://flow.org/try/#0C4TwDgpgBAysCGxoF4oG8BQUrzGAjAFzoDOCSAgnkVGQE4CWAdgOYC+ANFjngEzFoyiCFTD9awRq05RuuMAGYBQyniUSp7DGwwYAxgHsmZKBAAek+HuAAFOgbCoAPAGliAEhcQQJJ3GEAfAEAFGD2YABy8AC2EMQuHBLCxP5IAJQeAKIANhCxTMAAKuAQfuQQiS4BUMgBmFB0EMAArnRM2CoQANphDlGxALra3NgjUEA) code 
```javascript
type State = {
  app1: {stateApp1: string},
  app2: {stateApp2: string}, 
  app3: {stateApp3: string}
}

const extractProp= <K: $Keys<State>>(propName: K, state: State): $ElementType<State, K> =>{
 return  state[propName]
}
```
does not type check. Am I missing something or there is a problem in Flow?

on flow.org/try ` $ElementType<State, K>` resolves to
```
{stateApp1: string, stateApp2: string, stateApp3: string}
```
should it not be something like the following?
```
 {stateApp1: string} | {stateApp2: string} | {stateApp3: string}
```

**Comment by LoganBarnett** [comment] 2017-11-08 21:08
This sounds really similar to #4211.

**Comment by vaukalak** [comment] 2018-05-24 12:45
It looks like this issue explains the expected behaviors for most use cases (for example `set` method for immutable object). Really looking forward to get this fixed.

**Comment by goodmind** [comment] 2019-05-17 22:41
Duplicate of #4211.

**Closed by goodmind** 2019-05-17 22:41 UTC
Labels: Typing: destructors
