### ISSUE TITLE
How to extend a class, type or interface in an existing flowtype definition file

### ISSUE THREAD

**Issue by doberkofler** [facebook/flow#2421] opened 2016-09-08 07:52 UTC
I'm currently using a jQuery flow definition file (https://github.com/marudor/flowInterfaces) and it seems to works great. I would now also need to add definitions for some jQuery plugins and I cannot see how to extend the existing definition with other plugins sharing the jQuery namespace?

More generally asked. If I for example have an existing flowtype definition file like this:

```
declare class JQueryStatic {
   ajax(url: string, settings?: any): any;
   /* ... */
}
declare var jQuery: JQueryStatic;
declare var $: JQueryStatic;
```

How can for example add a new function (`ajaxsetup(settings: any);`) to this class without changing the existing definition file?

I would have hoped, that something like:

```
declare class JQueryStatic extends JQueryStatic {
   ajaxsetup(settings: any);
}
```

would work, but do not find anything like this and flow shows the error `JQueryStatic name is already bound`.

What is the proper way for extending a class, module or type definition in an external flowtype definition file?

**Comment by hon2a** [comment] 2016-11-10 12:23
Looks like a duplicate of #396 .

**Comment by vkurchatkin** [comment] 2016-11-10 12:24
@hon2a Thanks!

**Closed by vkurchatkin** 2016-11-10 12:24 UTC
