### ISSUE TITLE
Using anonymous arrow function incorrectly shows 'possibly undefined value'

### ISSUE THREAD

**Issue by priyajeet** [facebook/flow#3983] opened 2017-05-20 00:45 UTC
```js
/* @flow */

function foo(bar?: Function) {
  return bar ? () => bar() : null;
}
```

gives

```
4:   return bar ? () => bar() : null;
                        ^ function call. Function cannot be called on possibly undefined value
4:   return bar ? () => bar() : null;
                        ^ undefined
```

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swo44AKAIwEMAnAfgC4wAxHA47ASjAG9UYMPQCm+TPVJ16YRmEp8AvAD4wMxWFbZMMGAG5UAX1RA

**Comment by madbence** [comment] 2017-05-22 08:45
the problem is that flow is pessimistic about refinements. function arguments are `let` bindings (ie. you can reassign them), so inside the returned arrow function flow invalidates the refinement. obviously in this case we can see that nobody will reassign `bar`, but flow is not (yet) able to do this analysis. to solve this, you can use [`experimental.const_params`](https://flow.org/en/docs/config/options/#toc-experimental-const-params-boolean) to use `const` bindings in function arguments (ie. assigning to a parameter is never allowed), or you can use a placeholder variable:

```js
function foo(_bar?: Function) {
  const bar = _bar;
  return bar ? () => bar() : null;
}
```

**Comment by Brianzchen** [comment] 2020-11-01 02:46
Error fixed and try flow no longer throws error.

**Closed by Brianzchen** 2020-11-01 02:46 UTC
