### ISSUE TITLE
$Shape does not allow making properties read-only

### ISSUE THREAD

**Issue by CGamesPlay** [facebook/flow#6089] opened 2018-04-03 20:22 UTC
When you have a type with a read-only property, you cannot convert any type that contains that property to the`$Shape` of that type.

Example: [Try Flow](
https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AMVrKALygDeiooA1AEYCGATgFygBE9AXqwNyIC+vRAGNYAOwDOKUJBb5CJUqHrM2nVqAGIQoACS448XAEsAHgFksLFAAsj40OOuwArtAAmSnADc60I2+ExSVAAcxYdAGVrOmwAHjkAPmIyJUYWdjouDW4gA)

```js
// @flow

type Foo = {
  +bar: "baz";
};

const f: Foo = { bar: "baz" };
const g: $Shape<Foo> = { bar: "baz" };
```

In this example, the declaration of `f` typechecks, but the declaration of `g` fails with the confusing error message, "Cannot assign object literal to `g` because property `bar` is not writable in property `bar`."

**Comment by zeorin** [comment] 2018-06-05 15:22
Also having this issue. My use case is that I'd like to ensure that the props I'm returning from a `mapStateToProps` function are not wasted on the component:

```javascript
import React, { PureComponent } from 'react';

type Props = {|
	+foo: boolean,
|};

class MyComponent extends PureComponent<Props> {
	static defaultProps = {
		foo: false,
	};

	render() {
		return (
			<div>{this.props.foo ? 'foo' : 'nofoo'}</div>
		);
	}
}

const mapStateToProps = (): $Shape<Props> => ({
	foo: true,
	bar: true,
});
```
Errors:
```
    19: const mapStateToProps = (): $Shape<Props> => ({
                                                      ^ Cannot return object literal because property `bar` is missing in object literal [1] but exists in `Props` [2].
        References:
        19: const mapStateToProps = (): $Shape<Props> => ({
                                                          ^ [1]
        19: const mapStateToProps = (): $Shape<Props> => ({
                                               ^ [2]
    19: const mapStateToProps = (): $Shape<Props> => ({
                                                      ^ Cannot return object literal because property `foo` is not writable in property `foo`.
```
[Try Flow](https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDGMA0cDecAKArlEgMITgQB2SV8AvnAGZQVwDkJ6M7A3AFD8YATzBICrMAGc4AXlwAffgEgA1EwgQAXHABGmgDaoqmfgvoD+aAyikyAssPKUadOEgAeMWgBMZREmdIVxgAHnxJKQA+XBUpGBQYYDQ4HyQmFEIDGAiIaTlY5WUNbWYUAykkU2ULQWUSKjSoAAoASkL6pBhiKjhmlSLQn2AANyicGAALYCkAOjBI2ZK4AH4OEvY4HXYqCA36UIB6YbGB1oEa-npBNGp4uBAUMABlBO8AFQhc-Pk2nQASZ6TJ5IcKRGKyGLNHAqEo6GBQQhVFS6FBQeGI5H0c5AA)
I was only expecting the first error.

**Comment by phpnode** [comment] 2018-06-05 22:47
The type spread operator can help you here. For @CGamesPlay's scenario

```js
// @flow

type Foo = {
  +bar: "baz";
};

const f: Foo = { bar: "baz" };

const g: $Shape<{...Foo}> = { bar: "baz" };
```


and in @zeorin's:

```js
import React, { PureComponent } from 'react';

type Props = {|
	+foo: boolean,
|};

class MyComponent extends PureComponent<Props> {
	static defaultProps = {
		foo: false,
	};

	render() {
		return (
			<div>{this.props.foo ? 'foo' : 'nofoo'}</div>
		);
	}
}

const mapStateToProps = (): $Shape<{...Props}> => ({
	foo: true,
	bar: true,
});
```

**Comment by zeorin** [comment] 2018-06-06 08:17
@phpnode That's great! I knew that the type spread operator is a way to turn an `$Exact` type into a regular inexact one, but didn't know that it would also make the props invariant.

Is that to say that `$Shape` doesn't have a bug and it's working as intended, or is it still a legit bug, and using the type spread operator is merely a workaround instead of The Way™?

**Comment by vicapow** [comment] 2018-09-14 21:48
Curious if someone from the FB team would be able to verify if this is a bug or flow working as expected?

**Comment by Eoksni** [comment] 2018-09-21 10:29
Using the type spread operator is not really a solution, it just destroys "readonlyness" and after that $Shape works ok.

```js
type Props = {|
	+foo: boolean,
|};
const value: $Shape<{...Props}> = { foo: true };
value.foo = false; // can write now without any error
```

**Comment by villesau** [comment] 2018-12-23 01:49
Looks like this is fixed in 0.83.0.

**Comment by ericsoco** [comment] 2019-01-31 05:18
Yup. Just came across this again, bumped to `0.83.0`, error went away. This should be closed.

**Comment by TrySound** [comment] 2019-01-31 08:36
Thanks

**Closed by TrySound** 2019-01-31 08:36 UTC
