### ISSUE TITLE
A generic type seems to be incompatible with itself - or am I wrong?

### ISSUE THREAD

**Issue by esbenvb** [facebook/flow#6544] opened 2018-06-29 00:09 UTC
I tried to strip down my code as much as possible, while retaining the error - [try it here](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMZ6RayqgDkWJ5tiiOAnuoaAKIB2OWNgEFyyWLwAqHLgF46hLFSy1QAHzrxiWXsl4BzFetoBnHMRwBXY81bTQAeXQ4xvADwjn4gMKwAJoQA+UDkAb1VEUFAAajJPXh9-AC5QDxcEwgAaCOj2TmS+AWFRcSlOLNUAXxZcrlTxACEtRziAEUJIXWQ443di+L9A4NAQ7KiAbQLBOslpAF1k5pdeuPSAsdmsqsRIC14+0D1CHGnjADFsAGUzHEJltIGM0CvzQlWACmzTF+Tnm-SsyKxFzGZLTNodHTdO7eB5Pa6vAYBAGgUgAC1gxkIvGm6QA-KC+ulEABKAlxRpYRbicGdKE4xHDbIMSzaYagL6WEGgdaPTTaXR6ZI80AKJRC2agKpbGopPr1Cw4HANLQABSo6B69P8QVCo18yGMxAARtBCL5kkbYLBTcReMiorAnMCyS4KVTeDTIcDof1tfbvOiMYR3ck3kDxC6Yf5icEgqhkAAPM2bFikcSmWXkhVK3gUoY+94jSKO7rI-WGk3J7IBq2Y92bSO57PKrBqx2awmImMyIKufUANxR0GIxmMADliKhCDIAETTeWKlsz0DAALVOxg9q071azJwl6rIZF7m7+bDcKRSK8QgJnC-Qg-eH-bKRGr5fhTPqlTLZSop2ycE8bCmIQqCuPeh6hBe7Lwo+B4PIglQsLoNxYJAZBcBcwE3KgnpdEsu6PBBDLHlExjYaBJyNnhdKdv4RFPoiADciDSnYbYauBFGoIRQEgagxHake0FkdxPzcVx-GCYE9rkfxNEuOJ8lbl64iSThvFYVJjF+ohWw3pguBDiOxgELAlo4AAkrwXx7LcWkaXRe4OaB0lBDeNy8L4plELEAB0PgYOIWI4K42QcT0Lk8U5RHcW5iBBMeqK2r4ppRdMQxhk5SmOSsAzdolL4oum1qEH5fK8FleXRtkWyRAwXkKG8MbHpEaY2XgrWXnJOHJCEMEvJKyKXuy3EKeIw2SkMOCogafnoOqxgsCNzIWKyHwjZEfbIIOpDDqOE5TrO+DmbAVkdbapCEDOa6bZePoLjmFJFXd5bGqavgyCE6HQJiVR3SNNZBu6X0zXNyVeWl3HTP9APFk66ZfYcxx9Gclzwm8HJ7j1oHjbwfk49F3TErDd2ri9oCuMAA63ZexK1axiBAA)

I get the following error:
```
Cannot create ActionButtonBar element because SystemActionCode [1] is incompatible with SystemActionCode [2] in type
argument ActionCode [3] of property options.

 [3] 11│ type ActionBarOptionDefinitions<ActionCode> = {
       :
 [1] 47│   +systemActions: ActionDefinitions<ActionCode, StateCode>;
       :
 [2] 58│   handleSystemAction = (actionCode: SystemActionCode) => {
       :
     67│
     68│     return (
     69│       <div className="RobotInstance">
     70│         <ActionButtonBar
     71│           disabled={false}
     72│           onChooseOption={this.handleSystemAction}
     73│           options={getActionsForState(state, systemDefinition.systemActions)}
     74│         />
     75│       </div>
     76│     )
     77│   }

```

Apparently, it seems like my `ActionButtonBar` is not accepting the same type for the `options` prop as for the `onChooseOption` prop.

Setting `onChooseOption={ ()=>{} }` makes the error go away, which confirm my thesis.

But how do I make it happy? I guess the `getActionsForState()` should return a `ActionBarOptionDefinitions<ActionCode>` which is compatible with the rest of the generic types?

Thanks in advance for your support!

**Comment by wchargin** [comment] 2018-10-09 07:18
Duplicate of #6978. (Yes, this issue was earlier, but that issue’s repro
is far simpler.)

**Comment by goodmind** [comment] 2019-06-22 19:56
Duplicate of #6978

**Closed by goodmind** 2019-06-22 19:56 UTC
