### ISSUE TITLE
Destructuring with default values in function argument breaks union type

### ISSUE THREAD

**Issue by egeriis** [facebook/flow#6852] opened 2018-09-06 10:23 UTC
[Simple reproduction](https://flow.org/try/#0C4TwDgpgBAyglgL2gXigZ2AJzgOwOZQA+UOArgLYBGEmA3AFD0BmpOAxsHAPY7pfkQAYqzYAKAN5QANhGDAaMMAEM2uAqgAMUAL4AuKJJlyFy1fn3wkOgJQH62xmn5CRE6bPmZFKtfq3brBicBYXY3I09vMzx9AHIARjAAD1ibBiA)

When destructuring an object function argument and providing a default value to one of the keys, it appear to break union types.

In linked example `someFunc` takes one argument, and object, which are expected to have one property, `letterSpacing`. This is typed to be `string | number`. Calling `someFunc` with this property set to either string or number works fine. However, when providing a default value when destructuring, an unexpected errors is shown.

**Comment by superhawk610** [comment] 2018-09-20 14:39
Here's a variation on typing this that throws a slightly different error - [Try Flow](https://flow.org/try/#0C4TwDgpgBACgTgezAZygXigbwFBSgdwEsATYACwH4AuKAOwFcBbAIwjigB8plg5DaA5tgC+AbmzYAxglo8oAYQSMwMiLWDooAChx4ipMpoDkARgAMZgKRGANCJrwkyAJToAfHXoAbL0A).

```js
type Props = {
  width?: number | string
};

const Component = ({
  width = '100%',
}: Props) => null
```

```
6:   width = '100%',
     ^ string [1] is incompatible with number [2].
   References:
   2:   width?: number | string                      ^ [1]
   2:   width?: number | string
                ^ [2]
---------------------------------------------------------------------
6:   width = '100%',
             ^ string [1] is incompatible with number [2].
   References:
   6:   width = '100%',
                ^ [1]
   2:   width?: number | string
                ^ [2]
```

**Comment by goodmind** [comment] 2019-02-13 21:43
Duplicate of #2093

**Closed by goodmind** 2019-02-13 21:43 UTC
Labels: bug
