### ISSUE TITLE
flow 0.42 possible memory leak

### ISSUE THREAD

**Issue by vonovak** [facebook/flow#3565] opened 2017-03-23 10:55 UTC
I'm using flow 0.42 with VScode on the latest OS X.

![screen shot 2017-03-23 at 11 01 00](https://cloud.githubusercontent.com/assets/1566403/24244503/85992810-0fbf-11e7-96cb-bebdb3f30df0.png)

**Comment by vkurchatkin** [comment] 2017-03-23 13:18
What makes you think it's a memory leak?

**Comment by vonovak** [comment] 2017-03-23 15:06
@vkurchatkin can't say for sure it is one, but the consumption keeps growing and the mac starts swapping. I have 16GB of ram and the project has ~13kloc so at least I'd say the consumption is much higher than expected.

**Comment by aikar** [comment] 2017-03-29 05:05
even if it's not a 'leak', flow has no reason to need to use 10G of memory.

**Comment by overneath42** [comment] 2017-03-29 15:31
I can confirm this is happening for me. VS Code 1.10.2, Flow 0.42, using the Flow Language Support plugin. This is what I saw after having one project open for for maybe an hour and a half:

<img width="604" alt="screen shot 2017-03-29 at 11 25 22 am" src="https://cloud.githubusercontent.com/assets/1739079/24462892/2d968906-1473-11e7-9e3a-5134994463ce.png">

Not sure if this is an issue with Flow itself or the extension.

**Comment by EvNaverniouk** [comment] 2017-03-29 22:55
I am also seeing flow's memory usage get out of control (2+ GB). Have to restart my Mac frequently to resolve.

**Comment by tlrobinson** [comment] 2017-04-03 15:22
Who can beat 41.61 GB?

<img width="538" alt="screenshot 2017-04-03 08 20 57" src="https://cloud.githubusercontent.com/assets/18193/24616637/8c9dce4c-1846-11e7-9bdc-c857ff357f0b.png">

**Comment by rkurbatov** [comment] 2017-04-04 21:08
The same for 0.41. Our CI container which is limited to 4G stops due to large memory consumption. Is it possible to limit flow somehow? It's `flow check`, not server mode and errors are sporadic. Seems like flow running lot of processes consumes at some point more than container has.

**Comment by samwgoldman** [comment] 2017-04-06 22:49
Does Flow version 0.43.1 improve things?

**Comment by Sharlaan** [comment] 2017-04-09 13:51
@samwgoldman Nope, i just got a `out of memory`error too ...
Thanks to @gaeron for pointing me here.

**Comment by samwgoldman** [comment] 2017-04-09 17:52
@Sharlaan how much memory do you have available?

**Comment by Sharlaan** [comment] 2017-04-09 21:05
total 8G, but i don't know how to check how much Flow consumed exactly, i thought the message 'out of memory' self-explanatory, isnot it ?

**Comment by ekosz** [comment] 2017-04-09 21:06
@samwgoldman I've gotten OOM with 0.43.1 with 16 GB. Adding

```
[ignore]
<PROJECT_ROOT>/node_modules/.*
```
Made the issue go away.

**Comment by Sharlaan** [comment] 2017-04-09 21:14
@ekosz i just retried `yarn flow` with your line in my flowconfig file, but still get the OoM error.

I'm on Windows10 / Webstorm2017 / create-react-app 1.3.0

**Comment by zebMcCorkle** [comment] 2017-05-25 23:02
Ditto on Ubuntu 16.04, I've seen it reach 13GB on my machine with 16GB, as well as 13% CPU on an 8 thread machine. (Using Nuclide in Atom)

```
$ flow version
Flow, a static type checker for JavaScript, version 0.46.0
$ uname -a
Linux zeb 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
$ ps aux --sort -rss | grep flow
zmccork+ 15921 42.9 72.9 40161948 11893344 ?   RN   17:56   0:50 /usr/lib/node_modules/flow-bin/flow-linux64-v0.46.0/flow server --from nuclide --max-workers 6 /home/zmccorkle/Documents/visualizations
zmccork+ 15932  0.2  0.0  31060 14608 ?        SN   17:56   0:00 /usr/lib/node_modules/flow-bin/flow-linux64-v0.46.0/flow
zmccork+ 16419  0.0  0.0  29644  9384 ?        S    17:57   0:00 /usr/lib/node_modules/flow-bin/flow-linux64-v0.46.0/flow coverage --json /home/zmccorkle/Documents/visualizations/components/Row.js --retry-if-init false --retries 0 --no-auto-start --from nuclide
zmccork+ 15927  0.0  0.0 27327252 9332 ?       SN   17:56   0:00 /usr/lib/node_modules/flow-bin/flow-linux64-v0.46.0/flow
zmccork+ 15931  0.0  0.0 27327252 9300 ?       SN   17:56   0:00 /usr/lib/node_modules/flow-bin/flow-linux64-v0.46.0/flow
zmccork+ 15928  0.0  0.0 27327252 9276 ?       SN   17:56   0:00 /usr/lib/node_modules/flow-bin/flow-linux64-v0.46.0/flow
zmccork+ 15930  0.0  0.0 27327252 9256 ?       SN   17:56   0:00 /usr/lib/node_modules/flow-bin/flow-linux64-v0.46.0/flow
zmccork+ 15929  0.0  0.0 27327252 9244 ?       SN   17:56   0:00 /usr/lib/node_modules/flow-bin/flow-linux64-v0.46.0/flow
zmccork+ 15926  0.0  0.0 27327252 9200 ?       SN   17:56   0:00 /usr/lib/node_modules/flow-bin/flow-linux64-v0.46.0/flow
zmccork+ 16489  0.0  0.0  14224   964 pts/3    S+   17:58   0:00 grep --color=auto flow
```

![System Monitor](http://i.imgur.com/f1giHKA.png)

**Comment by barbalex** [comment] 2017-11-07 11:03
This seems to be rather prominent in the issues. Maybe related issues found after a five minute search:

- https://github.com/facebook/flow/issues/5271
- https://github.com/facebook/flow/issues/4370
- https://github.com/facebook/flow/issues/4070
- https://github.com/facebook/flow/issues/4046
- https://github.com/facebook/flow/issues/3565
- https://github.com/facebook/flow/issues/3370
- https://github.com/facebook/flow/issues/2152

**Comment by JofArnold** [comment] 2018-02-16 12:19
See my comment here for one way of preventing this: https://github.com/facebook/flow/issues/2152#issuecomment-366221060

**Comment by mrkev** [comment] 2018-07-04 07:47
Closing since there's other issues discussing this in greater detail. This should probably continue on #2152.

**Closed by mrkev** 2018-07-04 07:47 UTC
Labels: nontermination / perf
