### ISSUE TITLE
Variance lost when using type spread operator

### ISSUE THREAD

**Issue by danwang** [facebook/flow#5765] opened 2018-02-03 23:33 UTC
[flow try link](https://flow.org/try/#0C4TwDgpgBAYg9nAPAagCoD4oF4oG8BQUUywAXFKgDT4C+A3PvqJFAEICGATihtnoVAB0wgCQBRAB7sAxsETwkGdNXqNpcAHYBnYFABm5BYh2cAlhoDmmHAAoNAVwA2j8uw0gAlA3wB6H1AB5AGt2EHwbA1gEY2AzS3QvcMijAFtTCQgAEwTvPygAOThdOBCwiPIObhNzK0Tyti5ENIzsryA)

When using the `...` type spread operator to extend record types, it seems like field variance is lost.

For example:
```jsx
type Foo<+T> = {
  +t: T,
};

type Bar<+T> = {
  ...$Exact<Foo<T>>,
};

const f: Foo<string> = (null: any);

// Okay
(f: Foo<string>);
(f: Foo<mixed>);

// Not okay
(f: Bar<string>);
(f: Bar<mixed>);
```

Is there something else I could try to make this work? 😃

**Comment by SamChou19815** [comment] 2024-03-19 04:23
Closing as duplicate of https://github.com/facebook/flow/issues/5222

**Closed by SamChou19815** 2024-03-19 04:23 UTC
Labels: Typing: spread, Typing: property variance, Typing: destructors
