### ISSUE TITLE
Add % typed coverage info

### ISSUE THREAD

**Issue by Kegsay** [facebook/flow#720] opened 2015-08-14 16:17 UTC
Google's Closure Compiler tells you what percentage of your project is typed, which looks something like this:
```
WARNING: 0 error(s), 1 warning(s), 91,5% typed
```
This can serve as great way to gamify the often tedious nature of adding type information to functions once you've done the core parts of your project. It would be even better to get test coverage style reports indicating where type information would be required (cannot be inferred) to bump up your %.

**Comment by gregwebs** [comment] 2015-08-20 12:04
This seems similar to [noImplicitAny](https://github.com/facebook/flow/issues/298)

**Comment by danvk** [comment] 2015-11-05 14:03
Dupe of #276

**Comment by samwgoldman** [comment] 2015-11-16 22:05
@mroch landed `flow coverage` in 0ae34ae551b3ba17ccd0f9fbadb3cd73b3d17ddc

**Closed by samwgoldman** 2015-11-16 22:05 UTC
