### ISSUE TITLE
Spread Operator with $Shape

### ISSUE THREAD

**Issue by orlandoc01** [facebook/flow#7041] opened 2018-10-18 22:42 UTC
The following code results in an unexpected flow error:

```
type Test = {|a: number, b: number|}
type ShapeTest = $Shape<Test>;
type ManualShapeTest = {|a?: number, b?: number|};


const one: {...ManualShapeTest} = {a: 1};
//Unexpected Flow Error
const two: {...ShapeTest} = {a: 1};
```
Can be seen [here](https://flow.org/try/#0C4TwDgpgBAKhDOwoF4oG8A+BDAXFAdgK4C2ARhAE4A0UpeRZlGAvgFCiRQDKAFlpHEQooAEl78IAHkHAAfAG524aAFksRLABtxAhElSYsAfnoly1WiYJmmzRa1YBjAPb4hriHjQA6X2o3afLqIzMJouFAAjHasAPSxAKIAHpCOSAkUFM4UTq5CwADuzl6+3joQMqEGEdGKQA) on the "try flow" page.

I would have expected `ManualShapeTest` to be equivalent to `ShapeTest` and, as a result, both assignments to `one` and `two` should be valid. However, flow is saying the assignment to `two` is invalid because I'm missing a `b` property.

**Comment by wchargin** [comment] 2018-10-21 16:40
Duplicate of #6906?

**Comment by goodmind** [comment] 2019-05-16 13:47
Duplicate of #6906

**Closed by goodmind** 2019-05-16 13:47 UTC
