### ISSUE TITLE
Flow forgets type refinement in the presence of callbacks

### ISSUE THREAD

**Issue by wereHamster** [facebook/flow#2484] opened 2016-09-19 07:06 UTC
``` javascript
/* @flow */

type T
  = {type: 'ONE', one: number}
  | {type: 'TWO', two: {x: number}};

function f(t: T) {
  switch (t.type) {
    case 'TWO':
      return [1,2].map(x => x !== t.two.x);
  }
}
```

(it doesn't make any difference whether I use a switch/case or if).

Flow somehow loses the type refinement in the case block. It SHOULD know that `t.two` is of type `{x:number}`, but because I access it inside a callback, it forgets that information. If I change the case block to:

```
case 'TWO':
  const two = t.two;
  return [1,2].map(x => x !== two.x);
```

then flow doesn't complain anymore.

**Comment by mjadobson** [comment] 2016-09-19 13:30
Dupe of https://github.com/facebook/flow/issues/2318 I think

Encountered this when working with redux as well.

**Comment by mroch** [comment] 2016-09-19 19:12
this is discussed a bit [here](https://flowtype.org/docs/dynamic-type-tests.html#caveats)

since Flow doesn't know when the callback executes, it pessimistically assumes the worst.

**Comment by vkurchatkin** [comment] 2016-09-19 20:53
@mroch are there plans to introduce something like `const` attribute for functions?

**Comment by calebmer** [comment] 2017-08-01 15:30
This is intentional since in your callback we don’t know if the object or the function argument has been mutated. Please feel free to use covariant properties (`+`) and constant function parameters (reassign or use `experimental.const_params`)

**Closed by calebmer** 2017-08-01 15:30 UTC
