### ISSUE TITLE
Catch uninitialized property errors

### ISSUE THREAD

**Issue by danvk** [facebook/flow#802] opened 2015-09-15 20:09 UTC
Show Flow be able to catch errors of this sort?

``` javascript
class A {
  foo: string;

  super() {
    // missing:
    // this.foo = "";
  }
}

var a = new A();
```

When you call `new A()`, `foo` is `undefined`, which is not a valid `string`.

**Comment by vkurchatkin** [comment] 2017-02-09 18:19
Duplicate of https://github.com/facebook/flow/issues/650

**Closed by vkurchatkin** 2017-02-09 18:19 UTC
Labels: feature request
