### ISSUE TITLE
0.33 regression - cannot decide between function and map

### ISSUE THREAD

**Issue by aaronjensen** [facebook/flow#2543] opened 2016-09-29 16:09 UTC
```
// @flow
import React from 'react'

type Example = () => number
type Examples = Example | { [when: string]: Example }

const itRenders = (examples: Examples) => {}

itRenders(() => 3)
```

```
9: itRenders(() => 3)
             ^ arrow function. Could not decide which case to select
7: const itRenders = (examples: Examples) => {}
                                ^ union type
```

https://flowtype.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMZ6RayqgDkWJ5tiiOAnuoaAKIAexGaFwC8oABQBKUMIB8oAHYBXVACNCWVhy58B6IQGdpPfoK4AfUAG9QAbXgALQvIBcofTizJ5AcwC6rnVNQAF8WUlh5d1BkHCJ5ABN1Q1ExQhM9Qn0A9IMpWStQlFinRKx9MUlpOQBmCUQgA

**Comment by gcanti** [comment] 2016-09-30 06:13
Oddly switching the order of the union fix the error

**Comment by aaronjensen** [comment] 2016-09-30 15:14
Indeed, that does fix it, I'll use that for now, thanks. That definitely makes this seem like a bug then.

**Comment by gcanti** [comment] 2016-09-30 15:59
> this seem like a bug 

@aaronjensen Yeah, unless `|` is not commutative by design :)

**Comment by gcanti** [comment] 2016-10-28 04:19
@aaronjensen actually they are **not** commutative https://github.com/facebook/flow/issues/2074#issuecomment-232801891

> This is a design choice. Intersections and unions are necessarily ordered to make the process of selecting the best match predictable.

**Comment by aaronjensen** [comment] 2016-10-28 05:29
@gcanti interesting, thanks for that update. Even without commutativity, I still think this is a bug, as I do not understand how that function could be ambiguous with a map.

**Comment by gcanti** [comment] 2016-10-28 05:35
It's fixed on master though [try](https://flowtype.org/try/#0JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wChSYBPMJOAUQA8VwAbWgXjgAoBKOdgHxwAdgFcQAIyRQK1Wo2Zg2AZ370mrWgB84AbzgBtAO4ALJMIBccZTCjBhAcwC6VhZrgBfcmgjCbcYBhkYQATaVVOLiQNJSRlVxiVPkE9L1JA4LCoZS5efiEAZh4gA) (select the "master" option to the right)

**Comment by aaronjensen** [comment] 2016-10-28 05:41
Ah indeed. Interestingly enough, this typechecks even on master:

```js
const x: { [when: string]: Example } = () => 3
```

wat?

**Comment by aaronjensen** [comment] 2016-12-09 23:57
So the reason for this is that flow sees `() => 3` as the value of the `$call` property. This seems like a bug.

**Closed** 2016-12-10 00:01 UTC
