### ISSUE TITLE
When using Object as maps, Object.values treats values as mixed

### ISSUE THREAD

**Issue by xtinec** [facebook/flow#2221] opened 2016-08-09 21:18 UTC
I'm using objects as maps in the example below. It appears the type of Object.values is an array of mixed as opposed to an array of the Point type I defined.

``` javascript
type Point = {
  x: number,
  y: number,
};
type PointMap = { [key:string]: Point }

const foo: PointMap = { "1": { x: 5, y: 6}, "2": { x: 7, y: 8} };

Object.values(foo).map(p => {
  return p.x;
})
```

It appears if I do use Object.keys instead, flow can correctly infer the type of foo[key]

``` javascript
Object.keys(foo).map(key => {
  return foo[key].x;
})
```

This seems like a bug in flow, as we use Object as a map here and the type checker has enough info to correctly infer the type of Object.values(). Yes?

**Comment by gabelevi** [comment] 2016-08-10 02:27
### Why does `Object.values` return `Array<mixed>` currently?

At the moment, if you have a variable `obj` with the type `{ foo: string }`, what does that mean? It means that `obj.foo` has the type `string`. But it doesn't mean that `obj` only has a single property. There may be other properties. This is because we let you write code like this:

```JavaScript
function foo(obj: { foo: string, bar: number }) : { foo: string } {
  return obj;
}
```

Allowing subtypes to have fewer properties than super types makes structural subtyping with object types work well. But it means when you write `Object.values(obj)`, we can't say with certainty what types are in the resulting array.

### How do I specify an object with ONLY certain properties?

As of v0.30.0, there is no way. However, @bhosmer is here to save the day! He's in the middle of landing the `$Exact` magic type. `$Exact<{foo: string}>` is the type of an object who has exactly one property named `foo` that is a `string`.

### How does this help with `Object.values`?

Building on top of this, @samwgoldman is updating the types of `Object.{entries,keys,values}` to offer better types when used with exact types. So `Object.keys(obj)` should return `Array<'foo'>` when `obj` has the type `$Exact<{foo: string}>`. This might make v0.31.0, but if it doesn't it will definitely make v0.32.0.

**Comment by taion** [comment] 2016-10-27 16:46
I think this and https://github.com/facebook/flow/issues/2174 are duplicates.

@gabelevi Does what you're saying apply for map types, though? It seems like maps don't have this issue? As in the following gives me a type error on `a`:

```js
const a: {[key: string]: string} = {b: 3};
const b: {a?: string} = {b: 3};
```

Could this just be a matter of adding an overload for the case where the argument to `Object.values` or `Object.entries` is a map type?

**Comment by dsimmons** [comment] 2016-10-27 20:15
Having this exact same problem right now.

Use case:

```JavaScript
// types.js
export type FieldLabel =
    'SOME_FIRST_LABEL'
  | 'SOME_SECOND_LABEL'
  // ...
;

// constants.js
import type { FieldLabel } from './types';

export type FieldLabels = { [key: FieldLabel]: FieldLabel };
export const FIELD_LABELS: FieldLabels = Object.assign({}, ...[
  'SOME_FIRST_LABEL',
  'SOME_SECOND_LABEL',
  // ....
].map(label => ({ [label]: label })));


// elswhere, someFile.js
import type { FieldLabel } from '../types';

import { FIELD_LABELS } from '../constants';

const fieldLabels: Array<FieldLabel> = Object.values(FIELD_LABELS).sort();
```

Results in: `string enum This type is incompatible with (:0:1,0) mixed (/private/tmp/flow/flowlib_28d43509/core.js:52:39,43) [javascript/flow]`

**Comment by montogeek** [comment] 2017-01-20 12:33
Another simple reproducible case:
https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAKMAhgMYEC8YA3qmGAG4kwCueAXGAM4YBOASwB2Ac1QBfdNnxFSFAMLkAFlVr0wAbQEATLr0GiAul2Lk8E9GThDeRADIBBeQFEA+vKcAJZybl5FZCpg1DTiANyW1rbMbKoA5Bh4vHERqISOLu5ezhoJSRhxhsG0TCzsXHFQcHBxYOHoAPIARgBWeGQYAHQx7NwAFOlObh7y3gCUnVDC2n19OH6+ZmOLFMEAfGoMW3x4GKx8QmDzZt1lVJTUPXgR4mNhQA

**Comment by mull** [comment] 2017-02-22 12:46
Another very simple reproducible case, just in case it helps: https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwCSAJmALxgDO6ATgJYB2A5gNwY74Byc6tUtAxgEMecemTABvVGDC0iALkJEANNLABbXBQqDGuRVTpNVAX1Zs8YAMrph+cgBIAogA9B-dAB4JAbQDWuJiKxAC6ilw8fEIi9CYAfOb8olSUtuj61mn2kmaoqEn0KfTcvALCtKLhJVHlouISsgpgAOQAjM3KGlo6eorNcLTNYLlUdj7FkWUxAHRyIeITpdEV9InJ6GCLNTEUVZPLoj7z5ADyAEYAVrge0wBugjAArloAFKPpAJSsQA

I gave using $Exact<> an attempt here but looks like I might be using it wrong?

**Comment by verkholantsev** [comment] 2017-03-29 18:44
When I try to use exact notation to map

```js
/* @flow */

const a: {|[string]: string|} = {'a': '1'};
const values: Array<string> = Object.values(a);
```

I get these errors

```bash
3: const a: {|[string]: string|} = {'a': '1'};
                                   ^ property `a`. Property not found in
3: const a: {|[string]: string|} = {'a': '1'};
            ^ object type
4: const values: Array<string> = Object.values(a);
                       ^ string. This type is incompatible with
[LIB] static/v0.42.0/flowlib/core.js:52:     static values(object: any): Array<mixed>;
                                                                               ^ mixed
```

1. Can you please tell me, why does exact notation not working with _Object.values_ in this case?
2. Why is it not possible to declare some variable as object map and then assign an object literal to it?

**Comment by vkurchatkin** [comment] 2017-03-29 19:18
Type declarations like `{|[string]: string|}` are not really useful. Exact implies that all properties are known in advance.

**Comment by verkholantsev** [comment] 2017-03-29 19:23
@vkurchatkin Yes, that makes sense. But what how to deal with `Object.values` returning `Array<mixed>` for `{[string]: string}`?

**Comment by villesau** [comment] 2017-05-23 10:35
How the below should be written? Even when everything is exact, that doesn't work with 0.45.0

```
type Thing = {|name: string, b: number|};
type Things = {|[id: string]: Thing|};
const getSortedArray = (things : Things) => Object.values(things).sort((a, b) => a.name.localeCompare(b.name));
```

This is causing headache too often.

**Comment by madole** [comment] 2017-08-16 06:08
Any solution for this? Running into this all afternoon :(

**Comment by aikar** [comment] 2017-08-21 19:24
Just hit this too :(

**Comment by jcready** [comment] 2017-08-21 21:44
The reason this isn't supported was explained pretty simply by @vkurchatkin in [my (now closed) PR](https://github.com/facebook/flow/pull/4527):

> Here is a simple example:
> 
> ```js
> function test(val: { foo: string }) {
>   Object.values(val).forEach(v => {
>   	v.toLowerCase();
>   });
> }
> 
> test({ foo: 'x', bar: 123 });
> ```
> 
> This going to pass typechecking, but fail at runtime

My PR would've set the following function type signatures for `Object.entries`, `Object.values`, and `Object.keys`, but was closed after it was pointed out how unsound these are:

```diff
-    static entries(object: any): Array<[string, mixed]>;
+    static entries <T> (o: { +[s: string]: T }) : Array<[string, T]>;
+    static entries <T> (o: Array<T> | $ReadOnlyArray<T>) : Array<[string, T]>;
+    static entries (o: any) : Array<[string, mixed]>;

+    static keys <T> (o: { +[key: T]: any }): Array<T>;
     static keys(o: any): Array<string>;

-    static values(object: any): Array<mixed>;
+    static values <T> (o: { +[s: string]: T }) : Array<T>;
+    static values <T> (o: Array<T> | $ReadOnlyArray<T>) : Array<T>;
+    static values(o: any): Array<mixed>;
```

**Comment by villesau** [comment] 2017-08-22 07:09
@jcready that's not the case with exact types where we know exactly what the object contains.

**Comment by TiddoLangerak** [comment] 2017-08-22 13:43
I think the above definitions are *almost* correct, but the object-as-map version should be replaced with this:

```javascript
static values<T, O : { +[string] : T }>(val : $Exact<O>) : Array<T>;
```

(and likewise for `keys` and `entries`).

I'd love to provide a patch myself, but I currently don't have time to get the flow build working. I might give it a shot later this week, if no-one else took it before me.

**Comment by asolove** [comment] 2017-08-22 14:22
In a comment on another issue, @samwgoldman mentioned that support for better object-as-dictionary typings on exact objects was already his top priority. I think this issue might be closable since his work on that is already underway.

**Comment by aikar** [comment] 2017-08-22 14:30
Let's close it when it's actually fixed :P

**Comment by jcready** [comment] 2017-08-22 14:31
@villesau @TiddoLangerak the problem is that indexers in exact object types don't work as you'd expect:

```js
declare class Obj {
  static values <T> (o: {| +[s: string]: T |}) : Array<T>; // exact object w/ indexer
}

function test(val: {| foo: string |}) { // exact object w/o indexer
  Obj.values(val).forEach((v) => {
    v.toLowerCase();
  });
}

test({ foo: 'bar' });
```

The results in the following error:

```
6:   Obj.values(val).forEach((v) => {
                ^ property `foo`. Property not found in
2:   static values <T> (o: {| +[s: string]: T |}) : Array<T>;
                           ^ object type
```

Alternatively if we use @TiddoLangerak's definition for `values`:

```js
static values<T, O : { +[string] : T }>(val : $Exact<O>) : Array<T>;
```

Then type-at-pos reports that the `v` parameter inside the `forEach` function is `(unknown)`.

Unrelated, but @asolove I really wish the flow team would stop closing issues before they've actually **fixed** the issue. There seems to be an odd treatment of issues in this repo where they will be closed when the issue has simply be triaged or someone says they are going to make said issue a priority. Issues should be referenced in commit/PR messages so they can be closed automatically when the code actually gets merged to master.

**Comment by TiddoLangerak** [comment] 2017-08-22 14:52
You're right, I completely missed that `v` became untyped 😞

**Comment by underoot** [comment] 2017-11-23 10:21
[Seems that problem actual now](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAKcAlgHYZgC8YA3qmGAB4BcYZArgLYBGeATgBoGYLG068BwgL4BuTLgLFyGALIBDHNTpgA2gGs8YgM4Z+5AOYBdNsophp6AMZwypsFDhxbpChq00tGAARACMwWxBrGAArIKibABs0vHBAEwROtEA7PFiYAAc0g7yqADyPABWeE4YAHQAbuowHHjGABSecACUdVya7QEAfHQi-HgYHPxkYDh1TPLS3UA)

**Comment by adek05** [comment] 2018-01-10 12:05
Is anyone looking at resolving this?

**Comment by A-Tokyo** [comment] 2018-01-11 06:09
Still facing the problem with 0.61.0

**Comment by allmaxgit** [comment] 2018-01-17 04:39
Actual in 0.63.1

**Comment by sahrens** [comment] 2018-02-13 00:39
@gabelevi: Any progress on this when working with exact types now that they are a thing?  It is quite a ways since v0.32:

> So Object.keys(obj) should return Array<'foo'> when obj has the type $Exact<{foo: string}>. This might make v0.31.0, but if it doesn't it will definitely make v0.32.0.

**Comment by sibelius** [comment] 2018-02-13 22:11
another repro https://flow.org/try/#0KYDwDg9gTgLgBDAnmYcCCAVZqC8cDeAUHHANoDWwiAXHAM4xQCWAdgOYC6tLArgLYAjYFFIcANIQC+AbkKFQkWHADGEFgxUBDADbKe2zTGAYIMHXDwAKOsG3BlRgCYBlYIbq1M2AJTd+QqAsAPgJiOChgGB4oFjgAeQEAK3sYADoANx0eYDprWxTgFzcYOm9UiMceZWBLS01lPT59Q2gxFWiIlhgANSzgb2DQkhJVdXgbNj5gLpMzbQt2qE6evvLCqpq8yemYNAb+ZphW+mBtrt7tbIGcEKJh4YiomJOz3f2mgyPAgGoXqfO+rJ7pI2gAGbyyMIkR7RWL1RqHaBwX4Tf4wWY6IFwEFwcGyGSEIA

**Comment by sahrens** [comment] 2018-02-14 15:27
Note that `Object.keys` works now, but `Object.values` and `Object.entries` are still broken. Trivial repro:
```
function test(obj: {|foo: string|}): Array<string> {
  return Object.values(obj); // still `mixed` and flow fails
}
```
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5sx8BTAZ3wAo4AjAKwC4wBvAHyjjleoCdC2AOYcAvgEpWAQX78AhgE8APAKHCAfO1Rgw-cvkz9SAeSbkCAOgBu8mJip0mEgNyoxQA

**Comment by Whispers12** [comment] 2018-02-18 14:26
Yeah, have same issue, but `Object.keys(obj).map(key => obj[key])` solve problem

**Comment by bdrobinson** [comment] 2018-03-11 12:41
And you can trivially make that a bit more readable by making a flow-compatible helper function to replace `Object.values` with:

```js
const values = <T>(obj: { [string]: T }): Array<T> =>
    Object.keys(obj).map(k => obj[k])

values({ "key1": "value1", "key2": "value2" }) // ["value1", "value2"]
```

**Comment by marco-fp** [comment] 2018-03-15 15:05
Facing this problem right now.
The fact that this bug has been open for 2 years is ridiculous.

**Comment by dhoulb** [comment] 2018-04-15 21:05
The `Object.keys()` approach is less performant as you're doing an extra key lookup against the object (`obj[k]`) (and instantiating the arrow function that's used in `map()`). I know it's a micro-optimisation, but I still think it's bad practice to mangle good code just to get Flow working.

Personally I think the right way to deal with this is to mark it with `$FlowFixMe` until Flow is flexible enough to mark it up without hacks (same as Symbol keys in objects, etc). Then just keep an eye on the changelog and see when these things get fixed.

```js
const numberObject = { a: 1, b: 2, c: 3 };

// $FlowFixMe Object.values() returns mixed[] when it should return number[] https://github.com/facebook/flow/issues/2221
const vals: number[] = Object.values();
```

I'm pretty sure there aren't major downsides to this approach (but would love feedback). I guess language things like this are the reason Flow isn't 1.0.0 yet and the team will get to it at some point down the line.

Only frustrating thing is how much time I waste hunting down a solution when I find one of these untypable situations 😢 Is there a good list of gotchas somewhere?

**Comment by TrySound** [comment] 2018-04-15 21:26
@dhoulb Flow is stable enough. Do not expect 1.0.0. Flow follow only major and patch from semver. Semver just can't fit to such projects because any feature is actually a breaking change.

**Comment by gmaggio** [comment] 2018-06-03 14:08
@dhoulb : Since `Object.values()` returns an _array_, using `Array<any>` seems to fix the _error_.

```
const obj: { [string]: number } = { a: 1, b: 2, c: 3 };

const arr: Array<any> = Object.values(obj);
```

**Comment by luislhl** [comment] 2018-06-04 14:30
@gmaggio , but this way Flow will treat the elements of `arr` as `any`, instead of as `number`, right? So this doesn't solve the problem, just makes the error disappear.

**Comment by gchamon** [comment] 2018-06-21 15:23
If the declared type of the function argument passed to `Object.values(obj).forEach` was to be `Any` at the very least the programmer would be able to declare the expected type manually, thus propagating to the rest of the function, like  `Object.values(obj).forEach((value: MyType) => value.typeSpecificFunction())` without flow complaining about `MyType` being incompatible with `mixed`

**Comment by jcready** [comment] 2018-06-21 20:25
@gchamon that would be even less type-safe than the other proposed alternatives.

**Comment by sibelius** [comment] 2018-07-12 17:19
`Object.values` is not working well with $Exact

here is a failing test
https://flow.org/try/#0FAFwngDgpgBAojAvDA3gH2DL2cEMBcMAziAE4CWAdgOYA0mOjaAvgNzDADGA9pSTN0IJkKBgRgByXBPpsOXXvwBuSGAHkARgCsonEADoluADYBXKEQAU3AJT6AtrgiWViAHwwVAakmSbrIA

**Comment by jcready** [comment] 2018-07-12 18:21
@sibelius `Object.values` is not special cased to handle `$Exact` object types. https://github.com/facebook/flow/blob/0b2dbd4fd1c1fa0e864b1f452f6ad99a490e6639/lib/core.js#L62

It would require flow to add a way to handle function overloading based on the exactness of a parameter such that you could say:

```ts
declare class Object {
  static values<T>(object: $SpecialExactObjectIdentifierWithValues<T>): Array<T>;
  static values(object: any): Array<mixed>;
}
```

Because you don't want to constrain any keys or values of the object. You'd just want to specify the exactness constraint.

**Comment by ggregoire** [comment] 2018-08-02 19:26
The 2-year anniversary of this issue is approaching! 🎉

Nobody uses `Object.values` at Facebook?

**Comment by MrEfrem** [comment] 2018-08-05 18:43
I also don't understand why they can't fix this issue. The behavior of the `values` and `entries` completely known, those isn't black boxes.

**Comment by alexreardon** [comment] 2018-09-13 12:12
aye, my example is for when it is a map of the same types

**Comment by Frans-L** [comment] 2018-10-09 13:55
A temporary solution to avoid flow errors:
Cast 'mixed' to be a wanted type by casting it through 'any'.

```javascript
type Line = { name: string };
type Table = { [id: string]: Line };
const table: Table = { 'random': { name: 'Test' } };

(Object.values(table): any).forEach((line: Line) => console.log(line.name)); // works
```

**Comment by langri-sha** [comment] 2018-12-11 12:48
I follow @Frans-L example, but sometimes I don't want to import the `Line` type when I have a `table` value. I forcefully cast `Array<Mixed>` to `Array<typeof table>` and then silence the Flow error:

```
type Line = { name: string };
type Table = { [id: string]: Line };
const table: Table = { 'random': { name: 'Test' } };

// $FlowFixMe a meaningful description that mixed is being cast to `Table`.
(Object.values(table): Array<typeof table>).forEach((line) => console.log(line.name)); // works
```

This works plus it requires a useful comment left behind with why types were annotated manually.

**Comment by zeorin** [comment] 2018-12-19 07:58
@langri-sha If you like you can define a [suppressed type](https://flow.org/en/docs/config/options/#toc-suppress-type-string) that makes this a little more explicit and concise.

In `.flowconfig`:
```
# https://github.com/facebook/flow/issues/2221
suppress_type=$DownCast
```
Then in the code:
```
((Object.values(table): $DownCast): Array<Line>).forEach((line) => console.log(line.name)); // works
```
That way you don't have to create `$FlowFixMe` comments everywhere you use `Object.values`.

(BTW when you do this, whether you use my method or yours, you need to be very careful, as you're essentially telling Flow what the types are, and if you give the wrong type, it won't know. In your example code, `typeof table` is actually `Table`; `Object.values` on a `Table` won't return `Array<Table>`, but actually `Array<Line>`.)

**Comment by dsame** [comment] 2019-03-09 07:02
`it means when you write Object.values(obj), we can't say with certainty what types are in the resulting array.` sounds foolish because if `obj` is defined as 
```
type AType = {|
  foo: string,
 bar: number
|}

const obj:{[string]: AType} 
```
you definitely  must get an array of `AType` and not array of mixins.

**Comment by goodmind** [comment] 2019-03-09 20:33
I would just use actual es6 `Map` for maps

**Comment by FireyFly** [comment] 2019-03-23 18:34
It makes sense to use ES6 Map objects for when you want a mutable map, rather than using objects for it. But I think it's fair to say that oldschool "objects-as-maps" serve some purpose still--for instance in APIs where an object is provided as a literal mapping keys to values, like `combineReducers` in Redux. Using plain objects for the state tree in Redux (and other similar cases) is another example.

The original issue is very old, and plenty of things have been added to Flow since... wouldn't it make for a modern libdef for `Object.values` to type it as something like `<T: {}>(object: T) => Array<$Values<T>>` (together with a declaration like the current one probably, to catch non-object cases)? After all, the documentation for `$Values<T>` states that it "represents the union type of all the value types of the enumerable properties in an Object Type `T`.", which I think is exactly what we want to model.

That said, the current implementation of `$Values<T>` seems pretty janky. I tried something like this:
```js
declare class Object {
  static values<T: {}>(object: T): Array<$Values<T>>;
  static values(object: mixed): Array<mixed>;
}

declare var test: {
  name: string,
  value: number,
};

const v = Object.values(x);
// type-at-pos says v has type Array<$Values<{name: string, value: number}>>

const w: Array<string | number> = v;
// produces: Cannot assign v to w because:
//  • $Values [1] is incompatible with string [2] in array element.
//  • $Values [1] is incompatible with number [3] in array element.
```

Any eventual jankiness with `$Values<T>` should probably be sorted in a separate issue, but I hope we can improve the libdef for `Object.values` since it's rather hard to use at all currently... and I think it's important for the core libdef to model JS core as well as possible (whilst staying sound).

**Comment by goodmind** [comment] 2019-03-23 19:04
@FireyFly This isn't sound

```js
class A {
  x: number;
  constructor(x: number) {
    this.x = x;
  }
  f() {
    return this.x;
  }
}

type O = {+x: number, +f: () => number};
const test: O = new A(2);

((2): $Values<O>); // own property
((() => 2): $Values<O>); // not own property

console.log(Object.values(test)); // [2]
```

**Comment by FireyFly** [comment] 2019-03-23 19:12
Oh hmm... right, that's a good point, my bad. I guess the iterating over all properties rather than only own properties means we can't really do any better for a type for `Object.values` then. :\

**Comment by lxe** [comment] 2019-05-14 17:43
For sealed objects, which are very-well inferable, values/keys/entries should return sealed arrays, which also seem inferable.

**Comment by laszukdawid** [comment] 2019-08-10 03:42
Nice. Was promised a better way and burden-free development, but seems like another day with more problems of trying to incorporate the Flow into a new project.

Is anyone actually looking at this to provide some solutions or even, dare to say it, fix this? Today is the third anniversary <celebratory pew pew /> of this issue.

**Comment by jcready** [comment] 2019-08-10 12:10
@laszukdawid yes, @goodmind [has made sound versions of values/entries](https://github.com/facebook/flow/issues/6927#issuecomment-515685530), but apparently this still isn't good enough for the flow maintainers.

**Comment by lyleunderwood** [comment] 2019-08-11 12:18
@jcready That's not a very generous interpretation. Why not jump on discord and discuss it with them?

**Comment by jcready** [comment] 2019-08-11 15:55
@lyleunderwood what would you consider a more generous interpretation? I asked if I should make a PR for @goodmind's proposed libdef changes. @goodmind [said](https://github.com/facebook/flow/issues/6927#issuecomment-515778402):

> @dsainati1 doesn't like idea of exact constraint.

> [...] this was from Discord months ago when I proposed this libdef change

I attempted to find the conversation on discord and [I believe this is it](https://discordapp.com/channels/539606376339734558/539875369994420224/585875121084825601). @dsainati1's argument against it was:

> the whole concept of a supertype of all exact objects is inherently flawed though, since the point of exact objects is that they don't exhibit width subtyping

My interpretation of this is basically that even though @goodmind's implementation using an exact constraint is sound in practice (or at least as sound as the current `Object.keys()` implementation), in theory it just doesn't _feel_ right to @dsainati1.

The most reasonable argument against the exact constraint implementation I've see was from @samwgoldman in [this comment](https://github.com/facebook/flow/pull/5663#issuecomment-357593210) from January 2018:

> Vladimir is right. There are two issues.
> 
> Width subtyping:
> 
> ```ts
> var o: { p: number, q: string } = { p: 0, q: "", foo: "foo" };
> var keys: "p" | "q" = Object.keys(o); // lies
> var vals: number | string = Object.values(o); // lies
> ```
> 
> Proto vs. own
> 
> ```ts
> var o: { p: number, q: string } = Object.create({ p: 0, q: "" });
> var keys: Array<"p" | "q"> = Object.keys(o); // lies
> var vals: Array<number | string)> = Object.values(o); // lies
> ```
> 
> Exact object types are great for the former case, because they by definition exclude values having more properties. For the latter case, we really need to provide better mechanisms to specify object layout as part of types, since so many APIs depend on it. It's on our radar.

And while I agree that the proto vs. own issue still isn't solved by @goodmind's exact constraint implementation, the fact is flow has this same issue with `Object.keys()` right now and for some reason `Object.keys()` gets a pass. [I'll quote myself here](https://github.com/facebook/flow/issues/6927#issuecomment-479184685):

> So if this concession is made for `Object.keys()`, why not also for [`Object.values()`](https://github.com/facebook/flow/issues/2221) or [`Object.entries()`](https://github.com/facebook/flow/issues/2174)?

**Comment by lyleunderwood** [comment] 2019-08-12 10:45
The impression I got was that flow maintainers didn't want to make an API knowing they'll just have to change the API again down the road when the theoretically correct solution eventually comes along.

For what its worth, if I could [override the builtin libdef](https://github.com/facebook/flow/pull/7919) with @goodmind's exact constraint, I would have by now.

**Comment by yangshun** [comment] 2020-05-10 17:38
Here's a workaround that uses `Object.keys()` instead of `Object.values()`:

```js
type Line = { name: string };
type Table = { [id: string]: Line };
const table: Table = { 'random': { name: 'Test' } };

Object.values(table).forEach((line: Line) => console.log(line.name)); // error
Object.keys(table).map(key => table[key])
  .forEach((line: Line) => console.log(line.name)); // works
```

Try it out: https://flow.org/try/#0C4TwDgpgBAMglgO2gXigbygghgWwgLigGdgAnRAcygF8BuAKFEigBUsAjAGxXSgG04AE0IlyCCgF1C8JDQYBjAPYISUYB26E2XHhgDkpLAkGKcewhmx5CelhBJ6ac+vQDy7AFYR5wAHQA3LE4AV3sACnUdAEpfADNFUgBRLHkACzCwzkQCWGyoqGQAPiglFUVuX05FCkzs3ysIKKjaKAB6VqgIUlIEt09vPwBrCBAiCI1G3xwsMDDhkALiyO4+eYko+igoOITktIyspGk8xZLlInKISurapHrcRua2joB3BMGieiA

**Comment by danielo515** [comment] 2020-06-16 19:02
The object.keys workaround is an old a know one, but I think that not using some of the best ES6 features because flow it's a bad thing to face.
I think this should be prioritised since it has been open for more than 3 years.

**Comment by ealemda2** [comment] 2020-07-01 20:56
Closing in on 4 years on this issue. Any updates? 

It really is an inconvenience to spend 2 minutes writing a reduce function on Object.values() and then another hour on trying to write it in a way that flow would allow, and on top of that then explain it to everyone on your team why you had to do so.

**Comment by edoardo-bluframe** [comment] 2020-08-02 11:50
Hey guys!

Is cast to `: any` **really** our best solution?

Can we do better than that? :smile:

**Comment by EgMan** [comment] 2020-08-09 22:09
🎉 Happy Birthday!! 🥳🎂

**Comment by mmkvdev** [comment] 2021-02-01 16:53
Check for the type of the Object. In my case I accidentally set the type of the variable as `Array<Object>` but instead it should just be an `Object`.

If there's any condition associated inside the map function, we need to return some JSX for the callback or else `null`.

It's always advisable to use a variable outside the `parent return` to capture the results from a function (return value of Object.keys((callback))) and then use that variable to render inside the parent JSX to avoid flow from catching issues like: 

- `Array.prototype.map() expects a value to be returned at the end of arrow function`
- `Expected to return a value at the end of arrow function.`

**Comment by nnmrts** [comment] 2021-09-02 22:37
I think the assumption that solving this issue does not "align with [their] priorities" is safe. Or "sound", as the Flow team at Facebook would say. Let's close it. :)

https://medium.com/flow-type/clarity-on-flows-direction-and-open-source-engagement-e721a4eb4d8b

**Comment by FezVrasta** [comment] 2022-05-25 05:50
Is there any chance for this issue to be resolved?

**Comment by gkz** [comment] 2022-12-05 19:04
With above commit, object types that have an indexer and no explicit properties (e.g. `{[string]: number}`) have the type of their dictionary values returned by `Object.values` (e.g. `Array<number>`), and similarly with `Object.entries`, except the first element of the tuple works exactly like `Object.keys` (in this case, `Array<[string, number]>`)

**Closed by gkz** 2022-12-05 19:04 UTC
Labels: enhancement
