### ISSUE TITLE
Flow-remove-types breaks when the source have a long dash "–"

### ISSUE THREAD

**Issue by c58** [facebook/flow#7989] opened 2019-08-05 10:42 UTC
Flow-remove-types version:
2.104.0

## Expected behavior
Successfully remove the types from the following source:
```
// @flow
function createMessages<T>(a, b: T) {}

const MESSAGES = {
  RECOMMENDED_EXACT_PICKUP_TIME: 'test – test', // <-- long dash here
}

createMessages<typeof MESSAGES>('UIKIT_PICKUP_TIME_FIELD', MESSAGES)
```

## Actual behavior
Exit with error (when used with `flow-remove-types/register`):
```
createMessages<t                   'UIKIT_PICKUP_TIME_FIELD',
                            ^

SyntaxError: Invalid or unexpected token
    at Object._compile (/Users/artem/Development/test/node_modules/flow-remove-types/node_modules/pirates/lib/index.js:91:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

## Steps to reproduce
Run `npx flow-node` with the source showed above, you will see `Unexpected identifier`

## Findings
Appearantly the problem is with the long-dash `–` symbol. If i replace it with the regular dash `-` everything worked correctly

**Comment by jbrown215** [comment] 2019-08-05 16:36
@motiz88

**Comment by mroch** [comment] 2019-08-12 16:03
Duplicate of #7779

this caused by incorrect handling of multibyte characters :(

**Closed by mroch** 2019-08-12 16:03 UTC
Labels: bug
