### ISSUE TITLE
Flow forgets about type refinements over optional fields

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#1756] opened 2016-05-06 21:18 UTC
Here is an example:

``` js
/* @flow */

declare class Clip <a> {
  static write(clip:Clip<a>):Clip<a>
};
declare function createClip <a> ():Clip<a>;

class Lens <from, to> {
  get: (input:from) => to;
  set: (input:from, value:to) => from;
  constructor(get:(input:from) => to, set:(input:from, value:to) => from) {
    this.get = get;
    this.set = set;
  }
}

class Model <a> {
  clip: ?Clip<a>;
  constructor(clip:?Clip<a>) {
    this.clip = clip
  }
  swap <inner> (lens:Lens<Model<a>, inner>, f:(value:inner) => inner):Model<a> {
    return lens.set(this, f(lens.get(this)))
  }
}

const clip = new Lens
  ( model => model.clip
  , (model, clip) =>
    new Model(clip)
  )

const write = <a>
  (model:Model<a>) =>
  ( model.clip == null
  ? model
  : model.swap(clip, Clip.write)
  )
```

And errors reported by flow:

``` js
scratch.js:37
 37:   : model.swap(clip, Clip.write)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `swap`
 28:   ( model => model.clip
                  ^^^^^^^^^^ null. This type is incompatible with
  4:   static write(clip:Clip<a>):Clip<a>
                         ^^^^^^^ Clip

scratch.js:37
 37:   : model.swap(clip, Clip.write)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `swap`
 28:   ( model => model.clip
                  ^^^^^^^^^^ undefined. This type is incompatible with
  4:   static write(clip:Clip<a>):Clip<a>
                         ^^^^^^^ Clip


Found 2 errors
```

What I think the problem is that flow infers type of `clip` to be `Lens<Model<a>, ?Clip<a>>` there for type of it's getter is `?Clip<a>` while `Clip.write` expects `Clip<a>`. 

That all makes sense but `write` function explicitly checks that `model.clip` is `Clip<a>` and there for I'd expect flow to be able to infer that and there for refine `clip` type to `Lens<Model<a>, Clip<a>>` instead. 

Is flow supposed to be able to refine `clip` type as described or is current behavior expected one ? 

I also don't seem to be able to find a way to define `Model` such that flow would be able to allow me refine it's type prior to call to swap. Best I could come up with is to define a way is to refine `f`  functions by making them handle maybe types explicitly:

``` js
class Maybe {
  static lift <a> (f:(a:a) => a):(a:?a) => ?a {
    return ( input ) =>
      ( input == null
      ? input
      : f(input)
      )
  }
}


const write = <a>
  (model:Model<a>) =>
  ( model.clip == null
  ? model
  : model.swap(clip, Maybe.lift(Clip.write))
  )
```

**Comment by calebmer** [comment] 2017-07-26 21:58
Closing since this issue hasn’t seen a lot of activity. Sorry about that 😣

Please reopen with a reproduction on https://flow.org/try if you are still having issues!

**Closed by calebmer** 2017-07-26 21:58 UTC
