### ISSUE TITLE
Recommended .flowconfig for node projects using immutable?

### ISSUE THREAD

**Issue by wbeard** [facebook/flow#1741] opened 2016-05-03 21:51 UTC
Hi there,

I was wondering if there is a recommended setup for node projects that are using immutable.js?

Here is my .flowconfig

```
[ignore]
.*/node_modules/babel-core/.*
.*/node_modules/babelify/.*
.*/node_modules/bower-json/.*
.*/node_modules/bower/.*
.*/node_modules/config-chain/.*
.*/node_modules/enhanced-resolve/.*
.*/node_modules/npm/.*
.*/node_modules/npmconf/.*
.*/node_modules/npmi/.*
.*/node_modules/rally-ext-lean/.*
.*/node_modules/sombrero/.*

[libs]
node_modules/immutable/dist/immutable.js.flow

[options]
module.system.node.resolve_dirname=node_modules
module.system.node.resolve_dirname=.
```

I've had to omit seemingly random packages for some reason and I'm not sure why? I tried ignoring all of node_modules, but ran into problems when trying to import modules from there.

I'm also not sure why I have to point specifically to the immutable declarations. Is it a better config to just create a symlink in my `./flowtyped` folder pointing to this?

Anything others can share with me, best practices, etc for introducing this into their codebase would be appreciated!

Thanks!

**Comment by tryggvigy** [comment] 2016-05-04 01:13
Do you really have to specifically point to the immutable flow specifications?
We don´t do this.  Regarding the need to ignore "random" modules, it's unfortunate, but for very good reasons. I went and investigated why I needed to do this in our project and added some comments explaining the need.

Here is our `.flowconfig` for what it's worth. Might help you

```
[version]
0.24.1

[ignore]
# Tries to do `import * as Promise from ...` This is illegal, Promise is native.
.*/node_modules/react-side-effect/node_modules/*
# Contains depreceated flow definitions
.*/node_modules/react-motion/src/*
# Contains the non-standard Promise method `done`
.*/node_modules/fbjs/*
# Contains invalid json file with duplicate keys
.*/node_modules/json5/*

[include]

[libs]
app/types/

[options]
# Ignore flow warning about not supporting decorator types fully yet.
esproposal.decorators=ignore
esproposal.class_static_fields=enable
esproposal.class_instance_fields=enable

module.system=haste
munge_underscores=true
module.use_strict=true

# Provides an escape hatch to suppress flow type errors.
# Example: `function foo(bar: $FlowFixMe) {...}`.
suppress_type=$FlowFixMe

# Provides a way to suppress flow errors in the following line.
# Example: // $FlowSuppressError: This following line is borked because of reasons.
suppress_comment= \\(.\\|\n\\)*\\$FlowSuppressError

##
# Maps all imports of these types to the npm package `empty`.
# They will resolve as empty JS objects.
# This is necessary because flow tries to resolve all imports and
# these non-standard imports can't be parsed.
##
module.name_mapper='.*\(.css\|.png\)' -> 'empty/object'
# Cheat on the non-standard bang (!) import in app/LoggedIn/index.jsx
module.name_mapper='^.*!.*$' -> 'empty/object'

# Map webpack resolved module imports to the app directory
# Example: components/Foo -> `<project_root>/app/components/Foo`
module.name_mapper='^actions\/\(.*\)$' -> '<PROJECT_ROOT>/app/actions/\1'
module.name_mapper='^api\/\(.*\)$' -> '<PROJECT_ROOT>/app/api/\1'
module.name_mapper='^components\/\(.*\)$' -> '<PROJECT_ROOT>/app/components/\1'
module.name_mapper='^constants\/\(.*\)$' -> '<PROJECT_ROOT>/app/constants/\1'
module.name_mapper='^containers\/\(.*\)$' -> '<PROJECT_ROOT>/app/containers/\1'
module.name_mapper='^models\/\(.*\)$' -> '<PROJECT_ROOT>/app/models/\1'
module.name_mapper='^reducers\/\(.*\)$' -> '<PROJECT_ROOT>/app/reducers/\1'
module.name_mapper='^selectors\/\(.*\)$' -> '<PROJECT_ROOT>/app/selectors/\1'
module.name_mapper='^store\/\(.*\)$' -> '<PROJECT_ROOT>/app/store/\1'
module.name_mapper='^utils\/\(.*\)$' -> '<PROJECT_ROOT>/app/utils/\1'
module.name_mapper='^assets\/\(.*\)$' -> '<PROJECT_ROOT>/app/assets/\1'
```

**Comment by calebmer** [comment] 2017-07-26 21:50
Closing since this issue hasn’t seen a lot of activity. Sorry about that 😣

Please reopen with a reproduction on https://flow.org/try if you are still having issues!

**Closed by calebmer** 2017-07-26 21:50 UTC
