### ISSUE TITLE
Flow didn't catch a call to missing property(or method) on a function

### ISSUE THREAD

**Issue by AVykhrystyuk** [facebook/flow#7786] opened 2019-06-04 08:40 UTC
Flow version: 0.100.0

```ts
// @flow strict

function func(): void {
  return func.somethingMissing(); // <-- property 'somethingMissing' is missing
}

function func2(): number {
  return func2.__length__; // <-- property '__length__' is missing
}
```
## Expected behavior
Flow yields an error that property 'x' is missing on a function
## Actual behavior
Flow didn't catch a typo, so if that code is not covered by tests - you get a runtime error.

* Link to Try-Flow or Github repo: https://flow.org/try/#0PTAEAEDMBsHsHdQGcAuAnAlgYxQKF5AK4B2OGsxoRpAFAJQBcoAbrBgCagDeuooaAUxSE0lalgB0SWAFshACwzEA5gFkMSJEuX0A3KBCgAPAFoToAA5pYFgWhQBPUAHJpclIpXrN256A2gMhpaKrgAvvjiKORiJFgATPRMxIQyAEZ23Lz8QiKxpPESAPpF0AIqHiX6hqbmVjZ2ji4lZRXyJX4BQT6hEUA

* Link to how the same is handled in Typescript: 
https://www.typescriptlang.org/play/index.html#src=function%20func()%3A%20void%20%7B%0A%20%20return%20func.somethingMissing()%3B%20%2F%2F%20%3C--%20property%20'somethingMissing'%20is%20missing%0A%7D%0A%0Afunction%20func2()%3A%20number%20%7B%0A%20%20return%20func2.__length__%3B%20%2F%2F%20%3C--%20property%20'__length__'%20is%20missing%0A%7D%0A

**Comment by goodmind** [comment] 2019-06-06 08:09
Duplicate of #106

**Closed by goodmind** 2019-06-06 08:09 UTC
Labels: bug, needs triage
