### ISSUE TITLE
Problem with maybe Function

### ISSUE THREAD

**Issue by hmeerlo** [facebook/flow#1484] opened 2016-03-03 10:36 UTC
I will try to simplify my code:

```
type Props = {
  header: ?Function
}

class A extends React.Component {
  props: Props;

  render(){
    if(this.props.header != null){
      return this.props.header();
    }
  }
}
```

But flow still gives me the following error (note: error comes from the non-simplified code):

```
226:       return this.props.header(this.onSort.bind(this), this.state.sort, this.state.asc);
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `header`. Function cannot be called on possibly undefined value
 15:   header: ?Function,
                ^^^^^^^^ undefined
```

I have tried many different if statements to see if I could convince the parser that this is correct, they all failed.

**Comment by samwgoldman** [comment] 2016-03-03 11:17
Thanks for simplifying your code; it really helps us better understand issues. I think you may have oversimplified, though, because I can't reproduce an error with what you've included here.

I suspect you're running into the known issue described in the docs: http://flowtype.org/docs/dynamic-type-tests.html#caveats

Are you calling a function between the refinement of `this.props.header` and the call? If so, the workaround of assigning to a local should work for you.

**Comment by hmeerlo** [comment] 2016-03-03 11:23
Thanx for the quick reply. I'm not calling any functions in between. This is the actual code:

```
}else if(this.props.header != null){
      return this.props.header(this.onSort.bind(this), this.state.sort, this.state.asc);
}
```

**Comment by samwgoldman** [comment] 2016-03-03 11:24
Hard to say without an example that I can run and reproduce the issue. Can you provide an executable repro?

**Comment by hmeerlo** [comment] 2016-03-03 11:26
I will give it a try but I doubt whether I will succeed :-) The project I'm working on is large and complex and reducing it will probably make the error go away (Murphy's law)

**Comment by hmeerlo** [comment] 2016-03-03 13:28
Ok, I found the problem/solution. The solution is, what is described in the caveats as well, to assign the function to a local variable. The problem is caused by the first parameter being a method call, which I guess is assumed to be able to modify this.props.header. Am I right?

**Comment by samwgoldman** [comment] 2016-03-03 13:32
Oh, the call to `bind`? Yeah, that makes sense. Flow doesn't have enough information to determine (correctly) that it's safe to call bind. There's no reason it can't have that information, we just haven't built in that intelligence. The current situation is overly pessimistic, so you run into issues like this at the cost of soundness.

**Closed** 2016-03-03 13:32 UTC
