### ISSUE TITLE
 Assigning empty object to a variable with the inexact type of object doesn't occur error

### ISSUE THREAD

**Issue by oonsamyi** [facebook/flow#7935] opened 2019-07-16 09:39 UTC
Flow version:
0.102.0
## Expected behavior
Should be an error when an empty object is assigned to the variable with the inexact type of object:
```js
const test: {
  number: number,
  string: string,
  boolean: boolean,
  null: null,
  undefined: void,
  object: { string: string }
} = {}
```
## Actual behavior
No errors.

* Link to Try-Flow or Github repo:
https://flow.org/try/#0MYewdgzgLgBFCm0BcMDeAoGMwFcC2ARvAE4q6EkA0mM0xAlmAOYp2NPVYEggA28AQzApufQWE7YcvXmWm9JOMABN4AM0bxlKAG4h6yySAIAreMCgpUtKA2atb7GAF90zmAF40r9AmgA6YzMLfzZmGAB6CJhiJSh6PHgYEmIQYiA

## Investigation
This bug occurs after 0.88.0 version flow.

**Comment by goodmind** [comment] 2019-07-16 09:46
This is unsealed object, it's intended

**Comment by goodmind** [comment] 2019-07-16 09:47
Duplicate of https://github.com/facebook/flow/issues/7424

**Closed by goodmind** 2019-07-16 09:47 UTC
Labels: bug, needs triage
