### ISSUE TITLE
Optional / Maybe type causes flow error with defaultProps

### ISSUE THREAD

**Issue by johnryan** [facebook/flow#3982] opened 2017-05-19 21:36 UTC
If you have a component with an optional maybe type, for instance: 

```
type Props = {
  val? : ?string
}
```

and initialize the defaultProps to give that a null (or undefined) value:
```
static defaultProps = {
  val: null
}
```

you get an error if you try to pass a string prop to that component:
```
<MyComponent val="a string"/> string. This type is incompatible with val: null
```

See example [here.](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjYqfOLMAIn0pqYG51CBPHMsAAV6OAM5gAvGADeqMGABuFGAH4AXGBWjC+DADsA5qgC+XVFRgVR4gKIAPCrhgCydwmT0ATceWqEAdADCDHh6HsSy8jgiohrCcGJc8toUhBhUYJ5kUBQArjCE8WKSMnLyisoaevkwZcbo8qxeZPglABQAlJIAfGDVMDBc9agAPPaOOM4VMBIA5KIMAtq6hrPA3ahAA)

**Comment by ljharb** [comment] 2017-05-20 02:09
I would expect, at a minimum, that an absent maybe type is considered `undefined` - at a maximum, either `undefined` or `null`.

**Comment by vkurchatkin** [comment] 2017-05-20 09:54
Duplicate of https://github.com/facebook/flow/issues/3976

**Closed by vkurchatkin** 2017-05-20 09:54 UTC
