### ISSUE TITLE
Nested objects broken since v0.89.0

### ISSUE THREAD

**Issue by danwang** [facebook/flow#7700] opened 2019-05-06 19:46 UTC
Flow version: All versions `> v0.89.0`

## Expected behavior
This code should fail typecheck:

```jsx
({a: {}}: {a: {b: string}})
```

I'd expect to see an error like this, which is raised in v0.88.0:

```
1: ({a: {}}: {a: {b: string}})
        ^ Cannot cast object literal to object type because property `b` is missing in object literal [1] but exists in object type [2] in property `a`.
References:
1: ({a: {}}: {a: {b: string}})
        ^ [1]
1: ({a: {}}: {a: {b: string}})
                 ^ [2]
```

## Actual behavior
It passes typecheck.

* Link to Try-Flow or Github repo: https://flow.org/try/#0BQbwhgXABCC+vXIgRtAzgFwE4EsB2A5vAJRA

**Comment by dsainati1** [comment] 2019-05-13 17:53
This is because `{}` denotes an unsealed object. This is a duplicate of #7345

**Closed by dsainati1** 2019-05-13 17:53 UTC
Labels: bug, needs triage
