### ISSUE TITLE
error 'encaps tag. MIssing annotation'

### ISSUE THREAD

**Issue by bmcdaniel11** [facebook/flow#2188] opened 2016-08-04 15:44 UTC
I have a react mutation I'm using, and under the `getConfigs` method, I am getting the error 'encaps tag. Missing annotation'. As far as I can tell, I've set up the method exactly as the Mutation docs have directed. I'm not even sure what this error message means. 

Here is my code 

```
getConfigs () {
    return [ {
      type: 'REQUIRED_CHILDREN',
      children: [
        Relay.QL`
          fragment on RegisterTenantPayload {
            tenant {
              url
            }
          }
        `
      ]
   } ]
 }
```

Here is the error
![registertenantmutation_js_-_af_core_-____rails_af_core_](https://cloud.githubusercontent.com/assets/1737247/17408247/10e8885c-5a30-11e6-8fd5-732bf78d2a96.png)

A reference to the docs
https://facebook.github.io/relay/docs/guides-mutations.html - under REQUIRED_CHILDREN

Any idea what this error is being cause by?

**Comment by ivome** [comment] 2016-08-30 17:44
I had the same problem. Looks like flow does not like tagged templates inside of an array. 
This here works for example: 

```
const childQuery:any = Relay.QL`
  fragment on RegisterTenantPayload {
    tenant {
      url
    }
  }
`;

getConfigs () {
    return [ {
      type: 'REQUIRED_CHILDREN',
      children: [
        childQuery
      ]
   } ]
 }
```

**Comment by peternoordijk** [comment] 2016-09-24 11:13
I also got the same problem... you can also solve it by adding a return type to getConfigs like so:

```js
  getConfigs (): any {
    return [{
      type: 'REQUIRED_CHILDREN',
      children: [
        Relay.QL`
          fragment on MyPayload {
            name
          }
        `
      ],
    }];
  }
```

**Comment by calebmer** [comment] 2017-07-31 15:27
Closing since this issue hasn’t seen a lot of activity. Sorry about that 😣

Please reopen with a reproduction on https://flow.org/try if you are still having issues!

**Closed by calebmer** 2017-07-31 15:27 UTC
