### ISSUE TITLE
Issue with importing types when using objects as maps 

### ISSUE THREAD

**Issue by rpominov** [facebook/flow#464] opened 2015-05-22 16:07 UTC
Hi, I'm having issues with importing types. Here is my setup:

``` js
// types.js

/* @flow */

export type MyMap = {[key: string]: any};
export type PropName = {prop: string};
```

``` js
// main.js

/* @flow */

import type {PropName, MyMap} from './types';

function getPropValue(a: PropName, b: MyMap): any {
  return b[a.prop] || 0;
}

getPropValue({prop: 'bar'}, {foo: 1})
```

```
/Users/anon/projects/my/fluce/src/index.js:9:1,37: function call
Error:
/Users/anon/projects/my/fluce/src/index.js:6:10,18: access of computed property/element
Property not found in
/Users/anon/projects/my/fluce/src/index.js:9:29,36: object literal

Found 1 error
```

If I move type aliases to `main.js` everything works. Am I doing something wrong?

**Comment by samwgoldman** [comment] 2015-05-22 17:18
Hmm... Interesting issue! Flow has a notion of "sealed" objects which it uses to determine whether adding unknown keys is valid. When an object has an "indexer" component (a.k.a. object as map), the object is not sealed.

If the above code type checks when in a single file, I suspect the issue is import/export type does not carry the "sealed" type information along with the type itself.

Thanks for the issue and clear repro code!

**Comment by mroch** [comment] 2015-05-26 23:45
I looked into this briefly (will keep at it, but wanted to report) and it looks like the issue is that when the type is in the same file, flow knows the details of `PropName`, so when it sees `a.prop`, it knows that it's a `string` of any value (a `StrT(_, None)`); and when it sees `b`, it knows that it is a dictionary. Flowing a string (`a.prop`) to the dictionary's `[key: string]` is valid. Then later, and separately, it encounters the call to `getPropValue` and verifies that the args match the params, but doesn't "run" the function body, so never actually checks whether `bar` exists in `{foo: 1}`.

When they're in different files, flow does not know the details of `PropName` at the time that it is walking the function definition, so it sets up type vars for `a` and `b` and continues to the function call. There, it flows the params into those tvars, which effectively "runs" the function, and causes it to realize that `{foo: 1}` does not have a `bar` property, and error. Then it merges the two files together, where it does the same thing as the single-file case (flows a `StrT(_, None)` to a dictionary) and thinks that's fine.

So the problem seems to be that because `PropName` and `MyMap` are tvars instead of concrete types, the function call more or less actually evaluates the function based on the concrete types it inferred from the call, instead of waiting for the annotated types.

**Comment by brianmcallister** [comment] 2016-11-18 21:25
Maybe this is the wrong ticket, but I'm dealing with a similar issue (although not with objects as maps). My issue seems to be that importing and exporting types just doesn't work at all, even for very simple types. For example (this is contrived, I know), this code works (and produces Flow errors) as expected:

`add.js`
```js
// @flow

type AddArgs = {
  first: number,
  second: number,
}

const add = ({ first, second }: AddArgs) => first + second;

add({ first: 1, second: 2 });
add({ first: 1 }); // <-- error
```

However, if I move the type declaration into another file and attempt to `import` it, Flow reports no errors at all. Here's what I'm doing:

`add.js.flow`
```js
export type AddArgs = {
  a: number,
  b: number,
}
```

`add.js`
```js
// @flow

import type { AddArgs } from './add.js.flow';

const add = ({ first, second }: AddArgs) => first + second;

add({ first: 1, second: 2 });
add({ first: 1 });
```

I feel like I must be missing something obvious. I ready through [these docs](https://flowtype.org/docs/modules.html#type-imports--exports) a few times, and it doesn't appear like I'm doing anything incorrectly.

Apologies if this is the wrong ticket for this, I'd be happy to open a new one if appropriate.

**Comment by abenhamdine** [comment] 2016-12-06 20:17
I have exactly the similar pb that @brianmcallister has : import doesn't check anything, but if I move the type declaration in the same file, everything is going fine, and flow find some error as expected.

I don't post my example code : it's pretty the same.
The only difference I see is that I put the export in a `.js`file, and not a `.js.flow` file

**Comment by pdcarroll** [comment] 2018-01-05 22:33
@brianmcallister and @abenhamdine I had the same issue. I was able to suppress the error by adding an empty object literal union to the function param type, i.e.:

```javascript
const foo = (arg: ObjectLiteralType | {}) => 'bar';
```

**Comment by SamChou19815** [comment] 2023-02-04 05:37
This issue should be fixed a while ago.

**Closed by SamChou19815** 2023-02-04 05:37 UTC
Labels: bug
