### ISSUE TITLE
Overriding props with spread operator leads to union

### ISSUE THREAD

**Issue by honzabrecka** [facebook/flow#7967] opened 2019-07-25 15:17 UTC
When overriding props with spread operator, flow does not do override, but does union instead:

```js
// @flow

import React from 'react';

type A = {|
  +a?: boolean,
|}

type B = {|
  +a: string,
|}

const Button = ({ a }: B) => <span>Foo</span>;

const f = ({ a }: A): B => ({ a: 'foo' })

const HOC1 = (props: A) => {
  const x = f(props)
  return <Button {...props} {...x} />
}

const HOC2 = (props: A) => {
  const x = f(props)
  const y = { ...props, ...x } 
  return <Button {...y} />
}

const HOC3 = (props: A) => {
  const x = f(props)
  const y = { ...props, ...x } 
  return <Button {...props} {...x} a="foo" />
}

const ThisWorks = (props: A) => {
  const x = f(props)
  const { a, ...rest } = props // a is excluded
  return <Button {...rest} {...x} />
}
```

Flow version: 0.103

## Expected behavior

Should compile without any error.

## Actual behavior

Fails with Cannot create `Button` element because boolean [1] is incompatible with string [2] in property `a`. Actually it is not true as long as `a` is only of type `string`.

* Link to Try-Flow or Github repo:

https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AEoCmAhgMb6TaxqgDk2pFdA3MrgJ4ZGgCCoAXlABvAD6JQoANQkA-AC5QAI1ixopAHYAaRKIC+7LjwBCgkeMkzFAZ1zYUGgOY79yMrA23QxgK65cHmYAFMKgJKB6isYAlIIAfKAAPNYYJBpxAGKqicApaXFsiO6elMGh4ZF80VHxoCFhinSQqnQR0W4eXgASAPIAwsEY1BjWiryxAgnCEqDFXgAeZpBBQ7Aj7ZKMuD7YGkm+-oHCAHSnqyN6IqfH85fAcYgGRZ34vX0ATIPDo1W105JzfCLITLc7WDazF6gDhmULXMFaUDXRaXGZbHZ7RIHAJ7E6nDh3B5PQGgN4AZi+ax+4z+MxJwNAoO+EJJMKEcLO30RyIioDRRG2u32fhxV05VMueJulxIAgARM1YHLQPdHoggA

**Comment by goodmind** [comment] 2019-07-25 15:39
Duplicate of https://github.com/facebook/flow/issues/6108

**Closed by goodmind** 2019-07-25 15:39 UTC
Labels: Typing: spread, bug
