### ISSUE TITLE
string should be compatible with spread operand

### ISSUE THREAD

**Issue by stephencelis** [facebook/flow#2758] opened 2016-11-04 17:10 UTC
The spread operand shouldn't be incompatible:

``` js
> [...'test']
[ 't', 'e', 's', 't' ]
```

Unfortunately, Flow flags it as such

> ```
>   1: [...'test']
>          ^^^^^^ string. This type is incompatible with
>   1: [...'test']
>          ^^^^^^ spread operand
> ```

This PR attempted to solve the problem, but was abandoned and ultimately closed: https://github.com/facebook/flow/pull/1668

Opening this issue, in the meantime, to track compatibility.

**Comment by vkurchatkin** [comment] 2016-11-04 17:12
Duplicate of https://github.com/facebook/flow/issues/1059

**Comment by stephencelis** [comment] 2016-11-04 17:13
Ah, did a search but didn't see that one. Sorry for the noise!

**Closed by vkurchatkin** 2016-11-04 17:12 UTC
