### ISSUE TITLE
Custom loader integration

### ISSUE THREAD

**Issue by guybedford** [facebook/flow#293] opened 2015-02-27 14:48 UTC
Is it currently possible to specify a custom resolve hook? It would be really useful with this to be able to integrate a custom loader like SystemJS into Flow, which has its own resolution rules.

Basically, allowing a loader resolution hook to be provided as input. Generally the resolve hook takes the following form:

``` javascript
function resolve(url, parentUrl) {
  return resolvedUrl;
}
```

In the loader I believe it may also allow a promise to be returned for asynchronous resolution.

Does such a thing exist? Does it sound sensible?

**Comment by akxcv** [comment] 2017-04-20 04:41
The issue is also described well in https://github.com/facebook/flow/issues/2939 by @JohnLouderback.
At our company, we have the following lookup process:
```js
import './myFile'
// => apps/[currentProjectName]/assets/javascripts/myFile
// => apps/common/assets/javascripts/myFile (if the former file does not exist)
```
This is currently accomplished by a custom Babel plugin.

AFAIK, this isn't currently possible to do with Flow. What would be the best way to accomplish such behavior? I don't think we can allow babel to process files before Flow because then we'd need source maps and it would really complicate things overall. But clearly, we need to do *some* kind of processing that includes checking if a file exists (accounting for many possible extensions).

I'm willing to submit a PR, but first, we need to decide what we want to do (if anything).

**Comment by jakesyl** [comment] 2018-10-18 14:39
Looks like this got resolved in #6132/08b0c8ff31d33d117ebbb88f37a9483df761ce52

**Comment by apsavin** [comment] 2019-09-17 20:27
@goodmind should it be closed?

**Comment by goodmind** [comment] 2019-09-17 21:19
I don't think it should, Flow team planned to remove custom loaders

**Comment by nicolo-ribaudo** [comment] 2020-01-24 21:13
This is needed to be able to still use Flow with Yarn 2.

**Comment by jakesyl** [comment] 2020-01-24 23:16
@goodmind where's that thread?

**Comment by alexandrukis** [comment] 2020-11-08 10:47
Is there any (at this point I would accept any ugly, hack-ish solution) way of achieving this using the latest version of Flow?

**Comment by SamChou19815** [comment] 2023-01-20 06:41
I don't think we are likely to allow this in the future. Module resolution gets more complicated than a simple function call, when you also need to worry about updating the dependency graph incrementally.

**Closed by SamChou19815** 2023-01-20 06:41 UTC
Labels: feature request
