### ISSUE TITLE
Intersection type incompatible with $Diff<>

### ISSUE THREAD

**Issue by oliverzheng** [facebook/flow#3987] opened 2017-05-20 20:29 UTC
Should `A & B` not be the same as `$Diff<A & B & C, C>`? With the following snippet, flow emits a incompatible type error.

```
type A = {
  a: true,
};
type B = {
  b: true,
};
type C = {
  c: true,
};

const diff1: $Diff<A & B & C, C> = {a: true, b: true};

// error with incompatible types
const diff2: $Diff<A & B & C, C> = ({a: true, b: true} : A & B);
```

**Comment by futpib** [comment] 2017-09-12 10:16
Duplicate of #3246

**Comment by goodmind** [comment] 2019-06-22 19:58
Duplicate of #3246

**Closed by goodmind** 2019-06-22 19:58 UTC
