### ISSUE TITLE
Fails to resolve main property in package.json

### ISSUE THREAD

**Issue by dignifiedquire** [facebook/flow#278] opened 2015-02-24 17:11 UTC
If I have a file with 
```js
/* @flow */
var ReactRouter = require('react-router');
```
flow will fail with:

```
path/to/file:2 lib
Required module not found
```

Changing the `main` property from `lib` in the package.json of react-router to be `lib/index` makes it work.

* `flow@0.4.0`
* `react-router@0.12.2`

ref: https://github.com/facebook/flow/issues/46

**Comment by mjackson** [comment] 2015-02-24 19:27
What is the underlying issue here? Seems like flow doesn't understand node/npm's `index.js` convention.

**Comment by Dignifiedquire** [comment] 2015-02-24 19:38
@mjackson yes that is my current guess.

**Comment by pyryk** [comment] 2015-02-27 07:28
I ran into this issue as well. After some testing, it seems that flow does understand `index.js` convention when requiring (relative) folders in code (i.e. `require('./dir')`), but it does not support the convention in `main` property of `package.json`.

**Comment by tsing** [comment] 2015-03-09 02:13
It seems that the issue is fixed 0.5.0

**Comment by samwgoldman** [comment] 2015-06-24 00:28
Please reopen if this is still an issue.

**Comment by tp** [comment] 2015-09-28 14:25
I see this error again with Flow 0.16.0. Seems to be tracked by #654 now.

**Comment by splodingsocks** [comment] 2016-02-23 18:27
@samwgoldman, I'm seeing this in Flow 0.22.0 with the react-router package, which specifies its 'main' in the package json as just 'lib' instead of 'lib/index.js'.

**Comment by vjpr** [comment] 2016-02-29 01:52
Just upgraded from 0.21 -> 0.22 and seeing this bug.

**Comment by dsilva** [comment] 2016-03-15 09:30
This was fixed in 0.22.1, right?

**Comment by msdark** [comment] 2016-07-17 04:50
i'm seeing this error with flow-bin 0.29. every `import` that I do from `node_modules` is failing.

**Comment by mroch** [comment] 2016-09-16 18:29
just ran this test:

```
mkdir -p test/node_modules/foo/lib
pushd test
printf "// @flow\n\nmodule.exports = 'hello';\n" > node_modules/foo/lib/index.js
echo '{"name": "foo", "main": "lib"}' > node_modules/foo/package.json
printf "// @flow\n\n(require('foo'): number);\n" > index.js
touch .flowconfig
flow check
popd
```

and got this:

```
$ flow check
index.js:3
  3: (require('foo'): number);
      ^^^^^^^^^^^^^^ string. This type is incompatible with
  3: (require('foo'): number);
                      ^^^^^^ number


Found 1 error
```

so I think it's working now (v0.32)

**Closed by mroch** 2016-09-16 18:29 UTC
Labels: bug, module resolution

**Comment by vjpr** [comment] 2018-11-03 12:16
Just bumped into this again. Do NOT add this to your `.flowconfig`:

```
[ignore]
.*/node_modules/.*\.json$
```
