### ISSUE TITLE
Cannot refine union using intersection

### ISSUE THREAD

**Issue by pkuhanan** [facebook/flow#5179] opened 2017-10-24 20:15 UTC
```
/* @flow */

type SomeType = number | { thing: number };

function f(x : SomeType & {}) {
  (x : { thing: number });
}
```

I would expect this to work -- we would check before calling this function that some variable is an object, then pass it in.  I expect `x` to have the type of the object branch from `SomeType` but instead I get an error... what's going on here?

**Comment by btford** [comment] 2018-03-15 23:15
Possibly a duplicate of #3912 and/or #4029.

**Comment by goodmind** [comment] 2019-05-30 09:24
Duplicate of #4029

**Closed by goodmind** 2019-05-30 09:24 UTC
