### ISSUE TITLE
Error with intersection of unions

### ISSUE THREAD

**Issue by vaskevich** [facebook/flow#3912] opened 2017-05-10 03:46 UTC
Seems like Flow is incorrectly throwing an error:

```
/* @flow */

type T = {prop: string};

type Common = {type: 'foo'};

// Does not work:
type Bar = Common & ({t: T, u: true} | {t: null, u: false});

// Works:
// type Bar = (Common & {t: T, u: true}) | (Common & {t: null, u: false});

const bar: Bar = {type: 'foo', u: true, t: {prop: 'baz'}};

if (bar.u) {
  bar.t.prop;  // <-- error
}
```

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAqYAvGAN44BOcOAXGAM4ZUCWAdgOYC+A3OtnxgAwnAC2YuO1IVBeBgHIocOAr7pgwMABE4eRmHZwMYBHCoBrOplwEAQgEMqM0RKlgAZGAAU5DA0IAGjAAVwYWELxuMAAfWQZ2EJgYYLCwKAcYRiiASn5UTTAAdXMLRmtCuTBHZzJvV0lpLz8A1PCqSO4c2J8G92b-QySU0IYMrNz8gGMpZjAAIycGGpk-W0VlVTawCLxgwcoaejAFRYAvNXVUVigfRaoAOhDu8lQwBacHjAfqWl53woAHgAtMCwHgqDQqKhuEA

**Comment by Soreine** [comment] 2017-07-20 10:40
It looks like the same than https://github.com/facebook/flow/issues/4029
The solution for now being to use the DNF `(... & ...) | (... & ...)`

**Comment by goodmind** [comment] 2019-05-30 09:24
Duplicate of #4029

**Closed by goodmind** 2019-05-30 09:24 UTC
