### ISSUE TITLE
Vanilla Flow Installation Fails on Apple Silicon Mac

### ISSUE THREAD

**Issue by foush** [facebook/flow#8629] opened 2021-03-25 23:47 UTC
I decided to start a project with Flow on a M1 2020 Mac Mini. I followed the instructions on flow.org for setting up, and upon running `yarn run flow` got the typical startup message, however the server never finished starting up:

```
yarn run v1.22.10
$ /Users/foush/Dev/hello-world/node_modules/.bin/flow
Launching Flow server for /Users/foush/Dev/hello-world
Spawned flow server (pid=1178)
Logs will go to /private/tmp/flow/zSUserszSfoushzSDevzShello-world.log
Monitor logs will go to /private/tmp/flow/zSUserszSfoushzSDevzShello-world.monitor_log
Please wait. Server is starting up:
```

I tailed `/private/tmp/flow/zSUserszSfoushzSDevzShello-world.log` and found:

```
foush@MiniMedia hello-world % tail -f /private/tmp/flow/zSUserszSfoushzSDevzShello-world.log
[2021-03-25 15:46:08.899] lazy_mode=off
[2021-03-25 15:46:08.899] abstract_locations=on
[2021-03-25 15:46:08.899] max_workers=8
[2021-03-25 15:46:08.899] debug=false
[2021-03-25 15:46:08.900] Failed to use anonymous memfd init
Out of shared memory:
Raised by primitive operation at file "src/heap/sharedMem.ml", line 60, characters 25-49
Called from file "src/hack_forked/utils/sys/daemon.ml", line 272, characters 4-26
Called from file "src/flow.ml", line 107, characters 4-31
```

Flow version: v1.22.10

## Expected behavior
Flow server should gracefully handle failure in memory allocation AND flow server should be able to allocate memory in Mac OS

## Actual behavior
Flow server fatals and hangs without providing useful signal to developer. Flow does not run on M1 mac

## The Workaround
I found a way to get this to work:

modify `.flowconfig` to adjust the `sharedmemory.heap_size` option
```
[options]
sharedmemory.heap_size=3221225472
```

Then running `yarn flow stop` and `yarn flow start` allowed me to proceed with development. 

## Suggestion:
I'd suggest updating the setting up section of the flow website / README so folks can easily find a workaround while the actual fix is implemented.

no try-flow or GitHub link available due to the fundamental nature of this issue

**Comment by nmote** [comment] 2021-03-31 02:18
Duplicate of #8538

**Closed by nmote** 2021-03-31 02:18 UTC
Labels: Closed: duplicate, bug, needs triage
