### ISSUE TITLE
Internal error (see logs): merge_strict_job exception: Types_js.Key_not_found("SigContextHeap")

### ISSUE THREAD

**Issue by maarekj** [facebook/flow#1742] opened 2016-05-04 12:25 UTC
Hi,
I have a problem on version **0.23.*** and **0.24.*** on check.
On each of my files there is the following error:

    app/Screen/Component/ReviewButtons.js:1
      1: /* @flow */
         ^ Internal error (see logs): merge_strict_job exception: Types_js.Key_not_found("SigContextHeap",    "/Users/maarek/Documents/projects/netosoft/chevalannonce_mobile/ca/app/BBCode/Templater.js")`

The version 0.22.1 work perfectly.

An idea ?

**Comment by seekingBetter** [comment] 2016-05-06 04:23
@maarekj I ran across the same issue and just spent the last 30 minutes back tracing the error to find the cause. In the end, it was due to an external module class (fully flow typed written in ES6 with module.mapper enabled) that had one of its async static methods without any return type. Once i added the return type (Promise<Object>), that error disappeared. Hope this helps.

**Comment by maarekj** [comment] 2016-05-06 07:35
Ok, I need to check any error so.
Thanks You.

**Comment by maarekj** [comment] 2016-05-06 09:13
I fix the errors.
The main error was related to the dynamic polymorphic type bad bound.
Thank you for your help.

**Comment by mroch** [comment] 2016-10-06 18:58
we did a bunch of work around this exception a few months ago and haven't seen any new reports, so I'm gonna close this. but let us know if there's a new repro!

**Closed by mroch** 2016-10-06 18:58 UTC
Labels: bug, Crash, Typing: polymorphism

**Comment by haf** [comment] 2017-02-14 19:06
Declaring a module like this causes the exception:

```
declare module module {
  declare function hot(path: string, callback:() => void): void;
}
```

This works:

```
declare module module {
  declare function hot(path: string, callback:void => void): void;
}
```
