### ISSUE TITLE
Access of computed property/element (Indexable signature not found in Document)

### ISSUE THREAD

**Issue by jamsea** [facebook/flow#3146] opened 2017-01-06 23:49 UTC
I have a line of code that looks like:
```javascript
isFullscreen = !!document["fullscreenElement"];
```

Flow is giving me the error:
```
169:             isFullscreen = !!document["fullscreenElement"];
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ access of computed property/element. Indexable signature not found in
169:             isFullscreen = !!document["fullscreenElement"];
                                  ^^^^^^^^ Document
```

However, this code works fine in the browser. Is there something wrong with the builtin document type in flow or am I doing it wrong?

**Comment by jesseschalken** [comment] 2017-01-07 15:54
To index an object with `object[...]` syntax ("access of computed property" in Flow) it has to be declared with an index signature like `[key: string]: value` (see [here](https://flowtype.org/docs/objects.html#objects-as-maps)). The [Document](https://github.com/facebook/flow/blob/master/lib/dom.js#L500) class in Flow isn't declared with an index signature, so you can't use `object[...]` syntax on it.

I'd suggest that Flow _should_ support computer properties on `Document`, since it works at runtime, but I'm having trouble finding out what the values are supposed to be. Are they form elements indexed by name? If so, you should probably just use [`document.forms[...]`](https://github.com/facebook/flow/blob/master/lib/dom.js#L551) instead.

**Comment by unhammer** [comment] 2017-02-25 13:15
Maybe related: https://github.com/l20n/l20n.js/blob/1ad935c5a00c6529411c76d5b1544ed8a2a45c16/docs/bindings.md creates a document.l10n element – is it not possible to have that pass flow?

**Comment by mengxingshike2012** [comment] 2017-07-13 01:47
got same error even with type Array

**Comment by goodmind** [comment] 2019-05-31 03:59
Duplicate of #4014

**Closed by goodmind** 2019-05-31 03:59 UTC
