### ISSUE TITLE
flow gen-flow-files src/ --out-dir lib says it can't find a file, yet it had to find that file to know about it

### ISSUE THREAD

**Issue by jedwards1211** [facebook/flow#2635] opened 2016-10-16 22:36 UTC
On some projects I have no problems with it.  I've only seen this issue on this repo:

```
git clone https://github.com/jedwards1211/async-child-process ~/async-child-process
cd ~/async-child-process
npm run flow -- gen-flow-files src/ --out-dir lib
```

It errors out saying:

```
> async-child-process@1.0.0 flow /Users/andy/async-child-process
> flow "gen-flow-files" "src/" "--out-dir" "lib"

Found 5 files, generating libdefs...
Error: Failure("/Users/andy/async-child-process/src/join.js: Not_found")
```

But `/Users/andy/async-child-process/src/join.js` does exist and Flow obviously already found it 😆

**Comment by asolove** [comment] 2017-08-22 04:27
@jedwards1211 can you still replicate this? I tried with the current master of `async-child-process` and first got the `Not_found` error because there was no `lib` directory, but after creating that it succeeded. Hopefully that means the issue has been fixed in the intervening months!

**Comment by jedwards1211** [comment] 2017-08-23 14:59
@asolove no, for me it doesn't work even after I create the `lib` directory.  I would hope the error message isn't misleading in that it means it failed when processing `/Users/andy/async-child-process/src/join.js`, but that the `Not_found` error was actually caused by the `lib` directory being missing!

**Comment by asolove** [comment] 2017-08-23 15:15
Oh, yeah, didn't mean to imply that the error was misleading. Just meant that I couldn't reproduce the same issue you had.

**Comment by jedwards1211** [comment] 2017-08-23 15:32
@asolove well, obviously the file `/Users/andy/async-child-process/src/join.js` exists.  So flow either
* mistakenly thinks it can't find that file or
* gets a `Not_found` error when it tries to open `lib/join.js.flow` for writing (or some other file?), but prints something like `<input file>: <error code>` without printing the full error message about *which* file it failed to find.

**Comment by TrySound** [comment] 2019-02-09 10:45
flow-gen-files replacement is coming soon

**Closed by TrySound** 2019-02-09 10:45 UTC
