### ISSUE TITLE
complain when there are too many arguments

### ISSUE THREAD

**Issue by coot** [facebook/flow#1489] opened 2016-03-04 22:59 UTC
Here is an example which silently passes, while it should fail.

```
// @flow
declare type Arg = {arg: number};

var _arg: Arg = {arg: 0};

declare interface KO<T> {
  (): T;
  (arg: T): void;
}

var o: KO<Arg> = function(arg) {
  if (arg)
    _arg = arg;
  else
    return _arg;
}

o(1); // does not complain
```

_flow_ does not complain because it assumes that `o` is called with an additional argument, and the first type for `o` applies.  _flow_ should fail here, as this breaks the second declaration.  A solution would be to tell _flow_ that a function cannot be called with more arguments than declared.  This is important for knockoutjs observables which are functions which can set and get the value at the same time.

**Comment by coot** [comment] 2016-03-04 23:13
I actually found a nice solution, which might be worth putting in the documentation:
```
// @flow
declare type Arg = {arg: number};
declare class NO_MORE_ARGS {};

var _arg: Arg = {arg: 0};

declare interface KO<T> {
  (...w: Array<NO_MORE_ARGS>): T;
  (arg: T): void;
}

var o: KO<Arg> = function(arg) {
  if (arg)
    _arg = arg;
  else
    return _arg;
}

o(1); // does complain!
o({arg: 2});
var r = o();
r.arg;


```

**Comment by coot** [comment] 2016-03-05 09:29
pr #1490

**Comment by AgentME** [comment] 2016-03-09 23:19
I agree this is a real issue (my older report https://github.com/facebook/flow/issues/753 is about the same issue as this one but not put as simply), but the solution should be more nuanced than disallowing extra arguments to be passed to functions. I think it's very common for callbacks to not use all or any of the arguments passed to them. I can't count the number of times I've used or seen the following:

```js
element.addEventListener('click', () => {
  //...
});
```

(Okay, maybe not the right example because the caller of the callback providing too many arguments isn't here, but I imagine this example would trip the same rule.)

Maybe it would be good if the strictness only applied when there were other function overloads accepting different parameters.

**Comment by vkurchatkin** [comment] 2017-01-22 19:03
Duplicate of https://github.com/facebook/flow/issues/1017

**Closed by vkurchatkin** 2017-01-22 19:03 UTC
Labels: FAQ, Needs docs

**Comment by futpib** [comment] 2017-05-22 10:10
Trying to annotate ko here too! Here is a IMO slightly nicer way with arguments tuples (without need for a `newtype`-ish class).

```js
// @flow

declare interface KoObservable<T> {
  (...args: []): T;
  (...args: [T]): void;
}

const ko = {
  observable: <T>(initialState: T): KoObservable<T> => {
    let state: T = initialState;
    return (...args) => {
  	  if (args.length === 0) {
        return state;
      }
      state = args[0];
    }
  }
};

const o: KoObservable<string> = ko.observable('foo');

o();
o('bar');
o(1); // $ExpectError
```

https://flow.org/try/#0PTAEAEDMBsHsHcBQiAmBTAxtAhgJzaAJYB2ALmrpNhgQNKwDyARgM4UBu2T0aAPACoA+UAG9EoUAAoAdLLwBzFgC5QAbQC6AShX8A3OKmzpC5Wv5aV7WIRT6AvsgyxiLUqADWsUAF5RB2KwcXDwqAoKSJISkhNjQAMqk2OQ62qD0zGy4nNx8Qj7CYhISPG6uSWg6PkTEUTHxieT6RaD4pACuuMSGcriKmvl+EgCQEoSQUibSPMTypAAWPt6+AAz9hc1FrR1dZY0GzQ4boLsEviaqy+pNRYegDnb6iE4ubrAq6YFZwXyuuCTywl8nmkAUy2R4kgA5JBYLBIZpHrBJAjEEjIUw8PD9EiAIwI0AgUAAEgAogAPAAOmFIJNwuFguCAA
