### ISSUE TITLE
Internal error: uncaught exception: Failure("hd")

### ISSUE THREAD

**Issue by alexsasharegan** [facebook/flow#6909] opened 2018-09-20 01:14 UTC
Just started getting this error, and I have no idea what to do with it. It pops up as the first line, first character of the file.

```
Internal error: uncaught exception: Failure("hd")
Raised at file "map.ml", line 130, characters 10-25
Called from file
"hack/utils/collections/myMap.ml", line 15, characters 13-23
```

**Version:** `flow-bin@0.81.0`

**Comment by jbrown215** [comment] 2018-09-20 18:35
Do you happen to have a repro we can look at for this?

**Comment by alexsasharegan** [comment] 2018-09-20 20:51
Unfortunately, I don't. It's in a large private monorepo, and right now I'm pushing towards a deadline so I don't have a lot of extra time. I've reverted to `0.80.0`, and this problem is gone. One of our other repos inside the same project doesn't have this issue on `0.81.0`. :man_shrugging:

**Comment by mroch** [comment] 2018-09-24 15:54
can you see if `OCAMLRUNPARAM=b flow ...` gives you a better stack trace?

**Comment by romanlex** [comment] 2018-10-04 13:07
0.82.0 same issues
![image](https://user-images.githubusercontent.com/3369304/46475970-a722ff80-c7ef-11e8-9687-57fb4a5946c1.png)

**Comment by marudor** [comment] 2018-10-08 12:57
Ensure you do not have `traces=` in your config. This was the cause for me.

**Comment by jbrown215** [comment] 2018-10-10 15:50
This will likely be fixed in the next release of flow.  364290450d1764e06d20925127c0714bc294f634 fixes the issue when using `--traces`. I would appreciate if you could confirm this works when the next release comes out :)

**Comment by alexsasharegan** [comment] 2018-10-12 14:28
So far so good, but I haven't been in this sub-repo of the project as much after the update to 0.83. Will update with any issues.

I appreciate the help!

**Comment by jbrown215** [comment] 2018-10-12 14:54
great! closing for now. reopen and tag me if it crashes with `Failure("hd")` or `Failure("tl")`

**Closed by jbrown215** 2018-10-12 14:54 UTC
