### ISSUE TITLE
Flow cannot infer that property is non-nullable after a literal assignment

### ISSUE THREAD

**Issue by pasha-mf** [facebook/flow#918] opened 2015-10-08 21:51 UTC
I don't know if this bug was reported here or not, but in the following code Flow fails to notice that `a.foo` is actually well-defined:
```
type Fooo = { foo?: Array<number>; bar?: string; };
var a: Fooo = { foo: [] };
a.bar = "abc";
a.foo.push(7);


39: a.foo.push(7);
    ^^^^^^^^^^^^^ call of method `push`. Method cannot be called on possibly undefined value
39: a.foo.push(7);
    ^^^^^ undefined
```

**Comment by samwgoldman** [comment] 2015-10-08 23:28
I believe this is working as designed, but it does underscore a small tension between inference and annotations. Consider the following:

```javascript
var foo: ?string = "foo";
```

Flow "knows" that `foo` is always non-null, but since you provided an explicit annotation, we widen the type based on the annotation. This is exactly what's going on in your example, too.

When we say that something can be refined by definite assignment, we are talking about non-declaration assignment, because a) declarations without a type annotation don't exhibit this tension and b) declarations with a type annotation we assume should keep the type that's annotated.

I can slightly modify your example to take advantage of the refinement via definite assignment:

```javascript
/* @flow */

type Fooo = { foo?: Array<number>; bar?: string; };
var a: Fooo = {};
a.foo = [];
a.foo.push(7);
```

Does this explanation convince you that Flow is working as designed? Does it convince you that there is no issue here?

**Comment by samwgoldman** [comment] 2015-10-13 03:16
I'm going to close this. Let me know if you still think there is an error here.

**Closed by samwgoldman** 2015-10-13 03:16 UTC
