### ISSUE TITLE
It should be possible to refine DOM Node using nodeType

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#3358] opened 2017-02-08 23:33 UTC
Current [libdef for dom](https://github.com/facebook/flow/blob/master/lib/dom.js) does not allow refinements of nodes via [`nodeType`](https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeType) property which makes it really difficult to use flow for DOM intensive code. Here is [an example] also inlined below for convenience :

```js
/* @flow */

const serialize = (node:Node):string => {
  switch (node.nodeType) {
    case Node.ELEMENT_NODE:
      return `<${node.localName}>`
    case Node.TEXT_NODE:
      return `#text ${JSON.stringify(node.data)}`
    default:
      return ''
  }
}
```

In reality it's a valid code but flow will fail to type check with following errors:

```
return `<${node.localName}>`
                         ^ property `localName`. Property not found in
6:       return `<${node.localName}>`
                    ^ Node
8:       return `#text ${JSON.stringify(node.data)}`
                                             ^ property `data`. Property not found in
8:       return `#text ${JSON.stringify(node.data)}`
                                        ^ Node
```

Problem is that DOM spec defines `Node` as this abstract interface that all node types implement, but then it also uses this abstract `Node` interface in many API as a type union for all the actual node types. There for I think libdef should have one abstract class definition for `Node` that `Element`, `Text` and others inherit from and a separate type `Node` that is union of `Element`, `Text`, ...etc with `nodeType` sentinel property.

**Comment by vkurchatkin** [comment] 2017-02-08 23:37
Duplicate of https://github.com/facebook/flow/issues/1032

**Closed by vkurchatkin** 2017-02-08 23:37 UTC
