### ISSUE TITLE
Internal Error: type A<T: {}, U: {}> = { ...T, ...U }

### ISSUE THREAD

**Issue by mwalkerwells** [facebook/flow#3538] opened 2017-03-18 21:30 UTC
**Practical Use:**
````js
type A<T: {}, U: {}> = { ...T, ...U }
````
**Minimum Proof:**
````js
 type A<T: {}> = { ...T }
````
**Error:**
````js
. Internal error: Failure(Did not expect BoundT)
````

https://flowtype.org/try/#0FAFwngDgpgBAggHgCoC4YG8C+A+GBeDGAOhKRkyA

**Comment by mwalkerwells** [comment] 2017-03-18 21:32
@samwgoldman https://github.com/facebook/flow/commit/ad443dc92879ae21705d4c61b942ba2f8ad61e4d

**Comment by vkurchatkin** [comment] 2017-03-18 22:55
Duplicate of https://github.com/facebook/flow/issues/3535

**Closed by vkurchatkin** 2017-03-18 22:55 UTC
