### ISSUE TITLE
[Regression from 0.45 -> 0.46] resolve_dirname no longer applies

### ISSUE THREAD

**Issue by DanielHeath** [facebook/flow#4103] opened 2017-06-06 01:54 UTC
After upgrading from 0.45 to 0.46, we have hundreds of `Required module not found` errors.

The relevant flowconfig snippet is:
```
[options]
module.system.node.resolve_dirname=src/js
module.system.node.resolve_dirname=test/unit
```

An example of the new error:
```
src/js/client/<snip>/<snip>/<snip>/__tests__/index-spec.js:3
  3: import { within } from 'helpers/stubs';
                            ^^^^^^^^^^^^^^^ helpers/stubs. Required module not found
```

This file is present:
```
  $ ls test/unit/helpers/stubs.js
test/unit/helpers/stubs.js
```

**Comment by gabelevi** [comment] 2017-06-06 15:00
Can confirm this repros with https://gist.github.com/gabelevi/edc83db958db739fdf81749f205877b5 and that the issue was introduced with v0.46.0

@avikchaudhuri  - was this your moving of require resolution that you landed near the end of April?

**Comment by valscion** [comment] 2017-06-30 15:17
We are facing the same regression and as a result almost every one of our files have errors.

Is there anything I could do to help? I could whip up a reproduction repository if that helps.

An alternative we are considering is to stop using `resolve_dirname` to completely hide the root folder and introduce a new variable, say `appJS`, that would point to our JS root that we could use.

```ini
# .flowconfig

[options]
module.name_mapper='appJS' -> '<PROJECT_ROOT>/app/assets/javascripts'
```

```js
// webpack
return {
  resolve: {
    alias: {
      appJS: path.join(projectRoot, 'app/assets/javascripts')
    }
  }
};
```

**Comment by leethree** [comment] 2017-07-10 03:33
Got the same problem. This no longer works after upgrade beyond 0.45.
```
module.system.node.resolve_dirname=.
```

**Comment by valscion** [comment] 2017-07-10 07:18
The way we resolved it for now was to list out all the "root" directories separately with `module.name_mapper` option.

So instead of 

```
module.system.node.resolve_dirname=app/assets/javascripts
```

we have this:

```
module.name_mapper='boot' -> '<PROJECT_ROOT>/app/assets/javascripts/boot'
module.name_mapper='common' -> '<PROJECT_ROOT>/app/assets/javascripts/common'
module.name_mapper='conversation' -> '<PROJECT_ROOT>/app/assets/javascripts/conversation'
# ... and so on ...
```

It isn't nearly as nice as having the `resolve_dirname` work as before, as now when we want to add a new root directory, we will need to amend this list of name mappers to cover it.

**Comment by valscion** [comment] 2019-11-20 12:08
Looks like the functionality this regression issue points out has been added back, with a combination like this:

```
module.system.node.allow_root_relative=true
module.system.node.root_relative_dirname=./app
```

(Example copied from https://github.com/facebook/flow/issues/8156#issuecomment-549946882)

We were able to get rid of our

```
module.name_mapper='boot' -> '<PROJECT_ROOT>/js/src/boot'
module.name_mapper='common' -> '<PROJECT_ROOT>/js/src/common'
module.name_mapper='conversation' -> '<PROJECT_ROOT>/js/src/conversation'
....
```

configuration by changing the `.flowconfig` options to this:

```
module.system.node.allow_root_relative=true
module.system.node.root_relative_dirname=./js/src
```

---

References:

* https://github.com/facebook/flow/releases/tag/v0.111.0
* https://github.com/facebook/flow/pull/8098#issuecomment-548957526
* https://github.com/facebook/flow/commit/d17ed03661d8c0af2450cd91645c9641fdab9d69
* https://github.com/facebook/flow/issues/8156

Pull requests that never got merged but tried to get this feature back:

* https://github.com/facebook/flow/pull/7185
* https://github.com/facebook/flow/pull/8098

Sooooo... is this issue fixed now? Granted, it was a bit difficult to find out the correct configuration options to use as [the docs](https://flow.org/en/docs/config/options/) haven't been updated yet.

**Comment by spoulson** [comment] 2019-12-12 21:47
Can confirm `resolve_dirname` broken as of 0.111.0.  My .flowconfig:

```
[options]
module.system.node.resolve_dirname=node_modules
module.system.node.resolve_dirname=src/libs
```

Getting "Cannot resolve module" errors on 0.111.0.  No error on prior versions.

**Comment by valscion** [comment] 2019-12-13 05:30
Did you try the other approach I defined above, @spoulson?

**Closed** 2019-12-13 07:54 UTC
Labels: bug, module resolution

**Comment by spoulson** [comment] 2019-12-13 18:06
@valscion Yes, the `name_mapper` setting does work.  But, it's not ideal because I need to 1) update all my repos that use previously working `resolve_dirname` and 2) explicitly state the individual module mappings, which is a configuration burden.  I enjoyed the ability to just point to a relative directory and add that to the module import paths.

Technically, I can migrate to `name_mapper`, but if `resolve_dirname` is supported functionality I'd rather use that.

**Comment by spoulson** [comment] 2019-12-13 18:07
@TrySound Why close this bug?

**Comment by TrySound** [comment] 2019-12-13 21:25
resolve_dirname is not supposed to be used this way. It allows to specify node_modules alias. For node_modules flow does not watch file changes. This is implemented to solve your problem
```
module.system.node.allow_root_relative=true
module.system.node.root_relative_dirname=./js/src
```

So it's not really a bug. The change was made intentionally to solve performance issues.
