### ISSUE TITLE
nodejs streams with {objectMode: true}

### ISSUE THREAD

**Issue by lambdabaa** [facebook/flow#2936] opened 2016-12-02 23:07 UTC
Right now the stream stuff here https://github.com/facebook/flow/blob/master/lib/node.js#L1190 assumes you're doing text streaming, but there's also a very nifty [object mode](https://nodejs.org/api/stream.html#stream_object_mode) which doesn't work with the current definitions of `_read`, `_write`, `_push`, etc.

**Comment by vkurchatkin** [comment] 2016-12-03 08:03
Duplicate of https://github.com/facebook/flow/issues/2010

**Closed by vkurchatkin** 2016-12-03 08:03 UTC
