### ISSUE TITLE
Flow creating thousands of dead processes?

### ISSUE THREAD

**Issue by bradennapier** [facebook/flow#5802] opened 2018-02-11 21:37 UTC
Its just spawning and spawning and spawning and spawning.  I currently have a single file open in Atom Editor. When I leave they all go away.  If I open atom editor again they begin to create them over and over and over until I quit or my computer litearlly shuts itself down.

![image](https://user-images.githubusercontent.com/15365418/36078835-9fadae8a-0f30-11e8-9103-0548acb1d494.png)

**Comment by bradennapier** [comment] 2018-02-11 22:13
Looking at monitor logs it would appear this is a bug in flow code

```
Feb 11 14:11:37.715 [error] Closing connection 'some ephemeral connection' due to uncaught exception in read loop: End_of_file
Feb 11 14:11:37.715 [error] backtrace:
Feb 11 14:11:37.715 [error] Raised at file "map.ml", line 130, characters 10-25
Feb 11 14:11:37.715 [error] Called from file "src/core/lwt.ml", line 817, characters 20-60
Feb 11 14:11:37.715 [error]
Feb 11 14:11:37.715 [error] Failed to shutdown socket client: Unix.Unix_error(Unix.ENOTCONN, "shutdown", "")
Feb 11 14:11:37.715 [error] backtrace:
Feb 11 14:11:37.716 [error] Raised by primitive operation at file "src/unix/lwt_unix.cppo.ml", line 1533, characters 2-38
Feb 11 14:11:37.716 [error] Called from file "src/monitor/socketAcceptor.ml", line 173, characters 18-49
Feb 11 14:11:37.716 [error]
Feb 11 14:11:37.716 [error] Closing connection 'some ephemeral connection' due to uncaught exception in read loop: End_of_file
Feb 11 14:11:37.716 [error] backtrace:
Feb 11 14:11:37.716 [error] Raised at file "map.ml", line 130, characters 10-25
Feb 11 14:11:37.717 [error] Called from file "src/core/lwt.ml", line 817, characters 20-60
Feb 11 14:11:37.717 [error]
Feb 11 14:11:37.717 [error] Failed to shutdown socket client: Unix.Unix_error(Unix.ENOTCONN, "shutdown", "")
Feb 11 14:11:37.717 [error] backtrace:
Feb 11 14:11:37.717 [error] Raised by primitive operation at file "src/unix/lwt_unix.cppo.ml", line 1533, characters 2-38
Feb 11 14:11:37.717 [error] Called from file "src/monitor/socketAcceptor.ml", line 173, characters 18-49
Feb 11 14:11:37.717 [error]
Feb 11 14:11:37.717 [error] Closing connection 'some ephemeral connection' due to uncaught exception in read loop: End_of_file
Feb 11 14:11:37.717 [error] backtrace:
Feb 11 14:11:37.717 [error] Raised at file "map.ml", line 130, characters 10-25
Feb 11 14:11:37.717 [error] Called from file "src/core/lwt.ml", line 817, characters 20-60
Feb 11 14:11:37.717 [error]
Feb 11 14:11:37.717 [error] Failed to shutdown socket client: Unix.Unix_error(Unix.ENOTCONN, "shutdown", "")
Feb 11 14:11:37.717 [error] backtrace:
Feb 11 14:11:37.717 [error] Raised by primitive operation at file "src/unix/lwt_unix.cppo.ml", line 1533, characters 2-38
Feb 11 14:11:37.717 [error] Called from file "src/monitor/socketAcceptor.ml", line 173, characters 18-49
Feb 11 14:11:37.717 [error]
Feb 11 14:11:37.717 [error] Closing connection 'some ephemeral connection' due to uncaught exception in read loop: End_of_file
Feb 11 14:11:37.717 [error] backtrace:
Feb 11 14:11:37.717 [error] Raised at file "map.ml", line 130, characters 10-25
Feb 11 14:11:37.717 [error] Called from file "src/core/lwt.ml", line 817, characters 20-60
Feb 11 14:11:37.717 [error]
Feb 11 14:11:37.717 [error] Failed to shutdown socket client: Unix.Unix_error(Unix.ENOTCONN, "shutdown", "")
Feb 11 14:11:37.718 [error] backtrace:
Feb 11 14:11:37.718 [error] Raised by primitive operation at file "src/unix/lwt_unix.cppo.ml", line 1533, characters 2-38
Feb 11 14:11:37.718 [error] Called from file "src/monitor/socketAcceptor.ml", line 173, characters 18-49
Feb 11 14:11:37.718 [error]
```

**Comment by bradennapier** [comment] 2018-02-12 02:30
I also see tons of timeouts all over when using in nuclide.  When using in console it just straight up doesnt work

```
[2018-02-12T02:28:59.419Z] [ERROR] installErrorReporter - Caught unhandled rejection Timeout after 60000 for id: 35, Calling remote method getDiagnostics..
RpcTimeoutError: Timeout after 60000 for id: 35, Calling remote method getDiagnostics..
    at Call._timeout (/Users/bradennapier/.atom/packages/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:182:20)
    at Call._timerId.setTimeout (/Users/bradennapier/.atom/packages/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:144:14)
/Users/bradennapier/.atom/packages/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:127 Uncaught (in promise) RpcTimeoutError: Timeout after 60000 for id: 35, Calling remote method getDiagnostics..
    at Call._timeout (/Users/bradennapier/.atom/packages/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:182:20)
    at Call._timerId.setTimeout (/Users/bradennapier/.atom/packages/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:144:14)
RpcTimeoutError @ /Users/bradennapier/.atom/packages/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:127
_timeout @ /Users/bradennapier/.atom/packages/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:182
Call._timerId.setTimeout @ /Users/bradennapier/.atom/packages/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:144
/Users/bradennapier/.atom/packages/nuclide/pkg/nuclide-logging/lib/consoleAppender.js:52 [2018-02-12T02:28:59.441Z] [ERROR] installErrorReporter - Caught unhandled rejection Timeout after 60000 for id: 36, Calling remote method getDiagnostics..
RpcTimeoutError: Timeout after 60000 for id: 36, Calling remote method getDiagnostics..
    at Call._timeout (/Users/bradennapier/.atom/packages/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:182:20)
    at Call._timerId.setTimeout (/Users/bradennapier/.atom/packages/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:144:14)
/Users/bradennapier/.atom/packages/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:127 Uncaught (in promise) RpcTimeoutError: Timeout after 60000 for id: 36, Calling remote method getDiagnostics..
    at Call._timeout (/Users/bradennapier/.atom/packages/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:182:20)
    at Call._timerId.setTimeout (/Users/bradennapier/.atom/packages/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:144:14)
RpcTimeoutError @ /Users/bradennapier/.atom/packages/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:127
_timeout @ /Users/bradennapier/.atom/packages/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:182
Call._timerId.setTimeout @ /Users/bradennapier/.atom/packages/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:144
/Users/bradennapier/.atom/packages/nuclide/pkg/nuclide-logging/lib/consoleAppender.js:52 [2018-02-12T02:29:13.145Z] [ERROR] installErrorReporter - Caught unhandled rejection Timeout after 60000 for id: 40, Calling remote method getDiagnostics..
RpcTimeoutError: Timeout after 60000 for id: 40, Calling remote method getDiagnostics..
    at Call._timeout (/Users/bradennapier/.atom/packages/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:182:20)
    at Call._timerId.setTimeout (/Users/bradennapier/.atom/packages/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:144:14)
/Users/bradennapier/.atom/packages/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:127 Uncaught (in promise) RpcTimeoutError: Timeout after 60000 for id: 40, Calling remote method getDiagnostics..
    at Call._timeout (/Users/bradennapier/.atom/packages/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:182:20)
    at Call._timerId.setTimeout (/Users/bradennapier/.atom/packages/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:144:14)
RpcTimeoutError @ /Users/bradennapier/.atom/packages/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:127
_timeout @ /Users/bradennapier/.atom/packages/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:182
Call._timerId.setTimeout @ /Users/bradennapier/.atom/packages/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:144```

**Comment by bradennapier** [comment] 2018-02-12 02:32
```
[2018-02-12T02:31:25.646Z] [ERROR] datatip - Error getting datatip from provider nuclide-type-hint Timeout after 60000 for id: 53, Calling remote method typeHint..
RpcTimeoutError: Timeout after 60000 for id: 53, Calling remote method typeHint..
    at Call._timeout (/Users/bradennapier/.atom/packages/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:182:20)
    at Call._timerId.setTimeout (/Users/bradennapier/.atom/packages/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:144:14)
/Users/bradennapier/.atom/packages/nuclide/pkg/nuclide-logging/lib/consoleAppender.js:52 [2018-02-12T02:31:27.407Z] [ERROR] ActiveEditorRegistry - Error from provider for source.js.jsx Timeout after 60000 for id: 60, Calling remote method getCoverage..
RpcTimeoutError: Timeout after 60000 for id: 60, Calling remote method getCoverage..
    at Call._timeout (/Users/bradennapier/.atom/packages/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:182:20)
    at Call._timerId.setTimeout (/Users/bradennapier/.atom/packages/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:144:14)
```

Really just seems like flow straight up does not work

**Comment by TrySound** [comment] 2018-02-12 05:27
@bradennapier Did you tried to run flow without atom?

**Comment by callumlocke** [comment] 2018-02-12 11:24
I had this issue and I think it was atom-related too.

**Comment by nmote** [comment] 2018-02-14 01:51
This smells to me like a problem I looked at recently.

Nuclide sends a bunch of requests to Flow to power various IDE features. This is normally fine because they typically take a few tens of milliseconds at worst. Unfortunately some files contain pathological patterns that cause Flow to spend a lot of time typechecking them (since it doesn't store type information for every symbol it has to re-typecheck on every request -- we could probably improve this by doing some caching but I digress). This can cause the Flow server to essentially freeze because it's always busy with some request or another. This would cause the timeouts you're seeing on the Nuclide side.

I didn't personally see the symptom of thousands of waiting Flow processes but it seems like it could happen. Running `ps -eaf | grep flow` and pasting the results in a gist or something would let me see exactly what those Flow processes are doing, which could shed some light on the issue.

It would be interesting to know if this happens only when you have certain files open in Atom. You could also try making a small dummy project with only simple files and see if things work as expected with those.

@avikchaudhuri just landed an optimization (21bff4b376814f5a8bcb8baf8afcd029990162b9) which extends an optimization for typechecking unions of string literals to support more patterns. This was the root cause for the issue I described above, and this fix is coming out shortly with Flow v0.66.

Your issue might be related to this perf issue, or a different one, or I could be off the mark and it's something else altogether.

**Comment by bradennapier** [comment] 2018-02-15 04:10
One thing is that I use the component resolver plugin for webpack.  This means that instead of only resolving "index.js" in a folder it will first check for "<folder-name>/<folder-name>.js" then default to "index.js" if it fails.

On top of that I use `shared` and `node_modules` as "module directories" which I know has tons of reported bugs - but they are generally not this.  

Sounds like a fairly problematic environment in the end, but hey - need it to resolve :-) and that resolution schematic is key for us.

**Comment by bradennapier** [comment] 2018-02-16 01:18
Yeah so as far as I can tell - Flow does not work i you use module_dirname anymore.  That appears to be what is causing it.

**Comment by bradennapier** [comment] 2018-02-16 22:58
@nmote unfortunately 66 did not resolve it :( - run from shell it still hangs

**Comment by nmote** [comment] 2018-02-26 19:29
@bradennapier, I didn't see any IDE requests in that process list so I don't think that's the issue I initially suspected. More likely there is something about your project that Flow doesn't handle well. If you can nail it down to a specific config option or something that would make this report more actionable. Also, I noticed you're running Flow from two different locations -- if these are both for the same project, your IDE might be running its own copy of Flow which would make Flow take twice as many resources.

@glennflanagan It's normal for Flow to spawn several worker processes, that's how it parallelizes work. Obviously it should not be using 30 GB of memory but that's a separate issue.

**Comment by SamChou19815** [comment] 2024-01-10 17:31
Flow uses multi-process model for parallelism, so this is expected behavior.

**Closed by SamChou19815** 2024-01-10 17:31 UTC
Labels: nontermination / perf
