### ISSUE TITLE
Can't find PropTypes.symbol

### ISSUE THREAD

**Issue by ahstro** [facebook/flow#2727] opened 2016-11-01 10:28 UTC
I'm importing `PropTypes`
```js
import React, { PropTypes } from "react"
```

and using it in my component's `propTypes`

```js
Content.propTypes = {
  type: PropTypes.symbol.isRequired,
}
```

but Flow is sad

```js
src/content/components/Content/Content.js:26
 26:   type: PropTypes.symbol.isRequired,
                       ^^^^^^ property `symbol`. Property not found in
 26:   type: PropTypes.symbol.isRequired,
             ^^^^^^^^^ object type
```

**Comment by NullDivision** [comment] 2016-11-24 09:17
Since we're looking at this as a Flow issue and moreover regarding Symbol types there's also an issue with symbols not being recognized as valid typeof return values:

```
src/store/index.js:43
 43:           type: typeof action.type === 'symbol' ? action.type.toString().slice(7, -1) || null : action.type
                                            ^^^^^^^^ string literal `symbol`. This value is not a valid `typeof` return value
```

**Comment by vkurchatkin** [comment] 2016-11-24 11:35
Symbols are completely  unsupported, at the moment

**Comment by vkurchatkin** [comment] 2016-11-24 11:35
BTW, this issue is a duplicate of https://github.com/facebook/flow/issues/810

**Closed by vkurchatkin** 2016-11-24 11:35 UTC
Labels: Library definitions, react
