### ISSUE TITLE
`flow version` reports 0.44.1 for 0.44.2

### ISSUE THREAD

**Issue by tberman** [facebook/flow#3755] opened 2017-04-17 22:47 UTC

**Comment by gabelevi** [comment] 2017-04-18 14:51
The issue reported in #3753 was an issue with the v0.44.1 linux binary, due to a bug in our TravisCI deploy (fixed by #3756). While I could just update the release page for GitHub, I had to republish flow-bin. I try to keep the flow-bin version in sync with the Flow version, but in this case I chose to publish flow-bin@0.44.2, which distributes Flow v0.44.1. So this is the expected behavior.

**Closed by gabelevi** 2017-04-18 14:51 UTC
