### ISSUE TITLE
Enum refinement based on property value doesn't work with bracket + literal string syntax

### ISSUE THREAD

**Issue by floriancargoet** [facebook/flow#7982] opened 2019-07-31 15:29 UTC
Flow version: 0.104.0

## Expected behavior
Enum should be refined whether I write `if (value.isFoo) {` or `if (value["isFoo"]) {`.

## Actual behavior
Enum is only refined I write `if (value.isFoo) {`. 

This is problematic when a key contains characters that requires the brackets syntax like ` { "+foo" : "bar" }`.

I've seen a lot of issue related to constant vs literal property access but here we have literal access in both case so I think it qualify as a different issue.
  

https://flow.org/try/#0C4TwDgpgBAglC8UDeAfAUFTUCWBnAYgPaEBcUwATgK4QA0GWAZsWbpdgHYDm9KAvgG40oSFABCCZOiw4CLKIwCGAG1x0GmAEaKKrdt16C0aRlQ4BjYNkIcFACgBuKmmTgpxASmQNsjKI+cIADo8IkIvJA0oAHpoqAoIRk4IAFsIDmAoAHdCCgBrXFooJ2UaWShCPxFoGCiSmiDmQiFMPmNMX396iABtACJQ4j6AXQio2PjE5LSMqAATQghcDgByTJz8ou7ytmxlZQqq8GhYKHcxOsDG4haoNragA

```
type A = {|
    isFoo: true,
    foo: string,
|};
type B = {|
    isFoo: false,
    bar: string,
|};

function f(value: A | B) {
  if (value.isFoo) {
    // refinement works, value is of type A
    value.foo;
  }

  if (value["isFoo"]) {
    // refinement doesn't work, value is still of type  A | B
    value.foo;
  }
}

```

**Comment by goodmind** [comment] 2019-07-31 18:42
There is PR that fixes this https://github.com/facebook/flow/pull/7597

**Comment by goodmind** [comment] 2019-07-31 18:42
Duplicate of #7475

**Closed by goodmind** 2019-07-31 18:42 UTC
Labels: Typing: refinements, bug, needs triage

**Comment by floriancargoet** [comment] 2019-07-31 19:30
@goodmind Thank you for the info. I'll subscribe to your PR and I hope it goes through.

**Comment by floriancargoet** [comment] 2019-07-31 19:35
@goodmind Does your PR only solve the switch case?

**Comment by goodmind** [comment] 2019-07-31 20:59
@floriancargoet, no, it should fix `if` too
