### ISSUE TITLE
ignore type of overwritten object spread properties?

### ISSUE THREAD

**Issue by jedwards1211** [facebook/flow#6800] opened 2018-08-27 16:19 UTC
The following function is guaranteed to set the `name` property to a defined value, but Flow complains about the `...input` spread because its `name` property is optional.  Maybe the type of `name` from `...input` should be ignored since it is overwritten by the `name` in the object literal?

### Code [Try flow link](https://flow.org/try/#0C4TwDgpgBA8mwEsD2A7AhgGygXigb3QFsIB+ALihIGdgAnBFAcwBooAzJJClAV0ICMItAL4AoUJCgAlCAEceCWhAAmOfEQgUa9Jqw5covAULGi2PFAGNEqQ0lqFMCAF4QAFAzA9gFODfQYAJQUMvKKKviiUFBKwDy0KJHR0QB0aZ7ezFHJGhQZwCkaUAA+xVAA5BYayuVZ0WJiQA)
```js
type Optional = {name?: ?string, foo: number}
type Required = {name: string, foo: number}

function normalize(input: Optional): Required {
  return {
    ...input,
    name: input.name || 'unnamed',
  }
}
```

### Errors
```
5:   return {
            ^ Cannot return object literal because null or undefined [1] is incompatible with string [2] in property `name`.
References:
1: type Optional = {name?: ?string, foo: number}
                           ^ [1]
2: type Required = {name: string, foo: number}
```

### Less performant workaround
The only type-safe workaround I can think of (using object rest spread or similar) incurs a performance penalty:
```js
function normalize({name, ...input}: Optional): Required {
  return {
    ...input,
    name: name || 'unnamed',
  }
}
```

**Comment by adimit** [comment] 2018-10-29 14:01
This is a duplicate of #6108.

**Comment by goodmind** [comment] 2019-04-28 06:08
Duplicate of #6108

**Closed by goodmind** 2019-04-28 06:08 UTC
Labels: Typing: spread
