### ISSUE TITLE
Flow assumes `invariant` implementation

### ISSUE THREAD

**Issue by vkurchatkin** [facebook/flow#2617] opened 2016-10-12 00:24 UTC
It seems that function named `invariant` has a special meaning Flow, even if it's not imported from `invariant` package:

```js
function invariant(x: any, msg: string) {
  console.log('Look at me! Not actually doing anything');
}

const x: ?{ foo: string } = null;

invariant(x, '')

x.foo
```

**Comment by mroch** [comment] 2016-10-12 03:14
duplicate of https://github.com/facebook/flow/issues/112. this is a tough one to solve since it alters control flow, which flow analyzes at a different phase from type inference.

**Closed by mroch** 2016-10-12 03:14 UTC
