### ISSUE TITLE
Flow is outputting unreadable message

### ISSUE THREAD

**Issue by MadeoIT** [facebook/flow#6931] opened 2018-09-25 08:37 UTC
Every time there is a type error Flow output unreadable stuff, after I run the command
`yarn flow`

```
 "C:\Users\user\Google Drive\Web Development\Prototyping\CodeSamples\googlephotoclone.js\client\node_
modules\.bin\flow"
Launching Flow server for C:\Users\user\Google Drive\Web Development\Prototyping\CodeSamples\googlepho
toclone.js\client
Spawned flow server (pid=8292)
Logs will go to C:\Users\user\AppData\Local\Temp\flow\CzCzBUserszBuserzBGoogle DrivezBWeb Developmentz
BPrototypingzBCodeSampleszBgooglephotoclone.jszBclient.log
Monitor logs will go to C:\Users\user\AppData\Local\Temp\flow\CzCzBUserszBuserzBGoogle DrivezBWeb Deve
lopmentzBPrototypingzBCodeSampleszBgooglephotoclone.jszBclient.monitor_log
←[0K←[31mError ---------------------------------------------------------------------------------------
---------- src/App.js:11:18←[0m←[0m
←[0m←[0m
←[0m←[0mCannot←[0m←[0m ←[0m←[0mcreate←[0m←[0m ←[0m←[0m←[0m←[0m←[0m←[0;1mDashboard←[0m←[0m←[0m←[0m←[0m←
[0m ←[0m←[0melement←[0m←[0m←[0m←[0m ←[0m←[0mbecause←[0m←[0m←[0m←[0m ←[0m←[0m←[0m←[0;4mnumber←[0m←[0m ←
[0m←[0;2m[←[0m←[31m1←[0m←[0;2m]←[0m←[0m←[0m←[0m ←[0m←[0mis←[0m←[0m ←[0m←[0mincompatible←[0m←[0m ←[0m←[
0mwith←[0m←[0m ←[0m←[0m←[0m←[0;4mstring←[0m←[0m ←[0m←[0;2m[←[0m←[36m2←[0m←[0;2m]←[0m←[0m←[0m←[0m ←[0m←
[0min←[0m←[0m ←[0m←[0m←[0m←[0mproperty←[0m←[0m ←[0m←[0m←[0m←[0;1mmessage←[0m←[0m.←[0m←[0m
←[0m←[0m
←[0m←[0m     ←[0m←[0msrc/App.js
←[0m←[0m     ←[0m←[0m ←[0m←[0;2m7←[0m←[0;2m|←[0m←[0m ←[0m←[0;2mclass App extends React.Component<Props
> {←[0m←[0m
←[0m←[0m     ←[0m←[0m ←[0m←[0;2m8←[0m←[0;2m|←[0m←[0m ←[0m←[0;2m  render() {←[0m←[0m
←[0m←[0m     ←[0m←[0m ←[0m←[0;2m9←[0m←[0;2m|←[0m←[0m ←[0m←[0;2m    return (←[0m←[0m
←[0m←[0m     ←[0m←[0m←[0m←[0;2m10←[0m←[0;2m|←[0m←[0m ←[0m←[0;2m      ←[0m←[0m<Dashboard ←[0m←[0m
←[0m←[0m ←[0m←[0;2m[←[0m←[31m1←[0m←[0;2m]←[0m←[0m ←[0m←[0m←[0m←[0;2m11←[0m←[0;2m|←[0m←[0m ←[0m←[0m
    message={←[0m←[31m23←[0m←[0m}←[0m←[0m
←[0m←[0m     ←[0m←[0m←[0m←[0;2m12←[0m←[0;2m|←[0m←[0m ←[0m←[0m      />←[0m←[0;2m←[0m←[0m
←[0m←[0m     ←[0m←[0m←[0m←[0;2m13←[0m←[0;2m|←[0m←[0m ←[0m←[0;2m    );←[0m←[0m
←[0m←[0m     ←[0m←[0m←[0m←[0;2m14←[0m←[0;2m|←[0m←[0m ←[0m←[0;2m  }←[0m←[0m
←[0m←[0m     ←[0m←[0m←[0m←[0;2m15←[0m←[0;2m|←[0m←[0m ←[0m←[0;2m}←[0m←[0m
←[0m←[0m
←[0m←[0m     ←[0m←[0msrc/Component/Dashboard/index.js
←[0m←[0m ←[0m←[0;2m[←[0m←[36m2←[0m←[0;2m]←[0m←[0m ←[0m←[0m ←[0m←[0;2m5←[0m←[0;2m|←[0m←[0m ←[0m←[0;2m
←[0m←[0m ←[0m←[36mstring←[0m←[0;2m
←[0m←[0m
←[0m←[0m
←[0m
Found 1 error
error Command failed with exit code 2.

```

I am using flow with create-react-app and I have followed this instructions: https://flow.org/en/docs/tools/create-react-app/

**Comment by wchargin** [comment] 2018-09-25 16:54
Duplicate of #4568?

These are ANSI escape codes. Running `yarn flow --color=never` will
prevent these codes from appearing.

It looks like you’re running on Windows, so it’s probable that your
terminal emulator doesn’t have good color support. One way to solve this
problem would be to acquire a better terminal emulator:

<https://superuser.com/questions/413073/windows-console-with-ansi-colors-handling>

**Comment by anton6** [comment] 2019-03-02 10:18
@wchargin thanks for the link.

This issue should probably be marked as closed.

**Closed** 2019-03-02 10:27 UTC
