### ISSUE TITLE
narrower type inference of for..in loop variables

### ISSUE THREAD

**Issue by jedwards1211** [facebook/flow#2970] opened 2016-12-08 00:58 UTC
Flow seems to always infer `string` type for the variable in `for..in` loops, but it could make narrower inferences for enum types.  The following code fails to typecheck:

```es6
// @flow

type Axis = 'x' | 'y'

const axisProps: {[axis: Axis]: {}} = {}

for (let axis in axisProps) {
  const props = axisProps[axis]
}
```

```
src/temp.js:8
  8:   const props = axisProps[axis]
                               ^^^^ string. This type is incompatible with
  5: const axisProps: {[axis: Axis]: {}} = {}
                              ^^^^ string enum


Found 1 error
```

**Comment by mroch** [comment] 2016-12-08 01:15
heh, funny that this came up again. someone +1'd a duplicate of this yesterday: https://github.com/facebook/flow/issues/1736. i'll re-title that one, no wonder it's impossible to find.

**Closed by mroch** 2016-12-08 01:15 UTC

**Comment by jedwards1211** [comment] 2016-12-08 01:24
@mroch yeah I figured someone else would have come across this.  Thanks!
