### ISSUE TITLE
Retrieve / destruct generic

### ISSUE THREAD

**Issue by darky** [facebook/flow#2775] opened 2016-11-09 10:31 UTC
Can I in any way to destruct generic, where "destructing" is similar EcmaScript feature.
Example:

```javascript
declare type LodashChain<T> = {
  map : <S, T: Array<S>, U>(fn: (value: S, i: number, self: T) => U) => Array<U>
};
```

In this example `S` is `unknown` type, bacause it not declared clearly. But I want, that `S` will be type of `T` Array item. For example if I pass `T` as `Array<number>`, `S` should be type `number`. Need to retrieve / destruct genetic `T` and extract from it variables.

**Comment by vkurchatkin** [comment] 2016-11-09 11:57
Have you tried it? This should work

**Comment by darky** [comment] 2016-11-09 12:44
No, this not working, because `S` defined from scratch and has type `unknown`. But need to retrieve type from `T`, which appears as `Array<type_that_need_to_place_in_S>`

**Comment by vkurchatkin** [comment] 2016-11-09 13:19
Ah, yes, I haven't notice that you try to infer `S` from existing `T`.  This is a duplicate of https://github.com/facebook/flow/issues/30 then.

**Closed by vkurchatkin** 2016-11-09 13:19 UTC

**Comment by darky** [comment] 2016-11-09 22:51
This trick help me:

```javascript
declare type _GetArrayType2<S> = Array<S>;
declare type _GetArrayType<S, T: _GetArrayType2<S>> = S;
declare type GetArrayType<T: Array<*>> = _GetArrayType<*, T>;
```
