### ISSUE TITLE
Allow subtyping of strings via Regex

### ISSUE THREAD

**Issue by emdash** [facebook/flow#5533] opened 2017-12-18 21:35 UTC
Not sure  what the declaration syntax would look like, but maybe something like:
```
 var x: string</(a|b)*/>;
```

Examples:
```
x = "ab";            // good
x = "aaabbbbb" // good.
x = "abc"           // error
x = bar              // error, requires refinement

// good
if (bar.match(/(a|b)*/)) {
  x = bar
}{
```

**Comment by TiddoLangerak** [comment] 2017-12-19 08:10
https://github.com/facebook/flow/issues/4654

**Comment by TrySound** [comment] 2018-03-12 05:24
Duplicate of https://github.com/facebook/flow/issues/4654

/cc @vkurchatkin

**Closed** 2019-01-31 17:13 UTC
