### ISSUE TITLE
Type constraint in generic type parameters of an async arrow function causes parser error

### ISSUE THREAD

**Issue by noppa** [facebook/flow#8387] opened 2020-05-30 22:25 UTC
Flow version: 105.1

## Expected behavior
```javascript
const fn = async <S: string>(_: S) => _
```
Should not give errors.

## Actual behavior
Flow errors with
```
1: const fn = async <S: string>(_: S) => _
                      ^ Unexpected token `:`, expected the start of a statement
```

* Link to Try-Flow or Github repo: https://flow.org/try/#0MYewdgzgLgBAZmGBeGBDCBPMwYB4DKAXDNAE4CWYA5gHwAUA+sfgJTI0wNA

Flow does not give error if either `async` or the constraint is removed, or the function is changed from an arrow function to a "regular" async function expression/statement.
 
```javascript
const noError1 = <S: string>(_: S) => Promise.resolve(_)  // ok
const noError2 = async <S>(_: S) => _  // ok
const noError3 = async function<S: string>(_: S) { return _ }  // ok
```

**Comment by gkz** [comment] 2020-05-31 03:21
Duplicate of #8213

**Closed by gkz** 2020-05-31 03:21 UTC
Labels: bug, needs triage
