### ISSUE TITLE
If two files import each other, then Flow errors if you use .addEventListener

### ISSUE THREAD

**Issue by Macil** [facebook/flow#1155] opened 2015-12-04 02:47 UTC
a.js

``` js
/* @flow */
import './b';
var div = document.createElement('div');
div.addEventListener('foo', function() {});
```

b.js

``` js
/* @flow */
import './a';
var div = document.createElement('div');
div.addEventListener('foo', function() {});
```

```
[chris /tmp/foo]$ flow version
Flow, a static type checker for JavaScript, version 0.19.0
[chris /tmp/foo]$ flow
../flow/flowlib_2e6724f0/dom.js:62
 62: type EventListener = {handleEvent: EventHandler} | EventHandler
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^ Library type error:
 62: type EventListener = {handleEvent: EventHandler} | EventHandler
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^ property `handleEvent`. Property not found in
  4: div.addEventListener('foo', function() {});
                                 ^^^^^^^^^^^^^ function. See: b.js:4


Found 1 error
```

Flow only complains about the addEventListener calls in b.js strangely.

(This example is a silly use of circular dependencies, but circular dependencies can be perfectly legitimate. If neither module immediately relies on side effects of the other module -- like they both just export some functions that happen to refer to each other -- then there's no issue.)

**Comment by samwgoldman** [comment] 2016-01-27 05:54
This is pretty bizarre. I'll investigate this. Thanks!

**Comment by futpib** [comment] 2017-12-27 15:10
I can't reproduce this with `0.61.0`. (Tried to see if my issues were related.)

**Comment by SamChou19815** [comment] 2023-03-03 18:05
This issue should have been fixed by types-first

**Closed by SamChou19815** 2023-03-03 18:05 UTC
Labels: bug
