### ISSUE TITLE
Specify a range number

### ISSUE THREAD

**Issue by xareelee** [facebook/flow#3972] opened 2017-05-18 11:43 UTC
If I want to specify a variable to be a number type with a range, how can I do that?

For example, I have float variables `r`/`g`/`b` for colors within `0..1` ranges.

```js
type ColorChannelType = ...  // a number type within 0 to 1 range

const r: ColorChannelType = 0.3  // good
const g: ColorChannelType = 0.2  // good
const b: ColorChannelType = 0.1  // good

const rx: ColorChannelType = 3   // should raise an error
```

**Comment by vkurchatkin** [comment] 2017-05-18 12:37
You can't do that at the moment. To be honest, this doesn't seem particularly useful.

**Comment by emdash** [comment] 2017-12-18 21:27
I think it would be useful to restrict numeric types in various ways:
- Closed intervals (ranges)
- Integer (pseudo-type which allows only exact integers (forces you to use floor/ceil when operands aren't integers)
- Satisfies some arbitrary test: {x| x % 2 === 1}

**Comment by iddan** [comment] 2018-01-29 09:15
While writing [reactive-material](http://github.com/reactive-material) I wanted to specify statically that a prop only accepts a range of integers from 1 to 24. Eventually wrote a full union type but it felt wrong.

**Comment by vkurchatkin** [comment] 2018-01-29 13:14
It's not particularly hard to implement this feature. `1..5` could be basically sugar for `1 | 2 | 3 | 4 | 5`. The problem is that if Flow adds this, people would want proper refinements for this.

This should work, right?

```js
function test(x: number):1..5 {
  if (Number.isInteger(x) && x >= 1 && x <= 5) {
    return x;
 }

  return 1;
}
```

How about this?

```js
function test(x: 1..3):1..5 {
  return x + 1;
}
```

This would be much harder to implement.

**Comment by iddan** [comment] 2018-01-29 14:24
Interesting case. but if Flow knows to validate
```javascript
function test(x: number): number {
  return x + 1;
}
```
and able to infer the two sides of the arithmetic operation isn't it a scoped problem?

**Comment by emdash** [comment] 2018-01-29 19:38
Definitely would want the basic refinement with relational operators. For other cases, I would be satisfied with simply having to clamp an expression with `Math.min()` and `Math.max()`.

**Comment by iddan** [comment] 2018-01-30 09:45
I don't feel comfortable with idea of applying Math.max and Math.min for simple add. Can't it be reached statically? Maybe we can restrict arithmetic operations on ranges to ranges and number literals

**Comment by rhuankarlus** [comment] 2019-11-03 00:21
Is there something done about this here?

**Comment by SamChou19815** [comment] 2023-02-22 05:20
This is not possible, and we don't intend to support it.

**Closed by SamChou19815** 2023-02-22 05:20 UTC
Labels: feature request
