### ISSUE TITLE
ES7 decorator support or a way to ignore the error

### ISSUE THREAD

**Issue by bsr203** [facebook/flow#606] opened 2015-07-06 20:40 UTC
Hi,

ES7 decorators cannot be used with flow. Wish there is a way to continue using `flow` but may just ignore this feature. Currently it stops the server with error.

```
Unexpected token ILLEGAL

```

Error is pointing to the `@` character

```
@connectToStores(getState, TestStore)
export default class MyComponent extends React.Component {
```

**Comment by nmn** [comment] 2015-07-08 09:44
https://github.com/facebook/flow/issues/454#issuecomment-119524118

**Comment by majhork** [comment] 2015-07-13 01:35
try this:
```js
class Foo {
    /*::_(){`*/ @deco /*::`;}*/
    bar() {
    }

    /*::_(){`*/ @long_deco(
      params // ...
    ) /*::`;}*/
    baz() {
    }
}
```

**Comment by nrako** [comment] 2015-07-13 07:58
:fearful: oh my gosh, that is definitely not a viable solution.

**Comment by majhork** [comment] 2015-07-13 11:30
It isn't pleasant but it should be easy to find/replace when they support decorators later and it works right now.

**Comment by nrako** [comment] 2015-07-13 12:50
I agree that is an increasing pain point which at the moment hold me back from using Flow.

But for the sake of DX, I would rather see decorator ignored by the Flow parser than adding more flow comments...

Anyway, in the long term that doesn't solve the problems, however what is discussed in #454 might. I just hope we'll start to see a clear implementation details of that.

**Comment by nmn** [comment] 2015-07-14 10:02
I think for Flow's sake, it should get out of the business of implementing ES6 features entirely and offload that task to Babel.

This would mean that flow should switch to the AST that Babel generates, and do it's thing on that. Babel is already way ahead implementing new ES6 features. It would be a considerable amount of work in the short term, but would free up time for more important stuff in the future.

I'm not sure how difficult it will be to integrate the JS-based Babel into the OCaml based Flow.

**Comment by AgentME** [comment] 2015-07-15 17:51
@nmn ES6 is set in stone at this point iirc, so there's no longer an issue of Flow chasing a moving target. (And Babel is pretty far along in ES6 support.) A lot of ES6 features would be pretty complicated to support correctly if Flow only operated on the transpiled source. Babel renames scoped let/const variables when there are conflicts, and classes come out pretty mangled. Flow could be made to recognize the specific way that classes get transpiled, but then it probably would fail to recognize the way that classes with decorators get mangled unless it was changed to specifically recognize that. But then if there needs to be code added to Flow to recognize decorators, it might as well be made to just recognize (or ignore) the decorators directly.

That strategy of using Babel might make more sense with experimental/ES7+ stuff. Just use it to transpile things to ES6. Though I don't think decorators on classes can be transpiled to ES6 classes. The proposed :: bind operator is the one thing that I think could be a good workable use of Babel.

**Comment by nmn** [comment] 2015-07-16 09:53
@AgentME I'm actually not suggesting that Flow operate on the transpiled version. Babel works in three high level stages:
Parsing, Transformation, Code Generation.

The first Step of the three Parsing is the step where the source code is converted into an AST.

Flow has it's own Parser that does the same thing but to an AST which is of a slightly different format. All I'm suggesting is that Flow should adopt the Babel Parser and focus on error checking.

There would still be some considerable amount of work. Let/Const parsing has been in master for a while, but correctly checking for errors with them is more complicated. So this wouldn't solve the problem completely, but it would reduce the amount of work needed to be done in Flow itself.

Further, with Sebastian now joining Facebook, and React moving to Babel, Babel is much more likely to be contributed to by people other Sebastian as well. Further, Facebook now has some sort of control over the project. So it only makes sense to remove the duplicated effort.

Sebastian has also shown interest in working with Flow to build a better linter. Having a common AST format will definitely help with that.

**Comment by gajus** [comment] 2015-07-17 16:30
> Flow has it's own Parser that does the same thing but to an AST which is of a slightly different format. All I'm suggesting is that Flow should adopt the Babel Parser and focus on error checking.

Please do that. Implementing Flow in ES6 project is hard. Implementing Flow in a project that is using experiment features is near impossible.

**Comment by gajus** [comment] 2015-07-17 16:30
@nmn Please open a separate issue detailing your proposal.

**Comment by penguinsoccer** [comment] 2015-10-26 13:38
Any progress?

**Comment by TiddoLangerak** [comment] 2015-10-26 22:22
Using the babel AST would also open up the possibility for pluggable parsers: the guys behind many popular JavaScript parsers, including Babel, have created a spec for a JavaScript AST called [estree](https://github.com/estree/estree). If Flow would also use that format then it would automatically be compatible with many of those parsers.

**Comment by idolize** [comment] 2015-10-28 00:33
See https://github.com/facebook/flow/issues/850#issuecomment-142730653 for more information on suppressing decorator error output

**Comment by penguinsoccer** [comment] 2015-10-28 23:30
Thanks :)

**Comment by STRML** [comment] 2015-12-12 17:02
Just to update the progress of this, decorators are ignorable on methods, not on classes. #1001 is tracking a failing test.

You still must use the [above workaround](https://github.com/facebook/flow/issues/606#issuecomment-120781083) in the meantime.

**Comment by marudor** [comment] 2016-04-08 08:37
PR for this:
https://github.com/facebook/flow/pull/1638

**Comment by cheapsteak** [comment] 2016-04-14 22:18
It looks like the commits from @marudor 's PR were merged ?
https://github.com/facebook/flow/commit/07ff61c3c4545280d208af3d4c59e89f125b2c65

**Comment by LegNeato** [comment] 2016-04-23 05:40
I can confirm that setting `esproposal.decorators=ignore` in the `[options]` section of `.flowconfig` silences the error in latest homebrew release (0.23.1).

**Comment by STRML** [comment] 2016-04-23 16:07
:+1: I also see it working (finally get to remove those comment hacks, thanks @marudor!), but perhaps the docs should clarify that class decorators are simply ignored, not typed. 

Perhaps we should open another issue to track the work to transition from `ignore` to `enable`?

**Comment by jeffmo** [comment] 2016-06-23 12:33
Closing thanks to @marudor's fix. Woo!

**Closed by jeffmo** 2016-06-23 12:33 UTC
Labels: ES2015+

**Comment by c58** [comment] 2017-01-22 19:12
Hey guys! Is there any chance to add a support (just ignore for now) for function decorators in POJOs?
Flowtype generates a lot of errors for this code, even with `esproposal.decorators=ignore`:
```
const Test = {
   @test
   func() {
   }
}
```

**Comment by anback** [comment] 2017-02-27 06:13
This worked for me

![image](https://cloud.githubusercontent.com/assets/2440382/23350649/46a679fc-fcbc-11e6-99b8-6362515b2fd9.png)

**Comment by qaiser110** [comment] 2017-04-17 09:50
In `.flowconfig` set this option:

```sh
[options]
esproposal.decorators=ignore
```

Ref: [Flow Docs](https://flow.org/en/docs/config/options/)

**Comment by c58** [comment] 2017-04-17 09:51
It works for classes, but not for object properties.

**Comment by azarus** [comment] 2017-05-25 00:01
@majhork 
`/*::`*/ @deco /*::`;*/`
I can't believe that you were thinking its better than the warnin lol

**Comment by JanPeter** [comment] 2017-06-06 18:10
Is there any chance that flow will start to support decorators if they are in stage-3?

**Comment by azarus** [comment] 2017-06-07 11:51
> Is there any chance that flow will start to support at least class and property decorators if they are in stage-3?

I think that you can use thirdparty transforms, and add options to ignore the warnings for now?

**Comment by c58** [comment] 2017-06-07 11:53
yes, that works, but as i said multiple times before, flow just failing even if ignoring enabled for cases when decorator used with object property like this:
```
const myObject = {
   @my_decorator
   testFunction(){
   }
}
```

**Comment by azarus** [comment] 2017-06-07 13:08
Well i just looked into flow i wanted to add typings to my library to avoid comon errors with parameter types and the issues were just to overwhelming. SO i ended up using typescript and i wrote a couple of post events that transform the code for my needs. Looking forward to use flow with babel once theres proper support for decorators and for real this thing gets into an usable state.

**Comment by JanPeter** [comment] 2017-06-07 20:39
@c58 I've currently the same problem. It seems that if I add decorators to my library I can't get autocomplete to work properly if I include it in a new project via a dependency on VS Code or Atom. Though autocomplete works just fine when I write my tests for the library itself. Maybe somebody could have a look at it. https://github.com/JanPeter/neo4js

**Comment by jedwards1211** [comment] 2017-07-11 16:46
@mroch can't ignoring decorators cause type issues?  For instance, won't flow complain about a missing `foo` property in `<MyComp />` below, whereas if using `connect(...)(MyComp)` it wouldn't because it processes the `react-redux` type defs?

```js
type Props = {foo: string}

@connect(state => ({foo: state.foo}))
class MyComp extends React.Component<void, Props, void> {
  ...
}

const elem = <MyComp /> // won't flow flag an error about a missing `foo` property here?
```
