### ISSUE TITLE
`|| undefined` seems to silence property access errors

### ISSUE THREAD

**Issue by julienw** [facebook/flow#4190] opened 2017-06-16 13:51 UTC
Hi,
Today I was quite surprised that using a `|| undefined` somewhere seemed to silence an error.

Here is a simplified testcase:

```javascript
type MyObject = {
  property: string,
};

let object: MyObject = {
  property: 'hello world',
};

object.property; // no error
object.property1; // error
object.property1 || undefined; // no error ??
```
See the error live: https://flow.org/try/#0C4TwDgpgBAsiDyAjAVhAxsKBeKBvAUFFGAE4D2kJoAXFAM7AkCWAdgOYA0+AvgNz74ANhExkU6YLThJUGbHkLFylGlADkACwiDBZKAHcyJQQBM1XPgLGzgAOlIUIVEP2sT7yp6ACMr8Rg9HZ28oAB9QqABXFhMIADNWCBN+IA

**Comment by julienw** [comment] 2017-06-16 13:54
Same error if MyObject is an exact type.

**Comment by rsolomon** [comment] 2017-06-16 20:07
Duplicate of #3887 I think

**Comment by julienw** [comment] 2017-06-17 12:03
Yep, I think you're right

**Closed** 2017-06-17 12:04 UTC
