### ISSUE TITLE
Tons of "modified files:" reported when idle

### ISSUE THREAD

**Issue by cbrunnkvist** [facebook/flow#7415] opened 2019-01-30 14:04 UTC
Flow version:
**0.91.0**

## Expected behavior
When server sits idle, nothing should be happening.

## Actual behavior
Constant and seemingly spurious reports of files being modified everywhere inside the project root. Sometimes a couple, sometimes ten, sometimes thousands (from e.g. ./node_modules/).

"File watcher reported 42095 files changed"

Typically causes the server to be busy all the time. 

OS Version: 
MacOS 10.13.5

Project dir:
/Users/{username}/Documents/code

I've read some other report (can't find the ticket here on GH though) somewhere about perhaps iCloud Documents updating metadata perhaps be incorrectly triggering the file watcher. But that feels like something >HighSierra-specific which we could fix in such case.

* Link to Try-Flow or Github repo:

**Comment by cbrunnkvist** [comment] 2019-01-30 14:05
```/private/tmp/flow/zSUserszSXzSYzSui.monitor_log:Jan 30 21:03:00.903 [info] File watcher reported 29 files changed
/private/tmp/flow/zSUserszSXzSYzSui.monitor_log:Jan 30 21:03:01.905 [info] File watcher reported 1 file changed
/private/tmp/flow/zSUserszSXzSYzSui.monitor_log:Jan 30 21:03:04.576 [info] File watcher reported 21 files changed
/private/tmp/flow/zSUserszSXzSYzSui.monitor_log:Jan 30 21:03:05.920 [info] File watcher reported 16 files changed
/private/tmp/flow/zSUserszSXzSYzSui.monitor_log:Jan 30 21:03:06.924 [info] File watcher reported 17 files changed
/private/tmp/flow/zSUserszSXzSYzSui.monitor_log:Jan 30 21:03:07.929 [info] File watcher reported 1 file changed
/private/tmp/flow/zSUserszSXzSYzSui.monitor_log:Jan 30 21:03:09.932 [info] File watcher reported 3 files changed
/private/tmp/flow/zSUserszSXzSYzSui.monitor_log:Jan 30 21:03:10.934 [info] File watcher reported 38 files changed
/private/tmp/flow/zSUserszSXzSYzSui.monitor_log:Jan 30 21:03:11.936 [info] File watcher reported 58 files changed
/private/tmp/flow/zSUserszSXzSYzSui.monitor_log:Jan 30 21:03:12.941 [info] File watcher reported 89 files changed
/private/tmp/flow/zSUserszSXzSYzSui.monitor_log:Jan 30 21:03:13.941 [info] File watcher reported 55 files changed
/private/tmp/flow/zSUserszSXzSYzSui.monitor_log:Jan 30 21:03:14.947 [info] File watcher reported 5 files changed
/private/tmp/flow/zSUserszSXzSYzSui.monitor_log:Jan 30 21:03:15.947 [info] File watcher reported 6 files changed
/private/tmp/flow/zSUserszSXzSYzSui.monitor_log:Jan 30 21:03:25.979 [info] File watcher reported 1 file changed
/private/tmp/flow/zSUserszSXzSYzSui.monitor_log:Jan 30 21:03:28.992 [info] File watcher reported 51 files changed
/private/tmp/flow/zSUserszSXzSYzSui.monitor_log:Jan 30 21:03:29.993 [info] File watcher reported 40 files changed
/private/tmp/flow/zSUserszSXzSYzSui.monitor_log:Jan 30 21:03:30.997 [info] File watcher reported 3 files changed
/private/tmp/flow/zSUserszSXzSYzSui.monitor_log:Jan 30 21:03:31.998 [info] File watcher reported 18 files changed
/private/tmp/flow/zSUserszSXzSYzSui.monitor_log:Jan 30 21:03:35.005 [info] File watcher reported 1 file changed
/private/tmp/flow/zSUserszSXzSYzSui.monitor_log:Jan 30 21:03:36.006 [info] File watcher reported 1 file changed
/private/tmp/flow/zSUserszSXzSYzSui.monitor_log:Jan 30 21:03:37.009 [info] File watcher reported 1 file changed
/private/tmp/flow/zSUserszSXzSYzSui.monitor_log:Jan 30 21:03:40.016 [info] File watcher reported 7 files changed
/private/tmp/flow/zSUserszSXzSYzSui.monitor_log:Jan 30 21:03:44.028 [info] File watcher reported 12 files changed
/private/tmp/flow/zSUserszSXzSYzSui.monitor_log:Jan 30 21:03:45.033 [info] File watcher reported 5 files changed
/private/tmp/flow/zSUserszSXzSYzSui.monitor_log:Jan 30 21:03:48.040 [info] File watcher reported 4 files changed
/private/tmp/flow/zSUserszSXzSYzSui.monitor_log:Jan 30 21:03:49.044 [info] File watcher reported 38 files changed
/private/tmp/flow/zSUserszSXzSYzSui.monitor_log:Jan 30 21:03:50.046 [info] File watcher reported 8 files changed
```

**Comment by vicapow** [comment] 2019-02-01 00:16
Thanks for reporting, @cbrunnkvist 

I also suspect it may be caused by some activity on your system that Flow isn't in control of. As a shot in the dark, there may be an option to look for logs of watchman to see exactly what data about the files are changing: https://facebook.github.io/watchman/docs/troubleshooting.html

It may also help debug this issue by upgrading to Mojave and see if it's mitigated.

Do you mind if we close this for now and you can reopen if you're able to collect more info or have steps to reproduce?

**Closed by vicapow** 2019-02-01 00:16 UTC
Labels: bug
