### ISSUE TITLE
Can't Object.create on a polymorphic type, even after instanceof Object check

### ISSUE THREAD

**Issue by jedwards1211** [facebook/flow#1690] opened 2016-04-20 16:26 UTC
I can't get the following to work:

``` js
export default function headerSupport<X: Object>(collection: X): 
  X & {withHeaders: (theHeaders: Object) => X}
{
  if (collection instanceof Object) {
    return Object.assign(Object.create(collection), {
      withHeaders(theHeaders: Object): X {
...
```

Flow complains that

```
mindfront-react-components/meteor/collection/headerSupport.js:22
 22:     return Object.assign(Object.create(collection), {
                ^ call of method `assign`
 22:     return Object.assign(Object.create(collection), {
                              ^^^^^^^^^^^^^^^^^^^^^^^^^ Object.create. This type is incompatible with
 17: export default function headerSupport<X: Object>(collection: X): X & {withHeaders: (theHeaders: Object) => X} {
                    ^ some incompatible instantiation of `X`
```

But since my code checked that `collection instanceof Object`, `Object.create(collection)` will absolutely work at runtime and should not be considered an error.  Basically it should accept any X where `typeof X === 'object'`, since `null` is a valid argument as well.

Looking in the [core flow defs](https://github.com/facebook/flow/blob/master/lib/core.js#L36), I see

``` js
    static create(o: any, properties?: any): any; // compiler magic
```

What is this compiler magic?

**Comment by jedwards1211** [comment] 2016-04-20 16:32
Even casting to `(collection: any)` doesn't stop the error, which seems to totally violate the type signature from the core flow defs.

**Comment by calebmer** [comment] 2017-07-26 15:40
Closing since this issue hasn’t seen a lot of activity. Sorry about that 😣

Please reopen with a reproduction on https://flow.org/try if you are still having issues!

**Closed by calebmer** 2017-07-26 15:40 UTC
