### ISSUE TITLE
type Foo = Foo should error

### ISSUE THREAD

**Issue by vicapow** [facebook/flow#5573] opened 2017-12-26 16:36 UTC
````js
type Foo = Foo;
function foo(f: Foo) { f = f + f; }
````

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiccYAvESQNypQCuAdgMYYCWcDYUJAFFAFyU4ASjABvLuUkBqLlTABfIA

**Comment by NameFILIP** [comment] 2018-02-01 21:40
Similar to https://github.com/facebook/flow/issues/5559

**Comment by stereobooster** [comment] 2018-07-23 16:44
Duplicate of https://github.com/facebook/flow/issues/5771

**Comment by goodmind** [comment] 2019-05-30 02:25
Duplicate of #5771

**Closed by goodmind** 2019-05-30 02:25 UTC
