### ISSUE TITLE
Nested switch seems to throw away type refinement from the outer switch

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#1876] opened 2016-05-31 22:55 UTC
Here is an example:

``` js
/* @flow */

type Message =
  | { tag: "Foo", fooStep: 1 }
  | { tag: "Bar", barStep: 2 }

type Model =
  | { tag: "Foo", foo: FooModel }
  | { tag: "Bar", bar: BarModel }

class FooModel {
  foo: number;
  constructor(foo) {
    this.foo = foo
  }
}

class BarModel {
  bar: number;
  constructor(bar) {
    this.bar = bar
  }
}

export const inc =
  (model:Model, message:Message):Model => {
    switch (message.tag) {
      case "Foo":
        switch (model.tag) {
          case "Foo":
            return { tag: "Foo", foo: new FooModel(model.foo.foo + message.fooStep) }
        }
      case "Bar":
        switch (model.tag) {
          case "Bar":
            return { tag: "Bar", bar: new BarModel(model.bar.bar + message.barStep) }
        }
      default:
        return model
    }
  }
```

That reports following error:

```
scratch.js:36
 36:             return { tag: "Bar", bar: new BarModel(model.bar.bar + message.barStep) }
                                                                                ^^^^^^^ property `barStep`. Property not found in
 36:             return { tag: "Bar", bar: new BarModel(model.bar.bar + message.barStep) }
                                                                        ^^^^^^^ object type


Found 1 error
```

It seems to me that refinement over `message` type in the outer switch case has being thrown away due to nested switch statement. Also note that factoring out each case of the outer switch into own functions works as expected which further supports my suspicion of cancelled outer refinement further.

**Comment by asolove** [comment] 2017-08-21 19:51
I think the type error here, though legitimately very confusing, is not a bug.

Instead, it's just a classic problem with unexpected switch fall-through. Imagine what happens if we get a message of type "Foo" and a Model of type "Bar":

```
export const inc =
  (model:Model, message:Message):Model => {
    switch (message.tag) {
      case "Foo": // <- we select this case
        switch (model.tag) {
          case "Foo": // <- we don't select this case
            return { tag: "Foo", foo: new FooModel(model.foo.foo + message.fooStep) }
        }
       // as a result, we don't return, and we fall "through" the `case "Bar":` into the following code:
      case "Bar":
        switch (model.tag) {
          case "Bar":
            return { tag: "Bar", bar: new BarModel(model.bar.bar + message.barStep) }
        }
      default:
        return model
    }
  }

So you need to handle the case where you have a "Foo" message but a "Bar" model, by explicitly returning so you prevent the `switch` fall-through:

```js
export const inc =
  (model:Model, message:Message):Model => {
    switch (message.tag) {
      case "Foo":
        switch (model.tag) {
          case "Foo":
            return { tag: "Foo", foo: new FooModel(model.foo.foo + message.fooStep) }
          default:
            return model;
        }
      case "Bar":
        switch (model.tag) {
          case "Bar":
            return { tag: "Bar", bar: new BarModel(model.bar.bar + message.barStep) }
        }
      default:
        return model
    }
  }
```

And sure enough, that type checks!

I hope that makes sense! If not, let me know and I can try to make my explanation clearer.

Also, if that makes sense, I think we can close this issue.

**Closed** 2017-09-14 22:44 UTC
Labels: bug
