### ISSUE TITLE
Default Props not understood by flow

### ISSUE THREAD

**Issue by NgoKnows** [facebook/flow#1660] opened 2016-04-14 09:22 UTC
So I have a component like this

```
type Props = {
    name          : string,
    value         : number,
    tooltipValues? : Array<string>,
    handleChange?  : (value: number) => void
};
class Slider extends Component {
    static defaultProps = {
        tooltipValues : [],
        handleChange  : () => {}
    };
    state: State;
    props: Props;
...
```

So I should be able to use handleChange without Flow warning about a possibly undefined value, but it still warns me. Is there something I'm doing wrong or a way around this?

**Comment by marudor** [comment] 2016-04-14 09:30
Remove the optional in the Props.
Flow won't complain if you are missing handleChange due to the defaultProp.

**Comment by NgoKnows** [comment] 2016-04-14 09:33
Oh okay I see, thanks. But there is no way for it to work with optionals? I prefer it with optionals because it makes it clear within the context of the component, that those particular props are optional.

**Comment by marudor** [comment] 2016-04-14 09:34
Well the thing is: as a type it is no longer optional.
There is no way for it to be not defined anymore.
Thats why the type is non optional now.

**Comment by NgoKnows** [comment] 2016-04-14 09:39
Ah okay, that makes sense. I guess the optional props would be more of a PropTypes use case.

**Comment by gcanti** [comment] 2016-07-06 06:07
Flow deals with `Props` and `propTypes` differently though

this type-checks

```js
class A extends React.Component {

  static defaultProps = {
    name: 'Giulio'
  };

  static propTypes = {
    name: React.PropTypes.string // <= not required
  };

  render() {
    const name: string = this.props.name
    return <div>{name}</div>
  }

}
```

this doesn't

```js
type Props = {
  name?: string // <= not required
};

class B extends React.Component {

  static defaultProps = {
    name: 'Giulio'
  };

  props: Props;

  render() {
    const name: string = this.props.name
    return <div>{name}</div>
  }

}
```

**Comment by pconerly** [comment] 2017-01-31 18:43
@gcanti Isn't that because you should be not letting `name` be optional?

This typechecks for me:
```
// @flow
import React from 'react'

type Props = {
  name: string // <= not required
}

class B extends React.Component {
  static defaultProps = {
    name: 'Giulio',
  };
  props: Props;

  render() {
    const name: string = this.props.name
    return <div>{name}</div>
  }
}

const hmm = <B />
console.log(hmm)
```

**Comment by joehua87** [comment] 2017-02-09 02:46
I've just tried this & it just works (adding = {}):
```js
export default ({ children, title = 'This is the default title' }: {
  children?: Element<any>,
  title?: string
} = {}) => (
  <div>Hello World</div>
)
```

**Comment by dtaub** [comment] 2017-02-25 02:07
I understand why from a type safety standpoint an optional prop that needs to be defined in defaultProps is technically not optional. But does that mean there is no way to use Flow to declare that the component consumer is not required to pass a certain prop, but that the prop will never be undefined?

**Comment by dpehrson** [comment] 2017-03-12 05:28
I've also hit this, all my remaining flow warnings in my project are related to properties that are required, but have a default value.

**Comment by nmn** [comment] 2017-03-13 23:13
I just did a quick hack to try to enforce DefaultProps to be compatible with Props.

In the React types:
```typescript
// replace this:
declare class React$Component<DefaultProps, Props, State> { ... }

// with:
declare class React$Component<DefaultProps: $Shape<Props>, Props, State> { ... }
```

That seems to enforce Props and defaultProps to always be compatible.

---
Re-opening till I can test that fix more comprehensively.

**Comment by sebastienbarre** [comment] 2017-04-13 03:03
@nmn where can this change be made manually, if I may ask?

**Comment by nmn** [comment] 2017-04-18 19:05
@sebastienbarre You can't exactly do this without using the `--no-lib` flag and overriding the core type definitions for Flow.

**Comment by szagi3891** [comment] 2017-04-26 08:11
@nmn 
It would be nice if the core type definitions was updated.

**Comment by rosskevin** [comment] 2017-04-27 16:54
@nmn - any chance to get this in?  If I change my Props that are specified in DefaultProps to required, the rest of my lib then complains that the consumer hasn't specified the props - same as @dpehrson.

**Comment by rosskevin** [comment] 2017-04-27 16:57
Actually, I just found something that works (but I'm not entirely clear why). Using `type Props = DefaultProps & {...}` as seen in this [example](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuYASgKYCGAxgQDRgDeAojKZqQHa1gAKArnqQDCcHHHYcCAXzBQ8IsAHIBVAgoDcqVAQCe2UmAAipKOV4wC3OdgDOYALwNUYMJRG5xnAFxhrBPOnYAczAAHzAAMV52anQxGlRJTR09HitbByMTMws0sAAyRzBQECdkMAAVAAt9V1EPIl5rUgATGXwwAmqwOTgidjhm0gA6UvBGdE7SPDByHz8A4II4MEb9WYMAeQBZMFIWNk4wdtna9wkR5xRS07EJAH5vX38g0IiomLiEzUoYcmtbAAy5G0cF4RFIAA8CBxmrY+AJhHUJAAeTKmcyWOA2OiY7FgABucHQzQAfIU5uQCOhKGBBlkMWlvGjsrj0uTnDd6t4FM10PiFPFnJINKVsIzUljrCLnAJ2INpgAKACU3mYrBR5HY2jJ9FKHLEvnZzhcbluXjAiLOnFxguN0gcnXQ1iGYsl0uNAgI-HYYAVeuNyMtZpyWKKJP9So0QoSQA).

**Comment by rosskevin** [comment] 2017-05-05 15:49
This has become really problematic converting a codebase to flow that has a great deal of stateless functions.  So far, I need to hand-code the defaulting process so it passes flow, which doesn't seem feasible on a large scale.

Is there a recommended way to use defaultProps/optional Props with stateless functions that works?

**Comment by faceyspacey** [comment] 2017-05-08 08:25
An additional problem is if you're using https://github.com/brigand/babel-plugin-flow-react-proptypes to convert flow types to react propTypes, in which case a prop which isn't required will be required by flow *and also* required by the generated propTypes.

**Comment by rosskevin** [comment] 2017-05-18 16:50
I have just found a case the workaround as a class doesn't work at all.  Perhaps it's a different bug like #3952, but it means I'm dead in the water converting to flow.

Summary test cases (in "try flow"):
1. [`PureComponent` with intersection](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuYASgKYCGAxgQDRgDeAojKZqQHa1gAKArnqQDCcHHHYcCAXzBQ8IsAHIBVAgoDcqVAQCe2UmAAipKOV4wC3OdgDOYALwNUYMJRG5xnAFxhrBPOnYAczAAHzAAMV52anQxGlRJTR09HitbByMTMws0sAAyRzBQECdkMAAVAAt9V1EPIl5rUgATGXwwAmqwOTgidjhm0gA6UvBGdE7SPDByHz8A4II4MEb9WYMAeQBZMFIWNk4wdtna9wkR5xRS07EJAH5vX38g0IiomLiEzUoYcmtbAAy5G0cF4RFIAA8CBxmrY+AJhHUJAAeTKmcyWOA2OiY7FgABucHQzQAfIU5uQCOhKGBBlkMWlvGjsrj0uTnDd6t4FM10PiFPFnJINKVsIzUljrCLnAJ2INpgAKACU3mYrBR5HY2jJ9FKHLEvnZzhcbluXjAiLOnFxguN0gcnXQ1iGYsl0uNAgI-HYYAVeuNyMtZpyWKKJP9So0Qq+qB+f1sAEFsNhdlCYXD+EJTfVkYTiXQ880C0TSeTZfLfSqwGqDgRkZrtUbPd7ff7nMigSCwcBw8awJHStIwAkgA) - works (for this specific case, but not all cases, see next)
1. [`PureComponent` with intersection of prop with union of `Element<*>`](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuYASgKYCGAxgQDRgDeAojKZqQHa1gAKArnqQDCcHHHYcCAXzBQ8IsAHIBVAgoDcqVAQCe2UmAAipKOV4wC3OdgDOYALwNUYMJRG5xnAFxhrBPOnYAczAAHzAAMV52anQxULBmVgkAHhAAPhpUSU0dPR4rWwcjEzMLArAAMkcwUBAnZDAAFQALfVdRDyJea1IAExl8MAJWsDk4InY4XtIAOnrwRnRh0jwwch8-AOCCODBu-XWDAHkAWTBSFjZOMEH19vcJOecUevuxCQB+b19-IPjI6IEWLseKJK4EVIZLKaSgwcjWWwAGXI2jgvCIpAAHgQOL1bHwBMIOiliqZzJY4DY6BSqWAAG5wdC9NLVDbkIGUMDTErkgreUmlGmFVnON6dbwKXroOkKTLOSQaerYPn5SnWRXOATsaarAAUAEpvGCUuR2NoWfR6qKxL4Rc4XG53l4wESHpwaXL7dIHMN0NYZsq1Rr7QICPwQbqrfbkq6nWVKTU0lH9Rp5dDULD4bYAILYbDnbG4-H8ISOzrJBlMuiV3rVxnM1lanVgA1Gy4ms0WqOh8MtqPOZLI1Ho4BJ+1gFP1aRgLJAA) **fails**
2. [`PureComponent` without intersection](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuYASgKYCGAxgQDRgDeAojKZqQHa1gAKArnqQDCcHHHYcCAXzBQ8IsAHIBVAgoDcqVAQCe2UmAAipKOV4wC3OdgDOYALwNUYMJRG5xnAFxhrBPOnYAczAAHzAAMV52anQxGlRJTR09HitbB3onUBAnZDAAFQALfVdRDyJea1IAExl8MAJisDk4InY4atIAOlzwRnRG0jwwch8-AOCCODBK-VGDAHkAWTBSFjZOMHrR0vcJHucUXN2xCQB+b19-INCIqJi4hM1KGHJrWwAZcm04XiJSAAeBA41VsfAEwjKEgAPEYTGYLGk6JY4DY6AA3ODoaoAPkczl85AI6EoYE68PMKJs3jhpkpaXs+OcLjcpy8imq6HRCnizkkGly2DS3ip1gFzgE7E6wwAFABKbzMVgw8jsbR4zLMlnsXxMrUncreSF7ThU3nM6QORroaxdIWosWaLUCAj8dhgGW5LXQ41sxGosDAHFesByjR8hJAA) - **fails**
3. [stateless function](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuYASgKYCGAxgQDRgDeAojKZqQHa1gAKArnqQDCcHHHYcCAXzBQ8IsAHIBVAgoDcqVAQCe2UmAAipKOV4wC3OdgDOYALwNUYMJRG5xnAFxhrBPOnYAczAAHzAAMV52anQxGlRJTR09HitbByMTMws0sAAyRzBQECdkMAAVAAt9V1EPIl5rUgATGXwwAmqwOTgidjhm0gA6UvBGdE7SPDByHz8A4II4MEb9WYMAeQBZMFIWNk4wdtna9wkR5xRS07EJAH5vX38g0IiomLiEzSh3glj2MAAGXI2jgvAIAApsGlvJY4DY6K5OKQAB4EACUhWcLjEvix2JxdQk3mERM4cOw8QJ0gc0Ph1g0pWcAgI-ABEKZ2IAPKSzuSrEUAHyc9EaRKoYGg8FDQZZcwU9JYm71bwKZroABuCnikkZlBg5GstgAgthsLs0RxmrY+AJebdOFyNXB0M06M7Xe6Xc1BViBOxBtMIejvMxWBIueR2NpffROSy2WAOQTnFzJWCCMBhQTRaVpGAEkA) - **fails**

**Comment by kumar303** [comment] 2017-05-18 16:55
> ...but it means I'm dead in the water converting to flow.

You could use an [error suppression comment](https://flow.org/en/docs/config/options/#toc-suppress-comment-regex) until it's fixed.

**Comment by asolove** [comment] 2017-08-22 02:05
This has been fixed in Flow v0.53. [See an updated example here](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcARFDvmQNwBQdMAnmFnAArFjoC8cA3nTjC4AO2Qg2I6cIBccVDCjBRAcwA0QkQAtkogCYAbLAGFdaqfIAUAN2SGArlnmiHIAEZYoASjg8AfHA2EMD6dAC+9HS4hmjoAMqGoV5wWAAeMFgG6Nh4MAB0JiSQolkwADycENzqiIGC0orIMMC4cPpYBMgOhjBV3H4CWjJwMBAQvcBgAGr2TujyANoAupojwuZGpuaqlnBWvgEC4cNwkQwAkKgkWDDaKqoHQyN3wKj5YFzvm8ZmertWABM3no0hOJzo5USySgYgkWB4ZGukleajIAHp-EA).

The syntax for attaching the prop types to the `Component` has changed, and many bugs about the way props and defaultProps interact have been fixed. The result is that you can make `handleChange` required in the prop types, but Flow is smart enough to see that a default value is provided in the `defaultProps` and know that code creating instances of the component do not have to pass in that key. (In a sense, the prop types are the "internal" types, what a component instance will actually see after default props have been filled in. The "outside" type, specifying which props are required to be passed in, is just the props type minus any keys that have defaults specified.)

I hope that's all clear! If not let me know and I'm happy to try to improve my explanation.

In the mean time, I think with Flow v0.53, this issue can be closed. (/cc @calebmer)

**Closed** 2017-08-27 20:13 UTC
Labels: react

**Comment by johnryan** [comment] 2017-09-05 18:26
@asolove just to clarify with [this example](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcARFDvmQNwBQdMAnmFnAArFjoC8cA3nTjC4qYAC8sAfgBccAHYBXEACMsUADR0AvvToFF8-MAjy4AZQA2wACbq4ACjBdUczhG4BKAXQCQlGEUoMwAeG2AANwA+fmcPVAA6MUlEACZtEIB6cOidOitbdQS7AmRFSxh3bjg+QRFktjkATh09EIK7KEyohmZWOAB5GAALdSreHxFRCSw5JVV1LV0GAyMYEzMh0agO+ycXOS2xl29BfyxA4LgwyJi47iSZtIzs27yjnetO4qxS8sqXDVJsIGnBmq0GCEPrsulEgA)

Are you saying that the *right* way with flow `0.53+` is to not use the `myProp?: number` optional syntax? It seems like that was a pretty convenient way of visually understanding what props are required and which aren't (even if flow will do the work of combining Props and defaultProps)

**Comment by rosskevin** [comment] 2017-09-05 18:42
I agree with you @johnryan - our `material-ui/v1-beta` library exports our `Props` for reuse in composing higher level components, and our intent is that our `Props`, just like the react component itself, indicate required and optional.  [Example of how we use it.](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcARFDvmQNwBQdMAnmFnACJYHICuANjAAKxMOgC8cAN504cVMABeWAFxwAdjxAAjLFDoBfOlgAekWHGas4wiKLgTps+UoD8qjdt0AaA-ToEeNXxgCDU4AGU+YAATXTgACjARVFVObn4hZLgAMmtkgEopGThKGB4oMIAeaOAANwA+SSTbVAA6ZzYEACZ9SoB6GoaDOkiY3VbY9IEbOwdiuUU2VQBOXwZK0dioPvq6IA)  Unfortunately this is more verbose than I think it should be.

It seems like an impedance mismatch the way the new 0.53.1+ props are a mix of default and props.  I'd love to know a better way, but our `export Props` must exactly mirror the intent of the react components' usage.

**Comment by asolove** [comment] 2017-09-06 01:35
The example you provided me looks like the output I would expect. A good way to think about this is that the `Props` in the function argument represents the "internal" type of the props, what the component has access to after defaults have been passed in.

If you want a way to refer to "the type of the props you have to pass in" the the component, you can do something like:

```js
type RequiredProps = $Diff<OtherProps, typeof OtherSlider.defaultProps>;
```

Which, in this case, is equal to `{ size?: number }`. Does that match the need you have?

**Comment by johnryan** [comment] 2017-09-06 04:52
Got it, yea the "internal" type makes sense. I've personally always used the props at the top of the file as sort of a "header file" for how to use that component when i look at the source, but I see now how it works.

**Comment by rosskevin** [comment] 2017-09-06 14:22
Thanks for explaining that @asolove.  I [tried it](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcARFDvmQNwBQdMAnmFnAJIB2MWUnyAGwAKxMOgC8cAN504cVMABeWAFxxOAVxAAjXgBo6AX3p0sAD0iw4zVnBEQxcSQBIAIsAIEAPFx59B9mJ61ixYEARwAMoCwAAmvAB08QTIGgIwgagAfAwEGpz4wBCcUTHxUHAAFGCiqGq+vPzCtQCU0rJwlDAafHBescAAbllSNQ6oCQrKiABMhl4A9APDRnTRcYnJqemZTu1y8kpsagCcRiZe6+ULOUA) and like @johnryan, I don't think it is as self documenting as it needs to be.  I'd also wonder if react-docgen is going to pick up the proper `maybe` types here or not.

In any case, thank you.

**Comment by asolove** [comment] 2017-09-06 17:41
Yeah, definitely. I have a note to add this to the docs.

**Comment by lunij** [comment] 2017-11-07 08:24
I need to say that the new way Flow handles default props worries me. 😟

> FLOW IS A STATIC TYPE CHECKER FOR JAVASCRIPT

The is what the front page of [Flow.org](https://flow.org) is saying. How "static" is a type when we're able to _dynamically_ change the "internal" type of a React component by just assigning another type to the default props than we did with the "external" type?

Something like ...

```
type RequiredProps = $Diff<OtherProps, typeof OtherSlider.defaultProps>
```

... is far away from the word "static". It means I'm able to change the value of a default prop of type _string_ to a value of type _boolean_ and it would completely change the "internal" type because of the dynamic inference. This would also lead Flow to complain about _used_ props and their types in the wrong place although it should already complain in place of the default props assignment.

The prop types I'm defining for a React component whether it is from the "outside" or the "inside" should all be the same.

**Comment by MaxInMoon** [comment] 2018-04-01 12:28
Gentlemen, did someone found a better solution to type decently defaultProps **without** this verbosity and or flow/eslint warnings?
Thanks

**Comment by gausie** [comment] 2018-05-04 10:52
"Gentlemen"?

**Comment by pascalduez** [comment] 2018-05-04 14:31
@MaxInMoon Starting from Flow 0.53 just declare your defaultProps the same way as the required ones, without setting them as optional and Flow will do the rest :)


```js
type Props = {
  foo: string,
  bar: string,
};

class Baz extends React.Component<Props, void> {
  static defaultProps = {
    bar: 'whatever',
  };
}
```
All fine.

**Comment by dtaub** [comment] 2018-05-04 15:02
@pascalduez That works but what if we want to document that the prop is not required, without the consumer having to look at the component file?

**Comment by TrySound** [comment] 2018-05-04 15:12
@dtaub Write documentation for example or just place types and defaultProps near each other.

**Comment by darylszehk01** [comment] 2018-06-25 02:10
Assume i has a component B

```javascript
type Props = {
  name: string // <= not optional because flow type knows it has default one so not going to be optional anymore. 
};

class B extends React.Component {

  static defaultProps = {
    name: 'Giulio'
  };

  props: Props;

  render() {
    const name: string = this.props.name
    return <div>{name}</div>
  }

}
```

But in real usage, a container (A) will use this component (B), and take it's flow type Props as reference, I will add name attribute to it because I declared non-optional. And this doesnt make sense.

**Comment by apsavin** [comment] 2018-06-25 08:04
@darylszehk01 please reproduce on http://flow.org/try/

**Comment by dominicfraser** [comment] 2018-10-31 03:34
I would like to confirm my understanding of this thread, and what was mentioned in https://github.com/facebook/flow/issues/6993:

> You can think of the Props type as specifying the interface for
> this.props as used **inside** the component, not the exact props that
> need to be provided to **construct** the component.

And the docs:

> You don’t need to make foo (prop name) nullable (optional `foo?: string` syntax) in your Props type. Flow will make sure that foo is optional if you have a default prop for foo.

So for a functional component rather than:
```
type Props = {
  foo?: string,
}

const Component = ({ foo }: Props) => (
  // component using foo
  // etc
)

Component.defaultProps = {
  foo: "string one",
}
```

Would be properly written as:

```
type Props = {
  foo: string,
}
```
as Flow would make sure that the defaultProps were used when needed?

Which would get around more complex use cases where specifying `Props` as optional can result in errors such as 'JSX: "Property is missing in undefined" just after checking the object is defined' https://github.com/facebook/flow/issues/6350.

**Comment by sergiop** [comment] 2019-07-24 08:23
> @MaxInMoon Starting from Flow 0.53 just declare your defaultProps the same way as the required ones, without setting them as optional and Flow will do the rest :)
> 
> ```js
> type Props = {
>   foo: string,
>   bar: string,
> };
> 
> class Baz extends React.Component<Props, void> {
>   static defaultProps = {
>     bar: 'whatever',
>   };
> }
> ```
> 
> All fine.

@pascalduez all fine? You are completely losing control on required props. In your example `bar` is not required, since you defined its default value in `defaultProps` object, but in your type statement you have to set it as required even if it is not. This is really a mess.

**Comment by schumannd** [comment] 2020-04-10 08:45
Apart from the proposed solution makeing flowtypes inaccurate, the solution does not work with eslint, as this rule is violated:

https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/default-props-match-prop-types.md

**Comment by alfonso-cornejo-globant** [comment] 2020-05-22 21:47
Oh man how disappointing this is. Will be using // $FlowFixMe until this changes.

**Comment by AndreaCitrolo** [comment] 2020-07-23 11:31
How could this issue have been closed like this? The proposed solution doesn't work, the linter complains and for a good reason, optional parameters should declared optional and defaultProps should be handled by flow under the hood, I see maybe this is not a huge priority but still I would like it to be fixed sooner or later.
