### ISSUE TITLE
$PropertyType of property that is a string literal still compatible with any string

### ISSUE THREAD

**Issue by macrozone** [facebook/flow#4403] opened 2017-07-17 20:23 UTC
sorry, new flow user, maybe i do it wrong. I want to extract a union type (or enum?) from a union of more complex types. See this example:

https://flow.org/try/#0PTAEAEDMBsHsHcBQBTAHgB1gJwC6hwJ7rKgBissoAvKAN6HEBcoA5KQPLssC+KG2eBiQBCAQyzU6Q5i2EBBAEo9EfTLnxESAVQB2AS1g7J5SgB9QYrIiGgAClljoAKpskASe4+S4CL4gB5dAx0AGlAAIiFwgD4VRABjQwBnPAAjZk9nVxoAZlBQEFBvBwlRJKKMZHicZAATBOS8UQyHLOJJcLLayHCCsB1KYuww1IBXPCSAC1hR6Fr8SYd4UENkAH5EIA

line 9 shows an error as expected ("This type is incompatible with   ^ string literal `BAR`" and "This type is incompatible with   ^ string literal `FOO`")

but i would expect line 10 to show an error as well as "asdf" should not be compatible with any of the string literals.

Here an example without union type which shows the same problem:

https://flow.org/try/#0PTAEAEDMBsHsHcBQBTAHgB1gJwC6hwJ7rKgBissoAvKAN6HEBcoA5KQPLssC+iiDJcrAAqREjQAkABSyxiuAqOIAeIQBpQAIgGaAfHwDGsAHYBnPACNmQpeNABmUKBChkWWVlABDU64zIDHGQAE0QjMzwvawpbai0fYMhNZzBjSjcPDQsAVzxTAAtYbOhg-HzZeFATZAB+RCA

**Comment by vkurchatkin** [comment] 2017-07-18 09:51
Duplicate of https://github.com/facebook/flow/issues/3374

**Closed by vkurchatkin** 2017-07-18 09:51 UTC
