### ISSUE TITLE
Generic constraint on arrow function not recognized

### ISSUE THREAD

**Issue by jeremywiebe** [facebook/flow#6672] opened 2018-08-01 04:38 UTC
I _think_ this is supported other places but I cannot use a type constraint on arrow functions that are marked as `async`. This breaks in the Flow playground.

[Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzAA8wBeMAQ1wE9sMwAeAFQC4wB5AIwCsBTDfAD4AFETYEATgEtsAcwCUZQWADeqMAEgJvfAFcJ2MAAUJcALZTcvAHTbccGADdewlQF9FqN0A)

```
/* @flow */

const x = async <T: Object>(x: string) => {
 	return Promise.resolve({}) 
}
```

**Comment by bradennapier** [comment] 2018-08-03 02:37
Yeah I have run into this a few times.  It happens everywhere as well - only way to use generics in async function is to use a standard async function

[Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzHwFMCwBeMAb1TAA8AuMAQ1wE9sMwAeAFSYDyAIwBWxDPgB8ACkZgCAJwCW2AOYBKCpOq0AkAuL4ArguxgACgrgBbJbmIA6A7jgwAbsWlUAvptTf-IA)

**Comment by lll000111** [comment] 2018-08-03 10:44
Using the example, when I experiment just slightly I get yet another strange result.

[Flow Try Link](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzAA8wBeMAQ1wE9sMwoBXO-ASxzAB4AVALjADeUOHH4EATq2wBzAL4A+MAAoiY-JJkBKfgAVxcALatcAUx6KBqMGHEn8jcdkFXrDEfyIvZAblSzUQA)

Code:

```js
const x = async function <T: {foo: string}> (x: string): Promise<T> {
    return {
        foo: x
    };
}
```

Error:

```
4:   return {            ^ Cannot return object literal because object literal [1] is incompatible with `T` [2] in type argument `R` [3].
References:
4:   return {            ^ [1]
3: const x = async function <T: {foo: string}> (x: string): Promise<T> {
                                                                    ^ [2]
[LIB] ..//static/v0.78.0/flowlib/core.js:583: declare class Promise<+R> {
                                                                     ^ [3]
```

**Comment by Reisen** [comment] 2018-11-21 10:44
Related to this is it seems to break `$ElementType` accessors in async arrow functions as well, for example starting from the following code, I have a syntax error for attempting to use `: string` same as in the issue title.

### Broken (A)
```javascript
type Foo = {||}
const example =
  async <K: string>(key: K, value: $ElementType<Foo, K>): Promise<void> => {
  }
```

However even removing it, the following will now break:

### Broken (B)
```javascript
type Foo = {||}
const example =
  async <K>(key: K, value: $ElementType<Foo, K>): Promise<void> => {
  }
```

```
Cannot access computed property using K [1].
     1│
     2│
     3│ const example =
 [1] 4│   async <K>(key: K, data: $ElementType<Foo, K>): Promise<void> => {
     5│   }
     6│
     7│
```

### Working

Works absolutely fine as a standard async function:

```javascript
async function example<K: string>(key: K, value: $ElementType<Foo, K>): Promise<void> {
}
```

**Comment by goodmind** [comment] 2019-05-31 04:21
Duplicate of #5335

**Closed by goodmind** 2019-05-31 04:21 UTC
