### ISSUE TITLE
[feat] Regular Expression Analysis

### ISSUE THREAD

**Issue by langpavel** [facebook/flow#5942] opened 2018-03-12 03:12 UTC
It's not possible to confirm that arbitrary string is matching to regular expression in predictable time.
However it's possible to limit this question with constraints.
And it's possible to decide if regular expression can be finished inside *limited decision frame*.
*It should be possible* to mark *chosen* regular expression as predicates.

**Comment by TrySound** [comment] 2018-03-12 05:21
Duplicate of https://github.com/facebook/flow/issues/4654

/cc @vkurchatkin

**Comment by langpavel** [comment] 2018-03-12 13:09
Hi, this is not really a duplicate bud instead badly written from my side, sorry :smiling_imp:
The point is that some regular expressions show that they can be used as attack vector — [ReDoS](https://en.wikipedia.org/wiki/ReDoS)
I believe that some analysis can be done and flow can issue a warning when linting is configured

**Closed** 2023-08-08 02:28 UTC
Labels: feature request
