### ISSUE TITLE
HOCs cause parameterized React components to monomorphize

### ISSUE THREAD

**Issue by zgotsch** [facebook/flow#6903] opened 2018-09-18 03:08 UTC
I wish I could come up with a better title for this.

When I wrap a parameterized React component in a higher-order component, it tries to unify the type parameters between invocations. Minimal example and tryflow link attached.

I don't know if this an actual problem with the React types or something bigger, but the times it has come up for me have been in a React context.

```javascript
import * as React from "react";

function HOC<P: {}, C: React.ComponentType<P>>(Wrapped: C): React.ComponentType<P> {
  return Wrapped;
}

type ObjWrapper<T> = {|
  inner: T
|};
type Props<T> = {|
  +value: ObjWrapper<T>,
|}
const Simple = <T>(props: Props<T>) => null;
        
const HC = HOC(Simple);

// Removing the type annotations here makes the error go away, but for the wrong reason
const four: ObjWrapper<number> = {inner: 4};
const hello: ObjWrapper<string> = {inner: "hello"};

// This breaks
<div>
  <HC value={four} />
  <HC value={hello} />
</div>;
        
// But this works!
<div>
  <Simple value={four} />
  <Simple value={hello} />
</div>;
```

tryflow: https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcARFDvmQNwBQdBArgHb7AQtwASA8gMIAeAAoAuOAG8AvgBo4-cdjwwAdPxKQWWFjAAqATzBYRAPhMAKAOpRkYIwBNx-AJSKqq9eE7a9h48JNJOjg4ShgmKC5rWwd6KQYYPzheACMAK2i7LChBXUCAXkkAH2C4YBYtKHFdOiKpekSjOGFiMFRcguLSgGoAN2QAGyYscVSMmyycvJla+NxOVHgAZVAwAaw4Qo7zMFbUcRaINo7nTcCWJgGB+hDb27p5lkWefk2eAXMV8HXnejoAen+mCwIAgvXKAHM4DAABYbRobZAVCAwZAwDhPOBwyhwEDIADWWHQsI22WIUDgEIgKAA7sh9HIUkxCNBoXC4DTiCwoZQ0JwHgsWRFRulMkYchcQClsp0JOVKuIACz1AVPeBwq4QEXjGLZQSLKCQ2Xy7LiMgagYQMgqgFA3Qw4DoFK8-GoOiCezAXomUqCbivfpDLD5CQECARKRwf4+kJ+gODYYhi0QSPR93-T3em53e6AuAAIWZbMdHOgroAhO7MzG4IIvmsNoHE6Hw1BUzW66t1nAm8GJMn2+nqzQgA

**Comment by SamChou19815** [comment] 2023-07-14 02:06
Duplicate of https://github.com/facebook/flow/issues/5022

**Closed by SamChou19815** 2023-07-14 02:06 UTC
Labels: react
