### ISSUE TITLE
Object type with non optional property does not fit object with optional property?

### ISSUE THREAD

**Issue by esbenvb** [facebook/flow#6907] opened 2018-09-19 22:55 UTC
I believe this should work, since `NewVehicle` is less strict than `Vehicle` but has the same properties

However I get the error below, when writing the code. Is this a bug in flow?

```
19: show(carA)
         ^ Cannot call `show` with `carA` bound to `car` because in property `vehicleId`: Either undefined [1] is incompatible with number [2]. Or undefined [1] is incompatible with number [1].
References:
3:   vehicleId?: number,
                 ^ [1]
9:   vehicleId: number,
                ^ [2]`
```

```js
export type NewVehicle = {|
  vehicleId?: number,
  brand: string,
  model: string,
|}

export type Vehicle = {|
  vehicleId: number,
  ...$Exact<NewVehicle>,
|}

const carA: Vehicle = {brand: "Audi", model: "A5", vehicleId: 1234}
const show = (car: NewVehicle) => console.log(car)

show(carA)

```

https://flow.org/try/#0FAUwHgDg9gTgLgAjgTwiBA5EB3AaiACwEsBjAG3QF4EBvAH2AQQDdDSKBJAEwH4AuBADsArgFsARiBgAaRgnEwAhoK4CAznBhFBAc1lNRULiDLrN2vcDoBfYKEixEKNAnzFyVWgyat3nVUJikjJyAHThACQAomCKJHAAPFh4bB4AfLI2diRQghoIJIowAIICbuyeNArKAQBExcJcRLXSCIbGpgj1AKwtLKn+AgCMAEwAzAAstsAA9DOFMNm5+WoEUNgI1AAUCwLJ5R4AlJtpBctQFKFkUDo7RYd2q+t3JQ9AA

**Comment by wchargin** [comment] 2018-09-20 04:55
Duplicate of #6894, I believe, though this issue’s title is certainly clearer. :-)

Summary of answer:
  - It would be unsound to treat a `Vehicle` as a `NewVehicle`, because it would then be legal to delete the `vehicleId` property on the `NewVehicle` reference.
  - Making `vehicleId` read-only on `NewVehicle` fixes the error.
  - Making a shallow copy with `show({...carA})` also fixes the error.

**Comment by wchargin** [comment] 2018-09-21 08:28
You're welcome.

**Closed** 2018-09-21 08:28 UTC
