### ISSUE TITLE
Objects as maps does not throw error when it IMO should

### ISSUE THREAD

**Issue by CptFabulouso** [facebook/flow#6939] opened 2018-09-26 14:07 UTC
I have defined following types types
```
type Meta = {| id: string, val: string |};

type State = {|
	[key: string]: Meta,
|};
```
I would expect that any of the following examples will throw error, that any key in `State` will be forced to be `Meta`, but that does not look to be the case

Ex1: Does not give error
```
const test1 = (state: State, meta: Meta): State => ({
	[meta.id]: { ...meta, bu: 'fu' },
});
```
Ex2: Does not give error
```
const test2 = (state: State, meta: Meta): State => ({
	...state,
	[meta.id]: { ...meta, bu: 'fu' },
});
```

Ex3: Horaaay error, that `bu` is missing in `Meta`. Also that `other` is missing in state, I would argue it is still just a key, but I guess that has reasons.
```
const test3 = (state: State, meta: Meta): State => ({
	other: { ...meta, bu: 'fu' },
});

/* 
Cannot return object literal because:
 • property other is missing in State [1] but exists in object literal [2].
 • property bu is missing in Meta [3] but exists in object literal [4] in
   property other.

    [3] 24│ 	[key: string]: Meta,
          :
        36│ });
        37│
 [1][2] 39│ const test3 = (state: State, meta: Meta): State => ({
    [4] 40│ 	other: { ...meta, bu: 'fu' },
        41│ });
        42│
        44│ const test4 = (state: State, meta: Meta): State => ({
*/
```

Ex4: Same as before, only `...state` is spread and error disappears
```
const test4 = (state: State, meta: Meta): State => ({
	...state,
	other: { ...meta, bu: 'fu' },
});
```

Is this expected behavior? Am I doing something wrong?

**Comment by swac** [comment] 2018-09-28 05:27
I think this is the same bug as https://github.com/facebook/flow/issues/6871.

**Comment by goodmind** [comment] 2019-05-31 06:21
Duplicate of #6871

**Closed by goodmind** 2019-05-31 06:21 UTC
