### ISSUE TITLE
Weird post-hoc inferrence in function types generated from $Call?

### ISSUE THREAD

**Issue by tolmasky** [facebook/flow#8838] opened 2022-02-08 14:39 UTC
Flow version: 0.171.0

## Expected behavior
I'd expect both of these snippets of code to generate the same error, but only the normal generic errors, the `$Call` generated one does not:

```typescript
type ToFunction<Parameter> = (x: Parameter) => string;
declare var expectString : ToFunction<string>;

expectString(10); // Correctly gives me an error
 
type _ToFunctionFromCall = <Parameter> (Parameter) => (x: Parameter) => string;
type ToFunctionFromCall<Parameter> = $Call<_ToFunctionFromCall, string>;

declare var expectStringFromCall : ToFunctionFromCall<string>;

// Does not give me an error, instead changes type of `expectStringFromCall`
// to (string | number) => string;
expectStringFromCall(10); 
```

I need the call version because I am passing it to `$ObjMap`. Currently, the $ObjMap *appears* like it's working, as hovering over the resultant types shows me what I expect to see (`{ a: number => string, b: boolean => string, etc. }`). Yet the second I try to use any of them, it just changes their parameter types to accept anything I pass to them.

[Try in Flow](https://flow.org/try/#0C4TwDgpgBAKg9gMQK4DsDGwCWcUB4AKAhgE6EC2EwExAfFALxQAUAHgFxRGkVXECUDOgGdgxTCgDmAbgBQAEwhoANiWgA3ElAgtIGAMqjxEqB3jJ0WHLhFjJNWTO27gB2xKYBGAAx8pUAPT+UADCcMTEisBKIFASmGoQQlAUUIQoWuFhMlAyoJBQAPpmqBjYKAjEcGTBhEpKDFAEJOSU1HRMXC28AvTt7JzNPNQ9woaSsnnQxRZlFVU1dU3crbQNACQLSrhFiCWW5ZXVtUoANFA2RvYy8ooqEVAaxFo6ka5Gc0d1JrC7Mzgfm2sYwkVxkgSgABE4IkoCg4MBYvFoCk0hlKsQzuIRBBCHIoGgABZpCQwyZQOAAMygAAMnK9gQDjtSwUFgHBmBdJFAAD6wpBkABGw0E52Bsjp+gZh02nh8fiAA)

**Comment by mvitousek** [comment] 2022-02-08 20:41
This is a known issue with implicit instantiation of type parameters and is a huge motivator for our ongoing Local Type Inference project (https://medium.com/flow-type/introducing-local-type-inference-for-flow-6af65b7830aa). 

The problem is that when you call `_ToFunctionFromCall` on a string, Flow models this by introducing an "open" type variable as the instantiation of `Parameter`, and adding `string` as a lower bound to that variable. When you call it on `10`, rather than seeing an error because numbers are incompatible with strings, we simply add `number` as an additional lower bound on that type variable, causing it to be a union of those two types. This is unfortunate, and we're making substantial changes to how Flow performs inference to change this behavior.

**Comment by tolmasky** [comment] 2022-03-03 02:16
Is there any sort of action I can take today to prevent this? Something that would force it to become a "closed" type variable?

**Comment by tolmasky** [comment] 2022-03-03 02:20
It would appear that by adding some indirection, I can get it to behave properly:

```javascript
type _ToFunctionFromCall = <Parameter> (Parameter) => (x: [Parameter][0]) => string;
type ToFunctionFromCall<Parameter> = $Call<_ToFunctionFromCall, string>;

declare var expectStringFromCall : ToFunctionFromCall<string>;

// Now this gives me an error
expectStringFromCall(10);
```

As you can see here, I wrap it in an array, then immediately access it (`[Parameter][0]`). Could you possibly confirm given your inside knowledge that this is a sound way to do it?

**Comment by gkz** [comment] 2022-03-03 06:32
You can do this: 
https://flow.org/try/#0C4TwDgpgBAKg9gMQK4DsDGwCWcUB4AKAhgE6EC2EwExAfFALxQAUAHgFxRGkVXECUDOgGdgxTCgDmAbgBQAEwhoANiWgA3ElAgtIGAMqjxEqB3jJ0WHLhFjJNWTO27gB2xKYBGAAx8pUAPT+UADCcMTEisBKIFASmGoQQlAUUIQoWuFhMjKgkFAAorgwdIwwfoFQQhDQABbUEDJQOeDQAPpmqBjYKAjEcGTBhEpKDFAEJOSU1HRMXJO8AvQz7AXj3FO0i8KGkrK50B0W3b39g8Nr89OjACRnSrjtiJ2WPX0DQ0oANJU7EvbZCmUqigGmIWh0kVcRhO72GJlgTyOOBhd2sv3+MgqABE4IkoCg4MBYvFoCk0hk+sRvuIRBBCHIoGgamkJHj9lA4AAzKAAAyckN+KI+PMxQWAcGYNiMUAAPvikGQAEbULY-Nyyfn6QVvO6eHx+IA

**Comment by SamChou19815** [comment] 2023-02-01 17:49
This issue is fixed with `inference_mode=lti`

**Closed by SamChou19815** 2023-02-01 17:49 UTC
Labels: incompleteness
