### ISSUE TITLE
$ReadOnly does not guard against delete keyword

### ISSUE THREAD

**Issue by albertogasparin** [facebook/flow#7089] opened 2018-10-24 10:36 UTC
Looks like Flow does not detect objects being modified by the object `delete` keyword. This is especially problematic when the object is typed `$ReadOnly`, so we assume modifications on it are prevented but instead some code might still change the instance:

```js
type E = $ReadOnly<{| 
  a: string,
|}>
const e: E = { a: 'asd' }

delete e.a; // no error?
e.a = 'asd'; // error, not writable 👍 
```

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCiYAvGACQBKeAhgCYDyAdjFgDwDeAPmKmGDQBcYAM4YATgEsmAcwA0qLgF8AfOgDGcJmLB5hxMhwHCA5DRF0TYJejp4YeDATwA6GgG4wwYGCZxd4uJw4gD86K40pGBmFiae3gFB4kA

**Comment by wchargin** [comment] 2018-10-24 17:53
Yes, `delete` is totally unchecked. Duplicate of #5325.

**Comment by wchargin** [comment] 2019-02-14 17:58
This is a soundness issue. [This yields `coerce`:][1]

```js
// @flow
function coerce<T, U>(t: T): U {
  const o: { type: "A", x: T } | { type: void, x: U } = { type: "A", x: t };
  delete o.type;
  if (o.type === undefined) {
    return o.x;
  }
  throw new Error("Unreachable");
}
const twelve: number = coerce("twelve"); // no type error!
twelve.toFixed(); // runtime error!
```

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQkCuA7AxgFwJazaBrAKYBOGxAPACoA0oAqgHwAUWAXKNQJScOgBvRKEL4AzllCxOA0FgCeAB2KcARAEFV9AB6dqoAL6gAPoLlKVoAG6wcAEx19DoALxmFytZsdzDAbmFQO2JoYixiKQA6D2IAkRxIUBZYaItXFzd0YMgcNGI7bkFAkVIwlFICFO04w0CsAAtSBFA8+FAAUVIm0hZVBjRSgEMMesGAI1DVbgCDRCI0CTl4EKtLNBQAWzGyV1EyCl6sZehVqb9QEBbYc2VQMm6AQkQjleJo2AAxHG18lmmLsCkdC4DYRe6wUhPIA

**Closed** 2019-12-09 22:08 UTC
Labels: Typing: soundness, bug
