### ISSUE TITLE
Default arguments in an object destructure aren't checked for string literal unions

### ISSUE THREAD

**Issue by ayroblu** [facebook/flow#9188] opened 2024-07-13 16:41 UTC
This is a flow bug that caused an incident

Flow version: Latest

## Expected/Actual behavior

```ts
type MyEnum = 'Top' | 'Latest';

function test({
  // this should error but doesn't
  example = 'wrong',
}: {|
  example?: MyEnum,
|}) {}
```

### Link to Try-Flow or Github repo:

[try flow](https://flow.org/try/#1N4Igxg9gdgZglgcxALlAIwIZoKYBsD6uEEAztvhgE6UYCe+JADpdhgCYowa5kA0I2KAFcAtiRQAXSkOz9sADwxgJ+NPTbYuQ3BMnTZA+Y2yU4IwRO4A6SFBIrGVDGM7c+h46fNRLuKxJIGWh8MeT0ZfhYlCStpHzNsFBAMIQkIEQwJODAQfiEyfBE4eWw2fDgofDBMsAALfAA3KjgsXGxxZC4eAw0G-GhcWn9aY3wWZldu-g1mbGqJUoBaCRHEzrcDEgBrbAk62kXhXFxJ923d-cPRHEpTgyEoMDaqZdW7vKgoOfaSKgOKpqmDA+d4gB5fMA-P6LCCMLLQbiLOoYCqgh6-GDYRYIXYLSgkRZkCR4jpddwPfJLZjpOBkO4AX34kA0SQUjAglAkAAIVsYuQBZWgAUWEIi5AF4uQByAAqsKlXIAPtKADKZdoSKUAbgAOlA9TAHso4NAeRqABTAPVcrkAeltPNqtK5JFqEG0bC5JkoHOtXsUIkYbQl0oA7j6oAgpbw9fTkFzgIq-QpnEHsAB+eOCkWiGNQRX0gCUCfper19sdzudkGocwkBqN8KgZvsACZzSnA20s8LRSGpeHoFHi8BS-rHtB7P7U8HJVbm9Ou9h4wOI1G8-TdVAKxInSQudWOSxlHqOwG0-HE8nz21MwLe7m9QXC7kQA0TCQTVAkg0AAxWVsAGYAE4rAARhAekgA)

[typescript (correct behaviour)](https://www.typescriptlang.org/play/?#code/C4TwDgpgBAsiCiA7ArgWygXigcgCoHsxsoAfHAGQENgIBnYbAbgFgAoNgM2UQGNgBLfIig16ACgDebKFAD0skQAt+tKLUX5kAGwAmUCACcD+A9P0APSqjBboWbAHdjiAObYANGwC+ALihTWGQhLa1sAfj84JDRPVi8ASn8vIA)

**Comment by SamChou19815** [comment] 2024-07-14 17:58
Duplicate of #8972

**Closed by SamChou19815** 2024-07-14 17:58 UTC
Labels: bug, needs triage
