### ISSUE TITLE
[Feature request] const's type should using it's value

### ISSUE THREAD

**Issue by zaaack** [facebook/flow#4166] opened 2017-06-14 08:02 UTC
e.g.
current:
```js
const white = '#fff'
// typeof white = string
```

expect:

```js
const white = '#fff'
// typeof white = '#fff'
```

So in nuclide autocomplete  can show  the value of consts, just like VS Code.

**Comment by awestroke** [comment] 2017-06-14 08:36
I think this is a good suggestion. A literal string type is a subtype of string anyway.

**Comment by agentcooper** [comment] 2017-06-14 08:55
Duplicate of https://github.com/facebook/flow/issues/2639.

**Closed** 2017-06-14 09:12 UTC
