### ISSUE TITLE
types are tracked across index operator on arrays, but not unshift() function on arrays

### ISSUE THREAD

**Issue by matthargett** [facebook/flow#355] opened 2015-03-30 22:28 UTC
The incorrect property name is found in the first example below (thirdBug), but not the second example (fourthBug). These are simplified from a real-world bug in the Enyo sources that flow currently does not find.
thirdbug.js:
function normalizeHoldPulseConfig() {
    return {events: [{hold: 'a'}]};
}

function thirdBug() {
    // BAD/BUG reported correctly
    console.log(normalizeHoldPulseConfig().events[0].name);
}

fourthbug.js:
function normalizeHoldPulseConfig() {
    return {events: [{hold: 'a'}]};
}

function fourthBug() {
    var next_ = normalizeHoldPulseConfig();
    // BAD/BUG
    console.log(this.next_.events.unshift().name);
}

**Comment by popham** [comment] 2015-04-11 17:09
Not bugs.

For `thirdBug`, see http://flowtype.org/docs/nullable-types.html#undefined-values.

For `fourthBug`, I think you meant to `shift`.  See the definition of Array in `lib/core.js`:

```
declare class Array<T> {
  // ...
  shift(): T;
  // ...
  unshift(...items: Array<T>): number;
  // ...
}
```

**Comment by popham** [comment] 2015-04-11 18:15
Not a bug.  Append a call to the function `fourthBuf();`, and you'll get

```
...: property next_
Property cannot be accessed on global object
```

That's because without an explicit call, Flow can't know the binding of `this`.  By actually calling the function, Flow learns the binding of `this` and recognizes that `next_` doesn't exist on the global scope.

Playing with the binding of `this`, I discovered some goofy undefined handling:

```
function normalizeHoldPulseConfig() {
  return {events: [{hold: 'a'}]};
}

function fourthBug() {
  console.log(this.next_.events.shift().hold); // OK
  console.log(this.next_.events.shift().name); // NG
  console.log(this.next_.events.unshift().hold); // NG
  console.log(this.someUndefinedKey.events.shift().hold); // NG, but OK by Flow(?)
}

var A = function () {
  this.next_ = normalizeHoldPulseConfig();
};
A.prototype.f = fourthBug;

var a = new A();
a.f();
```

**Comment by matthargett** [comment] 2015-04-16 18:05
Oops, sorry for the mistake in my demo program. Should I file a separate issue for the someUndefinedKey case you mention above?

The next issue I run into with the original drag.js file is that flow doesn't understand enyo.clone() and enyo.mixin(). Is there a tutorial on adding library signatures somewhere?

**Comment by popham** [comment] 2015-04-16 19:04
I kinda figured that the problem from your use-case had something to do with `someUndefinedKey`-like behavior.  I'm not sure if it's a bug though (see http://flowtype.org/docs/nullable-types.html#undefined-values).  I don't intend to open an issue; if you think it's a bug, then go ahead and open an issue if you want (I wouldn't discuss it here for etiquette and response likelihood reasons).

For library signatures, check out the js files under `flow/lib/`.

**Comment by samwgoldman** [comment] 2015-04-25 00:18
@matthargett is this issue resolved?

**Comment by avikchaudhuri** [comment] 2015-06-19 11:09
Looks resolved to me, hence closing. Please reopen if you disagree.

**Closed by avikchaudhuri** 2015-06-19 11:09 UTC
