### ISSUE TITLE
Module type itself contains types

### ISSUE THREAD

**Issue by glasserc** [facebook/flow#7377] opened 2019-01-18 18:23 UTC
In https://gist.github.com/glasserc/757049f995199a58550ad60f13da0b92 I have put together a simple demonstration of a problem I'm facing on a larger react-redux project. Running flow 0.91.0 on this project produces:

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/index.js:10:12

Cannot call callAction with ActionStuff bound to actionModule because
ActionType [1] is incompatible with function type [2] in property ActionType.

     src/index.js
 [2]  6│ function callAction(actionModule: {[string]: () => ActionType}) {
      7│
      8│ }
      9│
     10│ callAction(ActionStuff);
     11│

     src/action.js
 [1]  3│ export type ActionType = "hello";



Found 1 error
```

This seems strange to me. It seems like if you are passing a module to a function, then you have to consider that module a value, and if you consider a module at the value level, types should not be present.

Of course, `callAction({action: ActionStuff.action})` is OK, but I'm trying to find a way to use a module as an ad hoc registry, so don't want to name every single member of the module. Some workarounds seem to produce results that are inconsistent with the above behavior. For example, trying to remove the type from the module explicitly fails with an `ActionType is not a value` error, which would make sense if `ActionType` weren't also in the module:

```
let {ActionType, ...myActionStuff} = ActionStuff;
callAction(myActionStuff);
```

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/index.js:10:6

Cannot import the type ActionType as a value. Use import type instead.

      7│
      8│ }
      9│
     10│ let {ActionType, ...myActionStuff} = ActionStuff;
     11│
     12│ callAction(myActionStuff);
     13│
```

Trying to delete the type from the module does nothing, probably because `ActionType` is not actually a member of the module. The following gives the same error message that passing `ActionStuff` directly does:

```
delete ActionStuff.ActionType;
callAction(ActionStuff);
```

Trying to copy only value things into a sanitized module also shows `ActionType` as an element:

```
let myActionStuff = Object.keys(ActionStuff).reduce((acc, key) => {
  acc[key] = ActionStuff[key];
  return acc;
}, {});

callAction(myActionStuff);
```

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/index.js:11:14

ActionType [1] is incompatible with any [2].

     src/index.js
      8│ }
      9│
     10│ let myActionStuff = Object.keys(ActionStuff).reduce((acc, key) => {
 [2] 11│   acc[key] = ActionStuff[key];
     12│   return acc;
     13│ }, {});
     14│

     src/action.js
 [1]  3│ export type ActionType = "hello";
```

This works OK though:

```
let myActionStuff = Object.keys(ActionStuff).reduce((acc, key) => {
  if (typeof ActionStuff[key] === "function") {
    acc[key] = ActionStuff[key];
  }
  return acc;
}, {});

callAction(myActionStuff);
```

**Comment by glasserc** [comment] 2019-01-18 18:34
Trying to define the workaround as a function also doesn't work:

```
function onlyFunctions(module: {[string]: any}): {[string]: function} {
  return Object.keys(module).reduce((acc, key) => {
    if (typeof module[key] === "function") {
      acc[key] = module[key];
    }
    return acc;
  }, {});
}

callAction(onlyFunctions(ActionStuff));
```

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/index.js:19:35

Cannot call onlyFunctions with ActionStuff bound to module because
ActionType [1] is incompatible with any [2] in property ActionType.

     src/index.js
 [2] 10│ function onlyFunctions(module: {[string]: any}): {[string]: function} {
       :
     16│   }, {});
     17│ }
     18│
     19│ let myActionStuff = onlyFunctions(ActionStuff);
     20│
     21│ callAction(myActionStuff);
     22│

     src/action.js
 [1]  3│ export type ActionType = "hello";
```

**Comment by jbrown215** [comment] 2019-01-19 16:37
There's a lot here so I just want to make sure I'm understanding correctly.

## Expected Behavior

Your example runs with no errors, since the only value exported from `action.js` is a function matching that type.

## Actual Behavior

There is a type error because of exported type alias in `action.js`, which is included in the type of `Action`. (`{|+ActionType: imported ActionType, +action: () => ActionType|}`)

**Comment by glasserc** [comment] 2019-01-19 17:00
Yes, that's right. Thanks, I forgot to actually express what I was expecting.

**Comment by jbrown215** [comment] 2019-01-19 17:20
No problem :) I blame that on our issue template!

**Comment by SamChou19815** [comment] 2024-03-19 04:01
The issue should be fixed recently when we cleaned up handling of types in modules

**Closed by SamChou19815** 2024-03-19 04:01 UTC
Labels: bug
