### ISSUE TITLE
Inconsistent type checking between new Object() and {}

### ISSUE THREAD

**Issue by gcazaciuc** [facebook/flow#364] opened 2015-04-05 15:49 UTC
Given the following example code and assuming this.props.item is an optional array :
 var items = this.props.items || new Object();
 var services = items.map((s) => {
            return <Service name={s.name} price={s.price} active={s.active} addTotal={self.addTotal} />;
  });

This piece of code is properly typechecked and reports error "call of method map. Property not found in object".

However if i replace "new Object" with "{}" in the code above no errors are reported.

**Comment by samwgoldman** [comment] 2015-04-25 00:13
Huh, that's interesting. `{}` treats unknown keys as `undefined` and does not complain—which is by design. It's not clear to me why `new Object()` behaves differently.

**Comment by samwgoldman** [comment] 2015-05-22 09:33
@gcazaciuc I just retried this with 0.11.0 and I get the same error for both `new Object()` and `{}`. Do you see different? If not, can you close this issue?

**Closed** 2015-06-08 13:20 UTC
