### ISSUE TITLE
Flow doesn't refine generic type

### ISSUE THREAD

**Issue by andreypopp** [facebook/flow#2513] opened 2016-09-22 20:56 UTC
Not sure if this is even possible:

```
/**
 * @flow
 */

type X = {
  type: 'x';
  x: string;
};

type Y = {
  type: 'y';
  y: string;
};

type XY = X | Y;

type Cont<+T: XY = XY> = {
  value: T;
};

function RenderC({cont}: {cont: Cont<>}) {
  if (cont.value.type === 'x') {
    let contx: Cont<X> = cont;  <-- ERROR: property 'x' not found XY
    return <RenderX cont={contx} />;
  } else if (cont.value.type === 'y') {
    let conty: Cont<Y> = cont;   <-- ERROR: property 'y' not found XY
    return <RenderY cont={conty} />;
  }
}

function RenderX({cont}: {cont: Cont<X>}) {
  return <div>{cont.value.x}</div>;
}
function RenderY({cont}: {cont: Cont<Y>}) {
  return <div>{cont.value.y}</div>;
}
```

On [TryFlow](https://tryflow.org/?code=LyoqCiAqIEBmbG93CiAqLwoKdHlwZSBYID0gewogIHR5cGU6ICd4JzsKICB4OiBzdHJpbmc7Cn07Cgp0eXBlIFkgPSB7CiAgdHlwZTogJ3knOwogIHk6IHN0cmluZzsKfTsKCnR5cGUgWFkgPSBYIHwgWTsKCnR5cGUgQ29udDwrVDogWFkgPSBYWT4gPSB7CiAgdmFsdWU6IFQ7Cn07CgpmdW5jdGlvbiBSZW5kZXJDKHtjb250fToge2NvbnQ6IENvbnQ8Pn0pIHsKICBpZiAoY29udC52YWx1ZS50eXBlID09PSAneCcpIHsKICAgIGxldCBjb250eDogQ29udDxYPiA9IGNvbnQ7CiAgICByZXR1cm4gPFJlbmRlclggY29udD17Y29udHh9IC8+OwogIH0gZWxzZSBpZiAoY29udC52YWx1ZS50eXBlID09PSAneScpIHsKICAgIGxldCBjb250eTogQ29udDxZPiA9IGNvbnQ7CiAgICByZXR1cm4gPFJlbmRlclkgY29udD17Y29udHl9IC8+OwogIH0KfQoKZnVuY3Rpb24gUmVuZGVyWCh7Y29udH06IHtjb250OiBDb250PFg+fSkgewogIHJldHVybiA8ZGl2Pntjb250LnZhbHVlLnh9PC9kaXY+Owp9CmZ1bmN0aW9uIFJlbmRlclkoe2NvbnR9OiB7Y29udDogQ29udDxZPn0pIHsKICByZXR1cm4gPGRpdj57Y29udC52YWx1ZS55fTwvZGl2PjsKfQo=).

**Comment by gcanti** [comment] 2016-09-23 07:47
Perhaps related to https://flowtype.org/docs/dynamic-type-tests.html#caveats, this works

```js
function RenderC({cont}: {cont: Cont<>}) {
  const value = cont.value // <= const binding
  if (value.type === 'x') {
    return <RenderX cont={{value}} />;
  } else if (cont.value.type === 'y') {
    return <RenderY cont={{value}} />;
  }
}
```

**Comment by andreypopp** [comment] 2016-09-23 09:17
I think `const` binding ins't even needed there. I think Flow can't just refine that—there's no function call which could lead to refinement invalidation.

```
    return <RenderX cont={{value}} />;
```
Yeah, that works but that require me to reconstruct an object which is not really great as in my original code `Cont` has more than a single field.

**Comment by calebmer** [comment] 2017-08-01 15:39
Closing since this issue hasn’t seen a lot of activity. Sorry about that 😣

Please reopen with a reproduction on https://flow.org/try if you are still having issues!

**Closed by calebmer** 2017-08-01 15:39 UTC
