### ISSUE TITLE
Methods with a `new this`/`new this.constructor` don't break given a child class ctor that breaks subtyping

### ISSUE THREAD

**Issue by popham** [facebook/flow#1841] opened 2016-05-24 19:34 UTC
Using `new this(...)` under static methods and `new this.constructor(...)` under nonstatic methods, Flow lets me sneak by a couple of false positives:

``` js
class A {
  x:number;
  constructor(k:number) { this.x = k; }
  static build(k:number): this { return new this(k); }
  clone() { return new this(this.x); }
}

class B extends A {
  s:string;
  constructor(s:string) {
    super(1);
    this.s = s;
  }
  // static `build` is no longer okay--must override
  // `clone` is no longer okay--must override
}

var b = new B("some string");
var staticFalsePositive = B.build(3);
var nonstaticFalsePositive = b.clone();
```

**Comment by calebmer** [comment] 2017-07-26 22:15
Closing since this issue hasn’t seen a lot of activity. Sorry about that 😣

Please reopen with a reproduction on https://flow.org/try if you are still having issues!

**Closed by calebmer** 2017-07-26 22:15 UTC
