### ISSUE TITLE
Circumventing @flow comments with an option in .flowconfig

### ISSUE THREAD

**Issue by calebmer** [facebook/flow#1634] opened 2016-04-07 16:03 UTC
I recently tweeted [this](https://twitter.com/calebmer/status/717822837482979328) to the flow Twitter account with the following question/request.

Is there a feature for `.flowconfig` to specify a glob of files to be type checked? This would allow people to avoid placing `// @flow` comments everywhere will still not type checking dependency code.

This would be especially useful for people with greenfield projects that want to use flow from the outset.

A concern risen in the Twitter thread was the complexity of nested `.flowconfig`s, one solution to this may be a `.enableflow` file which enables flow recursively for the current directory instead of requiring `// @flow` comments.

**Comment by SMLMRKHLMS** [comment] 2016-06-09 15:55
Any update on this?

**Comment by calebmer** [comment] 2016-08-15 02:21
Yes, any update on this? Requiring a `@flow` comment is why I still default to TypeScript for most projects. The TypeScript configuration story is better.

cc @thejameskyle

**Comment by thejameskyle** [comment] 2016-08-18 16:21
There is an option, it's `all=true`. It's currently undocumented because of the unintended side effects it can have in relation to having packages `node_modules` with/without that option on.

/cc @jeffmo

**Comment by SMLMRKHLMS** [comment] 2016-08-18 16:44
@thejameskyle Thank you! Much appreciated.

**Comment by thejameskyle** [comment] 2016-08-18 18:00
Again careful with that, it's not recommended right now.

**Comment by calebmer** [comment] 2016-08-18 18:12
Are there plans to make it a recommended option?

**Comment by thejameskyle** [comment] 2016-08-19 00:18
Not really, without an alternative file extension there's really nothing that resolves the issue. /cc @jeffmo

**Comment by clessg** [comment] 2016-09-17 20:08
Is it possible to restrict the `all` option to, e.g., the `src/` directory?

**Comment by zaynv** [comment] 2016-09-28 19:39
Noob here, but is there a reason it can't work like ESLint? Like having an `exclude` option and then just run for everything else. And maybe have some default `excludes` like `dist` or `node_modules` etc.

**Comment by mroch** [comment] 2016-10-14 05:00
I think this is a duplicate of https://github.com/facebook/flow/issues/284. Let me know if I should reopen, though!

**Closed by mroch** 2016-10-14 05:00 UTC
Labels: question

**Comment by calebmer** [comment] 2016-10-14 13:40
Given there have been three issues asking for this feature (#284, #1519, and #1634) are there any plans to incorporate such a feature? Also, I feel as if this issue has had more activity than #284 as well as providing a solution with `all=true`, perhaps this should be left open?

It seems like @jeffmo’s comment in #284 (https://github.com/facebook/flow/issues/284#issuecomment-155648150) is the only argument against this. As its almost been a year have circumstances changed? Also, if recursive `.flowconfig` files are difficult, why not introduce another file say `.enableflow` which would recursively enable flow? Or a `.flowinclude` file which acts as the inverse of a `.gitignore`.
