### ISSUE TITLE
Question: Support for JavaScript in html files?

### ISSUE THREAD

**Issue by JdKock** [facebook/flow#3272] opened 2017-01-26 07:33 UTC
Is it possible to use Flow for JavaScript in html files ?

I'm using Polymer to building Web Components and it would be nice if I can check the JavaScript in the html files.

**Comment by blake-newman** [comment] 2017-02-01 16:49
Linked to https://github.com/facebook/flow/issues/2691

**Comment by vkurchatkin** [comment] 2017-02-19 15:33
Duplicate of https://github.com/facebook/flow/issues/2218

**Closed by vkurchatkin** 2017-02-19 15:33 UTC
