### ISSUE TITLE
Default values in destructuring can not be assigned to union types

### ISSUE THREAD

**Issue by philipnilsson** [facebook/flow#5024] opened 2017-10-03 14:21 UTC
It doesn't seem like it's possible to assign default values to destructured parameters when other than simple types are involved. For instance I'd expect all the examples from [this fiddle](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swo44AKAbzAA8wBfALjFrtYH4BnfAJ0LYA5kwCUrXgOFtUYMHwCm+TH1IAiACYKoAQ0wx8YSYKFqA3KkboseIiTIUARjr416YALxg1x4Wqas7Fy+IoziRvwmMnKKyqreWrr6hiHmltY4BMSk5HDOruyeYDiJggoaAWz0wZHSYRK1ItSy8koq6ol6BhFSphZWGJl2OU4ubgxe2PowlUFgPI1iDb3RrXEd2l0pjWlWQA) to work.

```
/* @flow */

function fooOK({ x }: { x: ?string }): string {
  return "default string";
}

function foo2({ x = "string" }: { x: ?string }): string {
  return "default string";
}

function foo3({ x = undefined }: { x: ?string }): string {
  return "default string";
}

function foo4({ x = null }: { x: ?string }): string {
  return "default string";
}
```

Even explicitly typing the default values like `(null: ?string)` doesn't seem to work.

**Comment by JanPeter** [comment] 2017-10-04 05:52
I think that's not how assigning default values to destructured variables work. When you assign the default values correctly [flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swo44AKAbzAA8wBfALjFrtYH4BnfAJ0LYA5kwCUrXgOFtUYMHwCm+TH1IAiACYKoAQ0wx8YSYKFqA3KkboseIiTIUARjr416TVuy7HpjMAF42elY1H1MxCX4TGTlFZVUwTW09AyMo4XNLaxwCYlJyOGdXdg8gjjAedJE-QOoAAvKcLShBBQ0ItKkRall5JRV1ZpTDMMyrDBy7fKcXNwYWMu8qpgC2BtZsfRgOsJi++MHk-RGqsdQgA) won't complain:

```
/* @flow */

function foo({ x }: { x: ?string }): string {
  return "default string";
}

function foobar({ x }: { x: ?string } = { x: "string" }): string {
  return "default string";
}

function foobar({ x }: { x: ?string } = { x: undefined }): string {
  return "default string";
}

function foobar({ x }: { x: ?string } = { x: null }): string {
  return "default string";
}
```

**Comment by philipnilsson** [comment] 2017-10-04 09:53
@JanPeter It is possible to assign default values both in function parameter definitions like you have, and in destructuring definitions. Just try 

```
function foo ({ x = 10 }) { return x }
foo({})
>> 10
```

in your browser. More info [here](http://wesbos.com/destructuring-default-values/)

There is also a difference in behaviour in that in your defintions I can call `foobar()` with no arguments, whereas in my definition I have to at least provide `foobar({})`, and of course this should be reflected in the type checking.

**Comment by TomPradat** [comment] 2018-01-24 12:52
I'm still having the issue with flow-bin@0.63.1. Any news ?

**Comment by goodmind** [comment] 2019-06-21 22:28
Duplicate of #2093

**Closed by goodmind** 2019-06-21 22:28 UTC
