### ISSUE TITLE
A way to export a generic React.memo or React.forwardRef component?

### ISSUE THREAD

**Issue by kejistan** [facebook/flow#8788] opened 2021-11-17 07:00 UTC
## Proposal
Add some syntax to write unbound generic arguments in types. Perhaps we can change the behavior of `*`? Writing something like the following seems easy to fit into existing codebases:

```js
export default (React.forwardRef(MyGenericComponent): React.AbstractComponent<Props<*>, RefType>);
```

Currently this export isn't an error, but it is also not useful as the `*` becomes `any` typed.

Another idea would be to follow function types and expand the grammar to allow writing generic parameters in front of types:

```js
export default (React.forwardRef(MyGenericComponent): <T>React.AbstractComponent<Props<T>, RefType>);
```

This is probably more powerful as you can link types together and add constraints, but it is a much larger change to the syntax.

## Use case
Exports need to have explicit type annotations now that everything is types first. Excluding functions (e.g. `(genericFn: <T>(T) => T)`) I don't believe there is currently any way to write an annotation that has an unbound generic type. Notably this comes up with `memo` and `forwardRef` as they both result in `AbstractComponent<C,I>` types. HOCs are a bit out of favor now that hooks exist, but adding a ref to a functional component requires the use of `forwardRef`, so this still seems like an important missing piece.

[A flow.org/try with a more concrete example](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcARFDvmQNwBQdMAnmFnAArFioA8AKgD44AXjgBvAD504cANRYANlhBYAdjFQAuOABJsyACYB5VQqYBBKFGRN+AgDTS5EVQGVFWfNr4ihIYAAeWAaOEgC+9HQA9FFwfAAWwOjMrHAGEFioqgDk8CDIMDBYUHQGngrIlHAQYMgAjgCubCls2AR8LFiRZbgVVQQNqvjALnAAMkkwdgAUYFxaHPN29nCUBNpiuA1WajDabR2pEnCqDQoKKwB012Fwx9MHnXcnZwoAlL5w-kEGb-tUMEuADkIGVIjE4MBLlhLnAsAFILA0lgCMgzvAHgDLgRoAB3SoGNrTCaoGB-OAAIwq8Up1LedFwLlJcAAskwAKII6BFAwk+CiTF4QE4qD4qCElHEybk-T4S7mCmk6z4ADCJEgql2PE4NV4CAcmBRhywAjekQGQxgI1UcDVO3wfOmMqxILK4iclBg2xt0ycMh4bM5iJ5fL9MjhShU6lQwjEAG0AIz2ABM9gAzABdMJhmQudxKfCx6aoEhYIENEAU4raU6V4ofYRCRmqEtKS4KCAAc2LpfLdagb2z4bgUQETjNdGzdAtw1GAEkhtBKA7Jk7-kLgaC2GIPVgvVAfWGAxyubBgqHhzIPFGNLHEyn01mcyPYjog54YOyrNBn3mPIWxB7FQ+yrKBtCVYBVE7BsmyZCA2w7bsS2AitQMHMNR3HehsyAA)

**Comment by gnprice** [comment] 2021-11-17 08:29
I think the core feature request here is for a way to spell a polymorphic type that isn't a function or class. I agree that that would be quite nice, and that AFAIK there isn't currently a way to do this.

#5022 was a previous thread about this. Its author's [use case](https://github.com/facebook/flow/issues/5022#issuecomment-333821262) was essentially the very same as yours -- they have:
```js
type MyProps<T> = {
  val : T,
  consumer : T => any
};
```
and want to annotate an export as `<T>React$ComponentType<MyProps<T>>`, and you have in your try-flow example
```js
type Props<T> = {|
  +elements: $ReadOnlyArray<T>,
  +onSelect: T => mixed,
|};
```
and want to annotate an export as `<T>React.AbstractComponent<Props<T>, RefType>`.

In particular, in both cases you can't get the desired result by just filling in the type parameter as `mixed` or `empty`, because the type is invariant in the parameter -- you have one prop where it's in an output position, and one where it's in an input position.

**Comment by kejistan** [comment] 2021-11-17 19:52
Ah, yes. #5022 is the same issue.

**Comment by SamChou19815** [comment] 2023-07-14 02:05
Duplicate of #6903

**Closed by SamChou19815** 2023-07-14 02:05 UTC
Labels: discussion
