### ISSUE TITLE
No information about `/*::*/` in AST

### ISSUE THREAD

**Issue by fisker** [facebook/flow#8521] opened 2020-11-02 02:48 UTC
```js
require('flow-parser').parse('/*::*/');
{
  type: 'Program',
  loc: {
    source: null,
    start: { line: 1, column: 6 },
    end: { line: 1, column: 6 }
  },
  range: [ 6, 6 ],
  body: [],
  comments: [],
  errors: []
}
```

```js
require('flow-parser').parse('/*::*/', {types: true});
{
  type: 'Program',
  loc: {
    source: null,
    start: { line: 1, column: 6 },
    end: { line: 1, column: 6 }
  },
  range: [ 6, 6 ],
  body: [],
  comments: [],
  errors: []
}
```

We need some information about this comment to fix https://github.com/prettier/prettier/issues/9564

**Comment by thorn0** [comment] 2020-11-02 09:05
Duplicate of #8355

**Closed** 2020-11-02 09:13 UTC
