### ISSUE TITLE
Uninitialized class instance variables ignored: bug?

### ISSUE THREAD

**Issue by nvie** [facebook/flow#5205] opened 2017-10-27 07:37 UTC
I noticed that class instance variable types are not correctly checked by Flow.  For example, if you declare a class has property `x` of a certain type, then Flow seems to be unable to enforce that field is initialized correctly, which caught me off-guard.

```javascript
class Foo {
  x: string;
}

const f = new Foo();
f.x.toUpperCase();  // Uncaught TypeError: Cannot read property 'toUpperCase' of undefined
```

I would expect that Flow would enforce me to:
1. Type the variable as `string | void`; _or_
2. Is okay with it if I provide a correct value in a `constructor()` function for `this.x`.

Is this behaviour intentional or should this be considered a bug?

[Try Flow example](https://flow.org/try/#0MYGwhgzhAEBiD29oG8BQ1oA8Bc0IBcAnASwDsBzAblQF9VVh5SDoAzaAXmlIFMB3OIgAUASmqsAdJgn54AVQAOCnoQDCkHqMoYA9DuhzSwMAFdyAC3zQAKgE9lAUUKF4hXOtKl4VwjzAATaAUXZUJ8W2gAcllFUPUIHkjoeHYTUn8eVjIef1QgA)

**Comment by jfirebaugh** [comment] 2017-10-27 22:19
Duplicate of #650.

**Closed** 2017-10-28 09:11 UTC
