### ISSUE TITLE
Can't extract argument type using $Call

### ISSUE THREAD

**Issue by icpacc** [facebook/flow#6841] opened 2018-09-04 08:12 UTC
Hi,

Would like to share this result related to `$Call`. Not sure if this is a bug or expected behavior:

```js
/* @flow */

type Fn = boolean => number

type ReturnType = $Call<<T, R>(T => R) => R, Fn>
type ArgumentType = $Call<<T, R>(T => R) => T, Fn>
  
// (true: ReturnType); // fails - correct
(1: ArgumentType); // does not fail - wrong?

type ArgumentType2 = $Call<<T, R>(T => R) => T & $NonMaybeType<T>, Fn>
// (1: ArgumentType2); // fails - correct
```
[Try online](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiAdmALxgBGccMeAhqWQHxjECuAtpXgE7rZ8YAEp4M7XsQAquAhQAkAYXowYAHjVSANCOYAKKeVbCAlEZE6SzTLLABBXgHMueYhhlCFy1Ru26D5qbmflaoYGCowMBgehi87HgAXCJiEtKyJgDcYFFgUPQAljAAzmAAtGAAxnC8vHiVGKh6AIzJDs6cru4Z2bkAJnB4pcRwGHmFMOVgCLxwxI4Ctu0ubh54AEzkYEoq6po6wvqGLCJmJ4YAZNsAcnMAsvRYPGuazJbE1rktbU4r3fjrLI5aL5IqlCrVWr1DBAA)

Seems `ArgumentType` has `empty` type, but `ArgumentType2` has the correct boolean one.

The key point is `T & $NonMaybeType<T>` in the `type ArgumentType2`. I don't understand why this last bit fixes the type issue, would really appreciate some further explanation if someone knows more about this topic.

Thanks a lot for the library.

**Comment by koop** [comment] 2018-09-04 18:51
This appears to be a duplicate of #6647 and #6696.

**Closed** 2019-03-09 00:52 UTC

**Comment by jamesisaac** [comment] 2019-03-09 00:54
Closing as duplicate of #6647
