### ISSUE TITLE
Arguments typed using interfaces passes functions

### ISSUE THREAD

**Issue by bigslycat** [facebook/flow#6520] opened 2018-06-25 15:52 UTC
```ts
interface Subscriber<T> {
  next(value: T): void;
}

declare function wtf<T>(sub: Subscriber<T>): void;
declare function sub(): void;

wtf(sub); // I except Flow error here.
```
[Reproduce it](https://flow.org/try/#0JYOwLgpgTgZghgYwgAgMoFcBGBnBVibQA8AKgHzIDeAUMsiBAB5gAUAbnADboQBcyJAJT82Ae2AATANzUAvtWoSICTnCgoY6EAjDBRIZAHcwMUmRbYs-DDjwFi5YcjGSZSlWo1adeg5cwsTi7SCsYwFliCUkA).

I fixed it by using callable object notation:

```ts
type Next<T> = {
  (value: T): void,
};

interface Subscriber<T> {
  next(value: T): void;
}

declare function wtf<T>(sub: Subscriber<T>): void;
declare var sub: Next<number>;

wtf(sub);
// Cannot call `wtf` with `sub` bound to `sub`
// because property `next` is missing in `Next` [1]
// but exists in `Subscriber`
```
[Reproduce it](https://flow.org/try/#0C4TwDgpgBAchAewA8AVAfFAvFA3gKCigAoA3AQwBsBXCALihQEp6SB7ASwBMAaPAXwDcePOwB2wCACcAZmQDG0AMpUARgGc5k9iqmoM+QqITBSlGvSYsOnIX2GcIcimUnRpVUXODtWoqAHdgaT0iNVV6ZXVNbV10Zig2LiEHJxdockkoMJV6OEQkUSoAWx1JNCE8QOlQ1UYBIA).

**Comment by jcready** [comment] 2018-06-25 16:14
Looks to be a duplicate of #6490.

**Comment by jcready** [comment] 2018-06-26 18:43
It's all part of the same issue. Your bug is due to the fact that functions are currently inferred to be typed as callable objects with an indexer whose value is `any`, something like:

```ts
type Next<T> = {
  (value: T): void,
  [string]: any
};
```

This is why I said it was a duplicate. When the other bug is fixed, so will your bug.

**Comment by bigslycat** [comment] 2018-06-26 18:47
@jcready ok, thanks. =)

**Closed** 2018-06-26 18:55 UTC
