### ISSUE TITLE
Can't define class compatible with a type that has optional field

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#4620] opened 2017-08-16 18:58 UTC
Here is [an example illustrating the issue](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCqASgDJgC8YA3qmGDgIYYAWAdowLZ4D8AXAGcMAJwCWbAOaoAvugDGMRgIFEyAeQBGAKzxyMNOg2bsueQSPETKYAEQ2Z8uGyFgArsJh8S5KmzxJvTR09AAoASlQgA):

```js
/* @flow */

type URL = {
  pathname?:string
}

class URLObject {
  pathname:string = ""
}

const url:URL = new URLObject()
```

It is odd that `URLObject` isn't compatible with `URL`, furthermore it is impossible to define a class that would be compatible as there is no way to define optional class fields.

**Comment by vkurchatkin** [comment] 2017-08-16 19:08
Duplicate of https://github.com/facebook/flow/issues/2859

**Closed by vkurchatkin** 2017-08-16 19:08 UTC
