### ISSUE TITLE
gen-flow-files loses connection, no files built

### ISSUE THREAD

**Issue by paularmstrong** [facebook/flow#6171] opened 2018-04-19 15:36 UTC
*Setup:*
* flow-bin@0.70.0
* node@9.11.1
* npm@5.6.0
* yarn@1.6.0
* Mac OS Sierra 10.12.5

Using [this commit](https://github.com/paularmstrong/normalizr/commit/00b71d4b212902146a2b6eee06e7389af3c79df5) (in case something changes in the future and this starts working), running `flow gen-flow-files src/index.js > dist/normalizr.js.flow` (run through `yarn build:types`) causes the following:

```
$ flow gen-flow-files src/index.js > dist/normalizr.js.flow
Lost connection to the flow server (3 retries remaining)
Launching Flow server for /Users/paularms/dev/normalizr
Spawned flow server (pid=12263)
Logs will go to /private/tmp/flow/zSUserszSpaularmszSdevzSnormalizZr.log
Monitor logs will go to /private/tmp/flow/zSUserszSpaularmszSdevzSnormalizZr.monitor_log
Lost connection to the flow server (2 retries remaining)
Launching Flow server for /Users/paularms/dev/normalizr
Spawned flow server (pid=12520)
Logs will go to /private/tmp/flow/zSUserszSpaularmszSdevzSnormalizZr.log
Monitor logs will go to /private/tmp/flow/zSUserszSpaularmszSdevzSnormalizZr.monitor_log
Lost connection to the flow server (1 retry remaining)
Launching Flow server for /Users/paularms/dev/normalizr
Spawned flow server (pid=12729)
Logs will go to /private/tmp/flow/zSUserszSpaularmszSdevzSnormalizZr.log
Monitor logs will go to /private/tmp/flow/zSUserszSpaularmszSdevzSnormalizZr.monitor_log
Lost connection to the flow server (0 retries remaining)
Out of retries, exiting!
error Command failed with exit code 7.
```

The log file (`/private/tmp/flow/zSUserszSpaularmszSdevzSnormalizZr.log`):

```
Apr 19 08:33:35.483 [info] argv=/Users/paularms/dev/normalizr/node_modules/flow-bin/flow-osx-v0.70.0/flow start --temp-dir /tmp/flow /Users/paularms/dev/normalizr
Apr 19 08:33:35.484 [info] Creating a new Flow server
Unable to obtain kernel buffer: Operation not permitted
usage: sudo dmesg
Apr 19 08:33:43.811 [error] Flow server (pid 12730) was killed with sigsegv signal
Apr 19 08:33:43.811 [info] Monitor is exiting (Dying along with signaled server)
Apr 19 08:33:43.811 [info] Broadcasting to threads and waiting 1 second for them to exit
```

**Comment by ShaneMcX** [comment] 2018-04-22 16:34
I'm seeing the same thing. Differences: 

* Running "yarn run flow"
* package.json.scripts: "flow": "flow"
* Mac OS High Sierra 10.13.4
* The issue is not 100% repro. I had a couple good runs that found issues before getting back into this state.

**Comment by savannidgerinel** [comment] 2018-07-18 17:01
I started running into this same issue today, but with just the `flow` command. 100% reproducible. I mucked about with my dev dependencies and determined that the browserify module is casing the crash.

* MacOS 10.13.6
* flow 0.76.0
* npm 5.6.0

Dev dependencies:

```
  "devDepnedencies": {
    "@types/jasmine": "^2.8.8",
    "babel-cli": "^6.26.0",
    "babel-eslint": "^8.2.6",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-flow": "^6.23.0",
    "babel-preset-stage-2": "^6.24.1",
    "eslint": "^5.1.0",
    "eslint-config-airbnb": "^17.0.0",
    "eslint-plugin-import": "^2.13.0",
    "eslint-plugin-jsx-a11y": "^6.1.1",
    "eslint-plugin-react": "^7.10.0",
    "flow": "^0.2.3",
    "flow-bin": "^0.76.0",
    "flow-typed": "^2.5.1",
    "jasmine": "^2.4.0",
    "browserify": "^16.2.2"
  },
```

Remove the browserify dependency and Flow works fine.

**Comment by mroch** [comment] 2018-12-20 14:18
closing since we removed the gen-flow-files command while we rebuild it. sounds like there might be a separate issue with browserify, @savannidgerinel can you file a new issue if it's still reproing?

**Closed by mroch** 2018-12-20 14:18 UTC
