### ISSUE TITLE
Flow picks the wrong case for overloaded method declaration

### ISSUE THREAD

**Issue by nmote** [facebook/flow#2041] opened 2016-07-06 17:27 UTC
This ["fix"](https://github.com/flowtype/flow-typed/commit/f622abbe3eae89792276854dfb75ff41ff61b94b#diff-270e9bf6953824c91a5514fda457faa8) for the `rxjs` tests in `flow-typed` for Flow v0.28 is actually exposing a problem with Flow that is biting Nuclide in the upgrade process.

Flow is picking the wrong case for `combineLatest`. It's picking this one:

`static combineLatest<T, U>(t: Observable<T>, u: Observable<U>): Observable<[T, U]>;`

When we want this one:

```
static combineLatest<T, U, V>(
  t: Observable<T>,
  u: Observable<U>,
  resultSelector: (t: T, u: U) => V,
): Observable<V>;
```

Is there anything we can do to work around this issue?

CC @jeffmo @avikchaudhuri @marudor

**Comment by nmote** [comment] 2016-07-06 17:59
As a workaround it looks like I can add a third `void` argument to the first case.

**Comment by calebmer** [comment] 2017-07-31 15:17
Closing since this issue hasn’t seen a lot of activity. Sorry about that 😣

Please reopen with a reproduction on https://flow.org/try if you are still having issues!

Hi @nmote 😊

**Closed by calebmer** 2017-07-31 15:17 UTC
