### ISSUE TITLE
Property cannot be accessed on possibly null value

### ISSUE THREAD

**Issue by josebalius** [facebook/flow#1004] opened 2015-10-28 17:17 UTC
A team member of mine brought this case to my attention:

```
const nullThing = null;
const notNull = (nullThing !== null);
const breaksFlow = notNull && (nullThing.arbitraryAttribute === 1);
```

Has this already been reported?

**Comment by samwgoldman** [comment] 2015-10-28 19:31
Yeah, I think this is the same as #998 which came up yesterday.

**Comment by calebmer** [comment] 2017-07-19 21:23
Duplicate of https://github.com/facebook/flow/issues/998

**Closed by calebmer** 2017-07-19 21:23 UTC
