### ISSUE TITLE
Does not check props on React component if not declared at the top level.

### ISSUE THREAD

**Issue by jqyu** [facebook/flow#2599] opened 2016-10-09 17:42 UTC
If the definition of a react component is not a top-level value of the current scope, the proptypes are not validated:

https://flowtype.org/try/#0C4TwDgpgBACgTgezAZygXigbygMwQgLimWDgEsA7AcygF8AoegYwQpKgDF90oAKbPAjpF4SZAEp0APj70AkAB4AJmQBuUgd1oKA9CvVQo9cfUNmjLNsCgAhAIZwe2LkIbNW7VXYA2ZJTwUXXHw0ACJBUKgdKUYdHShgAAtoPG9vBAB3ShpfCmgstKgKBGtQSCZkpgBrAno4qEt2Si9ffwxA7mjY+KSyVFzoJQQIVDKICvGa9ysoZp8-APs4ADog6KA

The above is a contrived example, however this means that components imported with `import * as ...` will have typechecking skipped:

``` js
import * as Utils from 'some/path'

// type checking is skipped here:
<Utils.Component />
```

Whereas the following will behave as expected:

``` js
import { Component as UtilsComponent } from 'some/path'

// type checking is performed here
<UtilsComponent />
```

**Comment by minedeljkovic** [comment] 2016-10-14 23:23
I believe this is duplicate of #1113

**Comment by asolove** [comment] 2017-08-29 19:08
This has been fixed. See discussion over in #1113.

**Closed by asolove** 2017-08-29 19:08 UTC
Labels: react
