### ISSUE TITLE
Flow not working any more in Alpine Docker

### ISSUE THREAD

**Issue by peimansh** [facebook/flow#8390] opened 2020-06-02 06:53 UTC
```
ERROR: unsatisfiable constraints:
flow (missing):
required by: world[flow]
```

it seems on 31st May 2020, the package has been labeled "unmaintained" and no longer works in Alpine Linux builds on Testing/edge channel.

Has this been intentional ? Is there any solution in the works ?
All of our builds are failing and the package is deeply integrated in our application. Can someone provide a solution please ?

**Comment by mroch** [comment] 2020-06-05 03:54
we've never maintained official docker images nor musl support (which is used by Alpine instead of glibc IIRC?). can you provide some more details please?

**Comment by peimansh** [comment] 2020-06-05 06:42
Sure.
We were installing the flow package in Alpine Linux by using:
`RUN apk add --no-cache --repository https://nl.alpinelinux.org/alpine/edge/testing flow`
And it was working fine until 31st May. It seems it has been labeled unmaintained and our build are failing due to this and flow is heavily used inside our project. What could be the solution to install/add flow to Alpine linux ?

**Comment by peimansh** [comment] 2020-06-05 06:44
This is the link to the issue:
https://stackoverflow.com/questions/62127720/error-unsatisfiable-constraints-flow-missing-in-alpine-linux

**Comment by gajus** [comment] 2020-11-18 15:35
Duplicate of https://github.com/facebook/flow/issues/7509

**Comment by cristian-rivera** [comment] 2021-07-26 16:06
https://github.com/facebook/flow/issues/3649#issuecomment-886831975

Trying to share this comment everywhere I can to further help!

**Comment by SamChou19815** [comment] 2024-01-17 04:10
Closing since we can't commit to keep it working on alpine.

**Closed by SamChou19815** 2024-01-17 04:10 UTC
Labels: bug, needs triage
