### ISSUE TITLE
Flow allows mutating $ReadOnly objects when using modifier operators

### ISSUE THREAD

**Issue by craigayre** [facebook/flow#7666] opened 2019-04-24 14:26 UTC
Flow version: 0.97.0

## Expected behavior

When defining an object as `$ReadOnly`, I expect that flow should complain about modifying an object through modifier operators such as ++, += and /=.

It seems to give a false sense of security, especially when used in areas that need to be pure. It isn't intuitive that you are prevented from reassigning `o.foo = o.foo + 1` but not `o.foo++`

## Actual behavior

By using modifying operators you are able to change values of an object defined as `$ReadOnly`

```js
type O = $ReadOnly<{| foo: number, bar: number |}>
  
const o: O = { foo: 8, bar: 22 }

o.foo++ // Ok

o.foo /= 2 // Ok

delete o.foo // Ok

o.bar = o.bar + 1 // Not ok
```

See the flow repl for an interactive playground of the above:

https://flow.org/try/#0C4TwDgpgBA8lC8UAkAlCBDAJjAdgGxAB4BvAHygDMB7KgLihwFcBbAIwgCcAaKV9D+kzacopAL4A+AFBQoUgMZUcAZ2BQ6sBFGKUa9ABw8+AqACZTUMVKlUAdNSoBqR9bsOoAekSnrmCHghgaDcaV1tjLTsIxygARiA

**Comment by goodmind** [comment] 2019-04-24 15:34
Duplicate of https://github.com/facebook/flow/issues/7195

**Closed by goodmind** 2019-04-24 15:34 UTC
Labels: bug, needs triage

**Comment by craigayre** [comment] 2019-04-24 15:45
Apologies @goodmind, I had searched the existing issues but hadn't found any results (searching for the operators didn't show any matches)
