### ISSUE TITLE
string | Array<string> not working (object defaults)

### ISSUE THREAD

**Issue by bradennapier** [facebook/flow#4712] opened 2017-08-24 23:08 UTC
Not sure if there is another method of handling this, but I am having an issue where I can not allow a type to be a string OR an Array of strings.  

```js
type GetLastReportArguments = {
  index?: string | Array<string>,
  type?: any,
  size?: number,
  order?: string,
  sortBy?: string
};
```

```js
export async function getLastReport(
  systemIdentityID: string,
  {
    index = [TODAYS_METRICS('system-stats'), YESTERDAYS_METRICS('system-stats')],
    type = undefined,
    size = 1,
    order = 'desc',
    sortBy = '@timestamp',
  }: GetLastReportArguments = {},
): Promise<?SystemStatsEvent> { ... }
```

![image](https://user-images.githubusercontent.com/15365418/29692729-6d31b10c-88e6-11e7-8114-6b07df6edbcd.png)

**Comment by asolove** [comment] 2017-08-25 01:17
I tried taking out bits of this to get the smallest reproduction I could. Here's a simpler piece of code that fails in the same way:

```js
type InputType = {
  foo: string | number
};

export function getLastReport({ foo = "a" }: InputType): null {
  return null;
}
```

The error is about the same as before:

```js
6: export function getLastReport({ foo = "a" }: InputType): null {
                                   ^ number. This type is incompatible with
6: export function getLastReport({ foo = "a" }: InputType): null {
                                   ^ string
6: export function getLastReport({ foo = "a" }: InputType): null {
                                   ^ string. This type is incompatible with
6: export function getLastReport({ foo = "a" }: InputType): null {
                                   ^ number
6: export function getLastReport({ foo = "a" }: InputType): null {
                                         ^ string. This type is incompatible with
6: export function getLastReport({ foo = "a" }: InputType): null {
                                   ^ number
```

It seems like this issue is related to the combination of the object argument with a nested default for a key that has a union type.

**Comment by bradennapier** [comment] 2017-08-25 01:20
@asolove yep, that is what I was thinking.  Thank you for simplifying the issue down to it's bare metal!

**Comment by goodmind** [comment] 2019-05-30 00:48
Duplicate of #2093

**Closed by goodmind** 2019-05-30 00:48 UTC
