### ISSUE TITLE
Support for `typeof` aliasing

### ISSUE THREAD

**Issue by wessberg** [facebook/flow#2339] opened 2016-08-26 00:22 UTC
Consider the following scenario:
```javascript
type MyUnionType = string|number;

function isString (str: any): boolean {
    return typeof str === "string";
}

function myFunction (): MyUnionType {
    if (something) return "a string";
    else return 0;
}
let result = myFunction();
if (isString(result))           str.length; // flow warning
if (typeof result === "string") str.length; // All okay!
```
It would be preferable if flow understood that we already did the type check. For instance, consider a scenario where type `typeof` selector simply isn't enough:
```javascript
// Checks if the string is a primitive or Object string.
function isStringType (str: any): boolean {
	return typeof str === "string" || str instanceof String;
}
```

We could solve it by writing:
```javascript
if (typeof str === "string" || str instanceof String) str.length   // All okay!
```
But that's pretty boilerplatey and screams for a helper method.
So, my request is:
- How about making it possible to declare via a flow comment that the return value of a function substitutes the `typeof`/`instanceof` expressions?

- Or, how about parsing the return values of functions to see if they actually already determine whether or not a property exists on the return value?

**Comment by aackerman** [comment] 2016-08-26 00:31
Sounds like a duplicate of #34

**Comment by samwgoldman** [comment] 2016-08-26 19:12
Yeah, this is a duplicate so I'm going to close in favor of that issue. @wessberg feel free to subscribe there. This is something we're actively working on so you can expect an announcement in that issue soon. :)

**Closed by samwgoldman** 2016-08-26 19:12 UTC

**Comment by montogeek** [comment] 2016-08-30 18:58
I'm getting this behaviour when using Lodash isString module:

declarations
```js
declare module 'lodash.isstring' {
  declare function exports(value: any): boolean;
}
```

src.js
```js
parse: (value: Object|string): Object => {
    let query: Object|string = {};

    if (isString(value)) {
      query = url.parse(value, true).query;
    }
    ...
}
```

Error:
```
 28:       query = url.parse(value, true).query;
                   ^^^^^^^^^^^^^^^^^^^^^^ call of method `parse`
 28:       query = url.parse(value, true).query;
                             ^^^^^ object type. This type is incompatible with
1224:     urlStr: string,
                  ^^^^^^ string. See lib: /private/tmp/flow/flowlib_176bd1d7/node.js:1224
```
