### ISSUE TITLE
Can't filter types with Array.filter

### ISSUE THREAD

**Issue by funtaps** [facebook/flow#1915] opened 2016-06-09 10:37 UTC
It's impossible to filter element by type with Array.filter.
Here is example of valid code, that flow don't want to accept.

```javascript
// @flow
const input: Array<number|string> = [1, 'a', 2, 3, 'b'];
const result: Array<number> = input.filter(el => {
  return typeof el == 'number';
});
```

It returns

    3: const result: Array<number> = input.filter(el => {
                                      ^ call of method `filter`
    2: const input: Array<number|string> = [1, 'a', 2, 3, 'b'];
                                      ^^^^^^ string. This type is incompatible with
    3: const result: Array<number> = input.filter(el => {
                            ^^^^^^ number

Flow version 0.26.0

**Comment by avikchaudhuri** [comment] 2016-06-17 08:39
Duplicate of #1414

**Closed by avikchaudhuri** 2016-06-17 08:39 UTC
Labels: Closed: duplicate

**Comment by gcanti** [comment] 2016-06-26 07:51
@funtaps a possible workaround:

```js
const input: Array<number|string> = [1, 'a', 2, 3, 'b']
const result = ((input.filter(el => {
  return typeof el == 'number'
}): Array<any>): Array<number>)
```

**Comment by bsmith-cycorp** [comment] 2019-01-17 00:12
Really wish they would solve this. In the meantime, here's a less-gross-but-still-hacky version of the above that we use when we _know_ something is a type but we can't communicate that to Flow:
```javascript
function cast<T>(val: any): T {
  return val;
}
```
