### ISSUE TITLE
Typeof Object + null check but flow still fails

### ISSUE THREAD

**Issue by vieks** [facebook/flow#1598] opened 2016-03-30 16:22 UTC
```javascript
function foo(bar: Array<mixed>){
  bar.map(v => {
    if(v && typeof v === 'object')
      console.log(v['foo']); // v is compulsorily an Object here so WHY ???
  });
}

```

```
 72:       console.log(v['foo']);
                       ^^^^^^^^ access of computed property/element. Computed proper
ty/element cannot be accessed on possibly null value
 72:       console.log(v['foo']);
                       ^ null


Found 1 error
```

"cannot be accessed on possibly null value"  Seriously ??? ```v``` **CAN NEVER BE** ```null``` here.

**Comment by mroch** [comment] 2016-03-30 16:59
the problem is that `if (v)` when `v` is mixed would have to refine `v` to a basically-infinite union... `string | number | boolean | Array<mixed> | Object | HTMLElement | every other possible class`, so flow doesn't support that right now.

instead, you can do `if (typeof v === 'object' && v)`, which is equivalent. since `typeof v === 'object'` allows flow to refine the type to `Object | null`, then the `&& v` can filter out the null.

**Comment by mroch** [comment] 2016-03-30 17:04
closing out in favor of #1416 

thanks though, it's helpful to know that this is bothering people

**Closed by mroch** 2016-03-30 17:04 UTC

**Comment by vieks** [comment] 2016-03-30 17:24
So the solution is: **from** ```if(v && typeof v === 'object')``` **to** ```if(typeof v === 'object' && v)```

We call that a truly WTF...

Anyway thanks :)

**Comment by mroch** [comment] 2016-03-30 22:56
@vieks I special-cased the kind of check you're doing, see https://github.com/facebook/flow/commit/5673c29a74147d7ae253e6c8ae984e504c289379

**Comment by vieks** [comment] 2016-04-10 07:58
Thanks this is a consistent behavior now no more a kind of "jiggery-pokery".
Great job Sir @mroch
