### ISSUE TITLE
Type Checker fails to find object instances with non optional properties

### ISSUE THREAD

**Issue by beaucollins** [facebook/flow#7706] opened 2019-05-08 17:26 UTC
Flow version: 0.98.1

## Expected behavior

Object literal types with a property should fail type checking when instances do not have that property.

```js
type MyType = {
  name: string
}

// Expect this to fail because it doesn't have `name: string`
const thing: MyType = {};
```

## Actual behavior

Defining an object instance without the defined prop passes type checking.

* Link to Try-Flow or Github repo: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCyWAKgBYCWAdgOZgC8YA3qmG1QIYC2eAXGAGcMAJ2o0ANGFQBfVAGM4VIWDgYyeYeTH9iW2g2Yz0QA

**Comment by goodmind** [comment] 2019-05-08 17:41
@beaucollins this is duplicate of many issues related to unsealed object

**Closed by goodmind** 2019-05-08 17:41 UTC
Labels: bug, needs triage, unsealed objects

**Comment by jamesisaac** [comment] 2019-05-08 19:23
#7345
