### ISSUE TITLE
Function object argument type is incompatible with default

### ISSUE THREAD

**Issue by sHooKDT** [facebook/flow#7178] opened 2018-11-15 10:25 UTC
The thing is when you have an object function argument and specify a default value for it's property with complex type, Flow doesn't recognize type properly.

It may be hard to explain, just check this example: [Example](https://flow.org/try/#0PTAEAEDMBsHsHdQGcAuAnAlgYxQKFygJ4AOApqALKEAqJ5AvKAHYCuAtgEaloDaAuqAA+zdlzQBufJBZMcGWE1BtC02QAoA3rlCgAhmgDmoRgGYANLgC+ALlAa9h21VplQlgJR2r+ZaqyaHA1sARjd3SV8Zf3t9INAeYIEPcSA)

For example, I can't create a function, which accepts object with property that can be either an array of functions or a single function.

For those who want a quick look:
```
type MyType = number[] | number;

function myfunc({
  // Here flow screams that default arg is incompatible with number (WTF?)
  arg = 3,
}: { arg: MyType }) {
  console.log(arg);
}
```

**Comment by sHooKDT** [comment] 2019-01-21 09:20
bump! Still reproducible in 0.9X. Can someone explain why is this happens?

**Comment by goodmind** [comment] 2019-05-30 19:32
Duplicate of #2093

**Closed by goodmind** 2019-05-30 19:32 UTC
