### ISSUE TITLE
immutable-by-default config option

### ISSUE THREAD

**Issue by rattrayalex** [facebook/flow#4398] opened 2017-07-16 20:44 UTC
Hi there, 

The use of `$ReadOnlyArray<>`, covariant `{ +prop: type }`, `$Exact<>`, and probably others can help enforce immutability in a JS codebase which uses primitives. 

However, they're not very convenient to use manually every time. 

A config option that makes these the default could be helpful to those trying to enforce immutability in their codebases. 

For example: 
```jsx
const arr = [1, 2, 3]; // implicitly a $ReadOnlyArray
arr.push(4) // Error!

const record = { // implicitly $Exact
  foo: 1, // implicitly +foo
  bar: 2, // ditto
}; 
record.foo = 2 // Error!
record.qux = 3 // Error!
```

In order to opt-out, a new type may need to be introduced. For example: 
```jsx
const arr: $Mutable<Array<number>> = [1, 2, 3];
arr.push(4); // ok

const map: $Mutable<{[string]: number}> = {
  foo: 1,
  bar: 2,
};
map.foo = 2 // ok
map.qux = 3 // ok
```

I have not yet used Flow extensively, so please pardon any ignorance here 😄 

I think this feature could be popular among the React community especially.

**Comment by rattrayalex** [comment] 2017-07-16 20:50
Reading more into this, `$Exact` may be less useful than covariance and `$ReadOnlyArray`, given that objects declared this way will be sealed anyway.

**Comment by cloudkite** [comment] 2017-07-21 23:00
@rattrayalex great idea, this would be amazing! 

I think it would be better if you could just pass a type into $MutableObject

```
type MutableThing = $MutableObject<{ id: string, foo: number }>
```

This would allow you to convert existing types ie:

```
type Thing = { id: string, foo: number }
type MutableThing = $MutableObject<Thing>
```

**Comment by cloudkite** [comment] 2017-07-22 00:27
or better yet combine $MutableObject and $MutableArray into `$Mutable` which accepts either array or object

```
$Mutable<Array<number>>
$Mutable<{ id: number }>
```

**Comment by rattrayalex** [comment] 2017-07-23 05:36
This should of course also work for classes, ideally with proper support for setters in the constructor: 

```jsx
class Foo extends Bar {
  a = 1;
  constructor(b: number) {
    super(b);
    this.b = b;
  }
  method() {
    this.c = 1 // error!
  }
}
```
equivalent to
```jsx
class Foo extends Bar {
  +a = 1;
  +b: number;
  constructor(b: number) {
    (this: any).b = b; // https://github.com/facebook/flow/issues/2646
  }
}
```

**Comment by goodmind** [comment] 2019-07-22 06:44
Duplicate of https://github.com/facebook/flow/issues/5369

**Closed by goodmind** 2019-07-22 06:44 UTC
