### ISSUE TITLE
NodeJS#url - Weird union type mismatch (version 0.33)

### ISSUE THREAD

**Issue by ryyppy** [facebook/flow#2640] opened 2016-10-17 14:22 UTC
Please refer to following example:

```js
/* @flow */

import { parse, format } from 'url';

export function appendQueryParameters(url: string, params: Object): string {
  const urlObj = parse(url);

  return format(urlObj);
}
```

https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwBvMHAQ3wGcBTAGjCgKwuIF8n84swByAK74YfANzpaADzxEmAgHYBjQhjjywFHDlryAJgEUBtfAE8AClQpZahY9QAUQmAC4w1QvgzyA5o0r4ralcAeQAjACtaZQBKV3dPH1JUMDBFNXcwJzDwsABecio6R2Fo8WSwfBshdWZ8VkJimGzS1HYgA

I use nodejs' `url.parse` to parse a string to a url object, which is pretty much the same type signature as the  input parameter of `url.format`... strangely enough I get a weird `string is not a number` error, although I think this should be perfectly fine... 

I reduced the example to a minimal repro:

```js
/* @flow */

type T = {
  port: string
};

type U = {
  port: string | number
};

function format(x: U): string|number {
  return x.port; 
}

// Works, because flow doesn't assume a type
format({
 port: 1,
});

const t: T = {
  port: '1',
};

// Doesn't work, because flow is biased to T
format(t);
```

Which produces following output:

```
8:   port: string | number                    ^ number. This type is incompatible with
4:   port: string           ^ string
```

Actually I expected flow to let this through, since it fulfills the structural requirements?

Is this expected behavior?

**Comment by vkurchatkin** [comment] 2016-10-17 14:41
> Is this expected behavior?

Yes, it's because object types are invariant with respect to property type. In Flow 0.34 we can do this:

```js
type U = {
  +port: string | number
};
```

**Comment by ryyppy** [comment] 2016-10-17 14:46
Okay makes sense, we should probably update the nodejs libdefs after 0.34 lands... IMO it's very likely someone will use the output of `parse` to modify the result and get a string with `format` later on... This error message was super confusing to me :-)

**Comment by vkurchatkin** [comment] 2016-10-17 14:53
I guess we can start this process now, every property in every `options` object should be covariant.

**Comment by mroch** [comment] 2016-10-17 17:25
This is a duplicate of https://github.com/facebook/flow/issues/908. @vkurchatkin, would you mind copying your solution there?

**Comment by ryyppy** [comment] 2016-10-17 21:22
Oops, how could I not find this duplicate issue? I swear I tried to find it :-p

**Closed** 2016-10-21 12:30 UTC
Labels: Closed: duplicate
