### ISSUE TITLE
Nullable destructured named argument default value not handled properly

### ISSUE THREAD

**Issue by zenria** [facebook/flow#2678] opened 2016-10-25 08:11 UTC
`function foo({s = null}: {s?:?string})  {
    return s;
}
`
leads to the following errors: 
string This type is incompatible with null
null This type is incompatible with string 

https://tryflow.org/?code=ZnVuY3Rpb24gZm9vKHtzID0gbnVsbH06IHtzPzo/c3RyaW5nfSkgewoJcmV0dXJuIHM7Cn0K

**Comment by jsynowiec** [comment] 2016-10-26 21:17
Same behaviour can be observed for other primitive types - number and boolean. I was trying to solve this today for some time but without success. Ended using `any` type with optional property.

If nullable (maybe types) optional property is not specified for destructured properties that defaults to null then flow complains about missing properties from object literal used in function call.

**Comment by Yuripetusko** [comment] 2016-12-23 15:38
Also getting this

**Comment by goodmind** [comment] 2019-05-24 19:13
Duplicate of #2093

**Closed by goodmind** 2019-05-24 19:13 UTC
