### ISSUE TITLE
Missing type definitions for react and react-dom 16.6

### ISSUE THREAD

**Issue by kevinwolfcr** [facebook/flow#7106] opened 2018-10-27 15:55 UTC
Hello!

I was trying to use flow + (react & react-dom) `^16.7.0-alpha.0`, but I found that neither `createRoot` nor `Suspense` nor `use*` are flow-typed yet.

Any reason about this, or plans on adding this to lib definitions? I can create a PR if needed.

![screen shot 2018-10-27 at 14 37 51](https://user-images.githubusercontent.com/3157426/47609119-e7902a80-d9f5-11e8-8c38-64d3ef4c3e03.png)

**Comment by wchargin** [comment] 2018-10-27 23:36
Duplicate of #7093.

**Closed** 2018-10-28 00:11 UTC
