### ISSUE TITLE
No error / unrelated error when destructuring and assigning a default value on arguments. 

### ISSUE THREAD

**Issue by mrkev** [facebook/flow#6178] opened 2018-04-20 19:12 UTC
Take this code

```
const foo = ({a = 1}) => true
```

This is an error in javascript: https://repl.it/@aykev/LastingSimpleDebugging-1

```
TypeError: Right side of assignment cannot be destructured
```

However the error flow presents doesn't guide the user towards the real problem:

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwDqAFgIbq4BuuATmALxgDO61AlgHYDmYAPmOwFcAtgCMaAblQYc+AArU42RvTABvHqgCQjOENzoiHTgC5CpclWoAaVDwC+k1AGM47ZmChw4KgBSqdegZGKgDkAIwATADMIXam8oqMAJT0AHxgLAK4ji5u6GAiJLQMPgH6hlymxGSUNKGRMSl06ZnZqEA

Spotted on: https://github.com/facebook/flow/issues/6135

**Comment by jcready** [comment] 2018-04-20 19:47
Flow _does_ point you to the correct problem:

```js
const foo = ({a = 1}) => true;
foo();
```

```
2: foo();
   ^ Cannot call `foo` because property `a` is missing in undefined [1].
References:
2: foo();
   ^ [1]
```

Am I missing something?

**Comment by mrkev** [comment] 2018-04-20 19:50
Oh, try the flow.org/try example, not the repl.it example. That's the specific case I'm talking about

**Comment by goodmind** [comment] 2019-05-30 06:32
Duplicate of #2093

**Closed by goodmind** 2019-05-30 06:32 UTC
