### ISSUE TITLE
Required object prop does not error if argument defaults to empty object

### ISSUE THREAD

**Issue by torjusb** [facebook/flow#7692] opened 2019-05-02 09:05 UTC
Flow version: v0.98.0

If no arguments are passed to a function which takes an object with _required_ properties, but the argument defaults to an empty object, Flow doesn't catch the error.

## Expected behavior

Flow should catch the error

## Actual behavior

Flow doesn't catch the error

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swFD8ALAEQFMoBDTGfAeQCMArACgG8o4cADRh2DAE4BfAFxheAHzAC4sgM75xhbAHMw8yWAC8cyQEoTGHAWKlyVOJnx1GzNlz7KRYqbIVLBahpauvrmvJLowMBgAMqUDjAAJmC04uJw4qh2NPRMLBw8pgDckdEAomkZqmC4GeK0BDAAnlkUOS757uHFpWAV6eLVtWkN+M2t9o7OeW6FRUA

**Comment by dsainati1** [comment] 2019-05-02 17:12
This is another consequence of `{}` denoting an unsealed object and trivially passing all property checks. Duplicate of #7345.

**Closed by dsainati1** 2019-05-02 17:12 UTC
Labels: Closed: duplicate, Typing: object model, bug, unsealed objects
