### ISSUE TITLE
Adding __proto__: empty to an object type seems to make it compatible with any interface

### ISSUE THREAD

**Issue by mwiencek** [facebook/flow#8685] opened 2021-06-16 02:44 UTC
Flow version: 0.153.0

## Expected behavior

```JS
type ObjEmptyProto = {
  __proto__: empty,
  +[string]: string,
};

interface Foo {
  get(name: string): string,
  has(name: string): boolean,
}

declare var y: ObjEmptyProto;

(y: Foo);  // Should probably error, but works?
```

## Actual behavior

I can cast `y` to the `Foo` interface above without any error.  It errors if I remove `__proto__: empty`.

(I don't think it matters that the object types use indexers.  I get the same result with fixed properties.)

* Link to Try-Flow or Github repo: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDyARgFZgC8YA3qmGANQDaAzhgE4CWAdgOYC6ALjBsufADSoAvgG502fETIBRALY5sABXZwMcSjTpgA+sZw69p4XnXZJ9ZqJ4DhTidLmoeGPOygBDAGMCADE4fVp6XjwMAApuf1U8Vw5nAEoUsV57MAALfxZ4xOSRVL4MsGJwmDx-bkkpdAATPECYf3YCADcOsAAPYRJSORa2ju7erEGVWyxtXThPWIGwMLg0mXpgYDBldh12dFip1fCNrZ2AdTh2AGsWAH5UIA

**Comment by mwiencek** [comment] 2021-06-16 03:18
IIRC, I was using `{__proto__: empty, ...}` because in the past I couldn't create a function that accepted both regular objects and null-prototype ones, and found that as a workaround. But it seems that `{__proto__: null, ...} | {...}` or `interface {}` works now. I'd guess this is still weird behavior.

**Comment by dsainati1** [comment] 2021-06-16 13:45
Hmm I think the behavior with an `empty` prototype, because `empty` is a subtype of every object/interface type. The issue is rather that we should not actually make it possible to construct an object with an empty prototype. Thanks for the heads up.

**Comment by mwiencek** [comment] 2021-06-16 14:46
Ah ok, I was thinking maybe it didn't make sense where there are declared properties that explicitly conflict with the interface, but banning it outright solves that in any case. :)

And I was wrong about `interface {}` being compatible with `{__proto__: null, ...}`: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVATApgYxgQwCcswA3IsADwC4wBvAfQYAdC4AXOJ2gOwFcYMADRgAdOIC+Abky4CxMhQCetOuNHT0AChpgAlj3ZZCUfDhJ0JAShlaV+w8dPn61mUA (not sure if that is intended) though I think `{__proto__: null, ...} | {...}` still works.  Unfortunately there are still uses of `interface {}` or `{...}` in lib/core.js that block passing in null-prototype objects.

**Comment by SamChou19815** [comment] 2023-02-04 05:28
Closing since this makes sense. You can't construct an object with `{__proto__: empty, ...}`

**Closed by SamChou19815** 2023-02-04 05:28 UTC
Labels: Typing: object model
