### ISSUE TITLE
Flow does not support export from construction

### ISSUE THREAD

**Issue by yuri-karadzhov** [facebook/flow#2784] opened 2016-11-10 15:32 UTC
Flow report an error ```Unexpected identifier``` for construction
```
export Name from './path';
```

**Comment by erikdesjardins** [comment] 2016-11-10 19:42
Duplicate of #2403

In the mean time you can work around this with 

```js
export { default as Name } from './path';
```

**Comment by TrySound** [comment] 2018-03-12 13:18
Duplicate of #2403

/cc @vkurchatkin

**Closed** 2019-01-31 17:36 UTC
