### ISSUE TITLE
Empty object ({}) passes type check for a type with a required field

### ISSUE THREAD

**Issue by lfscheidegger** [facebook/flow#7668] opened 2019-04-24 18:16 UTC
Flow version:
0.97.0
## Expected behavior
This sample:
```
/* @flow */
type SomeType = {
	values: Array<string>,
};
const x: SomeType = {};
```
Should fail to validate, as `x` does not contain a `values` array.

## Actual behavior
The sample passes flow validation without issues:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDKcAtngCq4EC8YA3qgJABuAhjAK54DOAXGAEEATkNZYAPNwxCAlgDsA5gD4ANKgC+AbnQBjOHKlgAHv2JlK+MLTpagA

A few more interesting notes - if `SomeType` has more than one property, and the literal for `x` supplies some (but not all) of those properties, then flow correctly flags this as invalid:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDKcAtngCq4EC8YA3qgJABuAhjAK54DOAXGAEEATkNZYAPNwxCAlgDsA5gD4ANKjAawJOELwA1dlz6CRYydPnK1AXwDc6AMZw5UsAA9+xMpXxhaDDTZOHn4AbQBdG1sgA

Here's also a more involved example on how this can obviously cause runtime errors:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDKcAtngCq4EC8YA3qmGAG4CGMArngM4BcYAQQBOQ1lgA83DEICWAOwDmAPgA0qAL4BudFA5yAxhhlw5YKHDgAKAJT9iZSvnqMw+k1LAAPO6QpUwtHRaLkJ4GBxCpp7a6jp6hsamAEasQpbeRL6OeNbOTG5yHqwBZhY2AHRsnDzlMHiKGAAW2kyh4ZFgrDHoKWnmVtbWmkA

**Comment by jamesisaac** [comment] 2019-04-25 23:55
Duplicate of #7345 -- this is consequence of Flow treating `{}` as an [unsealed object](https://flow.org/en/docs/types/objects/#toc-unsealed-objects) -- probably best workaround for now is using [exact objects](https://flow.org/en/docs/types/objects/#toc-exact-object-types).

**Closed by jamesisaac** 2019-04-25 23:55 UTC
Labels: bug, needs triage
