### ISSUE TITLE
Boolean(variableName) check

### ISSUE THREAD

**Issue by jfidiles** [facebook/flow#7765] opened 2019-05-28 10:00 UTC
Hi!

I've got a component called `Text` that accepts `children` as props of type `Node`.

```
function Text({children}: {children: Node}) {
   return <span>{children}</span>
}
```

Then I have another component called `PersonCard` that uses `Text` component:

```
function PersonCard({name, description}: {name?: string, description?: string}) {
   return <>
      {Boolean(name) && <Text>{name}</Text>}
      {Boolean(description) && <Text>{description}</Text>}
   </>
}
```

Flow version: 0.94.0

## Expected behavior
Flow will understand that I am checking for both, `name, description` that exists using `Boolean(foo) && ...`

## Actual behavior
Inside the `PersonCard` I've got some flow errors saying that the `Text` component is not expecting a `null/undefined` value, which I find strange because I am checking that the variable exists and has values inside before I want to render the component. This only happens when I am using `Boolean(foo) && ... `

* Link to Try-Flow or Github repo: https://flow.org/try/#0JYWwDg9gTgLgBDAnmApnA3gOQgExQXzgDMoIQ4ByKFAQwGMYKBuAKBdEljgCVaHjS5Kn0asWSVHAAKKKAGcIAOwDCNKDgAqyNAF4MLAJCKaIFAH4AXHDkwowRQHMANCzhwDeOXTtgYwJZbWtvYOLPhsRACuigz+inAaKAAeMAAU6HQAFsAANjjUivhWGdl5BVbYePgAlPrucNQwkVDxADxyYDSKAHwlufkoha0A9B1d3azhLMPDCdlycMALRDS5IXAAtHAARpHwAJJwyaj8wPAwEHAA7tAA1ixRMX5K0rIKKmo4AOpnmQBCEAgOVoKkyKDot3SxlMTjgnm8wF8cSKr3kSlU6i0qFq6Fc7kazTa3TxbnQAKBINS0JQtQAZLS4K1EiletT8CNmTBuuE3KTycCuql4T5noo6QymckuehhYjRezhpzuSTGcMJmE2DM5ktFstVjl1ltdgcjkkTvAzghLjcoPdHrEXjI0R91D8YJlErBgGpEMowRCoSYULDZUilCine8MZptDi8QYCS1GcTeRh+ZTqbUzIyleg2Rypd0rIpIjkcjzeWTAQLFEKUF4RXEsznCzL6wiw0NFYXi6XyyqRuqplqNPNrnc5A9og74pH0Z83ZkACIQSLbYGYFAOGh+ABuKEDMLh7cb4asc5dMexdXxKCaSdaKcrAEJn9S4PSWyy80GFUqK6Sr6hqKH4SrmwHIgWLIAaqQ5AA

**Comment by AugustinLF** [comment] 2019-05-28 10:07
Yep, it's a common issue, there's already an issue for that #4526.

**Comment by goodmind** [comment] 2019-05-28 14:22
Duplicate of #4526.

**Closed by goodmind** 2019-05-28 14:22 UTC
Labels: bug, needs triage
