### ISSUE TITLE
[bug] Object maybe property as ConditionalExpression test doesnt infer correctly for consequent/alternate

### ISSUE THREAD

**Issue by Andarist** [facebook/flow#4155] opened 2017-06-13 11:44 UTC
Cant explain it better than in code itself:

https://flow.org/try/#0PTAEAEDMBsHsHcBQBjWA7AzgF1BgpjgLygAUsADlgJboYBcoA3qACYCGAnhgPwNoCuAWwBGeAE6gAvgEpQhAHxNEASFSYceAB7kqYvBjmgK1WgDp2XUN1AADANygtOvRkIASZmjzxQAETZYeCT+gaZoCCSyANRGlDSY5pwGAFSgAEwALKCpAGwADNmg+YUAjHnl0qZYsACqACoAwgDKWGJUaADmkVI2oAwA5P2goIiSiCMotDj4WGmGZHG0DMwWPHxCohIycoqM46CqU6xJhsbxGIlcKmrYjtq6+oarVrYOTg+uHqBePiFBf2EItFjpZUplCsVcgVUmUKlVao0Wm1Ot1JL0BkMRmNEIggA

**Comment by awestroke** [comment] 2017-06-13 12:21
This is not a bug, but a limitation of flow. `options` is an object, and flow cannot know if a seemingly unrelated function call (like `Date.now()`) will change it. If you call `Date.now()` before doing the null check, flow accepts it:

https://flow.org/try/#0PTAEAEDMBsHsHcBQBjWA7AzgF1BgpjgLygAUsADlgJboYBcoA3qACYCGAnhgPwNoCuAWwBGeAE6gAvgEpQhAHxNEoFaFSYcaBHNAARNljwA6LfBLSA3IgCQ67KDwAPclTF4MOitVpH2XUNygAAYWDs6u7oQAJMxoePB6BngkpqAA1KBeNJi+nB4AVKAATAAs0kZYsACqACoAwgDKWGJUaADm5lJBoAwA5L0qiJLKiCi0OPhYRTpklNn0TKx5vKACIuJSsgpKKrbjS-7EWT5+GFZ7GmEubh7EpwHBoU7XkTGr8YmGJPqGJgidGXuhVKoEKADYAAyg0CQ6EARghiPKlVqjWarQ6skk3T6A1AQ1GiCAA

**Comment by Andarist** [comment] 2017-06-13 13:58
Wow, thanks for the explanation! i guess i need to yet wrap my head around how flow thinks to avoid such confusion on my side

However still this could be fixed (I think) - i.e. `Date` constructor used here assumes that it wont mutate `options` here, same thing could be assumed for `Date.now()` and possibly other built-ins which behaves in the same way now.

**Comment by awestroke** [comment] 2017-06-13 18:00
I'll make an example that demonstrates why flow does what it does:

```js
// @flow
const set = (options: { days?: number }) => {
	const expires = options.days ? `; expires=${ new Date(Date.now() + options.days * 24 * 60 * 60 * 1000).toUTCString() }` : ''  
}

const options: { days?: number } = { days: 3 };
const _dateNow = Date.now.bind(Date);
Date.now = (() => {
    delete options.days;
    return _dateNow();
});
// the call to Date.now() inside set() will now make options.days undefined
set(options);
```

**Comment by Andarist** [comment] 2017-06-14 08:38
Ofc tampering with globals is always an option and literally anything can happen - overriding `JSON.stringify` or `Array.from`, but flow will still assume good 'faith' and will infer the results to be respectively string and array, wont it? Same good faith could be applied for `Date.now`

**Comment by awestroke** [comment] 2017-06-14 08:52
There is a feature suggestion for implementing purity in flow type declarations: #2715

**Comment by asolove** [comment] 2017-08-21 21:38
(@calebmer I think this can be closed as a duplicate) The bug referred to in the title isn't really a bug, but the behavior is clearly confusing. What's left in this issue is a request for declaring functions as pure, which is represented already in #2715.

**Closed** 2017-08-22 14:24 UTC
