### ISSUE TITLE
Unexpected token import: function-like import() module loading

### ISSUE THREAD

**Issue by teod** [facebook/flow#3474] opened 2017-03-06 15:32 UTC
Using the `import()` module loading new syntax proposal causes a `Unexpected token import` error. Using `suppress_comment` does not help for `Unexpected token` errors. Is there a way to suppress this ?

**Comment by vkurchatkin** [comment] 2017-03-06 15:42
Duplicate of https://github.com/facebook/flow/issues/2968

**Closed by vkurchatkin** 2017-03-06 15:42 UTC
