### ISSUE TITLE
[bug] destructured arg with disjoint type and default given

### ISSUE THREAD

**Issue by Andarist** [facebook/flow#4569] opened 2017-08-10 08:16 UTC
Can be seen here https://goo.gl/AAT8c3 and confirmed being a bug [here](https://twitter.com/calebmer/status/895266347210358784). Opening this issue as a reference.

**Comment by mwalkerwells** [comment] 2017-08-14 01:54
https://github.com/facebook/flow/issues/4575#issuecomment-322082784

**Comment by goodmind** [comment] 2019-05-29 07:07
Duplicate of #2093

**Closed by goodmind** 2019-05-29 07:07 UTC
Labels: Typing: unions/intersections, bug
