### ISSUE TITLE
string is incompatible with string literal

### ISSUE THREAD

**Issue by kevinwolfcr** [facebook/flow#6868] opened 2018-09-07 20:14 UTC
Hello, I am having some issues with flow that I don't know how to solve them, since they came on the flow core.

I have a function that receives an argument which type is an union of string literals. But when I try to iterate an object with `Object.entries`, I receive the error `string is incompatible with string literal`. When I iterate the object with `Object.keys`, it works.

Demo:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDCc8ATgHICGAtgQLxgDkCAFgJYZ6NgA+TARjEoBjANbc+jUngAmEgTACuXXkwDm0vADtG6KIq3CMbOFrDw1xMgAotNPAC4iJOBXsBKMAG9UYMMNMAZxI8ADoLawADK1cnABIvO1oAX0j3VGT0AK1AjH8XUkCwBh8-Vg5HJgBiADE6+sYAGl8wQRFRJ0YqgAZevqaW6RlO2pq+7oG-QWUR8brJsA08bVnugA5+5r8M9GBgMAAVdiKZODxAnTyEV1FA1AB5fgArPCNQ7QxSNnPrALJA9yhKCuACiIhY1msAG0wEk8I0wCw8AAPMAAXU8dAAfN4WhYYqRbB4MulUHtDscwNdSLcHs9XhhQqI8FhAr8CgCgaDweyyMUcfiCrzXO50kA

**Comment by wchargin** [comment] 2018-09-07 21:40
Duplicate of #5663 and a bunch of other issues: search `Object.values`.

**Closed** 2018-09-21 23:54 UTC
