### ISSUE TITLE
0.147.0: signature-verification-failure lint regression

### ISSUE THREAD

**Issue by mrtnzlml** [facebook/flow#8621] opened 2021-03-19 14:35 UTC
Flow version: 0.147.0

## Expected behavior

No errors with the following file:

```js
// @flow strict

export default function shouldLintAll(filename: string): boolean %checks {
  return /yadada/.test(filename);
}
```

## Actual behavior

Flow throws the following error:

```text
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/eslint-runner/src/shouldLintAll.js:4:10

Cannot build a typed interface for this module. You should annotate the exports of this module with types. Cannot
determine the type of this member expression. Please provide an annotation, e.g., by adding a type cast around this
expression. [signature-verification-failure]

     1│ // @flow strict
     2│
     3│ export default function shouldLintAll(filename: string): boolean %checks {
     4│   return /yadada/.test(filename);
     5│ }
     6│

```

## Additional context

This worked fine in 0.146.0 (no errors). Maybe something changed with `%checks` or we are using it incorrectly? Note that removing the `%checks` part makes it work again:

```js
// @flow strict

export default function shouldLintAll(filename: string): boolean {
  return /yadada/.test(filename);
}
```

This results in `No errors!`.

Thanks for having a look! 🙂

**Comment by samwgoldman** [comment] 2021-03-19 16:00
Hi @mrtnzlml, thanks for the detailed report!

The change you're seeing in v0.147 is that Flow complains loudly about this code, but the observable type checking behavior is unchanged. In v0.146 and earlier, the `%checks` is silently ignored.

Based on the reproduction case you shared, my suggestion is to simply delete the `%checks` part of your code. My understanding is that `%checks` doesn't have any effect on this code, but I might be missing something. The `%checks` predicate will encode certain tests, like `typeof filename === "string"`, but doesn't support all possible predicates.

That aside, the error message should be more helpful. I will see if I can improve the error message to indicate that the returned expression is not supported with `%checks`, instead of just saying "can't determine type."

Let me know if this helps. Thanks!

**Comment by mrtnzlml** [comment] 2021-03-19 20:11
Thanks @samwgoldman for your advice! I removed the `%checks` in our code and looking forward to see the improved error message. 👍

**Comment by SamChou19815** [comment] 2023-09-26 11:55
Closing since it's an issue about %checks. We now recommend type guards which do not have the issue.

**Closed by SamChou19815** 2023-09-26 11:55 UTC
Labels: bug, error messages
