### ISSUE TITLE
Check only specified files for Flow errors

### ISSUE THREAD

**Issue by yantakus** [facebook/flow#4679] opened 2017-08-22 12:02 UTC
Is there a way to check only specified files for Flow errors?

`flow file1.js file2.js` checks all the annotated files in the project.

This would be very helpful for adding a pre-commit hook that checks staged files for Flow errors before committing.

**Comment by asolove** [comment] 2017-08-22 14:17
I'm not sure if this is possible. For Flow to type one file, it needs to also type all the files that that file imports from, and if you keep following those dependencies, it ends up needing to do a lot. 

I'm curious about the use-case for staged files. Would you ever want to commit when in a state where the staged files are safe (assuming this could be defined), but there are type errors in files they rely on?

**Comment by goodmind** [comment] 2019-06-22 20:00
Duplicate of  #4189

**Comment by goodmind** [comment] 2019-06-22 20:00
Duplicate of #4189

**Closed by goodmind** 2019-06-22 20:00 UTC
