### ISSUE TITLE
Modeling ImmutableJS' Record type

### ISSUE THREAD

**Issue by farnoy** [facebook/flow#2062] opened 2016-07-09 17:55 UTC
Hi, I was wondering if it's possible to model ImmutableJS' Record type.

[docs](https://facebook.github.io/immutable-js/docs/#/Record)

For now, it's modelled like [this](https://github.com/facebook/immutable-js/blob/master/type-definitions/immutable.js.flow#L622-L629):

``` js
//TODO: Once flow can extend normal Objects we can change this back to actually reflect Record behavior.
// For now fallback to any to not break existing Code
declare class Record<T: Object> {
  static <T: Object>(spec: T, name?: string): /*T & Record<T>*/any;
  get<A>(key: $Keys<T>): A;
  set<A>(key: $Keys<T>, value: A): /*T & Record<T>*/this;
  remove(key: $Keys<T>): /*T & Record<T>*/this;
}
```

I wanted to replace my Maps, which have to be homogeneous, with Records, but I see no type safety will be gained right now. `$Keys<T>` doesn't seem to be doing anything - I can still call `get()` with keys not present in `T`.

Is there anything in the works to support this?

**Comment by jpolo** [comment] 2016-10-11 09:51
Here is a Gist explaining what workarounds can be tried and their caveats : https://gist.github.com/jpolo/b2555698d2f908c5cd448b40aaa400b5 #

Using flow v0.33.0,  it is possible to create a class factory (like ```RecordClass``` in the Gist) but :
* Type safety is lost when extending this class (i.e. errors like non existing properties are not reported)
* Error message when using instance of these class can be hard to understand

A suggestion of solution : maybe if flow provided a special type operator like ```$ClassOf<Member, Static, SuperClass>``` that could return a _real_ polymorphic type, developers would be able to create class factory functions and High Order Components easier than now.

**Comment by jpolo** [comment] 2016-11-10 10:44
The ```RecordClass``` pattern creates a massive performance issue that breaks the build on our project. (still version 0.33.0) .
A fix would very helpful

**Comment by calebmer** [comment] 2017-07-31 15:20
Closing since this issue hasn’t seen a lot of activity. Sorry about that 😣

Please reopen with a reproduction on https://flow.org/try if you are still having issues!

**Closed by calebmer** 2017-07-31 15:20 UTC
