### ISSUE TITLE
Flow Incorrectly handles polymorphic function annotations

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#1317] opened 2016-01-26 19:11 UTC
According to the documentation flow allows you to annotate variables with types, but that does not work work if types represent polymorphic functions. Consider following example:

```js
/* @flow */

type Map = <a, b>
  (f:(a:a) => b, a:Array<a>) =>
  Array<b>

export const map:Map =
  (f, xs) => xs.map(x => f(x)
```

This produces following invalid errors:

```
scratch.js:3
  3: type Map = <a, b>
                 ^ a. This type is incompatible with
  8:   (f, xs) => xs.map(x => f(x))
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ some incompatible instantiation of `a`

scratch.js:8
  8:   (f, xs) => xs.map(x => f(x))
                  ^^^^^^^^^^^^^^^^^ call of method `map`
  3: type Map = <a, b>
                    ^ b. This type is incompatible with
  8:   (f, xs) => xs.map(x => f(x))
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ some incompatible instantiation of `b`

scratch.js:8
  8:   (f, xs) => xs.map(x => f(x))
                  ^^^^^^^^^^^^^^^^^ call of method `map`
  8:   (f, xs) => xs.map(x => f(x))
                              ^^^^ b. This type is incompatible with
  8:   (f, xs) => xs.map(x => f(x))
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ some incompatible instantiation of `b`


Found 3 errors
```

Please note that inlining type annotations to the `map` implementation works as expected, although in more complex code it is often less practical.

**Comment by gabelevi** [comment] 2016-01-26 19:20
Does this work if you do

```JavaScript
export const map:Map =
   <a,b>(f:(a:a) => b, xs:Array<a>):Array<b> => xs.map(x => f(x)
```

?  Flow doesn't infer polymorphism at the moment, so I'm wondering if maybe it's inferring a monomorphic function and erroring it when you try to cast it to a polymorphic function.

**Comment by Gozala** [comment] 2016-01-26 19:24
> Does this work if you do

> ```js
export const map:Map =
   <a,b>(f:(a:a) => b, xs:Array<a>):Array<b> => xs.map(x => f(x)
```
@gabelevi It does; that's what I meant with inlining type annotations

> Flow doesn't infer polymorphism at the moment, so I'm wondering if maybe it's inferring a monomorphic function and erroring it when you try to cast it to a polymorphic function.

Sorry that's little over my head :) But I think that's what happening.

But does Flow even needs to infer here if I do explicitly provide a type ?

**Comment by samwgoldman** [comment] 2016-01-27 05:50
This is a dupe of your own issue! #1046.

**Closed by samwgoldman** 2016-01-27 05:50 UTC
