### ISSUE TITLE
inconsistent nullness checks

### ISSUE THREAD

**Issue by savvopoulos** [facebook/flow#1214] opened 2015-12-26 21:25 UTC
This code:
```javascript
    if (this.curMutation) {
      this.curMutation.start(this.state, this.store.getState());
    }
```

gives:
```
sheet-updater.js:186
186:       this.curMutation.start(this.state, this.store.getState());
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `start`. Method cannot be called on possibly null value
186:       this.curMutation.start(this.state, this.store.getState());
           ^^^^^^^^^^^^^^^^ null
```

whereas this works:
```javascript
    if (this.curMutation) {
      var m: Mutation = this.curMutation;
      m.start(this.state, this.store.getState());
    }
```

Is that expected?

**Comment by savvopoulos** [comment] 2015-12-26 22:26
Would be nice to understand these:

```javascript
    if (this.clock && this.fetchStart) {
      this.fetchLatency.push(this.clock.now() - this.fetchStart);
      this.fetchStart = null;
    }
```

gives:
```
$ flow
sheet-updater.js:254
254:       this.fetchLatency.push(this.clock.now() - this.fetchStart);
                                                     ^^^^^^^^^^^^^^^ null. This type is incompatible with
254:       this.fetchLatency.push(this.clock.now() - this.fetchStart);
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ number

sheet-updater.js:254
254:       this.fetchLatency.push(this.clock.now() - this.fetchStart);
                                                     ^^^^^^^^^^^^^^^ undefined. This type is incompatible with
254:       this.fetchLatency.push(this.clock.now() - this.fetchStart);
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ number


Found 2 errors
```

**Comment by savvopoulos** [comment] 2015-12-26 22:27
PS: likewise this fixes the error:
```javascript
    if (this.clock && this.fetchStart) {
      var wtf: Date = this.fetchStart;
      this.fetchLatency.push(this.clock.now() - wtf);
      this.fetchStart = null;
    }
```

**Comment by mroch** [comment] 2015-12-29 02:11
yeah, this is probably flow's most surprising behavior. it's discussed [here](http://flowtype.org/docs/dynamic-type-tests.html#caveats), and the problem is that the function calls like `this.store.getState()` might mutate `this`, which could cause `this.curMutation` to be falsy again. assigning to a local variable ensures that even if `this` changes, the local variable didn't.

**Closed by mroch** 2015-12-29 02:11 UTC
