### ISSUE TITLE
How to declare a variable/return value to be polymorphic?

### ISSUE THREAD

**Issue by TiddoLangerak** [facebook/flow#5022] opened 2017-10-03 10:59 UTC
Suppose I have a polymorphic type like this:

```js
type Identity<T> = T => T
```

I want to use this type to declare a variable or return type as the polymorphic version of `Identity`. E.g.:

```js
const id : Identity = x => x;
```

The above however gives an error: `Application of polymorphic type needs <list of 1 argument>. (Can use `*` for inferrable ones)`.

Trying to apply the polymorphic type doesn't give the desired result:

```js
const id : <T>Identity<T> = x => x; //doesn't compile
const id : Identity<*> = x => x; //compiles, but then the resulting function isn't generic:
var x : string = id('asdf');
var y : number = id(3);
/*
 4: var x : string = id('asdf');
                    ^ number. This type is incompatible with
4: var x : string = id('asdf');
           ^ string
5: var y : number = id(3);
                    ^ string. This type is incompatible with
5: var y : number = id(3);
           ^ number
*/
```

How am I supposed to type this? Or is it impossible to declare a variable to be of a polymorphic type?

**Comment by TiddoLangerak** [comment] 2017-10-03 11:53
```js
type Identity = <T>(T) => T;
    
const id : Identity = x => x;
```

gives

```
3: const id : Identity = x => x;
                         ^ function. This type is incompatible with
1: type Identity = <T>(T) => T;
                   ^ function type
This parameter is incompatible:
3: const id : Identity = x => x;
                              ^ T. This type is incompatible with
3: const id : Identity = x => x;
                         ^ some incompatible instantiation of `T`
```

Even explicitly typing `id` doesn't work:

```js
const id : Identity = <T>(x : T) => x;
```

**Comment by madbence** [comment] 2017-10-03 11:53
in this case: https://flow.org/try/#0C4TwDgpgBAkgJlAvFAPAFQHwAo0EokZRoDcAUAMYD2AdgM7BQCWcAXLAsutgB5t58Eo3MqSzMsARlxtqAVwC2AIwgAnXGTFwsAcgBmlStulR6KxtQDm6oA

```js
type Id = <T>(T) => T;
const id: Id = <T>(x: T): T => x;

(id(1): number);
(id('foo'): string);
```

**Comment by TiddoLangerak** [comment] 2017-10-03 11:58
Ahh, the addition of @madbence seems to work. However, this doesn't quite cover the entire story yet: this only works if you have full control over the `Id` type. How would you do this if the `Id` type is already provided? (In my case, I'm dealing with a polymorphic `React$ComponentType`, which I'd rather not re-type myself).

**Comment by AriaMinaei** [comment] 2017-10-03 12:21
This might help: https://github.com/facebook/flow/issues/4644#issuecomment-324252464

**Comment by marcianx** [comment] 2017-10-15 05:00
I'm seeing the same error here:
https://flow.org/try/#0MYewdgzgLgBAJgUwGYBsoEYYF4ZIK5jBQCW4APACoB8AFBAlCWAOYBcMFMAPjAG4jE4AGnjIAhnjQBJJAFUwiJMTAI47CgEp2AKhgBvAFAxjMAE4M8psDHqNlzbFhwFFy1TAD8opBOlyFyG5wMOy2TMwA3AYAvlGgkLCKaABM2LgERKRglLRh9urcfALC3r5QMvKuKmocWhz6RibmUJbWeSyOzgFK1Z6lkuX+Ve6hDOFRsQYG8dAwxBAAQmKm6OwARiAgKAhi1jhJGDQugdUiPij0GnHgs-NLpsnrm9u7aQfJR91BZ2IXCFcGIA

```javascript
// This one returns `*` to work around this bug in the compiler.
const deflt1 = function<T>(setting: T | void, defaultIfUndefined: T): * {
    return setting === undefined ? defaultIfUndefined : setting;
};
const deflt2 = function<T>(setting: T | void, defaultIfUndefined: T): T {
    return setting === undefined ? defaultIfUndefined : setting;
};

const isBar1: boolean = deflt1(undefined, false); // Happy here.
const isBar2: boolean = deflt2(undefined, false); // Same error as OP here.
```

**Comment by jcready** [comment] 2017-10-15 15:58
This seems to work:

```js
type Id<T> = <T: *>(T) => T;
const id: Id<*> = (x) => x;

(id(1): number);
(id('foo'): string);
    
// $ExpectError
(id(null): string); // error
```

The type-at-pos doesn't seem to return anything, but the types are still checked correctly.

**Comment by TiddoLangerak** [comment] 2017-10-16 05:41
@jcready Your still relies on the author being able to change the definition of `Id` (i.e. without the `<T: *>` it doesn't work). That doesn't work for the general case, since in a real-world codebase many types are imported from 3rd parties. I'm looking for a solution that works with any polymorphic type, regardless of it's implementation. 

The main problem seems to be that you can only declare functions to be polymorphic, but not arbitrary types. e.g, `<T>(T) => T` is allowed, but not `<T>MyType<T>` (even if `MyType` itself is a function type).

**Comment by SamChou19815** [comment] 2023-07-14 02:06
Duplicate of #5022

**Comment by SamChou19815** [comment] 2024-08-11 22:46
Closing since not every type can be polymorphic. For component types, we recently introduced component type (https://flow.org/en/docs/react/component-types/) which can be polymorphic.

**Closed by SamChou19815** 2024-08-11 22:46 UTC
Labels: Typing: polymorphism, Typing: functions
