### ISSUE TITLE
Show call site for function argument type mismatch

### ISSUE THREAD

**Issue by acruis** [facebook/flow#2685] opened 2016-10-26 11:13 UTC
Currently, if we define a function to have an object type as an argument, then we have to pass an object with the exact props as defined by the argument type definition (from #1657). Otherwise we get this error:

![image](https://cloud.githubusercontent.com/assets/8437638/19723805/b5d83f9c-9b85-11e6-8465-a6c3b37af620.png)

If we pass `text={null}` as a prop to `SampleView` when we declare `WrapperView`, the error goes away. However, the error message from Flow doesn't contain information about _where_ this prop was wrongly passed from (the function signature is underlined, instead of the `<SampleView />` line). This can be confusing, especially if `WrapperView` is placed in a different file from `SampleView`.

Is it possible to have an indicator of where the malformed argument was passed from in the error message? Or maybe relocate it to highlight the call site, instead of the method signature?

**Comment by pelotom** [comment] 2016-10-27 04:07
This looks like a duplicate of #2557 / #2587

**Closed** 2023-02-22 23:04 UTC
Labels: error messages
