### ISSUE TITLE
Apply method is missing on Array and Object 

### ISSUE THREAD

**Issue by akaRem** [facebook/flow#3805] opened 2017-04-24 20:19 UTC
Given:
``` js
/* @flow */

Array.apply
Object.apply
```

Output:
```
3: Array.apply
         ^ property `apply`. Property not found in
3: Array.apply
   ^ statics of Array
4: Object.apply
          ^ property `apply`. Property not found in
4: Object.apply
   ^ statics of Object
```

**Comment by vkurchatkin** [comment] 2017-04-24 20:25
Duplicate of https://github.com/facebook/flow/issues/1561

**Closed by vkurchatkin** 2017-04-24 20:25 UTC
