### ISSUE TITLE
false positive bug

### ISSUE THREAD

**Issue by kentcdodds** [facebook/flow#5135] opened 2017-10-18 21:35 UTC
Hi there! I'm still so new at Flow that I honestly have no idea how to describe this bug, but [here's a reproduction](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCiMeAtngHYZgC8YA3gL4DcmuBAInAMYCu5VWgwDmeDMTKUMAISwBJACYAKAM4YATgEsKwgJQAuIiQHUAPmAq8YMFugV5uMAIbqCANxdgFPflMNc+E1Y2fDA5Ck0MAHkcDE04ChUhelQwMHIVFSdRFQA5OHsAfkMJEzBzNzhNBVRGdCheCm44hLBtSKUUtIysnPz7IW9AqQA6UXFjKVlFJQByVydmgFoe7LwVWd1aw3DImJbE3QZUsGBgMAAjZwALS5uT1wxedQp09d71-rxa+sbm+NeCDg6gA1tphLsMEo4LEASodhForCEiojl0wNwUdR0d13ms8gUCHQhr4qGMxKUpvJlPM8IsMCs8TlNidGEIYQcVCczncnLcrnyHmJnq9Vn1CT8gA)

```javascript
/* @flow */

type Element = {};
type Document = {getElementById(string): Element | null};

declare var document: Document;

type InitOptions = {
  messagesNode?: Element | void
}

function init({
  messagesNode = document.getElementById('react-messages')
}: InitOptions) {
  // blah blah
  return messagesNode
}

function workingInit(options: InitOptions) {
  const {
    messagesNode = document.getElementById('react-messages')
  } = options
  // blah blah
  return messagesNode
}
```

For some reason, moving the destructuring from the param list to the function body works. I'm pretty sure that this is a bug. Or I'm just doing something dumb 🤷‍♂️ 

Thanks!

**Comment by kentcdodds** [comment] 2017-10-18 21:36
Ah, looks like this might be related: https://github.com/facebook/flow/issues/183

Feel free to close if you'd like

**Comment by Jacse** [comment] 2017-10-22 14:40
This is definitely a complete duplicate of #183 so I think you should close this issue and we'll focus our efforts on the original one.

**Closed** 2017-10-22 14:54 UTC
