### ISSUE TITLE
Fails to parse `("a")`

### ISSUE THREAD

**Issue by lydell** [facebook/flow#3242] opened 2017-01-22 20:59 UTC
```
~/bugs/flow-parens-string-bug  
❯ node --version
v7.2.0

~/bugs/flow-parens-string-bug  
❯ npm i flow-parser
/home/lydell/bugs/flow-parens-string-bug
└─┬ flow-parser@0.38.0 
  ├── ast-types@0.8.18 
  ├── colors@1.1.2 
  └── minimist@1.2.0 


~/bugs/flow-parens-string-bug  
❯ node
> try { require('flow-parser').parse('("a")') } catch (e) { console.log('err', e) }
err [ 0,
  [ 248, aw { t: 0, c: 'Failure', l: 7 }, -3 ],
  aw { t: 0, c: 'Nooo: T_LPAREN\n', l: 15 } ]
undefined
> 
```

Expectations:

- No error to be thrown. (And if one were to be thrown, I'd expect a real
  `Error` to be thrown, not an `Array`.)
- An AST to be returned.

The non-JS version of the parser seems to have the same problem:

```
~/bugs/flow-parens-string-bug  
❯ npm i flow-bin
/home/lydell/bugs/flow-parens-string-bug
└── flow-bin@0.38.0 


~/bugs/flow-parens-string-bug  
❯ echo '("a")' | flow ast --pretty
Unhandled exception: Failure("Nooo: T_LPAREN\n")
```

**Comment by vkurchatkin** [comment] 2017-01-22 21:46
Duplicate of https://github.com/facebook/flow/issues/3234

**Closed by vkurchatkin** 2017-01-22 21:46 UTC
