### ISSUE TITLE
Incorrect behavior since flow-bin 0.43.0

### ISSUE THREAD

**Issue by danwang** [facebook/flow#3902] opened 2017-05-08 17:26 UTC
Sorry for the vague title; I couldn't think of a short way to explain it.

Since version 0.43.0, Flow fails to report type errors when dealing with types exported across multiple files.

I made a small example that reproduces the error: https://github.com/danwang/flow-example

I've also reproduced the contents of the files here.

## a.jsx
```
(a.jsx)
// @flow
export type InternallyConsistent<A, B> = {
  oneway: (A) => B,
  anotherway: (B) => A,
};

type MapOf<T> = {[string]: T};
type AcceptsIC = <C: MapOf<InternallyConsistent<*, *>>>(config: C) => mixed;

const acceptsIC: AcceptsIC = (null: any);

export default acceptsIC;
```

This defines a type `InternallyConsistent` type that is the product of `A => B` and `B => A`. I expect the type declaration to only allow objects with matching types (e.g., `A => B` and `B => C` where `C != A` should be invalid).

The `AcceptsIC` type is an alias for a function that takes in an object whose values are all `InternallyConsistent`. I've exported a variable of this type as the default export.

## b.jsx
```
(b.jsx)

// @flow
import acceptsIC from './a.jsx';
import type {InternallyConsistent} from './a.jsx';

const foo: InternallyConsistent<*, *, *> = {
  oneway: (s: string) => 'WRONG',
  anotherway: (n: number) => 's',
};

acceptsIC({
  foo,
});
```

`foo` is declared as an `InternallyConsistent` when it's not (`oneway` is `string => string` and `anotherway` is `number => string`, which doesn't match). When using flow-bin versions 0.43.0+, **any of** the following allow Flow to report the error correctly:
- removing the last three lines (invocation of `acceptsIC`)
- moving the contents of `b.jsx` into `a.jsx`

**Comment by mosesoak** [comment] 2017-05-09 21:08
See #3522 ...?

**Comment by goodmind** [comment] 2019-05-30 20:24
Duplicate of #6587 3522

**Closed by goodmind** 2019-05-30 20:24 UTC
