### ISSUE TITLE
SyntheticInputEvent incompatible with HTMLTextAreaElement

### ISSUE THREAD

**Issue by ryami333** [facebook/flow#6390] opened 2018-05-31 02:57 UTC
If I try and attach an `onChange` handler to a textarea then I get an error message that seems to indicate that SyntheticInputEvent only caters for `HTMLInputElement`s.

The following:
```jsx
import React, { Component } from 'react';

class Foo extends Component {
  onChange = (e: SyntheticInputEvent<HTMLTextAreaElement>) => {
    if (e.target instanceof HTMLTextAreaElement) {
      // do things
    }
  }

  render() {
    return (
      <textarea onChange={this.onChange} />
    );
  }
}
```
Gives:
```
`HTMLTextAreaElement` (see https://github.com/facebook/flow/blob/v0.72.0/lib/dom.js#L2979) is incompatible with `HTMLInputElement`
```

**Comment by EnoahNetzach** [comment] 2018-05-31 15:03
Looks all right and working to me, the only missing piece is the missing type parameter to the `Component` generic (i.e. `Component<{}>`)

You can see it on [try flow](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQduANmugGIQRxYAeMWAOwAm6bHhgA6AMIlIAwTAA8AbwC+APjjK6cOBAFSAFsgEBzLHAC8cABRYAXHADKATwExDWGMFwBJAWAArjAAogBuCooAEgAqALIAMjG8MACClMghTFggCuoAlFaa2rq6wAS2WBIwyFDm8MACqDUCuFgQFbGJyXzpOFk5CoUlpboA9GNwQlwejaaoOqWqi8uLlMJYUDbDi7qUMIFQAra7pYr8fLU4egbGZliWyrOoEvpGJuaqcGPqp-n0umWqiAA), but you'll have to change the version to 0.54.1

Unfortunately try flow hasn't any libs loaded since 0.54.1, but another "hacky" method I sometime use is with runkit, and there it works ([try](https://runkit.com/enoahnetzach/5b100d3b83371a0013770c2e)) with version 0.73 too.

**Comment by ryami333** [comment] 2018-05-31 21:32
No the missing type parameter is not relevant - this is pseudocode. The actual implementation I'm having problems with has the component type parameter. I can update it and try on 0.73 if you'd like - but are you aware of any relevant fixes that went into that release?

**Comment by EnoahNetzach** [comment] 2018-06-03 15:10
It would work at least since 0.54.1, haven't tried on older versions (on try flow).

I'm not aware of any resolving fix prior to that version, or any bugged version between 0.54.1 and 0.73.

Is that the entire snippet of (pseudo) code you have?

**Comment by mrkev** [comment] 2018-06-06 05:49
Woah interesting hack runkit hack @EnoahNetzach.

@ryami333, I think what @EnoahNetzach means is your bug doesn't seem to be reproducible with flow versions above 0.54.1 using that snipped your provided

**Comment by Brianzchen** [comment] 2020-09-01 11:33
Gonna close, this is an old issue with older syntax. If anyone is interested something that works in current 0.132.0 would be
```
class Foo extends React.Component<{| |}> {
  onChange = (e: SyntheticEvent<HTMLTextAreaElement>) => {
    if (e.target instanceof HTMLTextAreaElement) {
      // do things
    }
  }

  render() {
    return (
      <textarea onChange={this.onChange} />
    );
  }
}
```

**Closed by Brianzchen** 2020-09-01 11:33 UTC
Labels: Library definitions
