### ISSUE TITLE
Refinements do not work with destructuring

### ISSUE THREAD

**Issue by echenley** [facebook/flow#3918] opened 2017-05-10 17:26 UTC
```js
type LoadingProps = { isLoading: true, item: null }
type LoadedProps = { isLoading: false, item: { id: string } }
type Props = LoadingProps | LoadedProps

const Works = (props: Props) => {
  return props.isLoading ? null : props.item.id
}

const DoesNotWork = ({ isLoading, item }: Props) => {
  return isLoading ? null : item.id
}
```

https://flow.org/try/#0C4TwDgpgBAMg9gQwCYEsB2BzACgJzmAZygF4oBvKFA+ZdDALimBwFcIAaJlAYwGsJgjNCwA2IqAF8AUKEixESCElz4ipClRqpMjAGYIRBDlz4DGGpIwLM6kyTPDQVhEvNqZnRAD5vFyvIRSUtxwaNZQAOpwOLxqUAAUYAEEjJ4AlCQAfORSUFA4Aiw4aFBJqgB0mgq2APxQwmJQjGWE5cA8-MCVSFLSwaHhACJwEAQAcnDAUTGu8RrU1Zic7abAkqnJGcTZZLn5hcWUC+4YUHUN4owrnd29UkA

**Comment by jfirebaugh** [comment] 2017-11-08 22:53
This is the same issue as #3932, #5212, and other dupes.

**Comment by goodmind** [comment] 2019-05-30 09:16
Duplicate of #3932

**Closed by goodmind** 2019-05-30 09:16 UTC
