### ISSUE TITLE
Dynamic type test is applied only to the first object property instance

### ISSUE THREAD

**Issue by dunnock** [facebook/flow#2940] opened 2016-12-03 20:14 UTC
Hi,

It seems flow forgets about dynamic type test after first usage of nested object construct.
```
type Props = { sigma?: mixed };
class My extends Component { 
  props: Props;
  ...
  if(this.props.sigma) {
    this.props.sigma.settings({drawEdges:true})
    this.props.sigma.refresh()
  }
```

raises error on the second line ( this.props.sigma.refresh() )
```
src/ForceAtlas2.js:76
 76: 				this.props.sigma.refresh();
     				^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `refresh`. Method cannot be called on possibly undefined value
 76: 				this.props.sigma.refresh();
     				^^^^^^^^^^^^^^^^ undefined
```

There is no such issue when type checking flat variable, e.g.

```
  let sigma = this.props.sigma
  if(sigma) {
    sigma.settings({drawEdges:true})
    sigma.refresh()
  }
```

**Comment by gcanti** [comment] 2016-12-04 07:18
[Flow is pessimistic about refinements](https://flowtype.org/docs/dynamic-type-tests.html#caveats)

Dupe of

- https://github.com/facebook/flow/issues/2895
- https://github.com/facebook/flow/issues/2877
- https://github.com/facebook/flow/issues/2836
- https://github.com/facebook/flow/issues/2831
- https://github.com/facebook/flow/issues/2768
- https://github.com/facebook/flow/issues/2704
- https://github.com/facebook/flow/issues/2693
- https://github.com/facebook/flow/issues/2602
- https://github.com/facebook/flow/issues/2513
- https://github.com/facebook/flow/issues/2318

**Closed** 2016-12-04 09:16 UTC
