### ISSUE TITLE
Disjoint unions: narrowed type for discriminator value not present in type is any

### ISSUE THREAD

**Issue by mbergal** [facebook/flow#1792] opened 2016-05-15 15:42 UTC
This produces no errors, but I'd expect something like 
property 'message' is not found in object type 

```
/* @flow  */

type Matrix = number[][]; // type of input and output for our function

type Result = Done | Error; // a disjoint union type with two cases
type Done = { status: 'done', answer: Matrix };
type Error = { status: 'error', message: string };

function invert(matrix: Matrix, callback: (result: Result) => void) : Result {
  return { status: 'done', answer: [ [1] ] };
}

function showInverseOf(matrix: Matrix) {
  invert(matrix, result => {
    switch (result.status) {
    case 'error':
      console.log ("Uh oh!", result.message);
      break;  // see what happens if you forget to break! :)
    case 'done':
      console.log ("Inverse:", result.answer);
      break;  // see what happens if you forget to break! :)
    // This should not happen but might if I renamed  discriminator in type
    // and didn't change it everywhere
    case 'erro': 
      console.log ("I'm an error!:", result.message); // <----- expect error here
      console.log ("I'm an answer:", result.answer); // <----- expect error here
      console.log ("I'm everything:", result.everything() ); // <----- expect error here
    default:
      console.log ("I'm an error!:", result.message); // <----- expect error here
      console.log ("I'm an answer:", result.answer); // <----- expect error here
      console.log ("I'm everything:", result.everything ); // <----- expect error here
    }
  });
}
```

**Comment by calebmer** [comment] 2017-07-26 22:09
Closing since this issue hasn’t seen a lot of activity. Sorry about that 😣

Please reopen with a reproduction on https://flow.org/try if you are still having issues!

**Closed by calebmer** 2017-07-26 22:09 UTC
