### ISSUE TITLE
Error trigger when it should not ?

### ISSUE THREAD

**Issue by Brakkar** [facebook/flow#1884] opened 2016-06-02 09:49 UTC
Hi,
can you please confirm if this is a bug or a problem with my code:

```
export let validationResult = function (fields:Object):IErrorReturn {
    // Create a model instance
    let directoryModel:IDirectoryLink = new DirectoryModel(fields)

    // Make sure all public field entered by user are valid
    let validationErrors = ValidationErrors(directoryModel)

    // If there are no validation errors returned...
    if (validationErrors === g.error.no) {
        // Return to the controller to inform the form is valid with no error
        return {
            error: g.error.no,
            model: directoryModel, // ERROR HERE
            errorBag: g.IsEmpty.empty
        }
    } else {
        // Return to the controller to inform there are errors and which are they
        return {
            error: g.error.yes,
            model: g.IsEmpty.empty,
            errorBag: validationErrors
        }

    }
}
```

and here are the interfaces:

```
declare type IDirectoryLink =
{
    link_title: string,
    link_desc: string,
    link_long_desc: string,
    link_url: string,
    link_note: string,
}


declare interface IErrorReturn {
    error: number,
    model: IDirectoryLink | string,
    errorBag: ([string, string] | number)[] | number  | string
}

in another, global file:
export let IsEmpty =
{
    empty: "empty",
    notEmpty: "notEmpty"
}
```

As you see IErrorReturn model accepts either an IDirectoryLink or a string. Yet when I pass it a directoryModel object which is of type IDirectoryLink it triggers this error:

195:             model: directoryModel,
................................^^^^^^^^^^^^^^ object type. This type is incompatible with
 21:     model: IDirectoryLink | string,
...............................................^^^^^^ string. See lib: interfaces.js:21

I don't understand why it compares directoryModel against string, since string is not enforced and there is the good corresponding IDirectoryLink interface option.

**Comment by calebmer** [comment] 2017-07-27 15:14
Closing since this issue hasn’t seen a lot of activity. Sorry about that 😣

Please reopen with a reproduction on https://flow.org/try if you are still having issues!

**Closed by calebmer** 2017-07-27 15:14 UTC
