### ISSUE TITLE
Consider babel plugin transformations

### ISSUE THREAD

**Issue by freddi301** [facebook/flow#5697] opened 2018-01-22 14:58 UTC
If a babel-plugin transforms code, type check the output of that plugin instead of original source.

example: [babel-plugin-transform-js-macros](https://github.com/freddi301/babel-plugin-transform-js-macros)

**Comment by apsavin** [comment] 2018-01-22 15:56
See #1515

**Comment by goodmind** [comment] 2019-06-21 22:45
Duplicate of #1515

**Closed by goodmind** 2019-06-21 22:45 UTC
