### ISSUE TITLE
$PropertyType doesn't type check literal values

### ISSUE THREAD

**Issue by imranolas** [facebook/flow#3606] opened 2017-03-29 09:52 UTC
```js
/* @flow */

type Action = {
 type: 'App/INIT'
};

// number. This type is incompatible with string literal `App/INIT`
const actionTypeA: $PropertyType<Action, 'type'> = 1;

// No error
const actionTypeB: $PropertyType<Action, 'type'> = 'FOO';
```

**Expected**: `actionTypeB` should fail its type check.

**Comment by gabro** [comment] 2017-03-29 12:24
Looks like a dupe of https://github.com/facebook/flow/issues/3374

**Closed** 2017-03-29 12:33 UTC
