### ISSUE TITLE
Type refinement is forgotten after setTimeout

### ISSUE THREAD

**Issue by whmountains** [facebook/flow#5016] opened 2017-10-02 19:51 UTC
https://flow.org/try/#0MYewdgzgLgBANiA5jAvDAFANwFw2gJwEsxkAfGAQX3wEMBPAHgOMQD4BKVVmAbwCgYMQgDMMUOgAcApiFGZUKNAHJmJJZ36DB8tAG1MAXQEwAvseMQpUACqEAtjICuUdOk4puoSCDhSAdAiIWH4AViDE6EoANOrs7HxmfIHoAERQUtAp7EA

```js
const log = (v: string | Array<string>) => {
  if (typeof v === 'string') {
    v = [v]
  }
  
  setTimeout(() => console.log(v.join(',')))
}

log("test")
```

**Comment by Naddiseo** [comment] 2017-11-24 16:38
Possibly a duplicate of #4941 ?

**Comment by goodmind** [comment] 2019-05-30 09:26
Duplicate of #4941

**Closed by goodmind** 2019-05-30 09:26 UTC
