### ISSUE TITLE
External library is not correctly typechecked

### ISSUE THREAD

**Issue by runn1ng** [facebook/flow#1410] opened 2016-02-15 23:40 UTC
We have a problem with typechecking external libraries. It just either doesn't show errors even when it should (so effectively doens't typecheck at all), or shows annoying errors at the top of each file.

I have made a simple reproduction code here, in this repo.
https://github.com/runn1ng/flow_ext_library_example

I want to use `bitcoinjs-lib` library - [this is my (purposely very short) example interface file](https://github.com/runn1ng/flow_ext_library_example/blob/with_include/types/bitcoin.js):
`````
declare module 'bitcoinjs-lib' {
    declare var address: {
        fromBase58Check(address: string): {hash: Buffer, version: number};
    }
}
````

[This is my code. You can see that both line 3 and 4 should not typecheck - I am using mistakenly Buffer where I should use an object, and I am using `Address` instead of `address` by mistake](https://github.com/runn1ng/flow_ext_library_example/blob/with_include/src/index.js):
`````
/* @flow */
import * as bitcoin from 'bitcoinjs-lib';
const foo: Buffer = bitcoin.address.fromBase58Check("1CrwjoKxvdbAnPcGzYjpvZ4no4S71neKXT");
const bar = bitcoin.Address.fromBase58Check("1CrwjoKxvdbAnPcGzYjpvZ4no4S71neKXT");
```````

[Now if I add bitcoinjs-lib to the `include` section, like this](https://github.com/runn1ng/flow_ext_library_example/blob/with_include/src/.flowconfig):
`````
[ignore]

[include]
../node_modules/bitcoinjs-lib

[libs]
../types/bitcoin.js

[options]
`````

flow does not warn me at all about the errors when I run `flow check`. It should! I just added the interface file!

[If I remove the folder from `include` section, like this](https://github.com/runn1ng/flow_ext_library_example/blob/without_include/src/.flowconfig):
`````
[ignore]

[include]

[libs]
../types/bitcoin.js

[options]
`````


`flow check` finally gives me all the errors (which is good), but it also gives me a giant warning:
`````
index.js:2
2: import * as bitcoin from 'bitcoinjs-lib';
                            ^^^^^^^^^^^^^^^ This modules resolves to "<<PROJECT_ROOT>>/../node_modules/bitcoinjs-lib/package.json", which is outside both your root directory and all of the entries in the [includes] section of your .flowconfig. You should either add this directory to the [includes] section of your .flowconfig, move your .flowconfig file higher in the project directory tree, or move this package under your Flow root directory.
`````
...which appears every time I import from 'bitcoinjs-lib'.

The repo is set in a way you can just clone it, go to `src` on both branches - `with_include` and `without_include` - and run `flow check`.

Now what should I do so that the code, using the third-party library, is **actually checked against the interface file**, but that I also don't see the big warnings on `import` everywhere?

**Comment by runn1ng** [comment] 2016-02-15 23:42
(I am running latest Flow from master)

**Comment by runn1ng** [comment] 2016-02-16 00:33
I am looking into tests if I con't see a correct example how to correctly use interface files, but there doesn't seem to be a test for that

**Comment by runn1ng** [comment] 2016-02-16 00:45
OK, I have discovered *one weird trick* to make it work.

I have to *simultaneously* add the files into `[include]` and `[ignore]` section. [Like here.](https://github.com/runn1ng/flow_ext_library_example/blob/include_and_ignore/src/.flowconfig)

Which is, of course, anti-intuitive and feels like it's not correct, but at least it's doing what it should be doing.

**Comment by runn1ng** [comment] 2016-02-16 11:50
I feel like it can be related to #1392 but I am not sure

**Comment by avikchaudhuri** [comment] 2016-02-16 22:48
Might also be related to #1401

**Comment by AgentME** [comment] 2016-02-19 00:01
You don't have to list the directory under `[include]`. The `[ignore]` and `[libs]` lines are what fixes it.

This issue is a duplicate of https://github.com/facebook/flow/issues/676.

**Comment by runn1ng** [comment] 2016-02-19 00:13
Yep, you are right! Should I close this?

**Comment by AgentME** [comment] 2016-02-19 06:32
Sure. Looks like the issue was just fixed in master even.

**Closed** 2016-06-23 13:04 UTC
Labels: module resolution
