### ISSUE TITLE
Object.defineProperty() getters do not typecheck

### ISSUE THREAD

**Issue by mbrowne** [facebook/flow#1336] opened 2016-01-29 03:48 UTC
This code does not typecheck:

```
/* @flow */

Object.defineProperty({}, 'foo', {
    get: function(): string {
        return '';
    }
});
```

I get the following error:

```
test.js:3
  3:    Object.defineProperty({}, 'foo', {
        ^ Object.defineProperty. Property not found in
  3:    Object.defineProperty({}, 'foo', {
                                         ^ object literal


Found 2 errors
```

**Comment by thomas-jeepe** [comment] 2016-05-01 03:32
Bump

**Comment by szdavid92** [comment] 2016-06-29 11:37
is their a plan to support `defineProperty` getters and setters in the future?

**Comment by despairblue** [comment] 2016-07-25 08:26
Duplicate of https://github.com/facebook/flow/issues/285

I think.

**Comment by calebmer** [comment] 2017-07-20 15:41
Flow currently doesn’t support getters and setters as it would be very difficult to ensure your code is sound if every property access or assignment could be a function call. If you want to use getters/setters we recommend you use `any` to define the property and then hide the getter implementation or you use the object literal syntax:

```js
const x = {
  get foo() { return '' },
};
```

**Closed by calebmer** 2017-07-20 15:41 UTC

**Comment by mbrowne** [comment] 2017-07-22 10:49
@calebmer Thanks for the info, but I'm still unclear on how it would be possible to use `defineProperty()`. For example, the following code fails:

    const x: {foo: any} = {foo: undefined};

    Object.defineProperty(x, 'foo', {
        get: (): string => {
            return '';
        }
    });

---

    Error: test.js:5
         v--------------------------------
      5: Object.defineProperty(x, 'foo', {
      6:     get: (): string => {
      7:         return '';
      8:     }
      9: });
         -^ Object.defineProperty. Property not found in
                                         v
      5: Object.defineProperty(x, 'foo', {
      6:     get: (): string => {
      7:         return '';
      8:     }
      9: });
         ^ object literal


    Found 1 error

It seems that flow isn't aware that the `Object.defineProperty()` method exists.

Also, the code sample you provided doesn't work either:

    6:   get foo() { return '' },
       ^^^^^^^^^^^^^^^^^^^^^^^ get/set properties not yet supported

Although I'm guessing that this feature might not have made it into a release yet (I tested with 0.51.0).

**Comment by mbrowne** [comment] 2017-07-22 10:54
Also, I understand what you're saying about the limitations of compile-time type checking when using getters and setters, and that makes sense. But I'm not asking flow to type-check properties defined in this way; I just want to be able to create them. If it's valid JS and I'm using `any` types, it should work, no?

**Comment by szdavid92** [comment] 2017-07-22 12:21
@mbrowne Flow doesn't prevent to create it JS, unless you have a syntax error in the type annotations. Have you tried [this](https://flow.org/en/docs/config/options/#toc-suppress-comment-regex) to make the error go away?

**Comment by mbrowne** [comment] 2017-07-22 12:39
@szdavid92 The `$FlowFixMe` comment suppresses the error - thanks for pointing that out.

But I still don't understand why this issue was closed. Is it intended that `$FlowFixMe` will always be required because flow will never support calling `Object.defineProperty()` without throwing errors? Even if it's low priority, I would expect flow to eventually recognize all the native methods of `Object`.

**Comment by mbrowne** [comment] 2017-07-22 15:01
I experimented a bit more and found that it will recognize `Object.defineProperty()` when providing `value` but not with `get` or `set` properties. Actually, flow seems to only require that the `value` property is present - even this works even though it's not valid JS:

    Object.defineProperty(x, 'foo', {
        value: undefined,
        get: (): string => {
            return 'foo';
        }
    });

If getters and setters are the only issue here and there's no plan to support them, then perhaps using them with `Object.defineProperty()` should produce the same error as the object literal example above:

    get/set properties not yet supported

But it sounds like maybe the object literal example was supposed to work? In that case it seems to me that doing the same thing with `Object.defineProperty()` should work too.

Sorry for all the separate comments, but I thought it was worth sharing the above.

**Comment by calebmer** [comment] 2017-07-22 19:23
@mbrowne also try: https://flow.org/en/docs/config/options/#toc-unsafe-enable-getters-and-setters-boolean to enable getters/setters.

**Comment by calebmer** [comment] 2017-07-22 19:24
The object literal syntax does work with `unsafe.enable_getters_and_setters`. See:

```js
const x = {
  get foo(): string { return '' },
};

(x.foo: number);
```

https://flow.org/try/#0MYewdgzgLgBAHjAvDA3gKBjA5gU1gMxBAAoBKALhmgCcBLMLVGavAV2rBgHIuYBfADRo+AbjRpicAHSEQlMKwC2AIxzVSYoA

**Comment by mbrowne** [comment] 2017-07-22 20:51
Thanks Caleb, I'll check that out. Also, I took a look at the other issue
mentioned above - https://github.com/facebook/flow/issues/285. That
describes the issue more precisely so I suppose if there are further things
to discuss we could do it there.
