### ISSUE TITLE
Handling unknown/arbitrary sized list of generics. 

### ISSUE THREAD

**Issue by cglacet** [facebook/flow#7488] opened 2019-02-20 13:24 UTC
## Proposal

Adding a way to handle lists of generics with unbounded size:
```es6
function identity<...T>(array: T) {
  // ...
}
```
Which would be equivalent to: 
```es6
declare function identity2<A, B>(items:[A, B]): [A, B];
declare function identity2<A, B, C>(items:[A, B, C]): [A, B, C];
// with infinitely many signatures
function identity<T>(items:T): T {
	return items;
} 
```

Test it [here](https://flow.org/try/#0PTAEAEDMBsHsHcBQiSgMoEsB2BzaBTUAZwxywEMAXAVwCdCAKbAB2suIwC9CBmASgBcoRJGpYAxpQywsoDABN8WKZQCeARgA8AQQA0oAEL6AwgD4mlfAFsiQgNp7DJgLqDQD-UdDHnoAN6IAJD0NLSyGJY2ANyIAL7C4jJE7ABu6vZY1FYARvi0+pk5efrJtNg4vgC8corKERoMdur6AEz6AEQ87a6gqADyANbIKGBo+Cl55NAcZFR0+ESgTFis7CTcQm2gPPoAdPtuiIri0OT0oKISUjI1SiqqLTqe5hHWth6GrvaOBs4xx6dzpdJNJwrV7o8fiYXpF3lDvF93PCfDFgdcwXd6o8ACowt4CbFubH+IIhOjhWExeKIRJYZKgFItDJZXL5YiUMq4Kq3OpqFqNZqgdotbp8XpgQY0pKpHjMopswqskoc8rchSYvkC1odLo9fpDWn0lIAFjlStAiuK7M5OAKLLyavBWK1oC2nXa+mNerAAFFaLRYLRkKgxhNaFMZhRQgsliw2BwNqByFhVHwRGIQTd1bzVDxNPtdriLPjCUJiQFgvhQhS3lSpXTUgBWM1Wy1s0rlO3yx0a3Mut1dT09IA).

## Use case

That would for example be useful to type a `reverse` function. That function would take an arbitrary number of arguments and return them in reverse order: `reverse(1, 2, "3") = ["3", 2, 1]`. For now it seems that this is only possible by having a fixed length for the input, or by declaring several signatures, one for each possible number of arguments.

A more concrete use case I have is with this [zip function](https://stackoverflow.com/questions/54689169/how-to-specify-a-list-of-generics-of-unknown-arbitrary-size), which for now only takes 2, 3 or 4 iterables as parameter:

```es6
declare function zip<A, B>(Iterable<A>, Iterable<B>): Iterable<[A, B]>;
declare function zip<A, B, C>(Iterable<A>, Iterable<B>, Iterable<C>): Iterable<[A, B, C]>;
declare function zip<A, B, C, D>(Iterable<A>, Iterable<B>, Iterable<C>, Iterable<D>): Iterable<[A, B, C, D]>;
export function *zip<T>(...iterables:Array<Iterable<T>>): Iterable<Array<T>> {
   const iterators = iterables.map(iterable => iter(iterable));
   while(true){
      const items = iterators.map(iterator => iterator.next());
      if (items.some(item => item.done)){
         return;
      }
      yield ((items.map(item => { return item.value }): Array<any>): Array<T>);
  }
}
```

**Comment by jbrown215** [comment] 2019-02-25 18:28
[Is this sufficient for your use case](https://flow.org/try/#0GYVwdgxgLglg9mABANwIYCcaoCYwgBTgBsBPAWznQAcALPfDVMgUymfQGcAeAFQC5EAEgBKzHAHkwpAILp0qElzIwAHs2wA+DQAoAdPowBzDgJ4BKU4gDeidKxDokRjgG4AvgCgPEBByiIoECoiZgEAbTAQMgAjdgAaRD9MMEME6LhiMTAAXUQAXhQMLFwCYnJKWnpGFjZObQBmBIAieqaE4FQiDmYzFyA)?

**Comment by cglacet** [comment] 2019-02-25 18:39
Well, I think it is! 

```

export function *iter<T: $ReadOnlyArray<mixed>>(iterable:Iterable<T>): Iterator<T> {
   yield* iterable;
}

export function *zip<T: $ReadOnlyArray<mixed>>(...iterables:Array<Iterable<T>>): Iterable<Array<T>> {
   const iterators = iterables.map(iterable => iter(iterable));
   while(true){
      const items = iterators.map(iterator => iterator.next());
      if (items.some(item => item.done)){
         return;
      }
      yield ((items.map(item => { return item.value }): Array<any>): Array<T>);
  }
}
```

**Comment by SamChou19815** [comment] 2023-06-27 01:25
Duplicate of #7876 1251

**Closed by SamChou19815** 2023-06-27 01:25 UTC
Labels: feature request, discussion
