### ISSUE TITLE
Class Mixins don't work with static properties.

### ISSUE THREAD

**Issue by STRML** [facebook/flow#2494] opened 2016-09-20 16:16 UTC
Example on [FlowType Try](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVATApgYxgQwCcsw98BncsANXxgEsN8AXfAIxhIG9UwxzWzejjAA3OoxZYAFAAdCcWVkLMAngDl8AWywAufs0L0AdgHMANGIlNmcQgDFj+6csL77AV2M4hcYwEowAF4APjE4RktFX2NyAH59AHk2ACtcZn99UQiMAG5eAxZhKwYbLAAmZ3lFZTVNHX0BIzNLcVKWO0dnV3cvH3o-QNDwyLBogdiEsGS0nyGw7MZ8gF98zFwCYlICSjAAJSwCVg5uAoEikTZDv1NyABU4Zy04bBgHxsMTCzHZZnJ9LgUD7Nb5QOxYeimYwAaSwqmBX2W8xGeVQq3Q2DIWywAA9ZHZmNsKFQALIvQ5gLT0HEmKi0drHTiWA5HdicMBcZboMmvAB0bUkzBkAHIwXBhZYoH0YtJApz-PkeYd+dYpOVpKK4OLJdKJrKOUjFeSYLyrvAzPc4BqxRKOUCwMK2ERbWDiJCYXD9MLnq8AJIYYWGoA)

The following code errors (note attempt at both static function styles):

``` jsx
declare class Validatable {
  static validate(propertyName: string, validatorFn: (err: Function) => void, options?: Object): void;
  static validate2: (propertyName: string, validatorFn: (err: Function) => void, options?: Object) => void;
};

declare class Relatable {
  static belongsTo: (modelTo: string, opts: {as: string, foreignKey: string}) => void;
};

declare export class Model mixins Validatable, Relatable {}

// 'validate' not found in statics of Model
Model.validate('foo', function() {});
// 'validate2' not found in statics of Model
Model.validate2('foo', function() {});
// 'belongsTo' not found in statics of Model
Model.belongsTo('foo', {as: 'bar', foreignKey: 'modelId'});
```

**Comment by calebmer** [comment] 2017-08-01 15:36
Closing since this issue hasn’t seen a lot of activity. Sorry about that 😣

Please reopen with a reproduction on https://flow.org/try if you are still having issues!

**Closed by calebmer** 2017-08-01 15:36 UTC

**Comment by STRML** [comment] 2017-08-01 16:28
The bug hasn't changed or been fixed - please reopen.
