### ISSUE TITLE
Incorrect type checking callback

### ISSUE THREAD

**Issue by szagi3891** [facebook/flow#2341] opened 2016-08-26 05:55 UTC
```
/* @flow */

type FuncType = () => void;

function foo(callback: FuncType): void {
  callback('asadsa');
}

foo(() => {
});
```

resulting message: No errors!

https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiArgHYDGAKrgQLxgAUAlGLQHxgBucAlgCYBudFDLkMPOKTBQ4cBuQCGMGACMF5ANYAuIqOr4mO7vzABvVGDCLlazQwDkCgM4K+L+0yEBfYbIbNWDnMvTyA

**Comment by gcanti** [comment] 2016-08-26 06:18
It's by design https://github.com/facebook/flow/issues/2155

**Comment by szagi3891** [comment] 2016-08-26 07:05
it is weak :(

**Comment by samwgoldman** [comment] 2016-08-26 09:10
Closing to keep discussion in the existing issue.

**Closed by samwgoldman** 2016-08-26 09:10 UTC
