### ISSUE TITLE
Option or default to enforce function arity

### ISSUE THREAD

**Issue by STRML** [facebook/flow#2155] opened 2016-07-28 17:04 UTC
The following code does not throw any errors.

``` js
function add(a: number, b: number) {
  return a + b;
}

var c: number = add(1, 2, 3);
```

There are [hacky ways](https://github.com/gcanti/babel-plugin-tcomb/issues/58) to fix this problem but I don't see why we should be so liberal as to allow this now that rest params exist.

["Try Flow" example](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swBDAEwoAoyAuMbTAWwCMBTAJwBoxWGmbLgEowAb1RgwndvkydSZMAGo+AblQBfdADcynMLjABeclWoBGXgCZeAZmEaMOAsUVVrtASw48+3oT8AOhCZAGd8BgBBTk4yAE8AHh04QgoAPlEJKRk5BXIVdS1dfTAKEzMKTyswWzAHNSA)

**Comment by avikchaudhuri** [comment] 2016-07-28 19:23
The recommended solution is
```
function add(a: number, b: number, _: void) {
  return a + b;
}
```

This is probably still hacky, but also more reasonable than the fix you linked to.

More generally, yeah we might revisit this design decision in the future. We definitely need it for function-function matching, because it's usual in JS to define closures that don't mention unnecessary params and pass them to places that expect closures with all params (e.g., https://github.com/facebook/flow/blob/master/lib/core.js#L201).

**Comment by gcanti** [comment] 2016-07-29 02:57
The recommended solution doesn't fix the problem though, `add(1, 2, undefined, 3)` is still possible

**Comment by samwgoldman** [comment] 2016-07-29 03:12
What is the problem, though? Passing extra arguments isn't a runtime error; why should it be a static error?

**Comment by gcanti** [comment] 2016-07-29 03:28
@samwgoldman indeed, IMO the current Flow behaviour is correct, describes how actually JavaScript works (was just pointing out that the proposed solution was not a real fix **if** you want to enforce the arity)

**Comment by STRML** [comment] 2016-07-29 03:31
Sure, it's not a runtime error, but suppose the arity of a function changes such that it no longer accepts an extra argument for whatever reason. That wouldn't be an error with the current behavior.

Is there a good reason to keep the current behavior if we have a chance to be more strict and catch potential bugs? Given how simple rest arguments are to use now, I seems it would actually be okay to do so.

**Comment by alexeygolev** [comment] 2016-07-29 13:14
it's
```js
function add(a: number, b: number, ...rest: Array<void>) {
  return a + b;
}
```

**Comment by thejameskyle** [comment] 2016-08-03 21:25
@alexeygolev has probably the best solution to this for now if you are concerned about adding arguments in the future and it being used incorrectly today. This is not unlike adding additional properties to objects than is in the type definition (although we did just add Exact for that).

**Comment by vkurchatkin** [comment] 2016-08-03 21:29
@thejameskyle maybe it worth adding syntactic sugar to make this easier?

**Comment by szagi3891** [comment] 2016-08-26 07:09
Maybe should be added to a more stringent checks? Something as strict mode in javascript.

**Comment by jedmao** [comment] 2017-01-19 06:45
`...rest: Array<void>` should be Flow's default behavior.

**Comment by vkurchatkin** [comment] 2017-01-22 19:03
Duplicate of https://github.com/facebook/flow/issues/1017

**Closed by vkurchatkin** 2017-01-22 19:03 UTC
Labels: feature request, linter, Needs docs

**Comment by STRML** [comment] 2017-05-09 22:42
Glad to see this decision has been reversed!
