### ISSUE TITLE
[NFR]/Bug Better CFG analyze for Ternary operator

### ISSUE THREAD

**Issue by ovr** [facebook/flow#4860] opened 2017-09-12 09:38 UTC
Hey!

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjYqfOLMAcn0pqYG51CBPHMsABUAFqwoATAKIA7Qhl5gAvGADeqMGFQBfbnwEBlQhUIDlajYVGVxALiFWJMubwA+0gK4wY29FHfSaDDhpMDh+aQBhCi8AdQxpcUQACTgAZ0IACksxW3scp3keAEo7dPx4gHNVdTBWQnd8EIAicTIoCk9iMsqmrh1UKmD0sHTjMjtDMaVVMGzrOw8vMC0uAaHiACNCEOUMmoAeDfdCQmCajWCImAwqAGtFFVGTADo5iTAAfjAMoqUAPlC4SisXiiQQKXSGSeZFeDnEvwWnhgOg0f3OgLI0gOwCOJ2CaKKqCAA

```javascript
/* @flow */

import React from 'react';

type ThreadEntity = {
  
}

type State = {
  thread: ThreadEntity|null
}

function openCallWindowHost(thread: ThreadEntity): string {
  return "default string";
}

const state: State = { thread: null };

const letsRenderLol = (
  <button
    onClick={state.thread ? () => openCallWindowHost(state.thread) : null}
  >
    open
  </button>
)
```

Ternary operator mutate possible values of `State` type

from `ThreadEntity|null` to `ThreadEntity` for positive case and `null` for negative

Thank

**Comment by ovr** [comment] 2017-09-12 09:53
More cases

![image](https://user-images.githubusercontent.com/572096/30319730-a26deac0-97eb-11e7-8179-b85b448ad17c.png)

![image](https://user-images.githubusercontent.com/572096/30319737-a574a560-97eb-11e7-9390-2d9dfb22d305.png)

![image](https://user-images.githubusercontent.com/572096/30319743-a7f7a922-97eb-11e7-8744-5c9f9c0c554a.png)

**Comment by asolove** [comment] 2017-09-12 14:40
Hi there! Can yuk please explain what you expect in the code above and what happens? I can read the code, but I’m not sure what about it you think is happening incorrectly.

**Comment by asolove** [comment] 2017-09-12 14:42
If the issue is about null being an option on this value even after you checked it with an if, then I think the answer to your quandary will be in the Refinement invalidation section here: https://flow.org/en/docs/lang/refinements/

**Comment by jcready** [comment] 2017-09-12 17:25
Yeah, to resolve your issue your `onClick` should look like this:

```js
onClick={() => state.thread ? openCallWindowHost(state.thread) : null}
```

The ternary has to be inside the arrow function otherwise the arrow function itself invalidates your refinement. Alternatively you can make a `const` that references `state.thread` and pass it to your function:

```js
const thread = state.thread
const onClick = thread ? () => openCallWindowHost(thread) : null
const letsRenderLol = (
  <button onClick={onClick}>open</button>
)
```

**Closed** 2017-09-13 08:01 UTC

**Comment by ovr** [comment] 2017-09-13 08:06
@vkurchatkin why this closed?

**Comment by ovr** [comment] 2017-09-13 08:17
thank @jcready 

> The ternary has to be inside the arrow function otherwise the arrow function itself invalidates your refinement

you are right, but why it's not possible for Flow to support this case? (invalidates refinement when it's really needed, because in my example it's pretty simple anonymous function)

**Comment by vkurchatkin** [comment] 2017-09-13 08:21
@ovr see @jcready's answer
