### ISSUE TITLE
`Array<T>` is not equal to `Array<T>` (where `T` is the same type)

### ISSUE THREAD

**Issue by talbenari1** [facebook/flow#7197] opened 2018-11-19 21:10 UTC
Passing an array through a function with the signature `<T>(x: Array<T>) => Array<T>` yields a return value with a type that differs from the inputted value's type (at least that's my understanding). Here's a contrived example of this strange behavior:

This works correctly [(link to Try Flow)](https://flow.org/try/#0GYVwdgxgLglg9mABDAJgUzLKBPAPAFQD4AKADwC5F8BKS-RAbwChFlhFiBBAJ24ENsAOhgBnHv2xlq1Ri1aJuaKCG5JSAbjkBfOYuWrEGplqA):
```js
function identity<T>(x: T): T {
  if (Array.isArray(x)) {
    return x;
  }
  return x;
}
```
But extracting the `return x` inside the `if` block into a separate function causes things to break [(link to Try Flow)](https://flow.org/try/#0GYVwdgxgLglg9mABDAJgUzLKBPAPAFQD4AKADwC5F8BKS-RAbwChFlhFiBBAJ24ENsAOhgBnHv2xlq1Ri1aJuaKCG5JUGLNnECpAbjkBfOYuWrEpfUaahIsBMnSYYObXiJlKrgoVqIvRWVYTFSQLJgMgA):
```js
function identity<T>(x: T): T {
  if (Array.isArray(x)) {
    // x is correctly refined...
    return identityArray(x); // ...but there's an unexpected Flow error here
  }
  return x;
}

function identityArray<T>(x: Array<T>): Array<T> {
  return x;
}
```

**Comment by TrySound** [comment] 2018-11-21 21:29
Use `$ReadOnlyArray`

**Comment by talbenari1** [comment] 2018-11-22 05:20
@TrySound ? That still doesn't work.

([link to Try Flow](https://flow.org/try/#0GYVwdgxgLglg9mABDAJgUzLKBPAPAFQD4AKADwC5F8BKS-RAbwChFlhFiBBAJ24ENsAOhgBnHv2xlq1Ri1aJuaKCG5JUGLNnECpAbjkBfOYuWrEpfUaahIsBMnSYYObXiJlKAEgBKaPigB5MAAbLV4BAkJaRB8-QJCwiUjZVhMVJABtAF1LIA))
```js
function identity<T>(x: T): T {
  if (Array.isArray(x)) {
    return identityArray(x);
  }
  return x;
}

function identityArray<T>(x: $ReadOnlyArray<T>): $ReadOnlyArray<T> {
  return [];
}
```

**Comment by Bannerets** [comment] 2018-12-16 12:17
@talbenari1 As I understand, it's not a bug, that shouldn't work.

For the same reasons that

```js
function identity<T>(x: T): T {
  if (Array.isArray(x)) {
    return []; // error
  }
  return x;
}
```

and

```js
function identityArray<T: Array<mixed>>(x: T): T {
  return []; // error
}
```

don't work.
You are returning another array, not the value of type `T`.

---

```js
function identity<T>(x: T): T {
  if (Array.isArray(x)) {
    return identityArray(x);
  }
  return x;
}

function identityArray<T: Array<mixed>>(x: T): T {
  return x;
}
```

This should work and it works, because you are returning the same array, of type `T`.

**Comment by talbenari1** [comment] 2018-12-17 16:53
@Bannerets 
> You are returning another array, not the value of type `T`.

I don't think that's actually a problem for 2 reasons:

1. If you replace `[]` with e.g. `[...x]`, you don't get an error, even though it's a new array.
1. `[]` is the subtype of all array types, and should therefore be assignable to all types; i.e. if `[...x]` works, then (as far as I can tell) there's really no reason why `[]` shouldn't work as well.

**Comment by Bannerets** [comment] 2018-12-17 17:55
@talbenari1 
I think it shouldn't work just like `function i<T: number>(x: T): T { return 5 }` doesn't work.

welp, `[...x]` looks like a flow bug to me. Example of unsound behaviour:

```js
function identity<T>(x: T): T {
  if (Array.isArray(x)) {
    return [...x]; // no flow error
  }
  return x;
}

class Arr<T> extends Array<T> { m() {} }

var b = identity(new Arr)
// type of b is `Arr<T>`, but in runtime it's Array

b.m() //=> Runtime TypeError
```

**Comment by wchargin** [comment] 2019-02-27 07:49
A bit simpler than that—`Array.isArray` refinement seems to be totally
broken. If `x: T`, then `Array.isArray(x)` refines to `x: Array<T>`,
which is obviously wrong: just because `T` is an array type doesn’t mean
that it is an array _of `T`!_

[This yields `coerce`:][1]

```js
// @flow
function coerce<T, U>(t: T): U {
  // `hmm` takes a non-empty array and returns its first element.
  function hmm<Z>(array: Z): Z /* actually $ElementType<Z, number> */ {
    if (!Array.isArray(array)) throw new Error("Unreachable.");
    const problem: Array<Z> = array; // ???
    if (array.length === 0) throw new Error("Unreachable.");
    return problem[0];
  }
  const result: Array<{ value: T }> = hmm([{ value: t }]);
  if (Array.isArray(result)) throw new Error("Unreachable.");
  return ((result: empty).value: U);
}
const twelve: number = coerce("twelve"); // no type error!
twelve.toFixed(); // runtime error!
```

(The root of the problem is marked with `// ???`.)

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQkCuA7AxgFwJazaBrAKYBOGxAPACoA0oAqgHwAUWAXKNQJScOgBvRKFAhQAAwAWAW2njQWAIYBrYgGdQi0GnwBaYtIAOWAJ6bSpRWcVoAJqFLEsKUmg04sGyDlJqsoYmgDYjQsADphUFRMXHxQGWlKAC1WRQsrTiTeUCTRACpNbBRFaGgzABIAUSDpEKxqE0MqJPo0FGkAIzImUDywIRERHEhQFgBCAEF0kzCcNSnLExY0xe5uBUlSBG1ieFBKi1hSFgAiBjRHRQxJRQ6gsJPuAG5IkSI3f0Mtu4NOBatkj0ALzmRZPURgAD80NeoGGoxWVjCQTQAHMsJJQEDsaAAAzrDFbPZoXb7Q7HM4XYhXG4-B7PWGOZyuUBfWA-aQAbVxAF0XiIAL6Rd5+BzqFDQDigf4mSgCUAANxKKGInGooAFwPishYnPlSugKs4-gFPIZQxGLBls3m0xYjjUEqwaw2RJ2ewOWwp50u11u90e-LFzIILHt4slnAMxhM3DCBqNjAZQpF-iw8ECCtV2naXVIWMIJHIxFO6czxEDEO0sAUjWIAXJY0QZegWbCWFgADEcAAPYi2FjPKukdC4WoNr1NoA

**Comment by wchargin** [comment] 2019-04-06 03:53
@dsainati1: Thanks for the patch! But I don’t think that it actually
resolves this issue, because the above `coerce` works just fine if you
replace all `Array`s with `$ReadOnlyArray`. The following test passes on
your commit (but should fail):

```diff
$ git rev-parse HEAD && git diff && make >/dev/null 2>&1 && ./runtests.sh -t arrays bin/flow
5639532065954e7f66a968af5e68f76a762a9c14
diff --git a/tests/arrays/isarray.js b/tests/arrays/isarray.js
index e29025da5..01a865893 100644
--- a/tests/arrays/isarray.js
+++ b/tests/arrays/isarray.js
@@ -25,3 +25,17 @@ function hmm(array: mixed) {
     problem[1] = 0;
   }
 }
+
+function coerce2<T, U>(t: T): U {
+  function hmm<Z>(array: Z): Z  {
+    if (!Array.isArray(array)) throw new Error("Unreachable.");
+    const problem: $ReadOnlyArray<Z> = array; // should error!
+    if (array.length === 0) throw new Error("Unreachable.");
+    return problem[0];
+  }
+  const result: $ReadOnlyArray<{ value: T }> = hmm([{ value: t }]);
+  if (Array.isArray(result)) throw new Error("Unreachable.");
+  return ((result: empty).value: U);
+}
+const thirteen: number = coerce2("thirteen");
+thirteen.toFixed();
Running up to 16 test(s) in parallel
[✓] PASSED:  arrays

Passed: 1, Failed: 0, Skipped: 505, Errored: 0
```

**Comment by dsainati1** [comment] 2019-04-08 16:31
@wchargin ahh you are correct. @mvitousek is actually working on some general changes to generics that will fix this case. I can reopen the issue until his fix is pushed.

**Comment by wchargin** [comment] 2019-04-08 17:02
Understood; thanks.

> I also wanted to say a general thank you, by the way, for consistently
> finding and posting such high quality bug reports! We had a sort of
> "bug bash" last week to fix some outstanding issues in Flow and your
> bug reports were really helpful.

You’re quite welcome—glad to hear that they’re helpful, and very happy
to see that some of them are being addressed! Thanks.

**Comment by goodmind** [comment] 2019-04-09 16:59
Related? https://github.com/facebook/flow/issues/3199

**Comment by mvitousek** [comment] 2019-04-09 17:15
Looks like that issue is resolved by @dsainati1's commit. The remaining issue here I think at its root arises from how we model generics and less from how refinements against mixed work (though they are inherently related).

**Comment by SamChou19815** [comment] 2023-01-31 04:13
This now works.

**Closed by SamChou19815** 2023-01-31 04:13 UTC
Labels: Typing: soundness
