### ISSUE TITLE
Error occurring only with "flow check-contents": "A. This type incompatible with A."

### ISSUE THREAD

**Issue by Macil** [facebook/flow#2235] opened 2016-08-12 00:07 UTC
_EDIT: See simpler reproduction case in the next post!_

a.js

``` js
/* @flow */

import useA from './useA';

class A {
  constructor() {
    useA(this);
  }
}

function id(t) {
  return t;
}

export default id(A);
```

useA.js

``` js
/* @flow */

import type A from './a';

export default function useA(a: A) {

}
```

```
$ flow
No errors!
$ flow check-contents a.js < a.js 
a.js:7
  7:     useA(this);
         ^^^^^^^^^^ function call
  5: class A {
           ^ A. This type is incompatible with
  5: export default function useA(a: A) {
                                     ^ A. See: useA.js:5


Found 1 error
```

I run into this issue a lot because I use some [ud](https://github.com/AgentME/ud/) functions with types similar to `id` here, and I use [linter-flow](https://atom.io/packages/linter-flow) with Atom which uses `flow check-contents` often behind the scenes and then points out these non-existent errors.

**Comment by thejameskyle** [comment] 2016-08-12 00:57
Simplified this code a bit to a [smaller repo case](https://github.com/thejameskyle/__flow-check-contents-error):

**a.js**

```js
/* @flow */

import b from './b';
export class A {};
b(A);
```

**b.js**

```js
/* @flow */

import typeof {A} from './a';
export default function b(a: A) {}
```

This seems more like an issue with cyclical type dependencies. Like the flow server isn't recalculating what A is when inside of `b.js`.

**Comment by gabelevi** [comment] 2016-08-12 04:17
Right, `flow check-contents` doesn't recheck dependencies. So if `b.js` has a `require('./a')`, we currently don't recheck `b.js` when you do `flow check-contents a.js < unsaved_a.js`.

This is a known limitation of `check-contents`. `flow check-contents` was intended to be a simple little thing, where you could do something like `echo var x: number = "hi" | flow check-contents`, but IDEs ended up liking it because it could check stdin code and would filter errors to just those from the stdin code.

We're coming up with a plan for how to better support IDE use cases - I actually drafted a proposal on Sunday night! So thanks a lot for reporting! It really helps my argument :)

**Comment by AgentME** [comment] 2016-08-12 18:01
>but IDEs ended up liking it because it could check stdin code and would filter errors to just those from the stdin code.

I'm probably just repeating the obvious but also another big benefit is that it allows unsaved changes to be type-checked. (linter-flow specifically only uses check-contents when the file has unsaved changes, so this bug has the funny consequence that errors appear only once you type in the file, and then disappear as soon as you save.)

**Comment by prigara** [comment] 2016-10-20 13:05
We’ve also bumped into the same [problem](https://youtrack.jetbrains.com/issue/WEB-23706) in WebStorm. Looking forward to having a better way to check the unsaved files (and ideally, as we've already mentioned, more than one).

**Comment by jacargentina** [comment] 2018-03-03 14:36
More than a year and a half later, any progress on fixing this ? Maybe the solution is to stop using `check-contents`

**Comment by SamChou19815** [comment] 2024-03-17 03:17
The issue should be fixed a long time ago

**Closed by SamChou19815** 2024-03-17 03:17 UTC
Labels: enhancement
