### ISSUE TITLE
No error when accessing a non-existent property of a function object.

### ISSUE THREAD

**Issue by hearnden** [facebook/flow#3301] opened 2017-01-30 07:44 UTC
Might be the same issue as https://github.com/facebook/flow/issues/3005, but this example demonstrates the issue far more concisely:
```javascript
const f: number => number = x => x + 1;

console.log(f.thisPropertyDoesNotExist);  // <-- surely this should raise an error.
```

All of these variants fail to fail:
```javascript
// Many ways of defining an increment function:
function f(x) { return x + 1; }
function g(x: number): number { return x + 1; }
const h = x => x + 1;
const i = (x: number) => x + 1;
const j: number => number = x => x + 1;

// ... but none of these property accesses raise errors.
console.log(f.thisPropertyDoesNotExist); 
console.log(g.thisPropertyDoesNotExist); 
console.log(h.thisPropertyDoesNotExist); 
console.log(i.thisPropertyDoesNotExist); 
console.log(j.thisPropertyDoesNotExist); 

// ... but for objects and arrays, non-existent property access is correctly detected.
const o: {} = {};
const a = [];

console.log(o.thisPropertyDoesNotExist);  // this correctly raises an error
console.log(a.thisPropertyDoesNotExist);  // this correctly raises an error
```
https://flowtype.org/try/#0GYVwdgxgLglg9mABMAFADwJSIN6IE4CmUIeSaiA1IgIwDciAvgFCiSwKIDm6AXImCAC2AIwJ4MfASLE58REmUo16zCAgDOURAAtEAXkTk9APkNK6TNWE2IY+xL35DR4-afJULVmwCtJzmRMnaTx7I3dzWiYmAHoYxAA5BAJEOGBEKG0CdRS8AEMYHMQxPDg8dQA6Sw04ABsCCtq4bmAKzMKABVKABzEoAE8AEThspKgAUTRCqAx6aus6hqbuTjbtTp6+oZH1Mcnp2cR59UXG5pRtNY24XrwB4dG4CanNQ+PT5ZQYK-Uum62HrsnvtXnNvB9zj4fn9bvcdnsXjM5sctHA+NgGPYMVFvFo8vYANoAXSi73qZ24cGhmzu20ezwOYJq5M+eWp-1pgIRjKOQA

Even if there was a compelling reason why accessing an unknown property of a function object shouldn't be considered an error, would it be possible to add an opt-in mechanism for a stricter interpretation of a function type, where such property accesses would be forbidden, either in the type declaration or as a config option on flow itself?

**Comment by asolove** [comment] 2017-08-21 20:06
This is really interesting! 

To get a sense of why this happened, I tried if the error was thrown for a full `Object`, rather than just `{}`:

```js
const o1: Object = {};
const o2: {} = {};

o1.doesntExist; // Does not error
o2.doesntExist; // Does error!
```

This gave me the idea that since `Function`s inherit from `Object`, maybe that was the reason why a normal function type silently allows other keys.

Which gave me another idea! It's actually possible to give a type to functions that have a specific set of expected properties also hanging off their object, like this:

```js
type FunctionWithProp = {
  (n: number): number,
  
  prop: bool
}

let x = (x) => x;
x.prop = true;

let y: FunctionWithProp = x;
```

So, what happens if we define a function with that syntax, but don't specify any other keys:

```js
type JustFunction = {
  (n: number): number,
}

let x: JustFunction = (x) => x;
x.stuff; // Errors!
```

This causes me to wonder whether the default version of `Function` isn't what should be used when inferring modern-stye JS code. Instead, maybe we should use a type that behaves like:

```js
type JustFunction<A, B> = {
  (in: A): B
}
```

(except it would need to work with multi-arg functions and various other crazy things). This would show errors if you just tried to fetch a property from a plain old function.

**Comment by leebyron** [comment] 2019-06-14 18:04
Just shipped a production error because of this the other day, so still a problem in the latest version.

[Flow repro in latest version](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swAPACgEoAuMbTAWwCMBTAJzAG9Uwx3W+TO1IBmVAF90uEgGd8YAJ50GLDmAC85AHRQ4cbcwCGnYMDABRMgAdWBVgBMwHdnHaogA)
[Same code in TS correctly catches this issue](http://www.typescriptlang.org/play/index.html#src=function%20x()%3A%20number%20%7B%0D%0A%20%20return%203%0D%0A%7D%0D%0A%0D%0Aconst%20y%3A%20number%20%3D%20x.foo.bar%20%2F%2F%20Expected%20error%0D%0A)

**Comment by goodmind** [comment] 2019-06-22 19:52
Duplicate of #106

**Closed by goodmind** 2019-06-22 19:52 UTC
Labels: Typing: soundness
