### ISSUE TITLE
Empty object not of exact type with optional properties

### ISSUE THREAD

**Issue by minedeljkovic** [facebook/flow#2386] opened 2016-09-03 08:00 UTC
Minimal example:

``` js
type PossiblyEmpty = $Exact<{
  a?: number
}>

const p: PossiblyEmpty = {} // this errors. Should it?
```

https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAKcAziQJYBGMWAogLY7ZgC8YAJLQB4CGAxhgA8Ab1RgwPAPwAuMADsArvUp4ATqgC+APnR84ckhjA5ZxMlRoMmWVmGEbUQA

Is this by design?

EDIT: inline an example

**Comment by samwgoldman** [comment] 2016-09-03 18:32
Yeah, looks like a bug to me. Thanks for the minimal example!

**Comment by samwgoldman** [comment] 2016-09-03 18:39
For what it's worth, I am responsible for making this an error (in [this commit](https://github.com/facebook/flow/commit/b95abaa81554f18f51826cba9c3764a42403a7b3)). In general, unsealed things can't be exact, because other references to them can widen the type in unexpected ways.

In this case, there are no other references, so it doesn't really make sense to consider the object literal to be unsealed. I think the fix here is to *not* create an unsealed object in this case. `var o = {}` should be unsealed, but `var o: T = {}` should not be.

**Comment by danez** [comment] 2017-11-18 16:32
Still getting the error. Is that something that will be fixed?

**Comment by Will-Wrightwa** [comment] 2017-11-19 18:08
I would also like to see this fixed.  Anytime you are using an options parameter it is helpful to allow {}

**Comment by knyzorg** [comment] 2017-11-28 00:55
@samwgoldman It's still an issue!

**Comment by chrisblossom** [comment] 2017-12-03 00:52
Look at https://github.com/facebook/flow/issues/4582#issue-249772183 for a workaround

**Comment by chrisblossom** [comment] 2017-12-13 22:59
@lgraziani2712 Why the thumbs down? Does it not work correctly? Please share your experience.

**Comment by lgraziani2712** [comment] 2017-12-14 02:23
The OP presents an object type with an optional attribute, while that workaround doesn't take in consideration those props. I tested myself with my object full of optionals attributes and didn't work.

**Comment by chrisblossom** [comment] 2017-12-14 02:25
@lgraziani2712 does this not provide your expected results? https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCiYAvGAN5iphgCGA-AFxgDOGATgJYB2A5gDTUqNYMDAB1OOwDWtdnACu3ACZgoUsHgAetAMYYw2fADoJU6SzqXt+fXmVDRYBAAs83MMry0YPXs84MFzA4ACMAKzx9SyDaA11aD1CCPABbHGxjIQBtRKwAXWY0jKwqAF90XThuNk1mYjJyMrAnbjhNdnl2Fkrq2qh60gowUMYARjBmpzxOqUtaay1bDHsgA

**Comment by lgraziani2712** [comment] 2017-12-14 02:43
Ok yep, it worked. I did it wrong: I kept the {||} exact pipes.

Thank you @chrisblossom

**Comment by julienw** [comment] 2018-07-03 12:37
[Here is another example](https://flow.org/try/#0C4TwDgpgBAQgThAhgawCYHsDuA7KBeKAbwB8oBtAZ2DgEtsBzAXQC4psBXAWwCMI4piAXwDcAKADG6bFSjcEKDDlbwkaLLgKERQA).
```javascript
type Breakdown = {| [string]: number |};
const breakdown: Breakdown = {};
```
=>
```
    2: const breakdown: Breakdown = {};
                                    ^ Cannot assign object literal to `breakdown` because inexact object literal [1] is incompatible with exact `Breakdown` [2].
        References:
        2: const breakdown: Breakdown = {};
                                        ^ [1]
        2: const breakdown: Breakdown = {};
                            ^ [2]
```

I think the explanation given in https://github.com/facebook/flow/issues/2386#issuecomment-244563036 is the right one. But it's been a while...

**Comment by ogard** [comment] 2018-07-25 18:57
Here is a possible workaround until bug is not fixed:
```javascript
/* @flow */

declare type Criteria = {| option1?: number, option2?: string |};

declare export function init(criteria: Criteria): void;

const test = init({ ...undefined });
```

**Comment by NilSet** [comment] 2018-10-24 22:38
Another workaround is `$Shape`:
```js
/* @flow */

declare type Criteria = $Shape<{option1: number, option2: string}>;

declare export function init(criteria: Criteria): void;

init({}); // ok
init({option1: 3}) // ok
init({option1: 3, rogueProp: 'secret'}) // errors as expected
```

**Comment by benjaminjkraft** [comment] 2019-01-04 22:02
Another workaround, which to my mind is the cleanest of any I've seen here, is to just pass an explicit `undefined`.  For many purposes the following is equivalent to an empty object:
```js
({foo: undefined}: {|foo?: number, bar?: number|});
```

**Comment by penx** [comment] 2020-04-15 10:46
Recommend you add the label 'unsealed objects' to this and probably close #2977 as a duplicate of this so that progress/conversation can be tracked in one place.

**Comment by Ashoat** [comment] 2020-06-24 11:48
#7624 is also a duplicate

**Comment by gnprice** [comment] 2020-09-18 20:13
Another workaround for this issue is to use `Object.freeze` ([playground](https://flow.org/try/#0BQbwBAHgXGDMYF8YgD6RgOwK4FsBGApgE5goICUA3GAPQ1gD2A1gFAuhJiplW33FEGRNsADyeAFYEAxgBcAdADMiBAgC8CHcshQ9qdRkzDAA7kKYBDQVgwATciyA)):
```js
({ x: 3 }: {| x: number |}); // ok

({}: {||}); // error

(Object.freeze({}): {||}); // ok (workaround)
```

I learned this from the thread at #2977; repeating it here in case it helps others, because this seems to be the canonical thread for this issue.

If you weren't planning to mutate the object, then this workaround is quite clean because it should have no effect at all on the behavior of the code that consumes the object. And in situations where you are planning to mutate the object, I think you typically want the "unsealed object" behavior anyway so this isn't an issue in the first place.

**Comment by gkz** [comment] 2022-12-19 05:16
This is fixed https://medium.com/flow-type/improved-handling-of-the-empty-object-in-flow-ead91887e40c

**Closed by gkz** 2022-12-19 05:16 UTC
Labels: bug
