### ISSUE TITLE
React.memo() does not work well with flow

### ISSUE THREAD

**Issue by codefln** [facebook/flow#7095] opened 2018-10-25 08:54 UTC
I'm add the flow for my component that uses React.Memo. And the flow gives me this error:
Cannot call `React.memo` because property `memo` is missing in object type [1].

Example:
[flow.org/try/#0PTACD](https://flow.org/try/#0PTACDMBsHsHcCgCWBbADtATgFwAQCUBTAQwGNdwNpkcAiDYsmgbnnhOgDsBnXAFWgBCBALIFk0HAF58DLADpkY6AApUlVFykA+HAG94OHPSwBXDBxzKDhnAB4AFgEYt1mzgDqmANbwAkLeAnF0MAShYAXzCgA)

**Comment by wchargin** [comment] 2018-10-25 19:52
Duplicate of #7093.

**Closed** 2018-11-14 14:22 UTC
