### ISSUE TITLE
Debugging Flow

### ISSUE THREAD

**Issue by agentcooper** [facebook/flow#4181] opened 2017-06-15 13:42 UTC
I am using Visual Studio Code with [vscode-ocaml](https://github.com/hackwaly/vscode-ocaml) extension. `./bin/flow` is compiled using `make build-flow-debug` (see also: https://github.com/facebook/flow/issues/4177).

`.vscode/launch.json`:

```js
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "OCaml",
      "type": "ocamldebug",
      "request": "launch",
      "program": "${workspaceRoot}/bin/flow",
      "console": "internalConsole",
      "stopOnEntry": false,
      "arguments": [
        "${workspaceRoot}/local-test"
      ]
    }
  ]
}
```

`local-test/test.js`:

```js
// @flow

const a: number = 'z' + 'd';
```

Debugging `main` seems to work:

<img width="794" alt="screen shot 2017-06-15 at 15 28 09" src="https://user-images.githubusercontent.com/794591/27183582-4f28422c-51df-11e7-9a48-af9d5b69d253.png">

However If I set a breakpoint somewhere in `src/typings/`, for example `statement.ml`, inside `variable_decl` function, then the breakpoint is skipped.

I suspect this is because of the server-client architecture - actual type checking happens inside a different process.

Is there any good way around this?

**Comment by kogai** [comment] 2017-08-20 13:46
I faced the same problem and I didn't solve it.

For the reference, I tried `flow check` command.
It seems to be checking type at foreground, but when using `ocamlbuild` with settings like below,
debugger responds with `cannot connect to debugger at 127.0.0.1 error: No such file or directory`.

```javascript
{
    "program": "${workspaceRoot}/bin/flow",
    "arguments": ["check", "path/to/mycode.js"],
}
```

The error occurred at `spawn` function in `hack/utils/daemon.ml`(yes, the debugger worked correctory), and I guess that it related to spawning server process.

**Comment by kogai** [comment] 2017-08-26 07:42
Still examining, but it seems to get some progress.

As above comment I guess, the problem caused by some process that created behind `flow`.

Then, I try out arguments "--max-workers" that described with `Maximum number of workers to create (capped by number of cores)`

I don't understand it in detail, but it seems related to some process behind `flow`.
So, I modified my settings like follows and executed `ocamldebug`.
 
```
{
    "program": "${workspaceRoot}/bin/flow",
    "arguments": ["check", "--max-workers", "0", "path/to/mycode.js"],
}
```

And the result looks as I expected.
At least it can execute `flow` according to `breakpoint` and process exit normally.

**Comment by villesau** [comment] 2018-10-21 12:10
@agentcooper @kogai have you tried to get debugger working with [vscode-ocaml-debugger](https://github.com/hackwaly/vscode-ocaml-debugger)? I can get the debugger working with simple example using `ocamlc -g helloworld.ml` but with Flow pretty much nothing happens, only the loading sign appears below debug menu,

**Comment by villesau** [comment] 2018-12-11 19:42
Looks like ocaml debugger runs roughly this kind of command: `ocamlrun bin/flow check my-own-test/test.js --max-workers 0`, when running the flow with `ocamlrun` the program throws

```
Fatal error: unknown C primitive `unix_waitpid'
```

Maybe this is the culprit?

**Comment by jbrown215** [comment] 2018-12-11 21:23
I don't use the ocaml debugger, but flow has a few debugging commands that I use to debug type checker behavior. `flow check --verbose-indent` will show the full list of flows in `__flow`.  The function that adds errors is called `add_output`, and it also logs when it is called with `--verbose-indent`.

**Comment by villesau** [comment] 2018-12-11 22:44
Nice, this probably already helps a lot, thanks for being so helpful!

**Comment by villesau** [comment] 2018-12-15 20:40
Ok, got debugger finally working in VScode!

VScode debugger config:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "OCaml",
            "type": "ocaml-debugger",
            "request": "launch",
            "program": "${workspaceFolder}/bin/flow",
            "console": "internalConsole",
            "stopOnEntry": false,
            "arguments": ["check", "${workspaceFolder}/local-test/test.js", "--max-workers=0", "--verbose-indent"]
          }
    ]
}
```

- `${workspaceFolder}/local-test/test.js` being the js file to check
- `--max-workers=0` apparently runs everything in single process
- `--verbose-indent` Debugger works also without, but still very useful

Other requirements:
- OCaml 4.05.0 <- later versions might work too, I only tested with 4.05.0
- VScode debugger plugin: https://marketplace.visualstudio.com/items?itemName=hackwaly.ocaml-debugger
- debugger adapter: https://github.com/hackwaly/ocamlearlybird/
  - needs to be installed with opam: `opam install earlybird` 
  - NOTE: Needs to be at least 0.1.3 version, earlier versions does not work

I also recommend to install Merlin: https://github.com/ocaml/merlin
```
opam install merlin
opam user-setup install
```

This might be worth documenting to e.g Flow wiki or readme.

**Comment by kevinbarabash** [comment] 2019-08-25 17:14
I would also suggest using `--merge-timeout=0` as well to avoid timeouts.

**Comment by kevinbarabash** [comment] 2019-08-25 17:15
@villesau thanks for the instructions.  Being able to step through things is going to be a big help.

**Comment by STRML** [comment] 2019-09-27 00:47
Thanks @villesau for such a useful comment.

I was unable to get mine running until I added to my user settings.json:

```json
{
    "reason.path.ocamlmerlin": "_opam/bin/ocamlmerlin",
    "reason.diagnostics.tools": [
        "merlin"
    ],
    "editor.formatOnSave": true,
    "reason.codelens.enabled": true,
}
```

and to my debug configuration:

```json
            /* start ocamlearlybird --server --port 4711 before running */
            "debugServer": 4711
```

I then run `$ ocamlearlybird --server --port 4711` in the Flow directory before debugging.

**Comment by SamChou19815** [comment] 2024-03-17 03:12
Closing since none of our team member uses debuggers regularly, so we also have no ideas...

**Closed by SamChou19815** 2024-03-17 03:12 UTC
Labels: Build, DX
