### ISSUE TITLE
Event handler parameters not type checked?

### ISSUE THREAD

**Issue by iainbeeston** [facebook/flow#5867] opened 2018-02-24 15:34 UTC
I would expect this to cause an error in flow, but it does not (as of flow v0.66.0)

```javascript
/* @flow */

import React from 'react'

type Props = {}

class TestComponent extends React.Component<Props> {
  handleClick = (x: string) => {
    console.info(x.toLocaleUpperCase())
  }

  render() {
    return (
      <button onClick={this.handleClick}> // *error should appear here*
        Click Me
      </button>
    )
  }
}
```

`<button>`'s `onClick` invokes it's callback parameter with an event object when clicked. In this case the callback parameter expects a string (not an event). However, no error is raised even though the type signature of the callback passed to `onClick` does not match the expected type signature.

If instead of using the DOM button element I use my own component, it correctly raises an error:

```javascript
/* @flow */

import React from 'react'

type ButtonProps = {
  children: string,
  onClick: (SyntheticEvent<HTMLElement>) => ?boolean
}

class Button extends React.Component<ButtonProps> {
  render() {
    <button onClick={this.props.onClick}>
      { this.props.children}
    </button>
  }
}

type Props = {}

class TestComponent extends React.Component<Props> {
  handleClick = (x: string) => {
    console.info(x)
  }

  render() {
    return (
      <Button onClick={this.handleClick}>
        Click Me
      </Button>
    )
  }
}
```

Here's the error I get for this:

```
Cannot create Button element because string [1] is incompatible with SyntheticEvent [2] in the first argument of
property onClick.

 [2]  7│   onClick: (SyntheticEvent<HTMLElement>) => ?boolean
       :
 [1] 21│   handleClick = (x: string) => {
     22│     console.info(x)
     23│   }
     24│
     25│   render() {
     26│     return (
     27│       <Button onClick={this.handleClick}>
     28│         Click Me
     29│       </Button>
     30│     )
     31│   }
     32│ }
```

I've seen this happen for many mouse-related event handlers, and on many different html elements (it's not specific to `<button>` or `onClick`).

**Comment by TrySound** [comment] 2018-03-10 12:37
This is because react dom element are not covered with specific types
https://github.com/facebook/flow/blob/master/lib/react-dom.js#L277

**Comment by TrySound** [comment] 2018-03-10 12:39
Duplicate of #5865
/cc @vkurchatkin

**Closed** 2018-03-10 15:51 UTC
