### ISSUE TITLE
Using generic types in $PropertyType

### ISSUE THREAD

**Issue by prztrz** [facebook/flow#6813] opened 2018-08-29 12:48 UTC
I tried to use generic types with property object in subsequent manner:

Let's say I have some type like this one:

```
type SomeType: {
    a: FirstType,
    b: SecondType
}
```
definition of `FirstType` and `SecondType` is not important right now, but then i created a function:

```
someFunction<T: $Keys<SomeType>(type: T) {
    //do sth
}: $PropertyType<SomeType, T>
```

so generaly i wanted to be sure that my function will return `FirstType` if `type === 'a'` and `SeoncdType` if `type === b` but I got an error: `Cannot use `$PropertyType` because the second type argument must be a string literal.`

Do you have plans to implement something like this or is there any way to workaround this problem?

**Comment by alexandersorokin** [comment] 2018-08-30 19:11
You can use $ElementType.

see:
https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagMqwLaYAqG2AvKAN6Ki2gCGAXKMgE4CumANDXQEbNI9aAGduiAL69aiSOwB2AY2QBLWPNAiCmAGILla+QB4izACQBpTKhFG8hElgB8TgBRoszIgEpzAUWhMQnlkR0w7bTCuUCInKmlQVkxkdlYNVwBGRnp5VG8AbklERFctQj0lVXVXAHJ6Gt8WDkwC0BBNdkVFTBERYtLtCoNqmr4G5jZOVvbMVlZYVkQgA

**Comment by prztrz** [comment] 2018-09-02 19:50
@alexandersorokin thank you for this example it helped me a lot, however could look ath [this](https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagMqwLaYAqG2AvKAN6Ki2gCGAXKMgE4CumANDXQEbNI9aAGduiAL69aiSOwB2AY2QBLWPNAiCmAGILla+QB4izACQBpTKhFG8hElgB8TgBRoszIgEpzAUWhMQnlkR0w7bTCuUCInKmlNeBVkRQALd1Jvajo6RXoxUAByekLGBNoASFZMZHZWDTZOAG5y0DyCwr5S1qqauo0hUUwWnKkpRFctQj0lVXVXYsLfFg5MbxaJqd19OfkFruXGtZagA) ?

In my real life app I am using `switchz depending on `type` arg and then it throws a lot of errors:
* flow expects nullable return although all possible cases are covered with `switch`
* Although I returned expected values for given keys it still complains that returned values are incompatible with values returned for different value of `T`

it looks like flow treats `$ElementType<SomeType, T>` here as an equivalent of `true | false`. Could you give me some furthter advice?

**Comment by alexandersorokin** [comment] 2018-09-03 17:57
1. Currently Flow does not infer empty type for return value type if all cases are covered with switch/if statement or infinite loop exists. You should explicitly tell to Flow that all cases are covered. For example you can use following construction:
```
function someFunction<T: $Keys<SomeType>>(type: T): $ElementType<SomeType, T> {
  switch(type){
    case 'a': return true;
    case 'b': return false;   
    default: return (type: empty);
  }  
}
```

2. It looks like type refinements do not work in that case. I do not know how to fix it without casting all return values in function to type `any`. I did try it but nothing works.
As a workaround you can try to organize the code in different way or cast return value to type `any`.

**Comment by goodmind** [comment] 2019-05-30 08:22
Duplicate of #4211

**Closed by goodmind** 2019-05-30 08:22 UTC
