### ISSUE TITLE
Error_suppressions.No_source exception thrown by flow

### ISSUE THREAD

**Issue by pastelsky** [facebook/flow#8579] opened 2021-01-25 09:56 UTC
Flow version:
0.130.0

## Expected behavior
I recently added some changes to my (largish) flow-typed codebase, that caused `flow status` to give this error —

```
Server threw an exception: Error_suppressions.No_source("\"<NONE>\": (0, 0) to (0, 1)")
Raised at file "string.ml", line 114, characters 19-34
Called from file "src/common/errors/errors.ml", line 154, characters 16-39
```

Because the codebase is large, finding a minimal reproduction scenario for this was tough. I was able to narrow it down to once seemingly innocuous file —

```
// @flow

export type GetAppListingByIdQuery = {
  marketplaceApp: AppListingHostingSelectAppFragment,
};

export type AppListingPartnerFragment = {
  name: string,
  slug: string,
};

export type AppListingHostingSelectAppFragment = {
  partner?: {},
};

```

Here, If I remove either `name` or `slug` from `AppListingPartnerFragment`, the error goes away. Similarly, if I comment out the `AppListingHostingSelectAppFragment` type definition, the error goes away.

This makes very little sense to me, but hopefully it adds to the stack trace in the error thrown. I can reliably reproduce this on my codebase.

## Actual behavior

No such error is thrown

**Comment by dsainati1** [comment] 2021-01-26 15:38
I can't seem to reproduce this error on my end. I put the file you provided in a directory on its own, but Flow completes fine on that file. So I have a couple of questions:

1) Is this file you linked in its own Flow repository? Or are there other files in the repo that might import from it or otherwise use it. I ask because the error you describe seems related to Flow's error suppresions, but there are no suppression comments in the repro you provided, which makes me think the issue might be somewhere else.

2) Flow version 0.130 is about 6 months old at this point, the newest release is 0.143. Does this error still occur in the new version? If not, then my suggestion is to upgrade to the new version, since any fix for this would be released in a subsequent version anyways, which would require an upgrade anyways.

**Comment by pastelsky** [comment] 2021-01-27 09:52
> Is this file you linked in its own Flow repository? Or are there other files in the repo that might import from it or otherwise use it. I ask because the error you describe seems related to Flow's error suppresions, but there are no suppression comments in the repro you provided, which makes me think the issue might be somewhere else.

This file is a part of a larger repository. We do use error suppression quite a bit, however, there are none in this file. I think the change I described is the "trigger" for this error more than the cause.
I'm not really sure how I can isolate the cause.

> Flow version 0.130 is about 6 months old at this point, the newest release is 0.143. Does this error still occur in the new version? If not, then my suggestion is to upgrade to the new version, since any fix for this would be released in a subsequent version anyways, which would require an upgrade anyways.

There seem to be multiple breaking changes between 0.130 and 0.143 so upgrading will take some time. Let me jump up a few versions to see.

**Comment by langri-sha** [comment] 2021-05-21 21:18
I'm running into this issue on `v0.151.0`, on a codebase written for `v0.104.0`. 

Seems things being to break at `v0.140.0`. I've removed all the suppression comments just in case. The codebase is pretty large, but I'd be happy to troubleshoot if someone can provide any suggestions how to narrow things down.

**Closed** 2022-07-31 00:08 UTC
Labels: bug, needs triage
