### ISSUE TITLE
Error not detected when using an intersection of types 

### ISSUE THREAD

**Issue by johnsonw** [facebook/flow#1791] opened 2016-05-15 01:44 UTC
I'm working on putting together a permutation of types that can be used to curry and use partial application. I'm using intersection to accomplish this, but i'm finding there are cases where intersection doesn't work. As a simple example, let's create an intersection of types to curry a function that will receive two parameters:

```
type placeholder = {};
const __:placeholder = {};

type curriedFunction = ((t1:placeholder)=>(t2:number)=>(t1:number)=>number) &
((t1:number)=>(t2:number)=>number);

declare var curry: (arity:number, fn:Function)=>curriedFunction;
const adder = curry(2, (a:number, b:number) => a + b);

adder(1)('a');
adder(__)(7)('a');
```

Notice in the first invocation I am passing a string instead of a number. Flow will catch this due to the second type declared in the `curriedFunction` intersection. Flow also catches the `'a'`  in `adder(__)(7)('a')`. So far, i'm able to curry using both two invocations and three invocations with a placeholder. That's a pretty good start, but i'm missing the simplest case of all: `adder(1,'a')`. Let's add this into the `curriedFunction` intersection:

```
type curriedFunction = ((t1:placeholder)=>(t2:number)=>(t1:number)=>number) &
((t1:number)=>(t2:number)=>number) &
((t1:number, t2:number)=>number);

adder(1)('a');
adder(__)(7)('a');
adder(1, 'a');
```

The first two still receive an error appropriately, but running this in http://tryflow.org/#fdaae8c5fb7aaed2faba85f013d0b699, `adder(1,'a')` doesn't receive an error. This doesn't seem right, let's simplify the `curriedFunction` type and see if it still doesn't report an error:

```
type curriedFunction = ((t1:number, t2:number)=>number);

adder(1, 'a');
```

Wait a minute, now it's reporting that 'a' should be a number when the type isn't an intersection. I've setup an example of this at try-flow: http://tryflow.org/#fdaae8c5fb7aaed2faba85f013d0b699. Is there something I'm missing here? It seems like the intersection should be pretty straight forward but it's possible i'm missing a step.

Here is the code for reference:

```
type placeholder = {};
const __:placeholder = {};

type curriedFunction = ((t1:placeholder)=>(t2:number)=>(t1:number)=>number) &
((t1:number)=>(t2:number)=>number) &
((t1:number, t2:number)=>number);

type curriedFunction2 = ((t1:number, t1:number)=>number);

declare var curry: (arity:number, fn:Function)=>curriedFunction;
declare var curry2: (arity:number, fn:Function)=>curriedFunction2;

const adder = curry(2, (a:number, b:number) => a + b);
const adder2 = curry2(2, (a:number, b:number) => a + b);

adder(1)('a');  // flow catches 'a'; should be a number
adder(__)(7)('a'); // flow catches 'a'; should be a number
adder(1, 'a'); // flow does NOT catch the error here. It should indicate that 'a' should be a number.
adder2(1, 'a'); // flow catchs 'a'; should be a number
```

**Comment by calebmer** [comment] 2017-07-26 22:09
Closing since this issue hasn’t seen a lot of activity. Sorry about that 😣

Please reopen with a reproduction on https://flow.org/try if you are still having issues!

**Closed by calebmer** 2017-07-26 22:09 UTC
