### ISSUE TITLE
flow-remove-types doesn't strip variance sigil 

### ISSUE THREAD

**Issue by mischnic** [facebook/flow#8725] opened 2021-08-15 17:11 UTC
Flow version: "flow-remove-types": "2.157.0"

Input file:
```js
class X {
	static +foo = "abc";
	+bar = "abc";

	run(x: string) {
		return 1;
	}
}
```

(Reduced from https://github.com/facebook/react-native/blob/f51773ecdedbac19d25eb20894e532edef2cb304/Libraries/Components/DatePickerAndroid/DatePickerAndroid.android.js#L80-L84)

## Actual behavior

Output of `yarn flow-remove-types flow.js -a`:

```js
class X {
	static +foo = "abc";
	+bar = "abc";

	run(x        ) {
		return 1;
	}
}
```

## Expected behavior

The variance sigil of the class fields should also be stripped.

**Comment by mischnic** [comment] 2021-08-16 12:19
I see two possible solutions:
- adding `Variance: removeNode,` to the visitor:
https://github.com/facebook/flow/blob/f9afdbc9c5971c2517ce96c64d996325cd6e6405/packages/flow-remove-types/index.js#L153-L171
- or adding `if(node.variance != null) removeNode(context, node.variance);` in here:
https://github.com/facebook/flow/blob/f9afdbc9c5971c2517ce96c64d996325cd6e6405/packages/flow-remove-types/index.js#L200-L204

**Comment by mroch** [comment] 2021-08-18 14:38
duplicate of #8549

**Closed by mroch** 2021-08-18 14:38 UTC
Labels: bug, Closed: duplicate, Accepting PRs
