### ISSUE TITLE
NODE_PATH and "Required module not found"

### ISSUE THREAD

**Issue by mfn** [facebook/flow#1019] opened 2015-10-31 07:41 UTC
I run my project with:
```
$ NODE_PATH=src babel-node src/index.js
works
```
But flow complains:
```
$ flow check
src/index.js:2
  2: import Foo from 'lib/Foo';
                     ^^^^^^^^^ lib/Foo. Required module not found


Found 1 error
$ flow version
Flow, a static type checker for JavaScript, version 0.18.1
```
File layout:
```
./src/index.js
./src/lib/Foo.js
./.flowconfig
```
src/index.js
```JS
/* @flow */
import Foo from 'lib/Foo';
console.log('works');
```
./src/lib/Foo.js
```JS
export default class Foo {}
```
.flowconfig
```
[ignore]

[include]
src/

[libs]
```

How can flow be taught about the concept of `NODE_PATH` ?

**Comment by dmnd** [comment] 2015-11-01 21:31
I think this is a dupe of #48. The comments there have a workaround

**Comment by samwgoldman** [comment] 2015-11-06 20:58
Agreed. @mfn, please let me know if the solution in #48 is insufficient for your use case.

**Closed by samwgoldman** 2015-11-06 20:59 UTC
