### ISSUE TITLE
'flow.exe' unhandled unix exception

### ISSUE THREAD

**Issue by chrizke** [facebook/flow#2183] opened 2016-08-03 08:00 UTC
Thanks for supporting windows! Great job!

Unfortunately, I cannot start the flow server with the default/start command. When I try to run

`flow.exe` or `flow.exe start`

flow crashes with an unhandled unix exception:

> Unhandled exception: Unix.Unix_error(12, "set_close_on_exec", "")

Nevertheless, starting the server with

`flow.exe server`

works and after that calling `flow.exe` works as well.

OS is Windows 7 64bit.

**Comment by gabelevi** [comment] 2016-08-03 18:05
When there is no server running, `flow.exe` will call `flow.exe start`, which creates a new server. Before creating the server, it calls `set_close_on_exec` on stdout and stderr, to avoid leaking those to the new server. It sounds like those calls are failing for you.

I haven't run into this myself, so I'm wondering how to reproduce. Does this happen to you with an empty repo? Like if you make a empty directory, call `flow.exe init` in that directory, and then run `flow.exe start`?

Thanks for the report, by the way!

**Comment by chrizke** [comment] 2016-08-04 07:20
On my machine (Win 7), it is deterministically reproducable as follows:

1. `mkdir flow_exception`
2. `cd flow_exception`
3. `flow.exe init`
4. `echo /*@flow*/ > script.js & echo var x : string = 42; >> script.js`
5. `flow.exe` or `flow.exe start`

**Comment by MoOx** [comment] 2016-08-05 13:01
A coworker is affected by this issue. We is also using Windows 7 64. On my test laptop (running Windows 10), no problem (except #2187 ^^).

**Comment by gabelevi** [comment] 2016-08-07 01:40
Interesting...I think I added the `set_close_on_exec` call after I upgraded my Windows test machine from 8 to 10. I'll see if I can dig up a Windows 7 VM image.

Thanks a ton for the detailed follow up! It really helps!

**Comment by derekgreer** [comment] 2016-08-08 15:40
Also experiencing the same issue: Windows 7 64 bit.

**Comment by gabelevi** [comment] 2016-08-12 02:03
I finally got a Windows 7 machine up and running today and have been investigating. I'm not really too sure what's going on. But here's a quick recap and my guess at what is happening.

`flow start` starts a `flow server` in the background and then exits. This works as expected.

You might want to run `flow start` from node. Maybe with a child_process exec or spawn. However you notice that the exec never returns and the spawn never fires the "close" event. This is because stdout and stderr are leaking to the server, and node's "close" event waits for those to close.

I think this isn't a problem on Linux and OS X, because `Unix.create_process` works correctly and doesn't leak stdout/stderr unless you explicitly create the new process with the same stdout/stderr. But it seems that on Windows those handles do leak.

On Windows 10, calling `Unix.set_close_on_exec` seems to fix the issue. But as this issue notes, that fails for some reason on Windows 7, and I haven't figured out why.

I think what we'll need to do is write a custom version of `Unix.create_process` for Windows that avoids leaking stdout/stderr. Sigh.

**Comment by gabelevi** [comment] 2016-09-01 13:44
This was fixed in v0.31.0

**Closed by gabelevi** 2016-09-01 13:44 UTC
Labels: Windows support
