### ISSUE TITLE
Object.assign({}, objOfType) causes `property not found in object literal` error

### ISSUE THREAD

**Issue by kmiyashiro** [facebook/flow#1805] opened 2016-05-18 01:17 UTC
flow 0.25
node 6.1.0

Is this expected behavior?

``` js
type MyType = {
  optional?: string
}

const test = function test(opts?: MyType = {}) {
  return Object.assign({ hi: 1 }, opts) // property `optional` of object type Property not found in object literal
}
```

**Comment by ericqianli** [comment] 2016-06-09 08:25
I'm having the same issue. It seems when doing Object.assign flow enforces all source fields to exist in the target, which makes no sense to me. See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

**Comment by ilkerguller** [comment] 2016-06-21 14:53
+1 😢

**Comment by SimenB** [comment] 2016-08-06 07:57
Still present in 0.30

**Comment by thejameskyle** [comment] 2016-08-09 18:42
Strange, a work around for now seems to be:

```diff
- return Object.assign({ hi: 1 }, opts)
+ return Object.assign({}, { hi: 1 }, opts)
```

**Comment by SimenB** [comment] 2016-08-09 20:40
@thejameskyle That makes it pass, thanks!

**Comment by Aweary** [comment] 2016-09-16 21:37
We recently ran into this [with React](https://github.com/facebook/react/pull/7736#r78857244), where we use `Object.assign` on the prototype of an internal component to extend it from internal component.

```js
Object.assign(ReactTestRenderer.prototype, ReactMultiChild);
```

**Comment by mockdeep** [comment] 2017-01-27 22:56
Not sure if this is the same issue, but running into something similar with `Object.assign`. Example code:

```js
// @flow
var myObj = { foo: 'blah' }

Object.assign(myObj, { wat: {} });

myObj.wat.bloo = 'blah';

console.log(myObj);
```

produces the following warning:

```
flowtest.js:6
  6: myObj.wat.bloo = 'blah';
           ^^^ property `wat`. Property not found in
  6: myObj.wat.bloo = 'blah';
     ^^^^^ object literal
```

**Comment by mockdeep** [comment] 2017-01-27 23:00
Or is this intended behavior around [object sealing](https://also.github.io/notes/2016/03/13/flow-object-assign.html)?

**Comment by thejameskyle** [comment] 2017-01-27 23:58
Yup, this does have to do with object sealing, it's not really a bug.

There's a difference between empty objects and objects with one or more properties.

```js
const obj1 = {}; // unsealed

obj1.foo = 1;       // Works!
obj1.bar = true;    // Works!
obj1.baz = 'three'; // Works!

const obj2 = { foo: 1 }; // sealed

obj2.bar = true;    // Error: Property not found in object literal
obj2.baz = 'three'; // Error: Property not found in object literal
```

[[Try](https://flowtype.org/try/#0PTAEAEDMBsHsHcBQiDGsB2BnALqWAjAKwEZQBeUAbwF8BuUEUAVywFMBDaVgE2QJIB0kWLHKhi9UFOmMA6rABOAa0wBCRP2ID87BWOwKmrSVLmKV6zdvYAvMQHJsACwWtW9+meVrkaLLn4AJjFKUGFYAC5xUDoGMEwOLl4NIkDrPQoDIxM40ABRBQVFKIAFIoAHVgVsAE9QdFhcYRZuUABLdDwiVhRcaDbsKs4UwjSdOwpHFzcPXIKihVKKqtr6xrDYFvbO-h6+gaHoRCA)]

Closing as this is not actually a bug.

**Closed by thejameskyle** 2017-01-27 23:58 UTC
Labels: bug

**Comment by kmiyashiro** [comment] 2017-03-16 22:55
There's still an issue with the result of Object.assign in this case:
 

```js
type MyObj = {|
  one: number,
  two: number
|}
var a: MyObj = Object.assign({}, { one: 1 }, { two: 2 })
```

**Comment by nmn** [comment] 2017-03-17 00:32
@kmiyashiro That's a bug with exact types that's a known bug and mentioned in another issue.

**Comment by FezVrasta** [comment] 2017-06-13 18:46
Any way to extend `this`?

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzAFsBLADxOzAF4wAKAJzjnwC4wB5AIwCsBTDPgCUNAHydeA-ADoAhrlwkA5tkbN8AGjABvMF1kN2dEdXEByfQC8zYAL5CA3Ogwx5uMADFmO1GD9gsPHwGAFdBOAZ6EW1ffzjSClV8AAsSXEdYv1t0OPw+AmMfOLjA3DgYPml4JToUtOl9BmMMuOzsoA
