### ISSUE TITLE
ErrorEvent not existent for addEventListener, should be alongside ProgressEvent

### ISSUE THREAD

**Issue by CharlesStover** [facebook/flow#5031] opened 2017-10-04 16:12 UTC
That, or ErrorEvent is just missing entirely. I'm not sure how you would want to handle this.

[Specification for ErrorEvent](https://developer.mozilla.org/en-US/docs/Web/API/ErrorEvent)
["the single error event object is supplied to window.addEventListener('error') handlers"](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror#window.onerror)

Flow has 'error' in addEventListener('error', listener) listed in the ProgressEvent types and ProgressEventListener, however it does not acknowledge that the argument to the listener is of type ErrorEvent instead of (or in addition to?) ProgressEvent.

```
var s: HTMLElement = document.createElement("script");
s.addEventListener("error", (event: TYPEHERE) => { alert(event.message ? error.message : 'Script error'); });
```

Using ProgressEvent for TYPEHERE gives an error that message is an unknown property.
Using ErrorEvent for TYPEHERE gives an error that ErrorEvent could not be resolved, nor did I see it defined anywhere in dom.js.

It should either be ErrorEvent or ErrorEvent & ProgressEvent.

**Comment by richsinn** [comment] 2019-07-10 06:11
Out of curiosity, why was this issue closed? It seems like it's closely related to https://github.com/facebook/flow/issues/3819

**Comment by goodmind** [comment] 2019-07-10 06:23
Well, maybe it is duplicate of #3819

**Comment by goodmind** [comment] 2019-07-10 06:23
Duplicate of #3819

**Closed** 2019-07-10 06:23 UTC
Labels: Accepting PRs, Library definitions

**Comment by richsinn** [comment] 2019-07-10 06:32
Well, it seems like #3819 is referring to `lib/bom.js` whereas this one, I'm assuming, would be referring to `lib/dom.js` - though I don't have full context as to the exact differences between the two here.
