### ISSUE TITLE
flow server sometimes doesn't work correctly

### ISSUE THREAD

**Issue by d14b3l** [facebook/flow#1726] opened 2016-04-28 11:52 UTC
When I'm running flow server sometimes after fixing an error in file flow still complains about it in error message but presents the changed code like in example below.

Before changes in file flow shows correct error:

``` javascript
src/tst.js:4
  4:     return param1 + 2;
                ^^^^^^^^^^ string. This type is incompatible with
  3: function investigateFlowServerProblem (param1/*: string*/) /*: number*/{
                                                                    ^^^^^^ number
```

After changes that should fix the problem flow error looks like this:

``` javascript
src/tst.js:4
  4:     return parseInt(param1) + 2;
                ^^^^^^^^^^ string. This type is incompatible with
  3: function investigateFlowServerProblem (param1/*: string*/) /*: number*/{
                                                                    ^^^^^^ number
```

This issue doesn't happen always and I'm not sure in which conditions it is 100% reproducible  but this is definitely a bug. I now for sure that once when this issue showed up I had two flow servers spawned in separate locations.

**Comment by calebmer** [comment] 2017-07-26 21:44
Closing since this issue hasn’t seen a lot of activity. Sorry about that 😣

Please reopen with a reproduction on https://flow.org/try if you are still having issues!

**Closed by calebmer** 2017-07-26 21:44 UTC
