### ISSUE TITLE
Spread operator and Object.assign lose type

### ISSUE THREAD

**Issue by olvnikon** [facebook/flow#6505] opened 2018-06-22 06:06 UTC
After using the spread operator or `Object.assign` we lose the unions of types.

```javascript
type A = {| a: 'a' |};
type B = {| a: 'b' |};
type C = {| a: 'c' |};
type ABC = A | B | C;

const a: A = { a: 'a' };

// Good
const b: ABC = a;
// Fail
const c: ABC = Object.assign({}, a);
const d: ABC = { ...a };
// Ok but we lose the strict type
const e: ABC | {} = { ...a };
```

https://flow.org/try/#0C4TwDgpgBAglC8UDeAfKBDAXFA5OnUKAvgNwBQokUAQgsmlrgEYHHmXQDCdqG2OAY1akK4aDGrdEcNLTSdyZAQHsAdgGdgfWD214CIsgHojUAOLLlAEyVrNUJtglSM5E1ABi6AJYAbWxpaAk6SdADyTABWEALAAHTo6ureAOaqABRIRAA0GACU5CqBUFYhLkhQcVXoUCLuYQDWDgCuWgDu0L7K6tDAABbQmgBO3rFQHAH2EGWEyES6VQm1JEA

**Comment by wchargin** [comment] 2018-06-22 15:33
The spread operator seems to behave consistently with its [expanded form][1]:

```js
// @flow

type A = {| a: 'a' |};
type B = {| a: 'b' |};
type C = {| a: 'c' |};
type ABC = A | B | C;

const a: A = { a: 'a' };

// Good
const b: ABC = a;
// Fail
const c: ABC = { a: b.a };
const d: ABC = { a: ('a': 'a' | 'b' | 'c') };
```

A more [minimal example][2]:

```js
// @flow
({x: ("A": "A" | "B")}: {|+x: "A"|} | {|+x: "B"|});
```

(The failure occurs with any mix of read-only-or-not and exact-or-not.)

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AQVALygDeAPqANQCGAXKAORX2ikC+A3KpjgEKEnlqdegCNmbTumygAwvzKVaDAMbiOXabh5yi+cn3IzOiZbAB2AZxSgl+IsRvCmodYhCgA4rFgATE+atQETotHRtOdwAxKgBLaH9La2UQ7XlHIIA6KhdOU0TQHxSwhyUACkZ6J3EGMRYVegBKHKA
[2]: https://flow.org/try/#0PTAEAEDMBsHsHcBQAKA3gDwFymQIgIK7YG6gA+ouAQrgJQC+2qZA1FpYWfeaM28TS60A3EA

It looks to me like the underlying bug is something more like, “object
of union type is not union of object types”. But, in any case, this also
looks like a duplicate of #6342.

**Comment by olvnikon** [comment] 2018-06-25 06:07
It is a copy of #6342, I agree. In my case I have an array of mixed objects, let's say, A | B | C. That's why I have this issue. I'll try to take a look again, probably, I can find another solution for that.

**Comment by vicapow** [comment] 2019-02-03 02:34
closing as dulicate

**Closed by vicapow** 2019-02-03 02:34 UTC
