### ISSUE TITLE
String literal union type variable cannot be used as a key on an lvalue object without an indexer.

### ISSUE THREAD

**Issue by bmomberger-bitovi** [facebook/flow#7182] opened 2018-11-15 20:58 UTC
```js
/* @flow */
class Vector { 
  x: number 
  y: number 
  constructor(x:number, y:number) { this.x = x; this.y = y; }
}
type xOrY = 'x' | 'y';
const vec = new Vector(1, 0);
const someCondition: boolean = Math.random() < 0.5;
const dim: xOrY = someCondition ? 'x' : 'y';
vec[dim] = 2;  // <-- ^ Cannot assign `2` to `vec[dim]` because an indexer property is missing in `Vector` [1].
```

This isn't a bug, since this isn't specified behavior, but intuitively it should be possible to infer that no type violation is possible here without the use of an indexer property.  Formally:

* Given that type `T` is a union type
  *  And that all types `Ti` in the union `T` are String literal types
  *  And type `U` is an object type
  *  And `Ti` is a keyed type property in `U` for all `Ti` in `T`
  *  And, Given `UTint` is the intersection of all types `U[Ti]`, for all `Ti` in `T`: `UTint` is not null.
* Then a value `V` matching type `UTInt` _should be_ assignable to the key `Ti` in any instance of `U` for any `Ti` in `T`

**Comment by goodmind** [comment] 2019-05-30 19:31
Duplicate of #4014

**Closed by goodmind** 2019-05-30 19:31 UTC
