### ISSUE TITLE
[question] Type Props for basic JSX elements

### ISSUE THREAD

**Issue by cprodescu** [facebook/flow#5865] opened 2018-02-24 00:14 UTC
Are there any packages that define the [list](https://reactjs.org/docs/dom-elements.html) of props that a react JSX element can take?
We would like to type our components as exact, but it's a pain to manually list all of these.

**Comment by cprodescu** [comment] 2018-02-28 18:54
These should also be listed in the `props` sections of `$JSXIntrinsics` definitions in https://github.com/facebook/flow/blob/60e640c2287c2e7b9d0f261e4c8a617763005f1e/lib/react-dom.js#L246

A few questions for the friendly maintainers (cc @samwgoldman):
- Are there any plans on this on the roadmap?
- Is this something you would accept PRs for or do you prefer `flow` react-dom bindings to remain unopinionated about `props` of JSX intrinsics?

**Comment by motiz88** [comment] 2018-08-06 16:46
Essentially a duplicate of https://github.com/facebook/flow/issues/3773

**Comment by goodmind** [comment] 2019-06-22 20:02
Duplicate of #3773

**Closed by goodmind** 2019-06-22 20:02 UTC
