### ISSUE TITLE
[>= v0.89.0] $ObjMap<...> always compatible with empty objects?

### ISSUE THREAD

**Issue by namuol** [facebook/flow#7491] opened 2019-02-20 23:25 UTC
Flow version: **0.89.0 - 0.93.0**

[**Try on Flow.org**](https://flow.org/try/#0C4TwDgpgBAggQgYSgXigbwFBSgQwFxQDOwATgJYB2A5gDRZQBGBx51d2Axs6ZbRgL4BuDBlCRYiAOplgACwByAVwC2DCCUIooAEgDyDAFYBZHGAA88BDSgAKHBRAoAfFAoq1JAJRPhGDgHsKYihgCGIARgJLaTklVXVNVExsfCgABnZGAnDMrigAJjohEQB6EqgASQoANxwAGzIAE2t1En8NIll-AHcKXE0IAA9IDlDG22UyQkJeKAADDjnPPD9A4NDifKipGQV3BK1k3AIM+iYoHPoyqDzCgV9rqtqG5sZFYFd-KFb2zUIu3pQShQJzINIAOgAHABOFYBIIfDbAADM2wQMT28Q6SSu5VSp2w13Ol0J5VuRQe5Se9SaLRIbQ6-x6fWBoIhMNsDHerggEHGwC+3RIpig3V2OgAooMcKNPKsESEwsAACwEbRSmXACw7WL7DQuHGk47pTJE7KmskEO5CIA)

![screen recording 2019-02-20 at 03 17 pm](https://user-images.githubusercontent.com/444629/53132083-6835e200-3523-11e9-92d8-74f87c2d58c5.gif)

## Expected behavior

Given this snippet:

```js
const foo = {
  a: 'test',
  b: 'hello',
  c: 'okay',
};

type FooWithNumbers = $ObjMap<typeof foo, (any => number)>;

const test1: FooWithNumbers = {};
```

I expect to see a warning about missing `a`, `b`, and `c`:

```
9: const test1: FooWithNumbers = {};
                                 ^ Cannot assign object literal to `test1` because property `a` is missing in object literal [1] but exists in object type [2].
References:
9: const test1: FooWithNumbers = {};
                                 ^ [1]
9: const test1: FooWithNumbers = {};
                ^ [2]
9: const test1: FooWithNumbers = {};
                                 ^ Cannot assign object literal to `test1` because property `b` is missing in object literal [1] but exists in object type [2].
References:
9: const test1: FooWithNumbers = {};
                                 ^ [1]
9: const test1: FooWithNumbers = {};
                ^ [2]
9: const test1: FooWithNumbers = {};
                                 ^ Cannot assign object literal to `test1` because property `c` is missing in object literal [1] but exists in object type [2].
References:
9: const test1: FooWithNumbers = {};
                                 ^ [1]
9: const test1: FooWithNumbers = {};
```

## Actual behavior

```
No errors!
```

## Workaround

Wrapping the `$ObjMap`-derived type with `$Exact` seems to eliminate the problem, but this is imperfect for cases where you want an inexact object.

**Comment by jamesisaac** [comment] 2019-02-21 03:18
This is a consequence of Flow treating the empty object as "unsealed".  There's more discussion about it in the docs, and issues like [this one](https://github.com/facebook/flow/issues/7456).

Recommended workarounds seem to be using exact objects, or avoiding `{}`.

**Comment by namuol** [comment] 2019-02-21 19:09
It's worth noting that the problem still exists if you use `$ObjMap` with an exact obj type:

https://flow.org/try/#0C4TwDgpgBAggQgYSgXigbwD4CgpQIYBcUAzsAE4CWAdgOYA0OUARkaZbQ7gMavnX1YMAXwDcWLKEixEAdQrAAFgDkArgFsmEMsRRQAJAHkmAKwCyeMAB54COlAAUeKiBQA+KFXWayASldisLgB7KlIoYAhSAEYiGzlFVQ0tHVQ0RgB6dPwiAAZOKEzmIij8wp4oACYGUSwgA

**Comment by jbrown215** [comment] 2019-02-21 22:31
The issue here is indeed due to `{}` being unsealed. This is on our radar and we know we need to fix it. We are still discussing what a good way to go about fixing it would be.

Duplicate of https://github.com/facebook/flow/issues/7345

**Closed by jbrown215** 2019-02-21 22:31 UTC
Labels: bug
