### ISSUE TITLE
Maybe Type Refining fail in Array method(map/filter/...etc.)

### ISSUE THREAD

**Issue by jetzhliu** [facebook/flow#5541] opened 2017-12-20 11:02 UTC
code see also [here in flow.org/try](https://flow.org/try/#0PTAEAEDMBsHsHcBQ0CmAXUBDAXKA-APIBGAVigMYYC8oArgHYAmKkAlvSo4q5KABSYAlKADeiUKGJlKAOgDWKAJ4BnAYJltoaFACc+c0FQB8WANpyAuoMQBfIA)

```js
// @flow
let a: ?Object = undefined
if (a) {
  Object.keys(a).filter(k => a[k])
}
```

It currently report error as follow:
```
4:   Object.keys(a).filter(k => a[k])
                                ^ computed property. Computed property/element cannot be accessed on possibly null value
4:   Object.keys(a).filter(k => a[k])
                                ^ null
4:   Object.keys(a).filter(k => a[k])
                                ^ computed property. Computed property/element cannot be accessed on possibly undefined value
4:   Object.keys(a).filter(k => a[k])
                                ^ undefined
```

**Comment by TrySound** [comment] 2017-12-20 11:44
It's know problem.
https://github.com/facebook/flow/issues/34

**Comment by apsavin** [comment] 2017-12-20 11:46
Variable with Maybe type can be changed. You [can use](https://flow.org/try/#0PTAEAEDMBsHsHcBQ0CmAXUBDAXKA-APIBGAVigMYYC8oArgHYAmKkAlvSo4q5KABSYAlKADeiUKHKx6AZwyxSoGpgDc40MTKUAdAGsUATxl8FJQdrbQ0KAE59dSgHyhTAbV0BdQYgC+QA_) `const` to ensure flow that refinement will not be lost.

**Comment by jetzhliu** [comment] 2017-12-21 01:28
How about the following case? @apsavin 
[flow/try](https://flow.org/try/#0PTAEAEDMBsHsHcBQkCuA7AxgFwJazaFgKYDOWAFAIYBcoA-APIBGAVkdgJSgDeiooAJyJYUAgpXqhmbbADoA1kQCeJKh1mQc0YgPLzQAXgB8oSgG15AXS60zlxAF8gA)

```js
// @flow
function test(a: ?Object) {
  return a ? Object.keys(a).filter(k => a[k]) : []
}
```

I don't want to add a const variable as `const b = a`, but it can fix this problem.☹

**Comment by jcready** [comment] 2017-12-21 01:37
Function parameters can be overwritten just like in your first example. There is a .flowconfig option you can enable to have flow treat function parameters as constants which would also fix your problem.

**Comment by vicapow** [comment] 2017-12-24 20:15
@jcready Thanks for the info. Could you go into more detail for me and others following along why Flow doesn't maintain the refinement into the body of the function when there's no new assignment of `null` to `a` within it? I've seen folks report this a few times so having a solid explanation would be helpful. Additionally, if this is not a bug, should we close this issue?

````js
function test(a: ?Object) {
  if (!a) {
    return null;
  }
  const keys = Object.keys(a);
  for (const k of keys) a[k]; // Works?
  // keys.filter(k => a[k]); // Flow errors?
}
````

**Comment by vicapow** [comment] 2017-12-24 20:18
Here's one more example that's a little confusing to myself.
````js
function test(a: ?Object) {
  if (!a) {
    return null;
  }
  let b = a; // Magically, this fixes the issue but couldn't `b` just as well be overwritten?
  return Object.keys(b).filter(k => b[k]);
}
````

**Comment by jcready** [comment] 2017-12-24 20:51
So I'm taking a guess here, but I believe the reason your last example works is because there can be not refinement invalidation of `b` because at the point `b` is declared it is typed as just `Object`, meaning it can never become `null`. The `a` function parameter on the other hand was typed as `?Object` and then *refined* to be `Object`, but that refinement can be invalidated. The `b` variable's type did not need to be refined and therefore cannot be invalidated.

**Comment by jcready** [comment] 2017-12-24 20:52
For example, this will throw the same error:

```js
function test(a: ?Object) {
  let b: typeof a;
  if (!a) {
    return null;
  }
  b = a;
  return Object.keys(b).filter(k => b[k]);
}
```

**Comment by stereobooster** [comment] 2018-07-23 18:19
in the latest flow this has no errors

**Comment by SamChou19815** [comment] 2024-08-11 21:40
no longer errors

**Closed by SamChou19815** 2024-08-11 21:40 UTC
