### ISSUE TITLE
Existential check fails with a function

### ISSUE THREAD

**Issue by nmn** [facebook/flow#679] opened 2015-07-31 10:37 UTC
Let's say I have an optional object:
```
var obj: ?Object
```

Reading values of it, correctly throws errors:
```
obj.x // error
```

It's possible to fix this like so:
```
obj && obj.x
```

But this doesn't work and throws an error incorrectly:
```
obj && fn(obj.x)
```

The current workaround to fix this is:
```
obj && fn(obj && obj.x)
```

While not too urgent, this flies in the face of the goals of the project to not take the joy out of Javascript.

**Comment by mroch** [comment] 2015-07-31 16:52
I'm having trouble reproing. I tried this: http://tryflow.org/#ab90bb36476122252488ce1781c3ee7c

**Comment by samwgoldman** [comment] 2015-07-31 18:05
@nmn What exact error is thrown from `obj && fn(obj.x)`?

**Comment by nmn** [comment] 2015-07-31 22:32
@samwgoldman 
`property x Property cannot be accessed on possibly null value null`

The problem is happening in React classes. obj is actually `this.obj`. I'll be able to find the exact place where this happened to me tomorrow.

For now I have something similar that may be of use:

```
// in a React Class
// channel: ?Object
if(this.channel){
  this.channel.bind('client-new-comment', this.newComment) // works
  this.channel.bind('cumulative_participant_count-increased', this.spectatorCountUpdate) //error
  this.channel.bind('participant-muted', this.userMuted) //error
  this.channel.bind('pusher_internal:subscription_succeeded', this.stateChange) //error
  this.channel.bind('broadcast-ended', this.broadcastEnded ) //error
  this.channel.bind('broadcast-banned', this.broadcastBanned) //error
}
```

Interestingly, if there are no function calls that works:
```
if(this.channel){
  this.channel.a
  this.channel.b
  this.channel.c
  this.channel.d
  this.channel.c
  this.channel.b
}
```
This works all fine.

In all cases, as soon as I call the first function, all the `this.channel` calls after that line start throwing errors.

For now my workaround to that problem is:
```
if(this.channel){
  var channel = this.channel
  channel.bind('client-new-comment', this.newComment)
  channel.bind('cumulative_participant_count-increased', this.spectatorCountUpdate)
  channel.bind('participant-muted', this.userMuted)
  channel.bind('pusher_internal:subscription_succeeded', this.stateChange)
  channel.bind('broadcast-ended', this.broadcastEnded )
  channel.bind('broadcast-banned', this.broadcastBanned)
}
```

The same kind of problem also happened with other kind of checks:
```
if(!this.channel){
  return
}
this.channel.bind('client-new-comment', this.newComment) // works
this.channel.bind('cumulative_participant_count-increased', this.spectatorCountUpdate) //error
this.channel.bind('participant-muted', this.userMuted) //error
this.channel.bind('pusher_internal:subscription_succeeded', this.stateChange) //error
this.channel.bind('broadcast-ended', this.broadcastEnded ) //error
this.channel.bind('broadcast-banned', this.broadcastBanned) //error
```

And:
```
this.channel = someFnThatReturnObj()
this.channel.bind('client-new-comment', this.newComment) // works
this.channel.bind('cumulative_participant_count-increased', this.spectatorCountUpdate) //error
this.channel.bind('participant-muted', this.userMuted) //error
this.channel.bind('pusher_internal:subscription_succeeded', this.stateChange) //error
this.channel.bind('broadcast-ended', this.broadcastEnded ) //error
this.channel.bind('broadcast-banned', this.broadcastBanned) //error
```

Hope that helps.

**Comment by samwgoldman** [comment] 2015-07-31 22:38
OK, this now makes sense. This is a very specific manifestation of a pretty well understood shortcoming in Flow: all heap refinements are invalidated when any function is called.

Here's a simple example:

```javascript
function example(x: { foo: ?string }) {
  if (x.foo) {
    (x : string); // OK, we know you're a string
    anyFn();
    (x : string); // Error, anyFn might have assigned x.foo
  }
}
```

In your case, the function that's killing the heap refinement is `bind`, and yeah, you and I know that `bind` isn't going to assign `this.channel`, but Flow doesn't.

The workaround you came to, `var channel = this.channel`, is the recommended workaround.

**Comment by samwgoldman** [comment] 2015-07-31 22:48
Closing this as a duplicate of #282. Please reopen if I misinterpreted something here, and this is actually a different issue.

**Closed by samwgoldman** 2015-07-31 22:48 UTC
