### ISSUE TITLE
Support Node's require('file.json')

### ISSUE THREAD

**Issue by glenjamin** [facebook/flow#167] opened 2014-12-03 16:10 UTC
This seems somewhat related to #73 - i use a `config.json` which is loaded with `require` to setup default configuration for the application.

```js
StartApp(require('./config.json'));
```

This results in a "module not found" error, which can't be fixed via a declaration until it's possible to declare the default export - ideally require-JSON support would give me the complete object as a "type".

**Comment by tcoopman** [comment] 2015-03-24 20:37
I believe this is a duplicate of #51?

**Comment by facebook-github-bot-2** [comment] 2015-08-04 18:06
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by jeffmo** [comment] 2016-02-23 22:41
As of [Flow v0.20](https://github.com/facebook/flow/blob/master/Changelog.md#v0200), Flow can now understand what it means to `require()` or `import` JSON files.

**Closed by jeffmo** 2016-02-23 22:41 UTC
Labels: feature request
