### ISSUE TITLE
`delete` must have the property to get deleted?

### ISSUE THREAD

**Issue by ardok** [facebook/flow#5360] opened 2017-11-17 23:31 UTC
[FlowTry](https://flow.org/try/#0C4TwDgpgBAglC8sBOSCGIA8BvVAuKAdgK4C2ARhEgDRRkD8+x5lAvgHwDcAUKJFAEIJkaTDkakKSdty4BjAPYEAzsCiyIAGw1KhAbTFQAjDTL5DLGgYBMJ-FYtQDAZhYBdGQDMiBWcACWilAe8vIAFOpaADJ+KvgwAJT4glhcUGqKKmoaihAAJkIRGtEqAHRKGn7qofElJKhg4QhsUADyZABWEL4lqEpKfgDmBKFYDrLx8dxphcXAJcFIAKKosgAWjfDNuZoQwNCyJWSTqVBIu0RIBGqaRTHA3CxcXEA)

```
type A = Array<{a: number, b?: number}>;
type B = Array<{a: number}>;

const cells = [{a: 1, b: 1}, {a: 2, b: 2}, {a: 3}];

function foo(cellList: A): B {
  const cloned = cellList.slice().map(c => Object.assign({}, c));
  cloned.forEach(c => delete c.b);
  return cloned;
}

foo(cells);
```

Resulting in:
```
8:   cloned.forEach(c => delete c.b);
                                  ^ property `b`. Property not found in
8:   cloned.forEach(c => delete c.b);
                                ^ object type
```

Am I doing it wrong?
I mean, I just want to have a function that will delete a property from an array of dictionaries.
There's nothing wrong by deleting a property that doesn't exist, right?
```
// All these `delete`s are fine (in terms of JS operations). They're just gonna be a noop
const a = {};
delete a.foo;
delete a.bar;
delete a.whatever;
```

I could get around the error by doing:
```
  cloned.forEach(c => {
    if (typeof c.b !== 'undefined') {
	    delete c.b;
    }
  });
```

But again, that seems to be necessary for a `delete` operation.
For the first child, that is.
I know that it's not safe to do `delete a.b.c`, because `b` might be `undefined`

**Comment by goodmind** [comment] 2019-06-02 11:10
Duplicate of #2207

**Closed by goodmind** 2019-06-02 11:10 UTC
