### ISSUE TITLE
error when combining types with object spread

### ISSUE THREAD

**Issue by chrisdrackett** [facebook/flow#6539] opened 2018-06-28 04:19 UTC
I'm trying to do the following (simplified) and running into issues:

https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AFSgCGAzqAEoCmxAxvpNrGqAOTY32vK2wB2pBv3wBeUAG9EoQQE9oVAFwSpoUGlgAjFPKWTV+3Clw7QAbQAsABgA0VgLrWV+jbAAmMpaYCMANmu+HJwBfKRCQxFwZDCpQADFhAGUUAC8qcjEAEgBpKhlSAB5I6NhIUEhhADpZeQr1LXkAPmQimIAFJgx05VVaAAttVw4+JWo6XAqAOTcqRHCW0ABRAA9cbGJ22E7QMT1QCv2NzsdVasU4xJS0xxDVFURaaDJyABUqFYBhHBi33Co+V3Io3oFU+mH4f1w+XE+wqy1W6w6pGsoFguF6VGwSkE2BQfAA5kEGt1QENXBiABQASmJPX4ggk0ki8mRfQGQ2RqPR2FAQW2oDRKFIFQwiOQ+lA8nwvxWCSZaT5u3F5T4uCSqSUyvGp1qmm0VFMpzspksgXF4XFHFwAFdsHxQPlXCgAG6MuRUETiaWquWkXmcjEe-3YQniVnQQZ-IL5YCOp1NVRhIA

Is this not the same as doing:

https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AFSgCGAzqAEoCmxAxvpNrGqAOTY32vK2wB2pBv3wBeUAG9EoQQE9oVAFwSpoUGlgAjFPKWTV+3Clw7QAbQAsABgA0VgLrWV+jbAAmMpaYCMANmu+HJwBfKRCQxFwZDCpQADFhAGUUAC8qcjEAEgBpKhlSAB5I6NhIUEhhADpZeQr1LXkAPhVEWmgycgAVKgAPXABhHBie3Co+V3JqOlwKgcx+Udx88VoAC21XDj4lSfoKgDk3KmtpSJN4vlwk1NJj2FwVqmwlQWwUPgBzIIblVU3XR4AFABKH76XgCfDiE5yI6gVbrTa3e6PUBBUBie4oUgVDBMDCkZD6UDyfAjXoJU5pdGgonlC5XRRlSrVKi1TTaKimFl2UyWQJE8JEji4ACu2D4oHyrhQADdofIROIyZdKaQ0XcHthFRrHl9lmtoBtRkF8sBpTKmqowkA

(which does work as expected)

**Comment by apsavin** [comment] 2018-06-28 08:54
See [fix](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AFSgCGAzqAEoCmxAxvpNrGqAOTY32vK2wB2pBv3wBeUAG9EoQQE9oVAFwSpoUGlgAjFPKWTV+3Clw7QAbQAsABgA0VgLrWV+jbAAmMpaYCMANmu+HJwBfKRCQxFwZDCpQADFhAGUUAC8qcjEAEgBpKhlSAB5I6NhIUEhhADpZeQr1LXkAPmQimIAFJgx0iQAfFVoAC21XDj4lajpcCoA5NypEbvCW0ABRAA9cbGJ22E7QMXFe1Qrj7c7HVWrFOMSUtMcFlUfaaDJyABUqdYBhHBjP3CofFc5HG9AqP0w-EBuHy4mOFTWGy2HVI1lAsFw-So2CUgmwKD4AHMgg1lKoRq5sQAKACUZP0vAE+HE0ki8jRAyGIzRGKx2FAQT2oExKFIFQwKOQ+lA8nwAPWCTZaSFemlZRuqSU5T4k0utU02iopkudlMlkC0vC0o4uAArtg+KB8q4UAA3VlyKgicTy3CKz2kQW87He4PYEniTnQYaAoL5YAu11NVRhIA)

Duplicates #6502

**Comment by goodmind** [comment] 2019-06-22 20:04
Duplicate of #6502

**Closed by goodmind** 2019-06-22 20:04 UTC
