### ISSUE TITLE
Won't complain when calling properties on function that doesn't exist

### ISSUE THREAD

**Issue by zaaack** [facebook/flow#4767] opened 2017-09-01 01:48 UTC
https://flow.org/try/#0PTAEAEDMBsHsHcBQjIFcB2BjALgS1uqAIIAUAlAN6IC+yRAdAIaPlA

here is typescript: http://www.typescriptlang.org/play/index.html#src=%0A%0Afunction%20A()%20%7B%20%7D%0A%0AA.aa()

**Comment by asolove** [comment] 2017-09-01 03:18
This is a duplicate of #3301. That issue has a discussion which includes a workaround if you need a way to declare a function that has no properties on it and should error if you try to access one.

**Closed by asolove** 2017-09-01 03:18 UTC
Labels: Typing: object model
