### ISSUE TITLE
[feat] Regular Expression Matching — alike String Subtype

### ISSUE THREAD

**Issue by langpavel** [facebook/flow#5941] opened 2018-03-12 03:11 UTC
Should be possible to match string variable against regular expression like this:
```js
// @flow
// Pattern definition compatible with JavaScripts RegExp constructor
type StartsWith = $Match<"^PREFIX">;
type EndsWith = $Match<"SUFFIX$">;
type ContainsWord = $Match<"word", "i">;
type ArticlePath = $Match<"^/article/[:a-zA-Z0-9_-]+$", "i"/>;
```

alternative, more friendly syntax can be for some cases:
```js
// @flow
// Pattern definition as regexp literal
type StartsWith = /^PREFIX/;
type EndsWith = /SUFFIX$/;
type ContainsWord = /word/i;
type ArticlePath = /^\/article\/[:a-zA-Z0-9_-]+$/;
```

Regular expressions may be limited to subset of javascript regular expressions.

**Comment by TrySound** [comment] 2018-03-12 05:21
Duplicate of https://github.com/facebook/flow/issues/4654

/cc @vkurchatkin

**Comment by vkurchatkin** [comment] 2018-03-17 01:12
Duplicate of #4654

**Closed by vkurchatkin** 2018-03-17 01:12 UTC
