### ISSUE TITLE
Incorrect type for export default async function

### ISSUE THREAD

**Issue by vjeux** [facebook/flow#6880] opened 2018-09-12 02:24 UTC
```js
export default async function foo() {};
```

```js
declaration: FunctionExpression
```

but it should be a `FunctionDeclaration`.

http://astexplorer.net/#/gist/d6369715d756f36d68df8dea5a9d5ac9/4fdf2c1d0d1797d295c0a687c7e831cabfa082ba

This was fixed in babylon 7.0.0-beta4 but apparently hasn't been fixed in flow and is causing issues with prettier. https://github.com/prettier/prettier/pull/1047

**Comment by mroch** [comment] 2018-09-12 14:44
Duplicate of #3264

Thanks though!

**Closed by mroch** 2018-09-12 14:44 UTC
