### ISSUE TITLE
support for 32 bit systems

### ISSUE THREAD

**Issue by szagi3891** [facebook/flow#2262] opened 2016-08-16 19:55 UTC
you can add support for 32-bit systems?
I would like to use the module from npm "flow-bin" in my 32-bit linux.

**Comment by gabelevi** [comment] 2016-09-05 03:12
https://github.com/facebook/flow/issues/270 has some context on why this is hard. The shared memory implementation assumes 64 bit, and it would be difficult to re-write for 32 bit.

**Comment by szagi3891** [comment] 2017-05-11 03:01
I suggest closing this issue.

**Comment by goodmind** [comment] 2019-06-04 07:19
Duplicate of https://github.com/facebook/flow/issues/270

**Closed by goodmind** 2019-06-04 07:19 UTC
Labels: Effort: hard, feature request
