### ISSUE TITLE
Compound assignment of object property does not respect property variance

### ISSUE THREAD

**Issue by louischan-oursky** [facebook/flow#5671] opened 2018-01-17 06:18 UTC
See https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDKGAhhgQLxgDeAPqmGANQDGcArgHbkBOAXGE7sAtgCM8PADSpaAXwDc6NpwDOGMCQHEylGgzBsuvAQAZpC9CQB0h7hOZUAjIuu3eYJ-KA

Line 11 should be a type error

**Comment by goodmind** [comment] 2019-05-24 03:34
Duplicate of #7195

**Closed by goodmind** 2019-05-24 03:34 UTC
