### ISSUE TITLE
Typed Holes + Type Wildcards?

### ISSUE THREAD

**Issue by damncabbage** [facebook/flow#2754] opened 2016-11-04 11:44 UTC
Haskell, Idris, Agda, PureScript and some other languages have a couple of different features that are useful for figuring out the types of functions or values:

* **Typed Holes**: Being able to put a _value_ that acts like a placeholder. If the type checker can figure out what the inferred type of that placeholder should be, it tells the user.

* **Partial Type Signatures**, or **Type Wildcards**: Being able to put in a _type_ that acts like a placeholder. If the type checker can infer from function implementations what the type should be, it tells the user.

For clarity, here's an example of each (in PureScript) respectively:

<img width="573" alt="PureScript: Typed Hole" src="https://cloud.githubusercontent.com/assets/133028/20004288/86cd8750-a2df-11e6-9ab0-6de8ca0b6295.png">

<img width="818" alt="PureScript: Type Wildcard" src="https://cloud.githubusercontent.com/assets/133028/20004299/97d43738-a2df-11e6-9715-4dc430f84415.png">

And the closest I've managed to get with Flow (same order):

<img width="824" alt="Flow: Typed Hole Attempt" src="https://cloud.githubusercontent.com/assets/133028/20004298/97c2ce94-a2df-11e6-8e01-c928d2f53f84.png">

<img width="928" alt="Flow: Type Wildcard Attempt" src="https://cloud.githubusercontent.com/assets/133028/20004300/97ebce0c-a2df-11e6-801f-c2628371f7ae.png">

---

In both of these cases, type-checking should "fail", to stop external tools thinking a dev leaving a type-debugging placeholder in the code is hunky-dory; it isn't, and should explode.

The typed-hole suggestion possibly breaks with Flow's current model (i.e. Flow being an overlay that can be removed at any time to result in JavaScript that just runs), but I'm considering it to be something that should never end up in finished real type-stripped code.

I use these a _lot_ with my day-to-day in Haskell and PureScript, to figure out the types of things when I'm deep inside some expression, and I reach for them in similar cases when I go to write Flow. Any thoughts?

**Comment by gcnew** [comment] 2016-11-04 12:34
Seems like a dupe of a questin asked 3 hours prior to this one: https://github.com/facebook/flow/issues/2750

**Comment by damncabbage** [comment] 2016-11-04 12:48
Haha, oh dear. I did have a look for issues, but seemed to miss that one, sorry. 💦 

There's some overlap in the sense that it's talking about using inference to help the dev experience, yeah, but I don't _really_ think it's a dupe. Happy to be corrected, though.

**Comment by gcnew** [comment] 2016-11-04 15:53
Yes, you are right. The linked issue seems to be concerned with the repl only while yours is more general. Type holes are not that old in Haskell too :)

BTW: I just opened flow's issues (haven't used flow at all) and saw two almost consecutive questions that seemed like they asked the same :)

**Comment by damncabbage** [comment] 2016-11-05 00:41
Thanks for linking #2750, @gcnew. It's a different workflow (needs IDE integration, eg. for tooltips or a type-under-cursor shortcut), but as far as I can tell `flow type-at-pos <file> <line> <col>` can handle both the cases I was talking about:

Typed Holes equivalent (check type of var):

<img width="508" alt="screen shot 2016-11-05 at 11 25 17 am" src="https://cloud.githubusercontent.com/assets/133028/20026276/7c194246-a34c-11e6-8b77-9ea7dfbdefb4.png">
<img width="508" alt="screen shot 2016-11-05 at 11 25 54 am hi" src="https://cloud.githubusercontent.com/assets/133028/20026275/7c112282-a34c-11e6-82e4-ac4e41c2bf07.png">


Type Wildcard equivalent (inferring return type of a function, in this case):

<img width="508" alt="screen shot 2016-11-05 at 11 23 37 am b1" src="https://cloud.githubusercontent.com/assets/133028/20026266/6ad08af8-a34c-11e6-8e38-fcfe08a8ea32.png">
<img width="508" alt="screen shot 2016-11-05 at 11 23 58 am b2" src="https://cloud.githubusercontent.com/assets/133028/20026270/72c05036-a34c-11e6-9f2c-c2830b66ead2.png">


Not sure whether or not to leave this issue open. I've edited the first message; I hope there's enough of a summary to make a quick decision either way as to whether this is a useful suggestion or not.

**Comment by damncabbage** [comment] 2016-11-08 02:47
Okay. The tooltips approach for works, but really only for inspecting already-compiling code. I haven't figured out a workaround[1] that works as well as type holes for the not-yet-compiling case.

1. Besides the one in the very first post, eg. `var hole: void;` for values; no idea what to do for functions.

**Comment by SamChou19815** [comment] 2023-02-24 03:29
type-at-pos in IDE should be able to give you the info. We don't intend to introduce other type holes.

**Closed by SamChou19815** 2023-02-24 03:29 UTC
Labels: feature request
