### ISSUE TITLE
Arrow functions cannot be typed

### ISSUE THREAD

**Issue by gcanti** [facebook/flow#297] opened 2015-03-01 10:27 UTC
It doesn't appear to work (for TypeScript v1.4 is ok instead):

```js
/* @flow */
var f = (x: number) => x * 2; // Flow Error: "Invalid left-hand side in formals list"
var f = (x: number): number => x * 2; // Flow Error: "Unexpected token :"
```

FWIW, this does work:

```js
/* @flow */
var f: (x: number) => number = x => x * 2; // ok
```

% flow --version
Flow, a static type checker for JavaScript, version 0.4.0

**Comment by samwgoldman** [comment] 2015-03-01 19:45
This is a duplicate of #37

**Comment by bhosmer** [comment] 2015-03-03 02:01
Hi @gcanti - per @samwgoldman this is on the todo list. Thanks!

**Comment by samwgoldman** [comment] 2015-06-24 00:41
This has been fixed since 0.12. Thanks for the report!

**Closed by samwgoldman** 2015-06-24 00:41 UTC
Labels: incompleteness

**Comment by runn1ng** [comment] 2015-12-14 11:44
Just a quick question - how exactly should I type the parameters and the returning type of the arrow function? As in the @gcanti original example?

**Comment by gabelevi** [comment] 2015-12-14 14:26
Everything in @gcanti's original post should work now. Arrow functions that surround their parameters with parenthesis put parameter type annotations after the parameters and return type annotations after the parens. Type parameters go before the parens, like `var identity = <T>(x: T): T => x`.

We disallow `x: number => x * 10` since it's ambiguous if the annotation is for the parameter type or return type.

**Comment by runn1ng** [comment] 2015-12-14 14:39
Thanks! I couldn't find it anywhere.
