### ISSUE TITLE
Is "Object" an implicit "any"?

### ISSUE THREAD

**Issue by lll000111** [facebook/flow#4726] opened 2017-08-27 10:22 UTC
It surprises me that this doesn't cause any errors. Code:

```javascript
// With or without "Object" type annotation - no difference
const o: Object = {};

// Test 1 (no error)
o.iDontEvenExist();

// Test 2 (no error)
// This is inconsistent even without knowing anything about the object
const n: number = o.number;
const s: string = o.number;
const b: boolean = o.number;

// Finally - at least THIS is an error
const f: string = o;
```

<br>

[**Flow try link**](https://flow.org/try/#0PTAEHUEsBcAtQPYCdQHcawQV2qARAPIBGAVgKYDG0eoAtKAHYKgAmkAZu2UmQxWQCgKCBgGdcCAFyhi5KqAC8oAN4BfANwCBIUAAUAhklwBGAQgB0kACIjoAUQBuvOwA9I4gBQBKTdrAGjUAAmIRFxRmkGLABbIm5FRHMo2O5NYTFcUWlxJEgGAHMEi2S4pDSw3CJpIgQEABsyfQYipJjS3x0AMTz9OrqATzpQfVwG-XCAFQAJAEkAZVB3YebuJGRQjNB2bOhcgqLNIA)

<br>

I think this is too weak. If people don't want to be specific they should say so in their code and use "any".

**Comment by TrySound** [comment] 2017-08-27 14:48
`any` is not an object. `Object` is any object. It's quite useful in opposite to `{}` to pass random object which does not have type annotations.

**Comment by TrySound** [comment] 2017-08-27 14:50
It's not weak. It allows to specify that I need an object here, not string or number.

**Comment by jcready** [comment] 2017-08-27 15:24
It has to with the [`Object` class including this indexer](https://github.com/facebook/flow/blob/master/lib/core.js#L59):

```js
[key:any]: any
```

The same thing is on the [`Array<T>` class as well](https://github.com/facebook/flow/blob/master/lib/core.js#L277):

```js
[key: number]: T;
```

```js
// no errors
const obj = {}
const arr = []
const a: string = obj.foo.bar
const b: string = arr[42].baz
```

**Comment by lll000111** [comment] 2017-08-27 16:00
@TrySound As you can see in jcready's answer, of course there is `any` involved. You even replied _twice_ without contributing anything useful.

**Comment by jcready** [comment] 2017-08-27 16:14
You can force individual objects to no allow this by annotating the object with your own indexer.

```js
type mixedObj = { [key:any]: mixed }
const o: mixedObj = {}
```

From there all of your original expected errors should trigger. I have a feeling that the reason `Object` and `Array<T>` have the `any` indexers is to make adoption easier, but I agree that it's not desirable in all cases.
```

**Comment by lll000111** [comment] 2017-08-27 16:31
@jcready Thanks, but my point is that this is unexpected. After a long time with Flow I feel I can work with the many limitations (many of them not anybody's fault, that's just what is possible), yet it caught even me off guard. I think this should not just pass the way it does. You can find presentations touting how Flow is more strict than its competitor - I don't think the above example, and it even is something common and not something exotic, doesn't fit the narrative.

**Comment by jcready** [comment] 2017-08-27 16:40
Oh, I'm totally with you. I just doubt the flow team would ever accept a PR where you flip those indexers from `any` to `mixed`. Maybe there could be a possibility for flow to add a new pragma `// @flow-strict` which would just interpret all `any` types as `mixed` or something.

**Comment by vkurchatkin** [comment] 2017-08-27 16:43
Indeed, `Object` means `AnyObject`.

**Comment by asolove** [comment] 2017-08-27 19:08
Can you describe the case where you needed to use the `Object` type but where this was unexpected behavior?

In my own code I rarely use `Object` at all. Either I use an object as a dictionary-like thing (`[key: string]: Whatever`) or I know the shape of the object and use a specific object type (`{a: number, b: string}`). Pretty much the only time I use `Object` is if I need to pass through typed code a complex configuration object bound for an untyped library. 

If there's a case where you have an `Object` and need to treat it more strictly, I bet we can find a good way to do that in Flow.

**Comment by jcready** [comment] 2017-08-27 19:15
He's not talking about using the `Object` type annotation (specifically). The issue happens without using annotations on the object. See [my first comment](#issuecomment-325205032). And unless you specify a exact object type or define your own indexer for an object type, the resulting object will still return `any` for any key you access on it which isn't explicitly typed.

**Comment by asolove** [comment] 2017-08-27 21:10
Ah, thanks for the clarification!

So this seems to happen differently depending on the object literal that's used.

For example, if the object literal has some properties, then accessing another one that isn't present does give an error:

```js
let obj = { a: "a", b: "b" };
obj.c; // property c not found
```

If I read the initial comment as being specifically about the type inferred for an empty object, I'm curious what people would suggest as a better option. It could be inferred as `{| |}`, but that's a pretty much useless type and rarely what real-world code means. 

I would guess that most real-world code using `let obj = {}` is right about to mutate and add some properties onto the empty object, so Flow assumes it should just guess `Object` because things are about to be added dynamically with unknown keys and types.

**Comment by mrkev** [comment] 2018-06-20 02:04
This is expected behavior, and a reason why `@flow strict` includes a lint rule against it.

`Object` essentially means it can be any object, and this includes object with any keys and keys of any type. If possible, it's good to avoid it.

I am rather split about inferring `{ [string]: any }` for `const o = {}`-- it's a side-effect of having it be an unsealed object you can assign to. I wonder if it's possible to have it be unsealed for writing, so people can do: 

```
const o = {}
o.foo = 'bar'
```

but not for reading, and rely on the inferred shape of the object for that.

**Comment by vicapow** [comment] 2019-02-01 09:19
To follow up here and answer your original question, `Object` is now an alias to `any`. Before it was more or less `{ [key: string]: any }`. I've also put together some codemods to rename Object accordingly, if you'd like to use them: https://github.com/facebook/flow/issues/7291

Also, it seems like this ticket is conflating a few different things. Specifically around what `Object` means, and also unsealed objects and their behavior. I'm going to close this in favor of: #7291 and #7424

**Closed by vicapow** 2019-02-01 09:19 UTC
Labels: feature request
