### ISSUE TITLE
Bottom type - Problems with the use of

### ISSUE THREAD

**Issue by szagi3891** [facebook/flow#2954] opened 2016-12-06 13:00 UTC
this code is correct :

```
export type CurrentOpenType
= {|
   type: 'message',
   networkId: string,
   messageId: string
|}
| {|
   type: 'thread',
   threadId: string
|};

const get = (current: CurrentOpenType): string => {
  switch (current.type) {
      case 'message': {
          return 'to jest message';
      }
      case 'thread': {
          return 'to jest thread';
      }
      default: {
          (current.type: empty);
          return 'some meaningless value';
      }
  }
};
```

but it will be much better if this could be used in this way:

```
export type CurrentOpenType
= {|
   type: 'message',
   networkId: string,
   messageId: string
|}
| {|
   type: 'thread',
   threadId: string
|};

const get = (current: CurrentOpenType): string => {
  switch (current.type) {
      case 'message': {
          return 'to jest message';
      }
      case 'thread': {
          return 'to jest thread';
      }
      default: {
          (current.type: empty);
          //return 'some meaningless value';     //unnecessary and senseless return
      }
  }
};
```

**Comment by gcanti** [comment] 2016-12-07 06:14
I throw instead of returning a meaningless value

**Comment by minedeljkovic** [comment] 2016-12-07 06:58
You can always return the value that is declared as empty:
```js
...
      default: {
          return (current.type: empty);
      }
...
```
[Try flow](https://flowtype.org/try/#0KYDwDg9gTgLgBDAnmYcDCBXKVgDsYDyKuAKssAFAC8cA3gD4VzNIoBccA5ALbADOfAIYBzYJwA0TZrmAwA7tADWASQAmHPjCgBLXMMnM4vASOBqNW3cIr0AvjbqNDrYB04wAFjkGqJUhF7APuZwmjp6NrYA3BQUAMYQuJpwovA0ABRxWDj4HJjYeITEZCgAlBbhwnBUAHx0Unxy2jBxHnCZ2YUAdC6l9YaGcYJ8qDz8QqKcHLT+A4Y4MFi4XDAQcABW-PDGE2Ixc3D2B0MjK4E+U-0H87JLK2ubyZ7evvtzR3OqwABmghgANjBprMDgs7h0CvgeuQOMBuGAkKU3gMPvZokA)

But I agree with @gcanti and always throw. Simple asserting function can reduce boilerplate slightly:
```js
const assertEmpty = (impossible: empty) => {
  throw new Error(`Unexpected value ${impossible}`);
}

...
      default: {
          return assertEmpty(current.type);
      }
...
```
[Try flow](https://flowtype.org/try/#0MYewdgzgLgBAhhCBTATlAogWwA5QJ4wC8MAFAJY4iJkBGANkgFwxI74CURAfDAN4BQMGFAAWKEAHcYYJFPQpxKEgAMAqjIAe2JMChIAJjABucOgFckMACS8K2KhFoMAvsvYBufs-78kWkGjCeNowAMJmCkhgUADy2mAAKsFI-MS8AD6CQvjazADkmEiIcADmSHkANFnSSFASAQDWAJL6zNAoZGAlVUIwhcVlLW1QHV386d7pfJm9OUwweaIoSHD6ldVLK-pDMO2dJePOnvygkLBlsMQkwBHL0czhkdFxUUna7MOjJdx8WRASZCgwBEpBuTygADo5pwBL1esAEJYCkUIKVysxYXCscsoBEwAsoCAYAArIqwfqosp5TxYmDeWkI5AEsRbPIY6q0mA4vEEomk6DCFmrakcoT0rH6JAAMzgZjoUHZnN63JQ+IQyDQWFweGutyikOhNKx4u8RyAA)

**Comment by szagi3891** [comment] 2016-12-07 07:08
Very clever workaround :) Temporarily I apply it in my code.

**Comment by TrySound** [comment] 2019-02-09 13:07
Duplicate of https://github.com/facebook/flow/issues/451

**Closed by TrySound** 2019-02-09 13:07 UTC
