### ISSUE TITLE
Feature Request: Utility function to get the values of an array (similar $Values for Objects)

### ISSUE THREAD

**Issue by EvHaus** [facebook/flow#6402] opened 2018-05-31 23:57 UTC
At the moment, flow provides a useful` $Values<>` type for getting the type of the keys of an Object. Could we also get a utility that gives us the values of an `Array`, or extend the `$Values<>` type to support Arrays instead of only Objects.

The specific use case I'm after is something like this:

```javascript
const list = ['a', 'b', 'c'];

const myFunc = function (key: $Values<typeof list>) => {
   console.log(key);
}

// This should be allowed
myFunc('a');
myFunc('b');
myFunc('c');

// This should throw an error because the given argument isn't one of the elements in my Array
myFunc('d');
myFunc('e');
myFunc(0);

```

**Comment by Mr-Wallet** [comment] 2020-04-09 20:57
This may be a duplicate of #961

**Comment by gkz** [comment] 2020-04-10 03:09
```
type ArrayValues<TArr> = $Call<<T>(Array<T>) => T, TArr>;
```

https://flow.org/try/#0MYewdgzgLgBAHhAXDAggJzQQwJ4B5poCWYA5gHwwC8MA2gOQAWhdANDHQEbYCmdAugG4AUEKjYADt1QYcANUwAbAK7cIuACro0FagBIAwooW4NZABRacpgJRUK6tpoxlhZgERw3yS9nnLVuGKSIABm8BBk1gIwAPQxMADyANJshFB0EDAABgTEJFlCZgCM3jK+iipqQdyh4ZHRcTAAogBKLQktbGBKALYc3GgwhJnEoD3imFCEHApSAO5pDDC5pEA

**Comment by jcready** [comment] 2020-04-13 17:22
This also works:

```ts
type ArrayValues<TArr> = $ElementType<TArr, number>;
```

**Closed** 2020-04-13 17:28 UTC
Labels: feature request

**Comment by EvHaus** [comment] 2020-04-13 17:39
@gkz @jcready Unfortunately neither of those work for my original usecase

```js
type ArrayValues<TArr> = $Call<<T>(Array<T>) => T, TArr>;
// type ArrayValues<TArr> = $ElementType<TArr, number>;

const list = ['a', 'b', 'c'];

const myFunc = function (key: ArrayValues<typeof list>) {
   console.log(key);
}

myFunc('a');
myFunc('b');
myFunc('c');

myFunc('d'); // This should fail but doesn't
myFunc('e'); // This should fail but doesn't
myFunc(0); // This fails correctly
```

https://flow.org/try/#0C4TwDgpgBAggTnAhiAaogNgVwgZwDwAq8cAfFALxQAkAwhunoSQBTHJMCUFZBANFEQQkA3ACgA9OKihIsBMjRZchYmUpUAouggBbCADtgBcBBUJ++zDoBGEUmNEBjAPb6cwKOgCW7ilADaAOSIgfyB1qFQgY6BALoOLm4eOiAAYpj6jn4AZhmOwF6uUMwA1hAgAFxySKgY2PgyEM7Znj7AJFwA3qJQvYk4ztoAdOjOAOal5RxiAL6iElIEABY+UDhLzpjoACZQtlD0zgDuENuiKemZzMGB0+dpedcRdxeP0bcOkgIrOGsbW7tgEs4McDvooHYQXA9hBHIhMDhoEDoGMvAA3AwHOBjKwGDw+fSBDyuaDNaRLaAQbR6Qy-LzglLVZD3S6Oa7bD4st4QTlAA

It seems to work on types `number` vs` `string` but doesn't interpret string enums.
