### ISSUE TITLE
Flow spins forever on Atom-based projects

### ISSUE THREAD

**Issue by paulcbetts** [facebook/flow#70] opened 2014-11-20 08:29 UTC
Repro:

1. Clone https://github.com/atom/atom
1. `script/bootstrap`
1. `script/build`
1. `cd $TEMP/atom-build/Atom.app/Contents/Resources/app`
1. `touch .flowconfig`
1. `flow --start --all`
1. `flow status`

Even after letting it run for quite some time, I still saw "Flow Server still initializing". I also tried the `[include]` syntax in `.flowconfig` but no dice - either it would spin forever, or it wouldn't detect my modules (and give me the bogus errors described in the troubleshooting guide)

**Comment by samwgoldman** [comment] 2015-06-24 02:37
I'm no longer able to reproduce this with the exact steps. Not because flow is very much faster, but rather because atom's build process has changed and `Atom.app/Contents/Resources/app` doesn't seem to exist anymore.

Regardless, I'm not sure how actionable this issue is, besides "improve performance" which is a) already pretty great IMO, and b) never going to really be done.

Please re-open this is you disagree, but I'm going to go ahead and close this.

**Closed by samwgoldman** 2015-06-24 02:37 UTC
Labels: performance
