### ISSUE TITLE
Hang for override method with rest parameters that recursively calls itself

### ISSUE THREAD

**Issue by andy-ms** [facebook/flow#3443] opened 2017-03-01 20:18 UTC
```ts
// @flow

class A {
    f(x: any, ...args: any[]) {}
}

class B extends A {
    f(x, ...args) {
      if (x.y) {
        this.f(x.y, ...args);
      }
    }
}
```

Type checking never terminates.

**Comment by philikon** [comment] 2017-03-02 18:38
Dupe of #3370?

**Comment by philikon** [comment] 2017-03-02 18:41
cc @gabelevi

**Comment by philikon** [comment] 2017-03-02 18:59
Yep, and much like I pointed out in #3370, if you declare the rest arg types on `B.prototype.f`, the problem goes away:

```
class B extends A {
    f(x, ...args: any[]) {
      if (x.y) {
        this.f(x.y, ...args);
      }
    }
}
```

**Comment by gabelevi** [comment] 2017-03-17 05:27
Ok, I have a fix! I'll try to get it reviewed and cherry picked into v0.42!

**Closed** 2017-03-17 15:59 UTC
Labels: bug, nontermination / perf
