### ISSUE TITLE
Array destructuring and assignment to object

### ISSUE THREAD

**Issue by hymm** [facebook/flow#3268] opened 2017-01-25 17:10 UTC
getting an error I think I shouldn't be getting when trying to destructure a tuple into an objects parameters
```javascript
// @flow
const x = {
    y: 1,
    z: 2,
};

// errors with "unsupported expresssion pattern in destructuring"
[x.y, x.z] = [5, 6];

// this doesn't error
const [y, z] = [5, 6];
x.y = y;
x.z = z;
```

**Comment by goodmind** [comment] 2019-08-20 00:50
Duplicate of #3073

**Closed by goodmind** 2019-08-20 00:50 UTC
