### ISSUE TITLE
Type refinement not working with instanceof

### ISSUE THREAD

**Issue by bluepnume** [facebook/flow#3062] opened 2016-12-21 21:55 UTC
I have the following code:

    function getBar(foo : mixed) {
      if (foo instanceof HTMLElement) {
        return foo.bar;
      }
    }
    
    function getBar2(foo : HTMLElement) {
      return foo.bar2;
    }

`getBar` passes, while `getBar2` fails...

    10:   return foo.bar2;
                     ^ property `bar2`. Property not found in
    10:   return foo.bar2;
                 ^ HTMLInputElement

Surely both of these should fail the type check?

According to the docs, [an instanceof check should refine the type](https://flowtype.org/docs/dynamic-type-tests.html#a-instanceof-b) of `foo` in this case, no?

**Comment by vkurchatkin** [comment] 2016-12-21 23:32
Duplicate of https://github.com/facebook/flow/issues/2282

**Closed by vkurchatkin** 2016-12-21 23:32 UTC
