### ISSUE TITLE
Cannot access property of a type

### ISSUE THREAD

**Issue by ppershing** [facebook/flow#2881] opened 2016-11-23 17:42 UTC
I would expect that
```
type t = {
  	x: () => void,
}

const fn: t.x = () => {}
```
would work, however flow returns
```
5: const fn: t.x = () => {}
             ^ x. Property cannot be accessed on
1: type t = {
        ^ type `t`
```

Any suggestions on how to work around this issue without explicitly declaring all inner types?

**Comment by gcanti** [comment] 2016-11-24 06:16
Seems a dupe of https://github.com/facebook/flow/issues/2865

**Closed** 2016-11-26 07:52 UTC
