### ISSUE TITLE
Flow doesn't check for property initialization

### ISSUE THREAD

**Issue by SamHowie** [facebook/flow#3676] opened 2017-04-06 18:26 UTC
Flow does not check class definitions for property initialization, failing to catch potential runtime errors.

```javascript
class Foo {
  _values: Array<number>;
  
  bar(value: number) {
    this._values.push(value);
  }
}

const foo = new Foo();
foo.bar(10); // Runtime error!
```

It would be safer for the type checker to assert that values not initialized upon declaration or in the constructor need to be a Maybe Type.

This would force the developer to write the below, catching their error:

```javascript
class Foo {
  _values: ?Array<number>;
  
  bar(value: number) {
    this._values.push(value); // Now it's a validation error!
  }
}

const foo = new Foo();
foo.bar(10);
```

**Comment by vkurchatkin** [comment] 2017-04-06 18:27
Duplicate of https://github.com/facebook/flow/issues/650

**Closed by vkurchatkin** 2017-04-06 18:27 UTC
