### ISSUE TITLE
Function Inference w/ Object Properties

### ISSUE THREAD

**Issue by damncabbage** [facebook/flow#2772] opened 2016-11-08 09:15 UTC
Terrible title because I can't quite figure out what to call this. Affects at least Flow 0.34.0.

This is the simplest triggering case I could find for this (original was a set of nested `reduce` loops and a bigger structure):
```js
// @flow
"use strict";
const example = {
  x: { y: 1 },
};
const props = (p) => Object.keys(p)
const key = props(example)[0];
const val = props(example[key]);
```

The error that is thrown:
```
  8: const val = props(example[key]);
                               ^^^ property `y`. Property not found in
  8: const val = props(example[key]);
                       ^^^^^^^ object literal
```

The type of `props` is:
```
$ flow type-at-pos Foo.js 6 7
(p: {x: {y: number}, y: number}) => [string]
```

Doing this resolves the error:
```js
const example = ...
const props1 = p => Object.keys(p)
const props2 = p => Object.keys(p)
const key = props1(example)[0];
const val = props2(example[key]);
```

... As does subbing in `Object.keys(example...)` directly for both cases.

Another example that triggers the error on the same `key` usage:
```js
const example = {
  x: { y: 1 },
};
const props = p => Object.keys(p)
props(example).forEach((key) => {
  props(example[key]);
});
```

And one weird one that *may* be part of this, but I really have no idea:
```js
const example = {
  x: { y: 1 },
};
const props1 = (p) => ["x"] // Works, but (true ? ["x"] : ["y"]) fails.
const props2 = (p) => ["y"] // Works, but (true ? ["y"] : ["x"]) fails.
const key = props1(example)[0];
const val = props2(example[key]);
```

**Comment by vkurchatkin** [comment] 2016-11-08 10:40
The problem is that `Object.keys` tries to be smart and return `Array<$Keys<T>>`, which is incorrect (see https://github.com/facebook/flow/issues/2645). Flow infers type of props as something like `{ ... } | { ... } => ['x' | 'y']` (it is reported as `[string]` but it's obviously not the case).

**Comment by goodmind** [comment] 2019-05-29 03:04
Duplicate of #2645

**Closed by goodmind** 2019-05-29 03:04 UTC
