### ISSUE TITLE
Error:  was expected of type  Unix.file_descr

### ISSUE THREAD

**Issue by mictadlo** [facebook/flow#1358] opened 2016-02-03 04:05 UTC
Hello,
I got the following error:

       Error: This expression has type string but an expression was expected of type
              Unix.file_descr

after I did the following steps:

    sudo apt-get install ocaml libelf-dev opam
    git clone https://github.com/facebook/flow.git 
    cd flow
    make

What did I do wrong?

**Comment by runn1ng** [comment] 2016-02-03 12:37
Duplicate of #1352

**Comment by runn1ng** [comment] 2016-02-04 12:50
Fixed now, I suggest closing

**Closed** 2016-02-05 00:39 UTC

**Comment by mictadlo** [comment] 2016-02-05 02:46
Thank you it works for me, too.
