### ISSUE TITLE
Flow errors when Array<x> is assigned to an Array<y> field when x subclass of y

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#2848] opened 2016-11-19 00:51 UTC
Here is the [code to reproduce](https://flowtype.org/try/#0MYGwhgzhAEBqCWAnALgVzCAoiApgWxwDtloBvAKGmmQE8AHHaAXmgCJt8jlXLpgALeCAAmiIgC5oAQUSIwNADwIU6LLgLEAfOQC+vcqEgwOG5ADkA9sMY4AHsiLCYytBhNcyvYBcIRkiVGBkC0QACgEhUQkZOUV3YktrTQBKTyoqCFQGMOTeKmRBCAA6CJExQmY+QTKiXj09IA) this issue:

```js
class VirtualElement {
  type = "Element"
  children: Array<VirtualElement>
}
  
class ElementNode extends VirtualElement {
  constructor(children:Array<ElementNode>) {
    super()
    this.children = children
  }
}
```

Which produces following errors

```
3:   children: Array<VirtualElement>
                     ^ VirtualElement. This type is incompatible with
7:   constructor(children:Array<ElementNode>) {
                                ^ ElementNode
```

Maybe I'm missing something, but I would expect this to type while it isn't.

**Comment by Gozala** [comment] 2016-11-19 00:53
Oddly enough [following code type checks](https://flowtype.org/try/#0MYGwhgzhAEBqCWAnALgVzCAoiApgWxwDtloBvAKGmmQE8AHHaAXmgCJt8jlXLpgALeCAAmiIgC5oAQUSIwNADwIU6LLgLEAfOQC+vcqEgwOG5ADkA9sMY4AHsiLCYytBhNcyvYBcIRkiVGBkC0QACgEhUQkZOUV3YktrTQBKTyoqCFQGMOTeKmRBCAA6CJExQmZoAG0i2tKowgBdXj09IA)

```js
class VirtualElement {
  type = "Element"
  children: Array<VirtualElement>
}
  
class ElementNode extends VirtualElement {
  constructor(children:Array<ElementNode>) {
    super()
    this.children = [...children]
  }
}
```

But then performance overhead of this is unacceptable :(

**Comment by Gozala** [comment] 2016-11-19 00:56
I also tried [going with types vs classes](https://flowtype.org/try/#0C4TwDgpgBAaglgJ2AVwIYBsCi6IFsIB2wUAvFAN4BQUUokAXFAETZ6HBMA01UAxgBZx0AEwSFGAQQQJUIADzwkaLDnxEAfJQC+PSr3SoAzoais1wAHIB7YdCo060Mi1XsmPAUNHioUmfMUUDDN2TRpeKwJDYARkXmArBAAKTxExAno-WTkQomtbdQBKCh4HQUMAOlTvAlI+QTTCHh0dIA), but I run into same issue:

```js
type VirtualElement = {
  type: "Element",
  children: Array<VirtualElement>
}
  
class ElementNode {
  type = "Element"
  children: Array<VirtualElement>
  constructor(children:Array<ElementNode>) {
    this.children = children
  }
}
```

**Comment by Gozala** [comment] 2016-11-19 01:03
Also worth mentioning that problem only occurs when `Array` is involved for example [following code works](https://flowtype.org/try/#0JYOwLgpgTgZghgYwgAgGrCmArnANgUVwgFsJxkBvAKGWTAE8AHCALmQCJCSyx2AaGskZwoPNukw4CRUuCoBfQVQS44AZzXIussADkA9gBMU1Wg2bIAvB2092g4aPDiM2PLbm0E+kGrBQsBDB9KAAKRzEPPSMIAEpKQTMAC2A1ADoI8mtMsEFFRSA) fine:

```js
interface VirtualElement {
  type: "Element",
  parent: VirtualElement
}
  
class ElementNode {
  type = "Element"
  parent: VirtualElement
  constructor(parent:ElementNode) {
    this.parent = parent
  }
}
```

**Comment by erikdesjardins** [comment] 2016-11-19 01:55
This is correct, it's the classic invariance example:

```js
const dogs: Array<Dog> = getArrayOfDogs();
const animals: Array<Animal> = dogs; // this shouldn't type check, because...
animals.push(new Cat()); // oh no, my dogs array has a cat in it!
```

**Comment by Gozala** [comment] 2016-11-23 22:48
I guess what I really wanted was along these lines instead:

```js
class VirtualElement <Child:VirtualElement<*>> {
  type = "Element"
  children: Array<Child>
}
  
class ElementNode extends VirtualElement<ElementNode> {
  children: Array<ElementNode>
  constructor(children:Array<ElementNode>) {
    super()
    this.children = children
  }
}
```

**Comment by qimingweng** [comment] 2016-12-14 17:56
Here's a simpler test case

```js
class Base {
  id: string;
}

class Test extends Base {
  id: string;
}

const getFirst = (t: Array<Base>): Base => {
  return t[0];
};

const b = new Test();

// This works
getFirst([ b ]);
// This works
const bArray1 = [ b ];
getFirst(bArray1);
// This does not work
const bArray2: Array<Test> = [ b ];
getFirst(bArray2);
```

output

```
11: const getFirst = (t: Array<Base>): Base => {
                               ^ Base. This type is incompatible with
23: const bArray2: Array<Test> = [ b ];
                         ^ Test
```

**Comment by vkurchatkin** [comment] 2016-12-14 18:42
Closing, not a bug

**Closed by vkurchatkin** 2016-12-14 18:42 UTC

**Comment by Gozala** [comment] 2016-12-15 19:29
@vkurchatkin I think maybe morphing this bug into providing better error message would be better than just closing. Once you consider mutation as pointed out by @erikdesjardins behavior starts to make sense, but often times people (at least on my team) tend to not consider that, partially due to algebraic data types being mostly available in languages that are free of this problem due to immutability. I would highly recommend include that in error message.
