### ISSUE TITLE
Flow error only when importing a constant from another file

### ISSUE THREAD

**Issue by tonai** [facebook/flow#6879] opened 2018-09-11 13:18 UTC
This is a strange bug that only happen when importing a constant from another file.

The following code is ok and do not generate any error:
```js
/* @flow */

type StackItem =
  | {
      type: 'TYPE_1'
    }
  | {
      trajectory: number,
      type: 'TYPE_2'
    };

const TYPE_2 = 'TYPE_2';

function test(item: StackItem) {
  switch (item.type) {
      case TYPE_2:
        console.log(item.trajectory);
        break;
    }
}
```
Tested online : https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDKGAhgMYDWAkhngLZgC8qYYAPmAN4uu-b4AuMAHIAKgE0ACgFEA+gEZhPVgF8eHbrz4AnEgCs8ZDHG1YhAOwCudAEZ5tAGmV9ceIWKlyATEq0qA3OhkcOYAzhhgEjKyXkwiUd7CgahQluZGAJYhYLThABQZtHRCxOTURQCUXDyhCIVkABZgBUUAdPx4VZpaYGQkoQQJMQLOWsFhcDB4rfAA5i307boGRiZYFYE9vDbaeCQUm7xqakA

But when you try to import `TYPE_2` from another file, it breaks.

b.js:
```js
export const TYPE_2 = 'TYPE_2';
```

a.js:
```js
/* @flow */

import { TYPE_2 } from './b';

type StackItem =
  | {
      type: 'TYPE_1'
    }
  | {
      trajectory: number,
      type: 'TYPE_2'
    };

function test(item: StackItem) {
  switch (item.type) {
    case TYPE_2:
      console.log(item.trajectory);
      break;
  }
}
```

This is the error I got:
```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/a.js:17:24

Cannot get item.trajectory because property trajectory is missing in object type [1].

 [1] 14│ function test(item: StackItem) {
     15│   switch (item.type) {
     16│     case TYPE_2:
     17│       console.log(item.trajectory);
     18│       break;
     19│   }
     20│ }
```

**Comment by tonai** [comment] 2018-09-13 09:47
@wchargin Thanks for your reply.

It is indeed the reason why this does not work.
But in fact the `b.js` file comes from a compiled modules located in node_modules...
So I can't modify it :/

How can I get around that problem ?

**Comment by NamPNQ** [comment] 2020-03-06 16:24
Because typeof TYPE_2 is string

**Comment by SamChou19815** [comment] 2024-12-11 19:14
Closing since it's expected behavior that files without @flow are just any, unless you configure `all=true`

**Closed by SamChou19815** 2024-12-11 19:14 UTC
