### ISSUE TITLE
Spurious error with Object spread operator and exact Object types

### ISSUE THREAD

**Issue by ml9951** [facebook/flow#3384] opened 2017-02-14 17:20 UTC
I'm getting some unexpected behavior with exact object types and the object spread operator.  The following code:

```JS
type strict = {|a : string, b : number|}

function test(x : strict) : strict{
  return {...x, b : 12}
}
```

produces the following error:

```
test.js:7
  7:   return {...x, b : 12}
              ^^^^^^^^^^^^^^ object literal. Inexact type is incompatible with exact type
  6: function test(x : strict) : strict{
                                 ^^^^^^ exact type: object type
Found 1 error
```

It seems like there are some other issues with the spread operator, and the following issues may be related: #1511 #1793

**Comment by benlangfeld** [comment] 2017-03-13 19:20
I think this is a duplicate of https://github.com/facebook/flow/issues/2405.

**Comment by ml9951** [comment] 2017-03-13 19:30
You're right, closing...

**Closed** 2017-03-13 19:30 UTC
