### ISSUE TITLE
circular references issue?

### ISSUE THREAD

**Issue by pgherveou** [facebook/flow#2322] opened 2016-08-24 04:04 UTC
if I create the following file resource.js

``` js
/* @flow */

export class Query {
  exec (): Promise<SnapShot> {
    return Promise.resolve(new SnapShot())
  }
}

export class SnapShot {
  url: string
  data: Object
  ref (): Resource {
    return new Resource(this.url)
  }
}

export default class Resource {
  url: string
  constructor (url: string) {
    this.url = url
  }
}
```

and then import it in an other file

``` js
/* @flow */

import Resource from './resource'

const resource = new Resource('https://...') 
console.log(resource)
```

flow will fail to identify resource as an instance of Resource

**Comment by samwgoldman** [comment] 2016-08-24 13:33
When you say that "flow will fail to identify resource as an instance of Resource," how are you testing this? The output of `console.log` will tell you what the runtime thinks, not what Flow thinks.

Can you write `const resource: Resource = new Resource('https://...')`?

**Comment by pgherveou** [comment] 2016-08-24 14:43
sorry flow gives me a coverage warning (Not covered by Flow in nuclide) on  the line `const resource = new Resource('https://...') `

if I modify resource.js to the following the warning disappear

```js
/* @flow */

export class Query {
  // exec (): Promise<SnapShot> {
  //   return Promise.resolve(new SnapShot())
  // }

  exec (): SnapShot { 
    return new SnapShot()
  }
}

export class SnapShot {
  url: string
  data: Object
  ref (): Resource {
    return new Resource(this.url)
  }
}

export default class Resource {
  url: string
  constructor (url: string) {
    this.url = url
  }
}
```

**Comment by calebmer** [comment] 2017-07-31 15:29
Closing since this issue hasn’t seen a lot of activity. Sorry about that 😣

Please reopen with a reproduction on https://flow.org/try if you are still having issues!

**Closed by calebmer** 2017-07-31 15:29 UTC
