### ISSUE TITLE
Mark a function as "mutation-safe"?

### ISSUE THREAD

**Issue by cglacet** [facebook/flow#8489] opened 2020-09-22 17:04 UTC
**Flow version**: 0.134.0

Is there a way to "mark" a function as "mutation-safe" (ie. a function that will not mutate anything). 
I have a piece of code that more or less look like this and and would like this code to raise no error (with the addition of a mark on function `IwontMutate`):

```
type T = {
  +a?: ?number
}

function IwontMutate(x: T){
  console.log("I'll never mutate anything");
  // For example, I won't do that `x.a = 3;`
}

const x: T = {a: 2};

if (x.a != null){
  const a: number = x.a;
  IwontMutate(x);
  const b: number = x.a;
}
```

This code raises the following (legitimate) error:

```
Cannot assign `x.a` to `b` because null or undefined [1] is incompatible with number [2]. [incompatible-type]

+a?: ?number          
     ^ [1]

const b: number = x.a;
         ^ [2]
```

**I actually have to questions:**

1. Is there a way to add anything on the function declaration `IwontMutate` to make sure the previous error wont show?
2. If yes, then would it also be possible if the function wasn't mine (a function from the standard library for example)?

**Comment by lyleunderwood** [comment] 2020-09-22 17:48
This appears to be a duplicate of https://github.com/facebook/flow/issues/2715

> Is there a way to add anything on the function declaration IwontMutate to make sure the previous error wont show?

Not currently, no.

**Comment by cglacet** [comment] 2020-09-22 19:04
Ah yes ! That's indeed a duplicate (even though I don't desire any constraint on side effects in general).

**Closed** 2020-10-12 18:16 UTC
Labels: question
