### ISSUE TITLE
Tuple should support ...rest types

### ISSUE THREAD

**Issue by CharlesStover** [facebook/flow#4829] opened 2017-09-07 15:18 UTC
I have an array of [string, boolean, ...string] with a variable length of strings appended to the end. It is not possible to verify this with Flow currently. I propose "...type" should be added to tuples.

**Comment by vkurchatkin** [comment] 2017-09-07 19:38
Duplicate of https://github.com/facebook/flow/issues/2443

**Closed by vkurchatkin** 2017-09-07 19:38 UTC
