### ISSUE TITLE
Over +100% slowdown after upgrading from 0.97.0 and 0.98.0

### ISSUE THREAD

**Issue by Macil** [facebook/flow#7716] opened 2019-05-11 03:41 UTC
In a large project I work with, with Flow 0.97.0, `flow check` would take about 70 seconds on my machine, and 35 seconds on our CI server. With Flow 0.98.0, it takes about 160 seconds on my machine, and 100 seconds on our CI server.

I noticed that Flow 0.98.0 enabled the deprecated-utility lint, so I tested 0.97.0 with that lint enabled, but it didn't seem to affect its runtime.

How should I go about debugging this?

**Comment by dsainati1** [comment] 2019-05-13 17:32
A common cause of Flow performance issues is dependency cycles within a codebase. As a first guess I'd recommend using `flow graph cycle` and `flow graph dep-graph` to see if your codebase contains any dependency cycles that can be refactored. If not, if you can identify and sanitize a smallish repro I can try to investigate the performance issues there.

**Comment by fabiomcosta** [comment] 2019-05-29 01:21
@dsainati1 I'm on `flow-bin@0.98.1` and when I run `flow graph cycle` I get:
```
```

**Comment by dsainati1** [comment] 2019-05-29 17:04
Hmm that's unusual. It works fine for me. Are you running it from inside your project?

**Comment by fabiomcosta** [comment] 2019-05-30 04:53
Yeah, from my project's folder

**Comment by dsainati1** [comment] 2019-05-30 16:58
Weird. I'll take a look.

**Comment by dsainati1** [comment] 2019-05-30 18:42
I am unable to repro this on my mac with a directory containing a `.flowconfig` and a file `my/project/entrypoint.js`. Are you using windows or have some otherwise non-standard settings in your repo?

**Comment by fabiomcosta** [comment] 2019-05-30 18:48
@dsainati1 I'm on macOS as well.

This is our `.flowconfig`:
```
[ignore]
// we do have some ignored paths, let me know if you want more details on this

[untyped]
// we do have some untyped paths, let me know if you want more details on this

[options]
module.file_ext=.js
module.file_ext=.json
module.file_ext=.css
module.file_ext=.ico
module.file_ext=.svg
module.file_ext=.png
module.file_ext=.scss

module.use_strict=true
suppress_type=$FlowIssue
suppress_comment=\\(.\\|\n\\)*\\$FlowFixMe

[lints]
all=warn

[strict]
nonstrict-import
unclear-type
unsafe-getters-setters
untyped-import
untyped-type-import
```

**Comment by dsainati1** [comment] 2019-05-30 19:07
Still can't repro this. Do you have any symlinks in your project? If you could isolate a smallish repro or link to a github project I can investigate directly.

**Comment by fabiomcosta** [comment] 2019-05-30 21:00
Hi @dsainati1 , unfortunately I can't do that, the project I'm working on is not OSS.
@neurosnap @menelike @mjmasn since y'all liked my report, I'm guessing you're also having this issue. Would any of you by chance be working on an open source project and, if yes, can you share that so Daniel can try to repro the issue?

**Comment by fabiomcosta** [comment] 2019-05-30 21:10
As a sidenote, I think that the slowdown on our project is more related to some sort of dep cycle than anything else because we didn't update Flow recently, but it started being significantly slower.
Our project is not 100% covered by Flow, so we are all the time increasing the coverage of that, which probably made Flow "find" a cycle and become slow.
It's significantly slow, in a way that it's being hard to work with it, and our project only contains about 1k modules, which should not be a problem for Flow in normal circumstances.

**Comment by dsainati1** [comment] 2019-05-31 20:14
Yeah, that definitely sounds like a dependency cycle issue, which is the whole reason we wrote the cycle command in the first place. I'd love to fix whatever issue is preventing you from using it; I just can't seem to repro it locally :(

**Comment by fabiomcosta** [comment] 2019-05-31 20:32
@dsainati1 thx for your help so far!
Out of curiosity, what is the output of that command? Can you share an example output?

**Comment by dsainati1** [comment] 2019-05-31 20:51
Usually it outputs a .dot format graph file showing all the files and edges in your dependency cycle. So if you have a file A.js that requires B.js, B.js that requires C.js and C.js that requires A.js, it would output something like:
```
digraph {
    A.js -> B.js,
    B.js -> C.js,
    C.js -> A.js
}
```

**Comment by goodmind** [comment] 2019-06-01 03:36
@dsainati1 I tried running it in my project and it is just unreadable as hell if you render it, and I didn't found any interactive viewers where you can move edges

**Comment by dsainati1** [comment] 2019-06-03 17:04
I like to use Gephi (https://gephi.org/) to visualize the graphs, but I agree that visualization is not always helpful. We output in dot format primarily because that format has more tools like Graphviz that you can use to manipulate the data. If you're interested in breaking up cycles you can use it to identify specific edges that you can remove in order to break a circular dependency.

**Comment by fabiomcosta** [comment] 2019-06-06 23:57
@dsainati1 isn't there a way to make Flow fast even with these dependency cycles?
My fear is that even if I work on removing the cycle today, it will be reintroduced at some point again in the future.
Is there any work on that front?

**Comment by dsainati1** [comment] 2019-06-07 00:06
We are actually finishing up work on a rearchitecture of Flow that will hopefully eliminate the cycle problem, but enabling the new mode requires some significant changes to a codebase (namely annotating the types of all module exports), but we will hopefully have something to say about this soon. 

FWIW, the dependency cycle idea was just a guess as to the slowdown. It's definitely weird that `graph cycle` is broken for you (and I would love to fix this if I could repro it), but if you are experiencing perf problems some other potential causes are large types. Very large objects and large union or intersection types can also cause Flow to experience exponential blowups in the amount of work necessary to check a file.

**Comment by fabiomcosta** [comment] 2019-06-07 04:26
When I update to the latest version of Flow and run it on my project, I get the following error:
```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/common/apps/Editor.js:0:1

Internal error: merge job timed out after 105.02 seconds
```

Is that a hint for a dep cycle?

**Comment by dsainati1** [comment] 2019-06-07 17:11
This almost certainly implies that you have a large cycle somewhere, since this error only occurs if we spend >105 seconds checking a cycle component (a component is a group of files that have to be checked together because they are in a dependency cycle). If you look at the `.log` or `.log.old` files after running a check, there should be a list of slow components, along with the time taken to check them. Find the list of files that took 105 seconds and that should indicate to you all of the files present in this cycle.

**Comment by fabiomcosta** [comment] 2019-06-07 17:16
Awesome, hopefully I'll be able to improve that.
In the meantime, I can't wait to have Flow be fast on these scenarios =D

**Comment by fabiomcosta** [comment] 2019-06-17 21:27
@dsainati1 I'm sill trying to make the rechecks faster. I think I made some progress, the list of files on the `slow MERGE` list is smaller now, but there is still a `slow MERGE` being logged.
Would having more `@flow strict-local` modules help improve the speed?

Any tips on how I could improve the speed in general other than fixing the cyclic dependencies (wish I sort of have fixed I think)?

**Comment by dsainati1** [comment] 2019-06-17 21:38
Oh that's great to hear. `flow strict` is mostly for safety, so I don't think it would have that much of an impact on performance. 

Other than cycles, the big performance sink is union types. If you have lots of large union types being compared against each other this can cause quadratic (relative to the number of elements of the union) performance blowups. These unions might be explicit, but they might also appear from inference and use of $Keys on large objects. To guard against complex types that emerge during inference, I'd recommend seeing what effect adding more annotations to your modules has on performance. If your performance issues are caused by complicated inference this can help.

**Comment by fabiomcosta** [comment] 2019-06-17 22:08
Our application has a big union type for all our redux actions, but I don't see a way around it, unless I want to make it `any` haha.
I used `any` as our Action type just to see what happens. It does improve the performance, but the server still takes 10 seconds to answer after any file change.

**Comment by fabiomcosta** [comment] 2019-06-17 22:13
Here is what I see on the log after any file change:
```
[2019-06-17 15:10:36.618] Persistent request: lspToServer textDocument/didChange
[2019-06-17 15:10:36.618] Persistent response: Ok lspFromServer None
[2019-06-17 15:10:37.148] Running a serial workload
[2019-06-17 15:10:37.148] Persistent request: lspToServer textDocument/typeCoverage
[2019-06-17 15:10:37.338] Persistent response: Ok lspFromServer textDocument/typeCoverage
[2019-06-17 15:10:37.340] recheck 1 modified, 0 deleted files
[2019-06-17 15:10:37.340] modified files:
[2019-06-17 15:10:37.340] 1/1: /src/common/actions/save.js
[2019-06-17 15:10:37.340] Parsing
[2019-06-17 15:10:37.502] Re-resolving directly dependent files
[2019-06-17 15:10:37.526] Recalculating dependency graph
[2019-06-17 15:10:37.569] remerge 481 dependent files:
[2019-06-17 15:10:37.569] 1/481: /src/client/error.js

[... list of 481 other modules]

[2019-06-17 15:10:37.576] Merge prep
[2019-06-17 15:10:37.576] to_merge: Focused: 1, Dependents: 481, Dependencies: 0
[2019-06-17 15:10:37.576] Calculating dependencies
[2019-06-17 15:10:37.582] Merging
[2019-06-17 15:10:48.127] sending (0 errors) and (warnings from 1 files) to 1 subscribed clients (of 1 total)
[2019-06-17 15:10:48.297] sending (0 errors) and (warnings from 4 files) to 1 subscribed clients (of 1 total)
[2019-06-17 15:10:48.351] sending (0 errors) and (warnings from 7 files) to 1 subscribed clients (of 1 total)
[2019-06-17 15:10:48.364] sending (0 errors) and (warnings from 8 files) to 1 subscribed clients (of 1 total)
[2019-06-17 15:10:48.390] sending (0 errors) and (warnings from 3 files) to 1 subscribed clients (of 1 total)
[2019-06-17 15:10:48.409] sending (0 errors) and (warnings from 5 files) to 1 subscribed clients (of 1 total)
[2019-06-17 15:10:48.632] sending (0 errors) and (warnings from 6 files) to 1 subscribed clients (of 1 total)
[2019-06-17 15:10:48.639] sending (0 errors) and (warnings from 1 files) to 1 subscribed clients (of 1 total)
[2019-06-17 15:10:48.645] sending (0 errors) and (warnings from 6 files) to 1 subscribed clients (of 1 total)
[2019-06-17 15:10:48.725] sending (0 errors) and (warnings from 2 files) to 1 subscribed clients (of 1 total)
[2019-06-17 15:10:48.795] sending (0 errors) and (warnings from 1 files) to 1 subscribed clients (of 1 total)
[2019-06-17 15:10:48.796] sending (0 errors) and (warnings from 2 files) to 1 subscribed clients (of 1 total)
[2019-06-17 15:10:48.815] sending (0 errors) and (warnings from 1 files) to 1 subscribed clients (of 1 total)
[2019-06-17 15:10:48.880] sending (0 errors) and (warnings from 1 files) to 1 subscribed clients (of 1 total)
[2019-06-17 15:10:48.981] sending (0 errors) and (warnings from 1 files) to 1 subscribed clients (of 1 total)
[2019-06-17 15:10:48.982] sending (0 errors) and (warnings from 1 files) to 1 subscribed clients (of 1 total)
[2019-06-17 15:10:48.982] sending (0 errors) and (warnings from 3 files) to 1 subscribed clients (of 1 total)
[2019-06-17 15:10:49.096] sending (0 errors) and (warnings from 4 files) to 1 subscribed clients (of 1 total)
[2019-06-17 15:10:49.112] sending (0 errors) and (warnings from 1 files) to 1 subscribed clients (of 1 total)
[2019-06-17 15:10:49.191] sending (0 errors) and (warnings from 3 files) to 1 subscribed clients (of 1 total)
[2019-06-17 15:10:49.216] sending (0 errors) and (warnings from 1 files) to 1 subscribed clients (of 1 total)
[2019-06-17 15:10:49.216] Merge skipped 0 of 482 modules
[2019-06-17 15:10:49.219] Done
[2019-06-17 15:10:49.227] Checked set: Focused: 989, Dependents: 0, Dependencies: 31
[2019-06-17 15:10:49.256] sending (0 errors) and (warnings from 538 files) to 1 subscribed clients (of 1 total)
```

Is doing all this common?

**Comment by dsainati1** [comment] 2019-06-17 22:33
When you change a file Flow needs to recheck all the transitive dependents of that file in case a change you made in that file causes new type errors later in the dependency tree.

**Comment by fabiomcosta** [comment] 2019-06-17 23:21
@dsainati1 removing some of the cycles I could see that Flow starts to log `[2019-06-17 15:10:49.216] Merge skipped 481 of 482 modules`, and everything stars to be much faster.
But in this process I had to make some types `any` in order to remove some `imports, which is not ideal.
So it sounds like those cycles are causing Flow to never skip any module when checking, causing the slowness on rechecks.

**Comment by dsainati1** [comment] 2019-06-18 00:01
Yeah that is the big performance issue with cycles; they make all dependencies into dependents as well (and vice versa). Getting rid of them sounds like it will fix your perf issues for sure.

**Comment by fabiomcosta** [comment] 2019-06-18 17:05
@dsainati1 I which there was a `mode/option` that would throw an error if a cycle is created, because even if I get rid of all the cycles, new ones are going to be quickly created back again.

**Comment by fabiomcosta** [comment] 2019-06-18 17:05
Is this in an advanced state?
https://github.com/facebook/flow/issues/7716#issuecomment-499712653

**Comment by dsainati1** [comment] 2019-06-18 17:20
Yes! It is. We will hopefully have details to announce publicly soon. 

As far as preventing new cycles, I like this idea, and this is something I've been thinking about for a while. The question is how best to add such a feature. Short of that, the solution I usually recommend is some kind of pre-commit hook that checks each changed file to ensure that `flow graph cycle file.js` produces an empty graph.

**Comment by fabiomcosta** [comment] 2019-06-18 17:23
@dsainati1 thank you for the suggestion!
At least I have something that I can work with while waiting for this new feature!
I can't wait for it!

**Comment by Brianzchen** [comment] 2020-08-26 00:19
Performance improvement was released as [types-first architecture](https://medium.com/flow-type/types-first-a-scalable-new-architecture-for-flow-3d8c7ba1d4eb) in v0.125.0, closing issue unless still needed

**Closed by Brianzchen** 2020-08-26 00:19 UTC
Labels: bug, nontermination / perf
