### ISSUE TITLE
Flow ignores that I in fact do check for undefined

### ISSUE THREAD

**Issue by lll000111** [facebook/flow#3322] opened 2017-02-02 08:51 UTC
`p` in line 18 cannot be `undefined`, obviously. Yet Flow complains. Code:

```javascript
// @flow
'use strict';

type PromiseProducingFnT = (...args: Array<*>) => Promise<*>;

const promiseTypes: Map<string, Promise<any>> = new Map();

const serialize = function (...fns: PromiseProducingFnT[]): Promise<*> {
    return Promise.resolve(42);
};

const serializeWithType = function (type: string, ...fns: PromiseProducingFnT[]): Promise<*> {
    let p: ?Promise<*> = promiseTypes.get(type);

    if (p === undefined) {
        p = serialize(...fns);
    } else {
        p = serialize(() => p, ...fns);
        //                 ^^^
        //                 FLOW ERROR
    }

    promiseTypes.set(type, p);

    return p;
};
```

Flow output for this code:

```
$ flow
lib/test.js:18
 18:         p = serialize(() => p, ...fns);
                                 ^ null. This type is incompatible with
  4: type PromiseProducingFnT = (...args: Array<*>) => Promise<*>;
                                                       ^^^^^^^^^^ Promise

lib/test.js:18
 18:         p = serialize(() => p, ...fns);
                                 ^ undefined. This type is incompatible with
  4: type PromiseProducingFnT = (...args: Array<*>) => Promise<*>;
                                                       ^^^^^^^^^^ Promise


Found 2 errors
```

EDIT:

So I read https://flowtype.org/docs/dynamic-type-tests.html and the section "Caveats". However, I don't see any possible way for the value of `p` to change here, it's lexically scoped, there is no loop or anything, whatever value `p` has at that point remains. No? And I have to include a check for another impossibility, this can never be `null`. The only place where `p` is set and put into the Map object is from the function that we guarantee to return a promise, so only `undefined` is possible.

EDIT^2:

Okay, so I thought about it and now I'm sure after another look at https://flowtype.org/docs/dynamic-type-tests.html and the examples there under "Caveats". The difference is there it's about accessing an object property, which indeed can change. The other example with `x: ?string` really can be `null`, the type allows it.

However, here we have a lexically scope variable - directly, not a property inside it, and it cannot be `null` or `undefined` according to all our types.

Note that the value of `p` is caught when the function is run, and while it can be `undefined` the `if` statement filters that. Subsequent runs of the function won't have any influence over `p` sent to `serialize()`!

A static analysis can conclude that `p` in the position of the Flow error on line 18 cannot be undefined, ever, not if the type information is true. Neither the arrow function parameter, nor the value returned from `serialize()`.

**Comment by jesseschalken** [comment] 2017-02-03 08:10
Anonymous functions capture variables by reference, not by value.

```js
let a = 1;
let f = () => { console.log(a); };
a = 2;
f(); // 2
```

So even though `p` won't be `undefined` or `null` when the callback is created, it could be `undefined` or `null` when the callback is run. Flow doesn't know that `serialize()` will call the callback given to it immediately. For all Flow knows, it could be called 2 weeks from now, and since `p` is a mutable variable that is nullable, it could have been set to `null` or `undefined` by then.

**Comment by lll000111** [comment] 2017-02-03 08:35
This is completely besides the point. The code doesn't modify it. There is no unknown code running somewhere else. We (Flow) see(s) all the code, and none of it modifies the value.

**Comment by jesseschalken** [comment] 2017-02-03 08:58
You declared a mutable variable with `let`. It doesn't matter that you don't assign `null` or `undefined` to it. You said it is mutable, so Flow takes what you said as true.

For the same reason, Flow rejects this code:

```js
const x: string|number = 2;
x.toFixed();
```
```
2: x.toFixed();
     ^ property `toFixed`. Property not found in
2: x.toFixed();
   ^ String
```

Why? After all, Flow can "see" all the code, and can see that the only possible value for `x` is `2`. So according to your logic, this shouldn't be an error. But it is, because if you say something (`x: string|number`), it will make sure that it's correct (`2` is compatible with `number`), but won't refine your statement to a stronger one (`x: number` or `x: 2`).

This is important, because declaring `string|number` _tells_ the rest of the code not to assume the variable will contain only `2` or only `number`, and you therefore have a guarantee that you can change the value of `x` to anything else that is `string|number` and the rest of the code will still type check. If Flow strengthened the type based on what you assigned to the variable, it would be breaking the contract that _you_ specified between the the line that assigns `x` and the rest of the code.

It's the same with mutability. If you specify a variable as immutable with `const`, Flow will prevent you from modifying it, but if you specify it as mutable with `let`, Flow takes what you said as true and lets you modify it, but as a consequence it has to assume that variable could change before it is used by a closure that captures is. You said it's mutable, so it is. The fact that Flow can't see any assignments of `null` or `undefined` is irrelevant. By making it mutable, you're stating that you want the freedom to do that in the future and that nothing else should assume otherwise. If you want an immutable variable, then make one.

**Comment by lll000111** [comment] 2017-02-03 09:00
???

Anyway, that doesn't make sense. Flow is supposed to use the actual code.

**Comment by mroch** [comment] 2017-02-03 22:16
This is a known limitation and is one of the pessimistic refinement invalidations that are referred to in the Caveats section (those docs list one or two examples of things that cause invalidation and do not claim to be exhaustive). As @jesseschalken said above, Flow doesn't know that `serialize()` will call its callback immediately, so it assumes it doesn't. Its refinement invalidation is also not able to look ahead to the rest of the scope to see that it is never reassigned. For now, you need to do that yourself using `const`.

This is a duplicate of https://github.com/facebook/flow/issues/1655 and https://github.com/facebook/flow/issues/2078

**Closed by mroch** 2017-02-03 22:16 UTC
Labels: Closed: duplicate, Closed: wontfix

**Comment by lll000111** [comment] 2017-02-07 10:15
> Flow doesn't know that serialize() will call its callback immediately

How is this an argument?

It does not matter WHEN it is called!

**The function has been declared as NEVER returning null/undefined!!!**

Even if it is called hours later, the return value CANNOT be undefined or null! The Flow type annotation says so!!

**Comment by lll000111** [comment] 2017-02-07 10:27
@jesseschalken and @mroch 

> Flow doesn't know that serialize() will call its callback immediately

How is this an argument?

It does not matter _when_ it is called!

The function has been declared as **never** returning null/undefined!

Even if it is called hours later, the return value **cannot** be undefined or null! The Flow type annotation says so!!

I would accept that you can say that the value can change and I would not expect Flow to have to know that, but **this isn't about ANY value, this is about null/undefined - WHICH ARE FORBIDDEN BY THE FLOW TYPES!**

The ONLY place where null/undefined can possibly be assigned to `p` is in the line in front of the `if` statement that guards against those! The other assignments to `p` are from a function with a Flow return type that EXCLUDES null/undefined!

So this isn't about random value changes (which may happen, as I said, I don't expect Flow to know what happens elsewhere). This is ONLY about the possibility of null/undefined, which the Flow types themselves exclude as an option.

Please reopen this valid issue. I would appreciate if people commenting would refer to the ACTUAL ISSUE that the ticket is about! I am well aware of Flow's stated limitations and this is NOT about those.
