### ISSUE TITLE
Definitely need to be able to spread Tuples/Arrays

### ISSUE THREAD

**Issue by bradennapier** [facebook/flow#5354] opened 2017-11-16 21:27 UTC
I have run into this a few times now.  Essentially I end up having a situation where I have an array that is more specific than array can provide. 

For example, say I have an array of key/value pairs rather than every value in the array being identical.  In general a tuple is how you could do this:

```js
type T = [string, number]
```

However, if instead of that it is the given structure of an unknown length, we don't have any solution.  

```js
type T = [string, number, string, number, string, number, ...]
```

---

That is a simplified example of the issue here.  Using Array would allow number where string is expected.  I could reform the way the data is structured to be `Array<[string, number]>` in this case but that also isn't a very good option since that isn't always possible.

In my specific case right now, the structure is as follows:

```js
type InvokeCheck =  boolean | (() => mixed) | mixed;
type InvokeFn = <A>(arg: A) => mixed;

// Below is the problem.  The idea is that the first element is an InvokeCheck that, when passed, 
// iterates the rest of the elements which are InvokeFns.  
// $ExpectError
type InvokeTest = [InvokeCheck, ...Array<InvokeFn>];

type InvokeTesters = Array<InvokeTest>;

type InvokeTests = Array<InvokeTesters>;
```

I am sure there are complexities to such a thing and I am sure the Flow team is working hard on providing more and more idioms for handling more complex or specific data structures.  Much appreciated all the work that is done here!  

---

Restructuring it, for example to instead be something like this:

```js
[InvokeCheck, Array<InvokeFn>]
```

would work, but it ends up making the code very difficult to read and work with (especially in this case when looking at the big picture).

**Comment by goodmind** [comment] 2019-05-30 01:18
Duplicate of #4413

**Closed by goodmind** 2019-05-30 01:18 UTC
Labels: Typing: tuple, feature request
