### ISSUE TITLE
Default value expressions in functions have incorrect 'this'

### ISSUE THREAD

**Issue by LPGhatguy** [facebook/flow#3070] opened 2016-12-22 19:41 UTC
I'm using this Flow-enhanced JS:

```js
// @flow

class XYZ {
	x = 5;

	show(value: number = this.x) {
		console.log(value);
	}
}
```

Flow says:
```
XXX: 	show(value: number = this.x) {
     	                          ^ property `x`. Property cannot be accessed on
XXX: 	show(value: number = this.x) {
     	                     ^^^^ global object
```

But stripping the types and running this in Chrome works just fine!

```js
class XYZ {
	constructor() {
		this.x = 5;
	}

	show(value = this.x) {
		console.log(value);
	}
}

new XYZ().show(); // 5
```

In addition, [this MDN example](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters#Default_parameters_are_available_to_later_default_parameters) seems to note that `this` should be the function, not the global scope in default parameters.

**Comment by danieljuhl** [comment] 2017-01-11 10:09
Duplicate of #1234

**Closed** 2017-01-11 11:31 UTC
