### ISSUE TITLE
$ObjMapi, $ObjMap and $TupleMap allow invalid writes

### ISSUE THREAD

**Issue by vkurchatkin** [facebook/flow#2674] opened 2016-10-23 17:02 UTC
Example 1:

``` js
type A = $ObjMapi<{ FOO: null }, <K>(k:K) => K>
declare var a: A;

(a.FOO : 'FOO'); // ok
(a.FOO : 'BAR'); // error
a.FOO = 'BAR'; // no error
```

Example 2:

``` js
type A = $ObjMap<{ FOO: null }, <K>(k:K) => 'FOO'>
declare var a: A;

(a.FOO : 'FOO'); // ok
(a.FOO : 'BAR'); // error
a.FOO = 'BAR'; // no error
```

Example 3:

``` js
type A = $TupleMap<[mixed, mixed], <K>(k:K) => 'FOO'>
declare var a: A;

(a[0] : 'FOO'); // ok
(a[0]: 'BAR'); // error
a[0] = 'BAR'; // no error
```

See: https://github.com/gcanti/flow-runtime/issues/11

/cc @gcanti

**Comment by gcanti** [comment] 2016-10-23 17:05
This is pretty bad for libraries like [validated](https://github.com/andreypopp/validated) or [flow-runtime](https://github.com/gcanti/flow-runtime) which rely on `$ObjMap` in order to build and extract a static type from a runtime value representing a schema.

/cc @andreypopp

**Comment by vkurchatkin** [comment] 2016-10-23 17:53
This affects only setting properties and literal assignment:

```js
var a: A = { FOO: 'BAR' }; // no error
```

but:

```js
declare var b: { FOO: 'BAR' };
var a: A = b; // an error
```

and:

```js
type A = $ObjMap<{ FOO: null }, <K>(k:K) => 'FOO'>

declare var b: { FOO: number };
var a: A = b; // an error
```

but:

```js
declare var b: { FOO: string };
var a: A = b; // no error
```

**Comment by samwgoldman** [comment] 2016-10-23 20:45
You're right, this is a problem. The cause in the implementation is that we use the existing mechanism for function calls to perform the mapping. This is convenient, but inherits an unfortunate behavior:

```
declare function f(): string;
var x = f();
if (true) x = 0; // cond. assign to avoid definite assignment refinement
(x: void); // errors: number|string ~> void
```

Calling a function returns a new, open tvar with the function return type as a lower bound. This doesn't prevent more lower bounds from flowing in, but all inflowing lower bounds are checked against any uses, so it's not totally unsound.

Just explaining this behavior, not excusing it. We should work to make the generate type more precise, because unlike function calls, these types come from annotations where people rightfully expect to establish an exact constraint, not just the lower bound side of one.

**Comment by vkurchatkin** [comment] 2016-10-23 21:05
@samwgoldman I though it was the case, but how does it explain this:

```js
type A = $ObjMapi<{ FOO: null }, <K>(k:K) => K>
declare var a: A;

(a.FOO : 'FOO'); // ok
a.FOO = 'BAR'; // no error, a.FOO should 'FOO' | 'BAR'
(a.FOO : 'FOO'); // error
```

**Comment by samwgoldman** [comment] 2016-10-23 21:11
That's caused by definite assignment analysis. On that line the value is definitely BAR. Wrap in a conditional or otherwise havoc the refinements to get the union.

**Comment by tkuminecz** [comment] 2017-02-04 02:17
Hey, just wanted to see if there were any plans for this. Would be pretty cool to have this working properly!

**Comment by steida** [comment] 2017-09-19 23:03
It should be fixed on Flow 0.55 but wasn't released yet.

**Comment by calebmer** [comment] 2017-11-15 20:14
These bugs were fixed a couple versions back. Sorry for not closing this sooner 😊

**Closed by calebmer** 2017-11-15 20:14 UTC
Labels: incompleteness, Typing: object model

**Comment by gcanti** [comment] 2017-11-17 13:09
This is a great news, thanks @calebmer
