### ISSUE TITLE
Error on simple unannotated function

### ISSUE THREAD

**Issue by tdawes** [facebook/flow#4541] opened 2017-08-04 15:36 UTC
The following code works fine:

```javascript
// @flow
const identity = x => x;
const first: string = identity("foo");
```

but adding a second usage produces errors:

```javascript
// @flow
const identity = x => x;
const first: string = identity("foo");
const second: number = identity(0);
```

```
test.js:4
  4: const second: number = identity(0);
                            ^^^^^^^^^^^ function call
  3: const first: string = identity("foo");
                           ^^^^^^^^^^^^^^^ number. This type is incompatible with
  3: const first: string = identity("foo");
                  ^^^^^^ string

test.js:4
  4: const second: number = identity(0);
                            ^^^^^^^^^^^ string. This type is incompatible with
  4: const second: number = identity(0);
                   ^^^^^^ number
```
It feels like something's going wrong here? Is this intentional?

**Comment by dmueller39** [comment] 2017-08-04 16:45
Looks like it should work based on this: https://flow.org/en/docs/types/functions/. 

But your example is implemented in the docs: https://flow.org/en/docs/types/generics/

**Comment by dmueller39** [comment] 2017-08-04 18:12
If you use nuclide and atom it actually shows you what the problem is: 
![screen shot 2017-08-04 at 2 09 40 pm](https://user-images.githubusercontent.com/9422359/28981164-a80c23c0-791e-11e7-991e-1b7e272d518a.png)

The mixed type `string|number` can't be assigned to a variable with an explicit type `string`. You need to use the annotation from generics to do what you are looking for.

**Comment by vkurchatkin** [comment] 2017-08-04 18:27
Closing, works as expected

**Closed by vkurchatkin** 2017-08-04 18:27 UTC

**Comment by tdawes** [comment] 2017-08-04 19:56
@dmueller39 Ah ok, that makes sense. 

Thanks very much!
