### ISSUE TITLE
Checking const that's set to null check expression should be equivalent to testing null check expression directly

### ISSUE THREAD

**Issue by philikon** [facebook/flow#998] opened 2015-10-27 00:42 UTC
Given the following snippet,

``` js
/* @flow */

type Socket = {
  connected: boolean;
  emit: (data: any) => void;
};

function sendData(socket: ?Socket) {
  const canTransmit = socket && socket.connected;
  if (canTransmit) {
    socket.emit('hello world');
  }
};
```

Flow 0.18.1 complains that the call of method `emit` might result on a potential `null` or `undefined` value.  This is somewhat similar to #76, but in this case
(a) there's no way other function closing over the scope that `canTransmit` is in
(b) `canTransmit` is a `const`, so it couldn't be modified anyway (even if (a) weren't true)
Am I missing something or should Flow be able to detect that `socket.emit()` won't be called if `socket` isn't truthy? Definitely with the `const`, but even if it were just `var` or `let`, right?

**Comment by samwgoldman** [comment] 2015-10-27 01:35
Currently refinements are syntactic. While the `canTransmit` booleans truthiness also implies the `socket` binding is non-null, Flow is not currently able to carry that implication along with the `canTransmit` boolean, and activate it in the conditional. #34 has some existing discussion around this, but I feel like this feature is still a bit far off.

For now, the following does work:

```javascript
function sendData(socket: ?Socket) {
  if (socket && socket.connected) {
    socket.emit('hello world');
  }
};
```

Here the conditional expression (specifically, the `if (socket)` part) will refine the `?Socket` type to just `Socket`.

Hope that helps!

**Comment by philikon** [comment] 2015-10-27 17:39
Thanks @samwgoldman. Yep, I have to resort to a syntactic refinement right now, which is fine. Just makes the code more verbose that it needs to be.

Reading #34, it's not 100% to me whether the scope of that issue is to merely provide the ability to add predicates to helper functions like `_.isFunction`, or to make the refinements that they can provide semantic as well. I suppose your `safeFormatNumber` example (https://github.com/facebook/flow/issues/34#issuecomment-126774771) would imply semantic refinements, right?

Anyway, thanks for the explanation.

**Comment by TrySound** [comment] 2019-02-04 23:10
Duplicate of https://github.com/facebook/flow/issues/7228

**Closed by TrySound** 2019-02-04 23:10 UTC
Labels: feature request
