### ISSUE TITLE
Conversion error, no such file or directory when building website

### ISSUE THREAD

**Issue by kasbah** [facebook/flow#5683] opened 2018-01-18 22:43 UTC
Running `make` in the website dir. 

```
make[1]: Entering directory '/home/kaspar/projects/flow/website'
Configuration file: /home/kaspar/projects/flow/website/_config.yml
            Source: /home/kaspar/projects/flow/website
       Destination: /home/kaspar/projects/flow/website/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
      GitHub Query: using fake releases for facebook/flow (no DOC_BOT_TOKEN)
  Conversion error: Jekyll::Converters::Markdown encountered an error while converting '_posts/2015-12-01-Version-0.19.0.md':
                    No such file or directory - flow
jekyll 3.2.1 | Error:  No such file or directory @ utime_internal - /home/kaspar/projects/flow/website/_site/static/master/flow.js
Makefile:35: recipe for target 'serve' failed
make[1]: *** [serve] Error 1
make[1]: Leaving directory '/home/kaspar/projects/flow/website'
Makefile:14: recipe for target 'start' failed
make: *** [start] Error 2
```
Symlink seems ok and I have flow.js compiled in `bin/`. 
```
$ ls  -l /home/kaspar/projects/flow/website/_site/static/master/
total 4
lrwxrwxrwx 1 kaspar kaspar 20 Jan 18 22:36 flow.js -> ../../../bin/flow.js
```

Running make again I get a "File exists" error 😕 
```
make[1]: Leaving directory '/home/kaspar/projects/flow/website'
make[1]: Entering directory '/home/kaspar/projects/flow/website'
Configuration file: /home/kaspar/projects/flow/website/_config.yml
            Source: /home/kaspar/projects/flow/website
       Destination: /home/kaspar/projects/flow/website/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
      GitHub Query: using fake releases for facebook/flow (no DOC_BOT_TOKEN)
  Conversion error: Jekyll::Converters::Markdown encountered an error while converting '_posts/2015-12-01-Version-0.19.0.md':
                    No such file or directory - flow
jekyll 3.2.1 | Error:  File exists @ syserr_fail2_in - /home/kaspar/projects/flow/website/_site/static/master/flow.js
Makefile:35: recipe for target 'serve' failed
make[1]: *** [serve] Error 1
make[1]: Leaving directory '/home/kaspar/projects/flow/website'
Makefile:14: recipe for target 'start' failed
make: *** [start] Error 2
```

If I run `rm -rf _posts/ en/ _site/` and run it again It seems like there are two different errors as the Markdown error disappears. 

```
make[1]: Entering directory '/home/kaspar/projects/flow/website'
Configuration file: /home/kaspar/projects/flow/website/_config.yml
            Source: /home/kaspar/projects/flow/website
       Destination: /home/kaspar/projects/flow/website/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
      GitHub Query: using fake releases for facebook/flow (no DOC_BOT_TOKEN)
jekyll 3.2.1 | Error:  No such file or directory @ utime_internal - /home/kaspar/projects/flow/website/_site/static/master/flow.js
Makefile:35: recipe for target 'serve' failed
make[1]: *** [serve] Error 1
make[1]: Leaving directory '/home/kaspar/projects/flow/website'
Makefile:14: recipe for target 'start' failed
make: *** [start] Error 2
```

**Comment by SamChou19815** [comment] 2024-08-11 19:14
The issue is referring to the old website that's now replaced by a docusaurus powered one. Closing since it's no longer relevant

**Closed by SamChou19815** 2024-08-11 19:14 UTC
