### ISSUE TITLE
Can't set a property on an object with an number-indexed key

### ISSUE THREAD

**Issue by mourner** [facebook/flow#7754] opened 2019-05-23 20:53 UTC
Flow version: v0.99.0

I'm trying to set a property on an object that has number keys (such as internal `CSSStyleDeclaration` type):

```js
declare class CSSStyleDeclaration {
  [index: number]: string;
  transform: string;
}

function foo(style: CSSStyleDeclaration) {
  style['transform'] = 'foo';
}
```

## Expected behavior

No errors.

## Actual behavior

```
9:   style['transform'] = 'foo';
           ^ Cannot assign `'foo'` to `style['transform']` because string [1] is incompatible with number [2].
References:
9:   style['transform'] = 'foo';
           ^ [1]
4:   [index: number]: string;
             ^ [2]
```

* [Link to Try-Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVATApgYxgQwCcsw98BncsAYQGV6AXATxiwBFcDD8GBLOAHZgA3qjBgA2rwHYAHgC4wAgK4BbAEZZCAXUXkGhaQHMA3GLAH8A8lDiFVeg8bMBfdFGUCcfQWFtwACn0WLEU6RhCOMm4fAQBKEXNg1gkAcktrW3tU7TAAXjBU-1TXIA)

The error goes away if I do `style.transform = `, but I need an indexed access because the property is determined at runtime. Is this a bug? Are there any workarounds? (Can't use `any` because I'm trying to convert a codebase to Flow Strict)

Thanks!

**Comment by goodmind** [comment] 2019-05-23 21:03
@mourner CSSStyleDeclaration actually has method `setProperty`

**Comment by mourner** [comment] 2019-05-23 21:14
@goodmind I know that, but still — `element.style['transform'] = value` should be a perfectly valid code. I don't think it's right to change valid and safe code to fix typing issues — I'd prefer to fix typing itself.

**Comment by retyui** [comment] 2019-05-24 12:54
@morozow 
How about this: [Try...](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVATApgYxgQwCcsw98BncsAYQGV6AXATxiwBFcDD8GBLOAHZgA3qjDiwAbV4DsADwBcYAQFcAtgCMshMAB8wAcgbcB5KHEJqDAXSXljMgOYBuVAF90UFQJx9BYczgACnsWLCU6RjCOMm4-AQBKETEwUNZJIxMzCytrMABeQ0CDVzcgA)

**Comment by mourner** [comment] 2019-05-24 12:58
@retyui the CSSStyleDeclaration is only there for the demo, since Flow Try doesn’t have the internal DOM/Browser/CSS types that it has when running the Flow CLI. So I can’t really change it. So either there’s a bug in Flow itself, or the internal types it has for CSS.

**Comment by retyui** [comment] 2019-05-24 13:02
@mourner Perhaps you should look for this module: https://github.com/frenic/csstype

**Comment by goodmind** [comment] 2019-05-30 06:01
Duplicate of #4014

**Closed by goodmind** 2019-05-30 06:01 UTC
Labels: bug, needs triage
