### ISSUE TITLE
Function returning `exports` breaks flow.

### ISSUE THREAD

**Issue by despairblue** [facebook/flow#1855] opened 2016-05-27 13:08 UTC
See [this](https://github.com/despairblue/recursive-export) module. _node_modules_ is checked in.

`flow check` says that [`get`](https://github.com/despairblue/recursive-export/blob/master/index.js#L7) is not exported, although `flow type-at-pos` says the function exitsts:

``` sh
$ flow check
index.js:7
  7: console.log(configman.get('PATH'))
                           ^^^ property `get`. Property not found in
  7: console.log(configman.get('PATH'))
                 ^^^^^^^^^ exports


Found 1 error

$ flow type-at-pos index.js  7 18
{ensureAllSet: (environmentVariables: Array<string>) => any, get: (environmentVariable: string) => string}
/Users/danny/git/flow-issue/index.js:7:13,7:21

See the following locations:
/Users/danny/git/flow-issue/index.js:7:13-21:
object literal
/Users/danny/git/flow-issue/index.js:7:13-21:
exports
```

**Comment by tryggvigy** [comment] 2016-05-27 23:32
Taking a wild guess here. 
This could be an issue related to the module import starting with `@`.
Try renaming the module and see if it works.

##### Side-note
[why do this](https://github.com/despairblue/recursive-export/blob/master/node_modules/%40wunderflats/configman/lib/index.js#L27)
![image](https://cloud.githubusercontent.com/assets/2373958/15623432/eedd8224-2462-11e6-837e-1e53cab9dd71.png)
instead of 
```js
module.exports = {
  ensureAllSet,
  get
}
```

**Comment by despairblue** [comment] 2016-05-29 13:23
It's just something I got used to, since some developers use just the `exports` object, which works until you assign something to it. Using `module.exports = exports = ...` seems unnecessary, but it prevents headaches if people who don't fully understand the culprits of *commonjs modules* do things like assigning to `exports`. It just removes a footgun for people who may fork the module, or if it's a rather big module in a shared code base. I just use it everywhere.

But thanks for the hints, I'll try that on Monday.

**Comment by despairblue** [comment] 2016-05-30 10:07
@tryggvigy ok I figured a way out to make it work. I seems that the functions have to be defined inline to make it work (I also tried hoisting to no avail):

```js
/* @flow */
/* eslint-disable no-process-env */

'use strict'

const debug = require('debug')('config:init')

const configman = {
  ensureAllSet (environmentVariables /* : string[] */) {
    environmentVariables.forEach(function (environmentVariable) {
      debug(`${environmentVariable}=${process.env[environmentVariable]}`)
      if (!process.env[environmentVariable]) {
        throw new Error(`Environment variable ${environmentVariable} is not set!`)
      }
    })

    return configman
  },

  get (environmentVariable /* : string */) /* : string */ {
    if (process.env[environmentVariable]) {
      return process.env[environmentVariable]
    } else {
      throw new Error(`Environment variable ${environmentVariable} is not set!`)
    }
  }
}

module.exports = configman
```

**Comment by calebmer** [comment] 2017-07-26 22:18
Closing since this issue hasn’t seen a lot of activity. Sorry about that 😣

Please reopen with a reproduction on https://flow.org/try if you are still having issues!

**Closed by calebmer** 2017-07-26 22:18 UTC
