### ISSUE TITLE
Use return type of a function

### ISSUE THREAD

**Issue by nickmessing** [facebook/flow#4002] opened 2017-05-22 23:36 UTC
Flow finds return type of functions very well, can we use that type in other declarations in any way?

Example of what I would like to achieve:
```js
const mapStateToProps =  (state: ReduxState) => ({
  val1: selector1(state),
  val2: selector2(state),
})

type Props = typeof mapStateToProps()

class Home extends Component {
  props: Props;
  render () {
    return <div />
  }
}

const connector = connect(mapStateToProps);

export default connector(Home);

```

**Comment by vkurchatkin** [comment] 2017-05-22 23:56
There are a couple of hacky ways to do this:

1. Use "existential" (star) type:

```js
type Return_<R, Fn: () => R> = R;
type Return<T> = Return_<*, T>;

function foo() {
  return 1;
}

const x: Return<typeof foo> = ''; // error
```

2. Call the function inside of a Flow comment block:

```js
function foo() {
  return 1;
}

/*::
const __result = foo();
*/

const x: typeof __result = '';
```

**Comment by futpib** [comment] 2017-05-23 15:16
@vkurchatkin Awesome example, I am now wondering why is the same trick not working for the function arguments:
```js
type Return_<R, F: (...args: Array<any>) => R> = R;
type Return<T> = Return_<*, T>;

type Arguments_<A, F: (...args: A) => any> = A;
type Arguments<F> = Arguments_<*, F>;

function foo(n: number) {
  return n;
}

const r: Return<typeof foo> = ''; // error
const a: Arguments<typeof foo> = ['']; // no error :(
```

**Comment by vkurchatkin** [comment] 2017-05-23 15:51
That's because type of arguments flows in the opposite direction. `*` captures whatever flows in, not what flows out. Simple example:

```js
var x: * = 1; // number ~> *
declare var y: typeof x;
(y: string); // error

declare function fn(x: number): void;

declare var z: *;

fn(z); // * ~> number

declare var u: typeof z;
(u: string); // no error
```

The same happens when function flows into another function, like in your example.

**Comment by wzrdzl** [comment] 2017-08-06 11:36
@vkurchatkin Do you think your `Return` utility type could be added to the language? Seems like useful thing

**Comment by vkurchatkin** [comment] 2017-08-06 12:17
Not `Return` specifically, but `Apply` makes sense to me

**Comment by sibelius** [comment] 2017-08-20 13:02
@nickmessing is this working for u? Do u have a repo example of this?

**Comment by nickmessing** [comment] 2017-08-20 21:21
@sibelius, yes, this helper works fine:
```js
type Return_<R, F: (...args: Array<any>) => R> = R;
type Return<T> = Return_<*, T>;
```

**Comment by sibelius** [comment] 2017-11-14 13:17
## Add ExtractReturn helper

```jsx
// https://hackernoon.com/redux-flow-type-getting-the-maximum-benefit-from-the-fewest-key-strokes-5c006c54ec87
// https://github.com/facebook/flow/issues/4002
// eslint-disable-next-line no-unused-vars
type _ExtractReturn<B, F: (...args: any[]) => B> = B;
export type ExtractReturn<F> = _ExtractReturn<*, F>;
```

## Extract return of mapStateToProps and mapDispatchToProps

```jsx
const mapStateToProps = state => ({
  user: state.user,
});
const mapDispatchToProps = dispatch => ({
  actions: {
    logout: () => dispatch(logout()),
  },
});

type ReduxProps = ExtractReturn<typeof mapStateToProps>;
type ReduxActions = ExtractReturn<typeof mapDispatchToProps>;
```

## Add ReduxProps and ReduxActions to your Component props

```jsx
type Props = {} & ReduxProps & ReduxState

class EntriaComp extends Component<Props> {}
```

I think we can use `$Call` to improve this as well

cc @calebmer 

can we close this?

**Comment by iddan** [comment] 2017-11-29 13:05
Can ExtractReturn be added to the global Flow helpers as $Return?

**Comment by sibelius** [comment] 2017-11-29 13:17
you can use $Call instead of ExtractReturn

**Comment by AlicanC** [comment] 2017-12-26 11:51
Proposed solutions do not work for my case: [Flow Try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzAEMN8BLHAYQCcBTI-Oa3MAXjAG9UwwdaAuMAAoiggEZw4MetgCUbAHzCuPHvgCeABwFgA5AHkAcgFFdAGm6rNRdfCIATQUQs8AvrJdh8COIKFjBAmoybABzeVYlIRVVDW1BXQAVAHV9c0sea1s4B3FPd098AAs6HSEIqJi1LR0kgAkAJWNTfI9UVwBudGBgMDqiansse1p7VDjaMABBUgpsNksAH04vGoSjFrAsu0cwCSkZMFcllYmElLSzLZsdwPxgsKOTjlX4vUTG5t0jrtQesAAJJQiDAYOMamAAPrGAAe9xI+AatHwAFdqPN2AAeBoKITlRRgBoVQldCZgWHw0hI1HozEAMWwSnYQJBMEx0Lh1AR1LR2CuDIUpIhM3IVAWPGWFK5VORvMxEzgUGIsyodAYTFwADo+AoTlLubLaQqlQi5jR6IxmJrvHBdRLyZyDTTsPKaorlaLsOb1VbiqVBd1erCyARaNhyCDwdoofqZc7jNj+dg-MScWwSVHJrHEYbsAmBemOZSc-HMSAkwGySK5sZxWBJY647yE8aPWa1ZatTq9Y2S83Xdp3abVRaNdafHb6w7izz0S23SaVV6O2O-bRaAHUNFXrUNuZrtlcl5qCjJq5BNWcLIutuzu9Uvvtjldrogt9z9Ml9ety87-UmqYRwXl+vy3msegbJCyQNEYADij43M+gj3KeQGfp6lDfmBbxJKkUEwYY8FXE+R6vvc77ARhWG-uB-7NPhcEUehZrfj+O7rCYDGEQhh67ChZ6UTW1Hsfe+hcURB63Hob5oZeebCX+HwAeJTFycY35AA)

I need to explicitly type returns of `actionCreators` to make these work: [Flow Try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzAEMN8BLHAYQCcBTI-Oa3MAXjAG9UwwdaAuMAApuPYoIBGcODHrYANKICUgrmLD4AngAcBYAOQB5AHIBRfYvXaim+EQAmk6bKILRAXzYA+YWrFbdQSMzC1Eea1s4B0EiSzB3JTj8BDhBEXUJQQJqMmwAcziVTjCNHT19ABUAdUNQqxs7RzBs3IKPb18SgPLq2rjwhqimiTiEpIALOj0hIr8ebqCKgAkAJVNzUY6hOdLAg2W1jY9E1HcAbnRgYDAlomp7LHtae1RusABBUgpsNlEAH04u3KJg2YAijScMjk8X+gIW+xqFjBg2izXwOXyMJ4AI4QMWq3W+niF1QVzAABJKEQYDBXmUwAB9UwAD3RJHwK1o+AArtQfuwADwrLxCIQAOgldzyuBi2E0Sg6KwVrB8KwubxZbNInJ5fIFADFsD52JTqTABUzWdR2TreQowIavOr6Z9yFRftiwJrrdquXaBd04FBiF8qHQGExcGK+F5Yd6bX69YHg+zvjR6IxmGLknBY57477ddgA2UgyG3dh0xGs-hJrRaE7LtcWWQCLRsORqXTdIyCxzE9hTEL5A7sGkJWKpTLiHLlarjWA1d3aF6rQmi0PHWxe2vC3ahyAR47nT3Xd9TB6wAC+7a+UPk+W0+HM1GY3Hd-2NyXdGXU2GM5G2YpHmV6rlqn77t+tC-qGlbPoBtZTI2qDbHiBggki4JDII6Lciu7iCGeOBKBcqHwpUiIjlhqL6NkRIER8sEkShuLkQchLxIRTEkmRZRBBhVEok0uH4VxFaUMxvF7BRfTIpENF0ZxjHiZJrF8fsBLmEpRGVsxLFocEoLUcJ1B4dpsGmKpBm9JhQlBIpDE6ZZpFqdJ7FaY5FnMUAA)

The dream is using `$ObjMap` to completely avoid duplication:
```javascript
const actionCreators = {
  // ...
};

export type Action = $Values<$ObjMap<typeof actionCreators, ExtractReturnType>>;
```

**Comment by mgtitimoli** [comment] 2018-04-05 20:03
Hi everyone,

@vkurchatkin, so based on what you wrote on [this comment](https://github.com/facebook/flow/issues/4002#issuecomment-303442984), I assume there is no way to extract function arguments, right?

**Comment by kangax** [comment] 2018-04-26 17:47
I can't get it to work either. Here's a [very simple example](https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDGMA0cDecDCE4EAdkifAL5wBmURcA5FKhowNwBQnMAnmEjgB9AKIAPGFHQxkMAK5QSAHgBC2AGIAuOAAoAdAZRQA5gGdtKErwDaAXQCUcALwA+OCrdP3XJGMiw4PgE4cUlpWQVldU9hUKkMCMUlACoNFy4efkEAcQAbCAAjFFyAZRgUGEEvPDlTJChtU0lgEmM4Sgy0Uia4EBQwMoqkABUIAAV6MFNnXSah7TzC4sHKx1ddGrqGuDnKvVr69vsMoMFkABM5MQmIKZm48KR5JNOIGl7+lZHxydN0zOCNzuXguVyB0wAZLg4Adtk0oC02h1uL5-PA0LkUKZpuoIBA4L5KiRztNCMQyBQlOC3DhOHA4CxifUdI5afT6SxniQ4EpzsAAG4uHAwAAWwFMejAv32Wz0NDxLMoSgA9HzBVx6ZROJQgA).

Does not throw:

```js
type Props = ReduxProps & { user: string };
this.props.user.foo();
```

Does throw:
```js
type Props = { user: string };
this.props.user.foo();
```

When using `ExtractReturn` helper, `user` type being "string" should be properly propagated from global state all the way to `this.props`. But it doesn't.

**Comment by TrySound** [comment] 2018-04-26 18:14
This probably can be closed.
/cc @mrkev

**Comment by mgtitimoli** [comment] 2018-04-26 18:45
Hi @kangax,

I've just seen your comment, would you mind to share `ReduxProps` type? 

I'm asking you this as I believe the error you were having was caused by the fact that using **&** if any of the intersected types share a property, the resulting one would be an union of all the values for it, does it make sense? was your error caused by this?

**Comment by sibelius** [comment] 2018-04-26 19:05
this is the version using `$Call`, it is much faster than using `*`

```jsx
export type ExtractReturn<Fn> = $Call<<T>((...Iterable<any>) => T) => T, Fn>;
```

Example of extracting ReduxProps:

```jsx
type ReduxProps = ExtractReturn<typeof mapStateToProps>;
```

https://flow.org/try/#0C4TwDgpgBAogHsATgQwMbAEoWAV0QOwB4AxfAPigF4oASAYWQBtHDCAVMgCk4Do+BJYBBQAjRhELJ8IMgEoqFNvMqKANFFJkA3ACgoO0JChYAJjjgBlYMiFUoAbz1RUALigBnJAEt8Ac1U6AL56OgBmOPjoXgD2+FDInJ42EG6m5lbJ8o5QUIjYeHHZOVAibklCPKgBOcHBYRFRsSWcYMgoALbubvBIaJj5BISGENGh8XIOTi1tyJ08pR7efrK6OdMd7vNuItHR4lIrQUA

**Comment by sibelius** [comment] 2018-06-15 14:54
can we close this?

**Comment by mrkev** [comment] 2018-06-15 17:09
Sure 👍

**Closed by mrkev** 2018-06-15 17:09 UTC

**Comment by ggregoire** [comment] 2018-08-27 17:47
I'm having some issues with typing `mapActionsToProps` as [an object of actions](https://github.com/reduxjs/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options):

```javascript
const mapActionsToProps = {
  logout
}

connect(null, mapActionsToProps)(Comp)
```

It seems as simple as using `typeof`:

```javascript
type ReduxActions = typeof mapActionsToProps

type Props = {} & ReduxActions // or Props = { ...ReduxActions }

class Comp extends Component<Props> {}
```

But it doesn't work, Flow loses the inferred type of the actions and see them as `any`.

I reported the bug (?) here: https://github.com/facebook/flow/issues/6797

Does someone has a workaround? Or am I doing something wrong? (cc @sibelius )

**Comment by punksta** [comment] 2019-02-11 10:15
Hello. I am trying to extract union type of "foo": `type Foo = "a" | "b" | "c"`
but I could get only `type Foo = "string"|"string"|"string"`

```
const getObject = () => {
  const r = {
      a: {foo: "a"},
      b: {foo: "b"},
      c: {foo: "c"}
  }
  return r;
 }

type ResultType = $Call<typeof getObject>;
type Values = $Values<ResultType>
type AUnion = $PropertyType<Values, "foo"> // should be union of literals, but it's union of strings
  
const a: AUnion = "a"
const b: AUnion = "b"

//should be an error here
const fooBar: AUnion = "bar"
```
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAodBjOA7AzgFzAHMBTfAeQCMArEjQgXjAAoBKMBgPjAG9UwwWPIQBOHXvwFSAhgC5eUOHHkAiaSoC+AGklSwleT0XKwKypp16BGQ8dUZNuqcGBhpYeIThQwcfAAsSMQBrEgBPXDAEAEsAhSVVAhFo7CIPWKDpGE0wADcsgFcSSQ1JETICkWwwEQBuflLUfDCABxIwACUSXAKYfAAVVvamABIAYSyYAB5mtu9iMipaek562faANULu8RGtmCLcKa6evsG2ziahsABBAFVsaJxdgAURODaRZvOSKf3DrSmYwqbguMC4fxwXoAE307QKj2e8xgGSqWVwgMoBUIsQA5JEEU9qvMkikiLhJKghAQ3PJ7ojqkw1CoqTgaQZbg8ieIzCzUC4IVCYLDKO1ogBbFpwXDRSgwYrUwjGABC0hEdK5zyZxkoapZQA

**Comment by alexandrricov** [comment] 2019-06-13 12:03
Hello, can't figure out how to use `$Call<typeof myfunc>`, in case myfunc returns promise.
Smth like:
```typescript
function asd(): Promise<number> {
	return Promise.resolve(3);
}

(async () => {
  const num: $Call<typeof asd> = await asd();
})()
```
https://flow.org/try/#0GYVwdgxgLglg9mABAQwM4BMAUBKAXIgBQCc4BbGVAUwB4wRSAjSogPkQG8AoASCMqhBEkxMhUoA6PqjgAbAG6VMAZmwBuTgF9O2zGgCekRDkQBeNl06JEEBKiiI6pfABIAwshkzqUPQAdKcMAoGGwmKADuyDD2aFhqmtg42kA

**Comment by jcready** [comment] 2019-06-14 20:22
@alexandrricov 
```js
function asd(): Promise<number> {
	return Promise.resolve(3);
}

(async () => {
  const num: $Call<typeof $await, $Call<typeof asd>> = await asd();
})()
```
