### ISSUE TITLE
"assignment of identifier Could not resolve name" with Array destructuring

### ISSUE THREAD

**Issue by thecachedbyte** [facebook/flow#3642] opened 2017-04-03 11:39 UTC
**Sample code:** 

`const [a, b = 0, c = 0, d = 0] = '1_3'.split('_').map(item => parseInt(item, 10));
console.info(a, b, c, d); // 1 3 0 0`

**Error:**

_3: const [a, b = 0, c = 0, d = 0] = '1_3'.split('_').map(item => parseInt(item, 10))
                               ^ assignment of identifier `c`. Could not resolve name
3: const [a, b = 0, c = 0, d = 0] = '1_3'.split('_').map(item => parseInt(item, 10))
                                         ^ assignment of identifier `d`. Could not resolve name_

flow version: "^0.37.0"
Can someone explain whats wrong here?

**Comment by madbence** [comment] 2017-04-03 12:07
i guess it's a bug in flow, you can fix it if you declare the `c` and `d` before the destructuring (unfortunately `c` and `d` are not `const` anymore in this case :crying_cat_face: )

```js
let c, d;
const [a, b = 0, c = 0, d = 0] = '1_3'.split('').map(item => parseInt(item, 10));
```

**Comment by vkurchatkin** [comment] 2017-04-03 12:13
Duplicate of https://github.com/facebook/flow/issues/1985

**Closed by vkurchatkin** 2017-04-03 12:13 UTC
