### ISSUE TITLE
Element props marked as mixed since 0.89.0

### ISSUE THREAD

**Issue by villesau** [facebook/flow#7306] opened 2018-12-29 20:20 UTC
[try flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuyYAhgM5gBKApiQMZFR5yZgDketDbA3KgQE9s1MAAVm2CgF4wAbxIAuMADsArpgBG1PAF9+QkQGEWYGTXoEAdAFEY1TNWUEAPOYaXjOOMscEAKgbO4nCSAHyhfKh03mSMyqZgABTRmEqeAJSmoXKoAJDJLJbYEmRKwZLpfDpAA)

Following code:

```
/* @flow */
import * as React from 'react';
type Props = {a: number}
type Com = React.Element<React.ComponentType<Props>>;

const fn = (com: Com) => {
	(com.props: Props);
}
```

errors since com.props is mixed. it works if using [React.Element<React.StatelessFunctionalComponent<Props>>](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuyYAhgM5gBKApiQMZFR5yZgDketDbA3KgQE9s1MAAVm2CgF4wAbxIAuMADsArpgBG1PAF9+QkQGEWYGTXoEAdAFEY1TNWUEAPOYaWAygRIFqdsmQAYqrKDOhwyiQwxjgRji7icJIAfMl8qHQRZIzKpmAAFJmYSjEAlKbJcqgAkIUsltgSZEqJkqV8OkA), or [React.Element<Class<React.Component<Props>>>](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuyYAhgM5gBKApiQMZFR5yZgDketDbA3KgQE9s1MAAVm2CgF4wAbxIAuMADsArpgBG1PAF9+QkQGEWYGTXoEAdAFEY1TNWUEAPIZjkyz8w0vGccZUcXcThJAD4IvlQ6ALJGZVMwAAoYzCU-AEpTMLlUAEgUlktsCTIlEMkMvh0gA) but obviously that is often too strict requirement. looks like [React.StatelessFunctionalComponent<Props> | Class<React.Component<Props>>](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuyYAhgM5gBKApiQMZFR5yZgDketDbA3KgQE9s1MAAVm2CgF4wAbxIAuMADsArpgBG1PAF9+QkQGEWYGTXoEAdAFEY1TNWUEAPOYaWAygRIFqdsmQAYqrKDOhwyiQwxjgRji7icJIAfGAAPgAFhjDkZK5cVjG4yvHOiSnJyXyodBFkjMqmYAAUtZhKMQCUpqmyqACQrSyW2BJkSuVknXw6QA) would work too which is odd since by the documentation, it should be pretty much the same as [React.ComponentType](https://flow.org/en/docs/react/types/#toc-react-componenttype). It's just crazy cumbersome way to say that "Hey, I want an element which has these props"

As seen from this [code sandbox](https://codesandbox.io/s/lxjz5jq0ym), accessing props from component instance is fine.

This works in 0.88.0 and earlier versions, but in 0.89.0 props are marked as mixed.

Btw, would be good if there would be something like `React.ElementType<Props>` that would do the same as `React.Element<React.ComponentType<Props>>` is supposed to do.

This issue makes it very difficult for us to update to latest Flow.

**Comment by jbrown215** [comment] 2019-01-03 16:03
React.ComponentType is no longer the union of class and function components. Now, it is an alias for AbstractComponent, which gives `mixed` for ElementProps.

The reason for this is that the ElementProps type destructor only really used to work on classes or functions, but nothing wrapped in an HOC. We chose not to support it with AbstractComponent because we would need to also propagate DefaultProps as a type argument to use it.

If you want to use ElementProps in a way that Flow can give you useful information, you can define a type alias to be the union of function and class components:
```
type FunctionOrClassComponent<Props> = React$StatelessFunctionalComponent<Props> | Class<React$Component<Props>>
```
and use that type where you need ElementProps instead of ComponentType.

**Comment by villesau** [comment] 2019-01-03 16:52
Ok, thanks! How open are you to introduce that kind of utility types in `React.SomeUtilityType` form? `React.ElementType<Props>` and `React.FunctionOrClassComponent<Props>` would still be super useful, at least for our usage patterns. Or is it just recommended to build some own utility libraries instead?

**Comment by jbrown215** [comment] 2019-01-03 16:53
For now, I recommend just adding those aliases in your own libdef. If more people start to request this, then I will re-evaluate.

**Comment by jbrown215** [comment] 2019-01-10 14:35
@villesau: Does `ElementProps` returning the Config on AbstractComponent work for your use case?

**Comment by borlaym** [comment] 2019-02-04 14:55
@jbrown215 I've used your following suggestion:
`type FunctionOrClassComponent<Props> = React$StatelessFunctionalComponent<Props> | Class<React$Component<Props>>` to use in a HOC function. However, this stops working once I wrap a class function with it that also has a state. I'm finding it hard to figure out how I would modify the above to get to a point where it would allow for wrapping both stateless and stateful components at the same time.

All in all I'm pretty confused by these changes. So I have two issues:
1. Can't use AbstractComponent in HOC because information is lost ([flow try](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdMAnmFnAJIB2AVlvlgBMACsTDoAvHADecAhAgAuOJwCuIAEZYocAL706BFZ3zAInOAAkA8gGEAPDbMFgAcyVde-YaNQA+ABR0cHCO4GZYnDBK2HgwAHQAguqoMFCxoZCcETAOTq6+QQCU0VTxSSlp+BnhkXYAJAAiwAQEuZzOLgA0HDx8MIIiEGK+vtJBlDAqUOaGxjCm5gDqaWCsUNVZkYHBwWA+So3NrY7trt0efQM+vp1BcIVjO3ATU+a5YZvwUnE-e0OoOlk8nEUgALAAmQEAel89GCejgdB0DFwZhScAAyqAwAAbLAbbJwST+P5iJQydTIKBKCrAThdIGKZRqTTaHQPcSjOxgXxSUmoOKUqA6Pk+OJyCA6OxQnl0VGcdFY8B45bIVaCImWWz+JW4-EkTLZQoMWYmMwhA01GAAFQAFsgYBY0ATIglUIMwCT9tI4CBkHSXVFMKU4gBRPEgbJ2ZisCAETHYlUrVgCUbsx4ASBe0zg-jsAmAADdefy4n6A5bPnFS0KpVCC8WHkigA))
2. If I use the above mentioned helper in the HOC, can't use with stateful components ([flow try](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdMAnmFnAJIB2AVlvlgBMACsTDoAvHADecAhAgAuOJwCuIAEZYocAL71mrOADEVnfMAicA8lADCAGzSpbJSJyycYAHhEQxAPjhJbDwYABIAZRhkGCx7LFRUEzMYC05kexdwSw9vXwC4AB84BycvEPwwrLdcn1FUf38GOgJTc0s4AAkrWzq-VCUuXn5hev8ACjo4EtcczyVk9us7R0TqubyxqYBKJQqYADoomLiEpLbUywz1908vMIARYAICPrEAGg4ePljR-sbpFNKDAVFBOLILmk4AB1KDIMCsOyzW4wSbTaZgepKR7PV75VCfIY-QT4-zvKZwbaA9FwYGg8FeG65aQHVmY-o6WTycRSAAsACZOQB6fz0aZ6OB0HQMXCWVDwCKgMDxJmeIJwcbssRKGTqZBQJTyqDATgAc0+ckUyjUmm0Oip4kCXjA-ikWtQBz1UB0bvqB0tOi8QpddFlnHlcEV4HisPhrAE6u6tnGUeVWFVMG2MtW6GOsVamWRzKwAA9YpwBOh9gcM14ZJalKoNFpdJ9dfrDTBjWbdIEpNKwxG81gC7GEYJEz0U9F8ypC9kUdsgA))

Please let me know if there is a solution to the latter.

**Comment by namuol** [comment] 2019-02-15 01:45
> React.ComponentType is no longer the union of class and function components. Now, it is an alias for AbstractComponent, which gives `mixed` for ElementProps.

@jbrown215 Why was this breaking change made? I assume there's some good technical reason, but from an API "politeness" standpoint this is very disruptive.

Our codebase, and likely a lot of library definitions still operate under the assumption that `ComponentType` refers to `Stateless | Class` components.

> For now, I recommend just adding those aliases in your own libdef.

This should help us move forward; thank you for clarifying :+1:

> If more people start to request this, then I will re-evaluate.

I do think a general purpose `ComponentType` is very useful. Most React code doesn't "care" about whether a component is stateless or stateful, so most abstractions that work with components will probably need to rely on their own duplicate alias, which will lead to more confusing error messages in the long run.

**Comment by jbrown215** [comment] 2019-02-15 02:20
> Why was this breaking change made? I assume there's some good technical reason, but from a standard library standpoint this is very disruptive.

ComponentType as a union of function components and class components wasn't sufficient to model react components that were released in the last year. A few of these components include React.StrictMode, React.ConcurrentMode, React.Fragment, React.memo, React.lazy, React.forwardRef, etc.

In order to provide a more maintainable abstraction for React, we created AbstractComponent. Class Components and Function components are both AbstractComponents, but all the newer react components are also AbstractComponents. AbstractComponent keeps track of the Config (Props with all DefaultProps marked optional)  and Instance of a component, which we hope will be enough to model more react components that are as of yet unreleased.

ElementProps was the only use case that required that we still propagate information about the default props separately from the config in AbstractComponent. That use case did not seem like it was worth propagating a third type parameter for in AbstractComponent, which we tried to keep as ergonomic as possible.

> I do think a general purpose `ComponentType` is very useful

AbstractComponent _is_ that general purpose type for referring to all components. It precisely does not care about the state (or lack thereof) in a component-- all it cares about is the config type, which is at an even higher level of abstraction than props and default props.

When I said I'd re-evaluate, I was talking specifically about the decision to _not_ propagate DefaultProps in AbstractComponent.

If you want to read more about AbstractComponent, check out our blog post: https://medium.com/flow-type/supporting-react-forwardref-and-beyond-f8dd88f35544

**Comment by namuol** [comment] 2019-02-19 02:19
Thanks for the explanation @jbrown215 🙇 

I'm writing an upgrade guide for my team right now; is it safe to say `ElementConfig` is _probably_ want you want to use in most cases where you would have used `ElementProps`, previously?

For example:

```js
import * as React from 'react';

declare var Foo: React.ComponentType<{|foo: number|}>;

type FooProps = React.ElementProps<typeof Foo>;
type FooConfig = React.ElementConfig<typeof Foo>;

declare var FromElementProps: React.ComponentType<FooProps>;
declare var FromElementConfig: React.ComponentType<FooConfig>;

<FromElementProps />; // `foo` missing, but no error detected 🙈

<FromElementConfig />; // `foo missing, error detected 👍
```

[**(Try on flow.org/try)**](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdAJlrgDbKVwBuHcAYhAgAuTFRgA6AMIlIAOyyyYAFQCeYLAB4A3gB8CgkbICuIAEZYoOgL4A+enRhqs-QQAViYdAF5ReCQFFWLBAFGHcITw1HdQgCFwg7Byd46VkCYABzOB9sP3FA4NDU9Iyop1j4xKYWdk4eKH5iEAKQxXDPEVz8KRkIeUVVdQ0BCHbUROY2Dmd6xpIWor6SzrEe8D7Qwc0R4syq4aaFto90AHo7OFPTuAA5CDgLYgbmGBZXxjhAXg3ACT2GA-mgq0YLssucaJdrv4oE84C83lgPp9ALI7dCAA)

**Comment by villesau** [comment] 2019-02-19 08:32
@namuol can you make the guide public? :) I'm sure it would be very helpful for the community!

**Comment by jbrown215** [comment] 2019-02-19 16:24
@namuol: Mind showing a less contrived example? There's no need to use ElementProps or ElementConfig there since using `Foo` directly has the behavior you want.

**Comment by namuol** [comment] 2019-02-19 17:06
> can you make the guide public?

@villesau Maybe later after I'm more confident about the general advice I'd give.

> There's no need to use ElementProps or ElementConfig there since using `Foo` directly has the behavior you want.

@jbrown215 One of the most frequent usages of `ElementProps` was to provide a concrete `P` type for HOCs like `React.memo`:

```jsx
React.memo<React.ElementProps<typeof Foo>>(Foo);

// or

(React.memo(Foo): React.ComponentType<React.ElementProps<typeof Foo>>);
```

But we also use it in other places to share/extend prop types across components:

```jsx
type BarProps = {
  ...React.ElementProps<typeof Foo>,
  bar: number,
};
```

Here's an actual example from our codebase:

```jsx
type PopoverBalloonProps = {
  ...React.ElementProps<typeof Balloon>,
  anchor: ?Box,
  rect: ?Box,
  position: PositionIdentifier,
  children: React.Node,
};
```

In the above example, post-0.89, the concrete type for `PopoverBalloonProps` becomes:

```jsx
type PopoverBalloonProps = {
  [string]: mixed,
  anchor: ?Box,
  children: Node,
  position: PositionIdentifier,
  rect: ?Box
};
```

Switching to `ElementConfig` fixes the issue in this case and many other similar usages :+1:

**Comment by jbrown215** [comment] 2019-02-19 17:14
Mind showing how you specify the Props for `Balloon`? I recommend _not_ using the type destructors if you can avoid it. AbstractComponent gets rid of the need to use ElementConfig.

If I were writing Balloon and wanted to extend its Props for another component somewhere, here's how I would do it:
```
Balloon.js

export type Props = {|
  // Balloon's props
|};

function BalloonComponent(props: Props): React.Node {
 // ...
}

module.exports = BalloonComponent;
```
```
PopoverBalloon.js

import type {Props} from './Balloon';

type PopoverBalloonProps = {|
  ...Props,
  // Extra props
|}
```

Mind joining the discord or opening a new issue to discuss further? I'm happy to help you get a recommended usage guide down.

 https://discord.gg/8ezwRUK

**Comment by edahlseng** [comment] 2019-02-27 23:03
@jbrown215 was there any helpful information discussed in discord about this issue that could be summarized here? I'm running into a similar issue, but am unable to fix it in the way that you describe above, as it's a HOC (so we are inferring `Props` instead of being able to import it).

**Comment by jbrown215** [comment] 2019-02-27 23:11
@edahlseng: Mind sharing a bit more about your use case? I don't think the discussion @namuol and I had will generalize well to everyone, but here is a summary of how I recommend to use ElementConfig after 0.89. Tl;dr, you probably shouldn't use it anymore:

The main purpose for ElementConfig prior to 0.89.0 was for writing HOCs and preserving the "optionality" of defaultProps on the resulting component. Since AbstractComponent already changes Prop+DefaultProps into a config, using ElementConfig is no longer necessary in HOCs.

Using ElementConfig will not give you the same Props that you parameterize a component with if defaultProps are specified. ElementConfig gets the props of a component and marks all defaultProps optional, so this won't always work as you expect it to. I really do recommend exporting the Props types directly, but if you can't then ElementConfig is probably the next best bet.

I recommend 1 exported component per module with a toplevel exported "Props" type alias so that it's easy to import a Component and its Props type.

**Comment by edahlseng** [comment] 2019-02-27 23:53
@jbrown215 thanks, it's helpful to know some more of the background on this!

The real-world use case that I'm running into issues with is with updating the flow-typed defs for styled-components ([flow-typed PR #3165](https://github.com/flow-typed/flow-typed/pull/3165)).

I tried putting together a minimal reproducing case, and am even getting different errors than what libdefs are encountering, but may still illustrate the root issue:

```javascript
import React from 'react';

type Props = {
  name: string,
  count: number,
  background: string
}

const TestComponent = (props: Props) => null

type Interpolation<P: {}> = (executionContext: P) => string;

type TaggedTemplateLiteral<R, P: {}> = (strings: string[], ...interpolations: Array<Interpolation<P>>) => R;

const styled = <Config: {}>(Component: React$AbstractComponent<Config, *>) => (strings: string[], ...interpolations: Array<Interpolation<Config>>): React$AbstractComponent<Config, *> => Component;

// This fails, saying that `background` does not exist
const StyledTestComponent = styled(TestComponent)`
	color: ${props => props.background}
`;
```

**Comment by jbrown215** [comment] 2019-02-28 14:49
I'm unfamiliar with the backtick syntax you're using. Mind explaining?

Also, instead of `*` you can use `mixed`

**Comment by villesau** [comment] 2019-02-28 15:07
@jbrown215 it's [styled components](https://www.styled-components.com/) using [tagged template literals](https://wesbos.com/tagged-template-literals/) ( https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals )

**Comment by jbrown215** [comment] 2019-02-28 16:43
Ah, got it. Fancy stuff there, JS.

@edahlseng: Flow doesn't infer generics, which is what I think is causing the error here. It's hard for me to parse `styled`, but I think you need to annotate the return type of the outer function. [Here it is  rewritten a bit and working as expected](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdMAnmFnAArFjoC8cA3nThwAdshBYAXHFQwowEQHMANELi4IAVxExpIzSABGWKKuGG8Aa0XFtAE2mz5SugF8GGkbLgAVLLIBhEkgRLB04PgAKMC5UaU4IbgBKCIA+UU0AG0yGZlY4AEkdE0hM5BhgCBEAHnZpfld0qKwADyxcTQqqoOKW3Q4UnnSnBUV6OgB6Cc9vWSZMrDsIuGqegmBFesbIoPAqsP7sPBgAEgBBQydj3ZCD1ar1lTgQYDa7VKTpI-xzy7lr4L7HT3ESPZTPV6LJrpSIjJRxGRyUYAbQAuuCAHRYhQwEoQMpdLzSM5QKDIJjVIq4qClcqVGprDapD5fKinC5XfA3IEwEFgiFvaFwbmhHTjOztMqUOAEbT4emI+aLPkbLapHaA0WHNkYjn-Lmau6MxQstSwpHwxwWxRozHY4o0-F0qoIklkilUvEE+kqk0fNKYHV6skGvZa32pehTXwAC2A6AIyGAmVQ4NQ5NGcBgMfKcAABhZcNZbCI7Hm4HYIP5RBB4K14-AFPmYolUHm6DN4ABlZgLOx+QKG8J8OZ92qxdUDmAig5JdsASA0mWg0hO-Bb3ADG9QGMLxa0pfcwmEGm0-TX263sQxADla2cfHGlO48zQgA).

**Comment by edahlseng** [comment] 2019-03-01 01:43
Ahh, thanks @jbrown215, that rewrite was helpful. I didn't realize that was a limitation.

Is this a fundamental limitation? It would be awesome if some day Flow could just infer these , and I'm curious what it would take to get there.

**Comment by jbrown215** [comment] 2019-03-01 15:08
@edahlseng It is a fundamental limitation of the inference algorithm we use :(

**Comment by goodmind** [comment] 2019-03-11 13:38
Is this resolved? @villesau

**Comment by jbrown215** [comment] 2019-03-11 15:41
@goodmind: I'm open to considering improvements again in the future, but for now this is safe to close.

**Closed by jbrown215** 2019-03-11 15:41 UTC
