### ISSUE TITLE
Function variable behaves like any. fn.a.b.x.d is not giving any error

### ISSUE THREAD

**Issue by OlegMalkov** [facebook/flow#7437] opened 2019-02-02 11:57 UTC
Flow version: 0.92

function fn(){}
const x = fn.a.b.x.d

## Expected behavior
Show error "a is not found in fn variable"
## Actual behavior
"No errors"
* Link to Try-Flow or Github repo:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swo44AKASjAG9UBfdXEgZ3zAA8wBeMigDouggJ5igA

**Comment by wchargin** [comment] 2019-02-02 19:00
Duplicate of #6490.

**Closed** 2019-02-03 02:09 UTC
Labels: bug
