### ISSUE TITLE
Dependent refinements aren't supported

### ISSUE THREAD

**Issue by bkendall** [facebook/flow#2034] opened 2016-07-05 20:55 UTC
I'm not entirely sure what to call this, but the behavior changed between 27 and 28, so I wanted to follow up and verify if the new behavior is correct.

Roughly, I have the following code:

``` js
/* @flow */

type TestObj = {
  name: string,
  value?: string
}

function foo (opts: TestObj) {
  if (opts.name === 'hello' && !opts.value) {
    console.error('name = hello requires a value')
    return
  }
  let message = opts.name
  if (opts.name === 'hello') {
    message = `${message} ${opts.value}`
  }
}
```

With flow 27, this did not cause any issues. Flow 28 causes this error:

```
src/test.js:15
 15:     message = `${message} ${opts.value}`
                                 ^^^^^^^^^^ undefined. This type cannot be added to
 15:     message = `${message} ${opts.value}`
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^ string
```

This surprised me. By making the second `if` statement identical to the first `if` statement, the error goes away (they both check `opts.name === 'hello' && !opts.value`). I _assume_ this is correct behavior - having to keep track of knowing what kind of checks were made before is tricky. I can see it going either way in my head.

Let me know if you need any other information.

**Comment by mroch** [comment] 2016-07-05 21:36
so, the reason this changed between 0.27 and 0.28 is because flow previously allowed implicit coercion of `undefined` to string in a template literal. if you'd done this in 0.27, it would've complained too:

```
message = message + ' ' + opts.value;
```

(0.28 made templates act like string concatenation)

maintaining the refinements between complex conditionals is a nice feature request, though.

after the first `if` statement (inside the else branch, if you will), flow would have to infer that `opts` is now `{ name: <any string other than 'hello'>, value?: string } | { name: 'hello', value: <non-empty string> }`. we can (internally) represent `<non-empty string>` (a `StrT(..., Truthy)` type) but don't have a way to represent `<any string other than 'hello'>`.

**Comment by vkurchatkin** [comment] 2016-07-05 22:05
> don't have a way to represent <any string other than 'hello'>

BTW, it would be nice to have a way to express this, in addition to union and intersection

**Comment by bkendall** [comment] 2016-07-05 22:48
phew - okay, I think I get that. thanks for the information! I definitely understand that the refinements are a _hard_ thing to do. But now I know I'm not just going crazy :)

(if you want to remove the `Question` from the title, now that nice labels are in place, that's cool)

**Comment by TrySound** [comment] 2019-02-05 00:02
Duplicate of https://github.com/facebook/flow/issues/7228

**Closed by TrySound** 2019-02-05 00:02 UTC
Labels: Effort: hard, Typing: refinements, feature request
