### ISSUE TITLE
Flow 0.55.0 breaks react-redux for some cases

### ISSUE THREAD

**Issue by johnhaley81** [facebook/flow#4939] opened 2017-09-21 19:16 UTC
Hi all,

A quick note that when updating to flow 0.55.0 I started getting errors with some `connect` functions I have with `react-redux`. [Here is an example on flow.org/try](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AEoCmAhgMb6TaxqgDk2pFdA3MiKALTc+egBCRAOYoAdqEbQiANxKj8AA0YATAK4APBaDnLQSprk4qNW5UTLQS2ErhSxRAZy69uyMxatFQuAJ4YvACIoDhg2ZAAWAIIACgCSADyRAHygALygABTktvYAXKCRAJRpKZFs7paM3n6BwaG4EYn5AN7V-vkAJADKqgBGvv7xDrjYYkIpAL4p6UEhYVFxiUlsiBWebV4AsijKylLwnjEJXQA0BWcBaaCz9Y3J06DNiKCgynXz+QFsL0JEuF24GxEDKFfJdNgTFZrKoDLwAnBEeKnc7XK43eZLB5PF5vOYNcKfb6gX7-QG4YGg0DgxCQtzmSpeWGgTYkDAAoEAFVg0WoGAcSLOAHlovlBb0AFbmXBnLoi0BiyUUB4ZZ6gYZAsEnVUIUQ82B80XRRDFVIpDIZdXkzWgHV6g3y6ImlKy4oAHyp0Sh9PWTJZGHR+K5dv5kSFcoVUou4YlUumqvd5txtwJ13e+KWZ1tvIchqd10d8fzXo8MJqzKI2F+waR0SjopjFDD9cV0tA0ZbytVlqIwbBtdVSfmvfzWpeWf1OYdxpKbeLDI2oAAwvZyep8OlWsMEWDcAj4gAqM77yZz9YeBxOZeiURSojKZeYexEeTxYVnaIpIhr5-KJzEbIdA+WA3i+wopNiapkigZCgAA6tYGD+PeNDAc+uD5IulgXvE-4UIBKFPi+H5JKOxJ-PBrJIbEjiAqIZAUvkuG4Phj4gbg8QfqRGDZoapHdvk0iwDsNJ0iWjJlleN4UHeQGEbgmEkNhb5tg8CnYaqkm3shrFoa+tYqYgyyifOTKaRQOB6e+nYvGQBFsYxBgsah8gcjUHFJNOppLvYUnktpznyVh-LKR+p5VOeTh6tIOwVgKBSft+oi-oQjmyWx8QQVujA7nuyLJKREQoNAyiMKIAD8+RyD4NLgRMxnrJAqh0Tk4hkIwQJRTF2Aqi8WVEAA0kQPgVZBoyiEIfF9INw35MMY1CMa+SdWY2AHkeRmrN6pb+N515SoKGAtU4G6qhgqiMCNvSwLAUhyKR8AoLg4TEJAl3Xbdog0mF4k7QAcqo0DQFcogA0D7qCTs32gI1zV2K1PlSokYZJD1oAAHQY4wwz5JE2DWD48QQ8oKQcPE6TwDgADWViwE1uiQDgoDhLguAGiAIhPX0aO2WgwCQOQRBXbAlN83A8DAMEDiqEQDjAAATAAzAAbAADItu2+RZyndKo-h4G5rSDvinxpnckygAAZA6SQbdCXgwxQcOgLZe0UEj1uo2grLsuSQY8aA-2A6RXv+qb4R+xO+SB9AwcVlW-vR6R+pHRhCMUAdR3q2Zu6rdrPR67CGWvGHJt4mboATJb1u21t9tNY79jO2n7F5WGMofp73tkkQEf2n6Ps99y2ZxcpsokaqIcBhEveTonE9xz2Ceg0nh1ww4I3Zxna9Z83Wv6TrBdubKVeGyXqZl+ESwV1XYE12J0P1y1Teu+xoYOlGKMT13nJD5HAfL1-UOF8Z75D9FPcOv8+Tu2UgETi89KyLz-nPMcq97Dr1Ti-LeaCd4vz3mcA+FZC6wJvsRKGDsn4u18nFN+o99KwM-i8EOA8QHMm-r7SB-JkS0PHow1k4CWFgLDjPaBdC4GMIXsOZBNpUGOA3s3LBjgcGa1zvvfOhCj7RCrsQq2t8yGPydpQxGrd34eijFZTubJu4CLYYPasXD9Jj2DnwoRHCo4APEQg4cmwJHD1lGYkxYjpFHTkZgmRDglFSjwSpPRsNG6GLdsY2h-iO6AOYa41hlif52Lbh6HhoBJ4uK8c44BHCREf1jp4-23jKkThrP4kKeTk5rxCb5BR4TKTZyiaFVULxel9P6QMwZ-TEAcBcNwUAABRJKrwto2DXs4FwyAmQDyuBBAA1AzWA+QQZoF6BWLUtJEAu2GPkmxM8riowAPo7iBKRCCY5ICQAcH8UiEwWg9JtI8556FQA7L2dgV5nkPIvAyK0TZFc8yguhtdfI4K1mfKeX8CFKxjn4AAGLXQuWCzFbzHjQq2b81QuyKwQpnPEN40gkjNE2RMeIwAKUbVRRrLSGLYBXHibgDITCrEcMKBkVlhQWBAA). Note that there is an error in 0.55.0 and *not* 0.54.1.

It seems that if you have `mapStateToProps` as a function that returns a function, flow can't figure out the correct intersection. It gets confused between cases:

```javascript
declare function connect<S, A, OP, SP>(
  mapStateToProps: MapStateToProps<S, OP, SP>,
  mapDispatchToProps: Null,
  mergeProps: Null,
  options?: ConnectOptions
): Connector<OP, $Supertype<SP & { dispatch: Dispatch<A> } & OP>>;
```

and case:

```javascript
declare function connect<S, A, OP, SP, DP>(
  mapStateToProps: MapStateToProps<S, OP, SP>,
  mapDispatchToProps: MapDispatchToProps<A, OP, DP>,
  mergeProps: Null,
  options?: ConnectOptions
): Connector<OP, $Supertype<SP & DP & OP>>;
```

Which to me seems like a bug and that case 1 is the only valid choice.

**Comment by echenley** [comment] 2017-09-21 19:54
Related flow-typed issue: https://github.com/flowtype/flow-typed/issues/1269

**Comment by julienw** [comment] 2017-11-02 14:59
I tried to make a reduced testcase, but after reducing a log, I got a case where it's breaking in both 0.54 and master ;)

Still I'd like to mention these 2 cases:
[Case 1](https://flow.org/try/#0CYUwxgNghgTiAEAXAngBwQWSqgyoqiIAKgPYAKMJqAzgDw5kBc8A8gEYBW4iAfPALwAoePAAUASgF9REqfAaSAPvLIBuQYNCRYCAGYBXAHZhEASxKH4YC4e70yPUcPgBbbHgLFylGsyy58QlIKKjoGHgAaQXFmADcSU2B1TXBoOHgDYzMLKxs7Bgj4AC1mdi4TR2c3AM9gn2o-d0CvEJp7SKrsABFTalQCMAALOtDmIqiY+HjE5OtDWxMnEVl+aQBvDJISZgBGeABfcWj1EVOz84uL50ub2+vbh7OgA) works in both versions, while [Case 2](https://flow.org/try/#0CYUwxgNghgTiAEAXAngBwQWSqgyoqiIAKgPYAKMJqAzgDw5kBc8A8gEYBW4iAfPALwAoePAAUASgF9REqfAaSAPvLIBuQYNCRYCFOnhZUAEQCW1VATAALUhSp0jTVp259+8R+s3hoceADMAVwA7MEQTEmD4MEjg7noyHlFheABbbDwCYnJKGmZDTMJbXLoGHgAaQXFmADcSE2AvLV8EINDwyOjY+IZy+AAtJJT03HwinPt8jLHsuxoEiuHsU3NLGwm8g2WzC0RrYvtaQcrq+DqGrxjguLDkkVl+aQBvAJISZgBGeABfcSr1ESAoHAkEglKgiGQ8GQmFAoA) fails in both versions. If I mention them here is that I don't really understand why they yield different results, and I feel like this can be related to this issue.

Now I'm going back at finding a reduced test case.

**Comment by julienw** [comment] 2017-11-02 15:17
[I think this is the most reduced test case I can find](https://flow.org/try/#0CYUwxgNghgTiAEAXAngBwQWSqgyoqiIAKgPYAKMJqAzgDw5kBc8A8gEYBW4iAfPALzwAUPHgAKAJQC+YydPgMpAHwVkA3EKGhIsBCnTwsqACIBLaqgJgAFqQpU6xpq07c+-EeLn8+T5fCcNLXBoOHgAMwBXADswRFMSaPgwROjuejIeMU8AW2w8AmJyShpmIwLCOxK6Bh4AGiEJZgA3ElNgIO1QhCjY+MTk1PSGOoDM7NE83HxK4ocy-Jmi+xoM+tzsMwsrWznSw03zS0QbKodaJ3Wm+Fb2oJTotLiJ8SkfcQBvCJISZgAWABM8AAvhJGhpRJCodCYTDPLCEYj4YiUVDkajUeiMYigA):
```javascript
declare type MapStateToProps<SP: Object> = 
  () => (() => SP) | SP;

declare type MapDispatchToProps<DP: Object> =
  (() => DP) | DP;

declare function connect<SP>(
  mapStateToProps: MapStateToProps<SP>,
): void;

declare function connect<SP, DP>(
  mapStateToProps: MapStateToProps<SP>,
  mapDispatchToProps: MapDispatchToProps<DP>,
): void;

connect(
  () => ({ foo: 42 })
);
```

There is something strange happening because changing `MapStateToProps` to
```javascript
declare type MapStateToProps<SP: Object> = () => SP;
```
(which is the correct type here) removes the error. I don't see why changing the type for `MapStateToProps` makes it correctly decide that `mapDispatchToProps` can't be null.

**Comment by julienw** [comment] 2017-11-02 15:29
Calling connect like this works:
```javascript
connect(
  (): * => ({ foo: 42 })
);
```
Which makes things even weirder to me :)

**Comment by xdissent** [comment] 2017-11-02 15:56
Heh, yeah, it gets even weirder. Try defining your connectors in one file then applying them to a component in another. It magically makes many checks fail and others pass. I think it comes down to *when* the types are evaluated, in combination with the fact that subtyping rules for **object function args** are different than for normal object types. I'm hoping to pick it back up this evening - I took a crash course in Ocaml the other day just in case!

**Comment by TLadd** [comment] 2017-11-07 23:15
A couple of other relevant issues in flow-typed:
https://github.com/flowtype/flow-typed/issues/1432
https://github.com/flowtype/flow-typed/pull/1317

It seems that the react-redux libdef is no longer catching quite a few errors starting in 0.55. Doesn't seem to be totally clear if it's a flow bug or libdef issue though.

**Comment by bdrobinson** [comment] 2017-11-08 15:59
I've found the commit that broke things. I went through and did a `git bisect` on the flow source code, and found that both the OP issue AND the issue described in https://github.com/flowtype/flow-typed/issues/1432 start happening after Flow commit https://github.com/facebook/flow/commit/bd938abfb8970972d512847415d0f68563120480 .

I'm not at all familiar with the flow source code so I don't know whether this commit introduces a bug, or just changes the API. Hopefully identifying the breaking commit will make it easier for people who actually understand how flow works (ie, not me!) to work out what the issue is. @calebmer and @samwgoldman : you wrote/reviewed the commit in question, if you get a chance would you be able to shed any light on this?

**Comment by djb5143** [comment] 2017-11-14 16:31
As @TLadd said it seems most of the $ExpectErrors just emit warnings saying they weren't used, which doesn't actually fail the tests. I encountered this myself when I was trying to fix #1498, I had test code working in a project I'm working on but I couldn't get the flow-typed test to run and catch errors. I think there might be a bigger issue and until the test is fixed we can't fix the libdefs, @villesau do you know if this was ever fixed I remember seeing a comment you made about it somewhere.

**Comment by villesau** [comment] 2017-11-14 21:32
@djb5143 the $ExpectError issue was fixed in this PR for flow-typed: https://github.com/flowtype/flow-typed/pull/1407 and tested in https://github.com/flowtype/flow-typed/pull/1411

So instead of relying on exit code of flow, now it checks the output instead.

Try out with up to date master branch of flow-typed?

**Comment by wiscat** [comment] 2018-01-19 06:54
Continued to be an issue with flow version 0.63.1, but the error is gone when explicitly set mapStateToProps function return type.

**Comment by villesau** [comment] 2019-03-02 19:15
React-redux libdefs have been rewritten twice after this so I assume this is no longer valid.

**Closed by villesau** 2019-03-02 19:15 UTC
