### ISSUE TITLE
Type Refinement is not working with constants

### ISSUE THREAD

**Issue by josh-schlick** [facebook/flow#6986] opened 2018-10-10 21:15 UTC
Tested with flow.org/try: [Example](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVxhgCoE8AOApmAEqFQCWAdoQLaFUAuYFAzmFXMwnAE4DW1AOZgEFRgAswAYzhVWjAIZNWALnSMCxbAE0ACgFEA+gHkAcgbABeMAHJzB2wG5Umojn3HsAdRPW7PibO6LLyzA6qHoamFv72FsGhCji+kbrRgXGBwahJzEr8hKwmNP4AFPiKvIq0aZ4xBgCU1gB8YADeAL4uGFgAInBFHFyifPyiEgwycLSVvMJgikKK1MmK02HKjLlyyXKEJrzYPHXRDmAAPlFevv4OLhRQYGX7h8dw1lY2Ds3tqGBgApFEqEF40N48RpOMCoTroTBgAZDHgCCZTWSzKoLJYrMKLMAwcSEaowVCPZ6vI48T42eKOX7-QGKQrFGhgg5UuBQmFw3pgADCk2kgioIhxq2Y6zyWzAABNBuwUeMEJMqCxmGwWGrlGA4AAjABWhGk2zyusNkXahVwp2MDk6lw61ttRkCDps7TAzrA526ZKeL0NADprTSfRYGQCgazQfqDSHCLhubC+ZxGIRLd70nbYlds67fA75UM06MBOgK0A)
```js
/* @flow */

// Type Refinement is not working with constants:

type TYPE_ONE = 'ONE';
type TYPE_TWO = 'TWO';

const ONE: TYPE_ONE = 'ONE';
const TWO: TYPE_TWO = 'TWO';

const takesOne = (param: TYPE_ONE) => {};

// Does not work when comparing against a constant
const oneOrTwo: TYPE_ONE | TYPE_TWO = ONE;
if (oneOrTwo === ONE) {
  takesOne(oneOrTwo); 
}

// Does work when comparing against a literal
if (oneOrTwo === 'ONE') {
  takesOne(oneOrTwo); 
}

// Checking against a constant does work when it is in an object
const obj: {key: TYPE_ONE} | {key: TYPE_TWO} = { key: ONE };
if (obj.key === ONE) {
  takesOne(obj.key); 
}
// note: {key: TYPE_ONE | TYPE_TWO} does not work
```

```
16:   takesOne(oneOrTwo); 
               ^ Cannot call `takesOne` with `oneOrTwo` bound to `param` because string literal `TWO` [1] is incompatible with string literal `ONE` [2].
References:
14: const oneOrTwo: TYPE_ONE | TYPE_TWO = ONE;
                               ^ [1]
11: const takesOne = (param: TYPE_ONE) => {};
                             ^ [2]
```

**Comment by wchargin** [comment] 2018-10-10 22:48
Duplicate of #6968?

**Comment by josh-schlick** [comment] 2018-10-10 23:28
Yes, looks like this is a duplicate.

**Closed** 2018-10-11 18:22 UTC
Labels: Closed: duplicate
