### ISSUE TITLE
Using type name `Class` introduces type error

### ISSUE THREAD

**Issue by deian** [facebook/flow#942] opened 2015-10-13 23:40 UTC
Version: 0.17.0

Using the type name `Class` introduces a type error. For example, the following program:

``` javascript
/* @flow */
'use strict';

class A {
  /*::
   classes: Array<Class>;
  */
  constructor(classes) { 
    this.classes = classes; 
  }
}

class Class = { 
        constructor() {}
}
```

fails to type check with the following error:

```
a.js:6
  6:    classes: Array<Class>;
                       ^^^^^ Incorrect number of type parameters (expected 1)


Found 1 error
```

**Comment by samwgoldman** [comment] 2015-10-14 00:14
I have actually run into this one before myself. To shed some light here, the issue is that `Class` is actually a builtin type. Given a class, `A`, the type `Class<A>` is the type of classes that create instances of `A`.

Because this is a builtin type, when we see `Class` in a type annotation, Flow automatically assumes we mean the `Class<T>` builtin, hence the error message you got.

I think this is 100% a bug in Flow, but I'm not sure how to fix it. Here are a couple options, definitely not a complete list:

1. Consider the current scope when evaluating type aliases—if a type named Class is in scope, it should shadow the global builtin `Class<T>` type.
2. Rename `Class<T>` to something else. This just moves the problem around, unless we can come up with a naming/scoping mechanism that keeps locally defined types separate from globally defined ones.
3. Prevent people from creating local types that shadow global ones. Really, I'm listing this here more as a strawman. It's too easy to create a conflicting type name via class declaration and I see no reason to go this route.

**Comment by gabelevi** [comment] 2015-10-15 16:01
We had a very long debate about this back in May. There were a few issues in contention:

* We could have made the builtin type operator be called `$Class` instead of `Class`. However thus far the `$` was used for experimental things rather than just for reserving things for Flow.
* How should builtin type operators be invoked? I was of the opinion that they should have a different syntax to differentiate them. For example, we do `typeof MyClass` rather than `Typeof<MyClass>`. We could have done something like `classof T` or `Class(T)` or really anything except reuse the generics syntax.
* Should we let local variables shadow operators? We can pretty easily see that `Class` is defined locally and use that instead of the `Class` operator. Though this doesn't really work if there is a global variable named `Class`

We really should have fixed this back in May before people started using `Class<T>`. Le sigh.

Personally, I think this is what we should do:

1. Type functions should be called using parens. With a single argument parens are optional. So things like `var a: typeof b`, `var c: class A`, `var d: $Diff(e, f)`
2. `$` should be continued to be used for experimental-only
3. We either stop supporting `Class<T>` immediately, or continue legacy support, using that if-locally-defined-do-the-right-thing trick. I think I'd rather make the breaking change, though.

**Comment by deian** [comment] 2015-10-19 05:47
+1 I think that is a pretty reasonable approach. I'm personally in favour of the breaking change. Though I like the if-locally-defined-do-the-right-thing trick, I suspect it may lead to some confusion.

Thanks both for looking into this!

**Comment by nicolo-ribaudo** [comment] 2020-03-05 01:21
We just got hit by this in Babel (https://github.com/babel/babel/pull/11196#issuecomment-594383590). It also affects `Function`.

Personally, I think that shadowing is what makes the most sense, since `Class<>` is intuitively a global type which should follow the same scoping rules as everything else.

**Comment by SamChou19815** [comment] 2023-02-10 22:11
Fixed by https://github.com/facebook/flow/commit/e57b70b0c42c300a4785f8eefb540c81e8e557f8. Once that got into the release, we will no longer ignore shadowing of builtin types.

**Closed by SamChou19815** 2023-02-10 22:11 UTC
Labels: bug
