### ISSUE TITLE
flow doesn't report error on wrong lambda attribute accessing

### ISSUE THREAD

**Issue by rvion** [facebook/flow#4589] opened 2017-08-13 10:07 UTC
try flow link:

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCAJnGALxgDeY2+AXGAEQCGpTANGAK47EsY8xAMrcARgGcMAvIwDyYgFZ4AxhjABfTLgIk4cnBgkVqvfoJHipM+UtUYteAB444AJ3Uq4AOylg2ZJQAFHCGEox6BkYAlGARpBQAfGBBVKhgtDr0rOwc6Tx8MpaS0oKMAQB0xEI1AF7EyrUAltxgwMBgADwAtGAAFnhusrQDQ2ASfXDcxGBiBCzeYINu7qga0UA

```js
/* @flow */

type Ado = { type: "ado", updatedSubstate: Object }
type AdoOpts = { updatedSubstate: Object}
export const ado = (opts: AdoOpts) : Ado => ({
  type:"ado",
  updatedSubstate: ado.dededezdjeziu // <- here: there shoud be an error
})
```

**Comment by vkurchatkin** [comment] 2017-08-13 10:55
Duplicate of #106

**Closed by vkurchatkin** 2017-08-13 10:55 UTC
