### ISSUE TITLE
Cannot use extends in declaration file

### ISSUE THREAD

**Issue by runn1ng** [facebook/flow#1240] opened 2016-01-03 21:08 UTC
You cannot use `extends` (and `mixins`) in declaration file now.

See
https://github.com/facebook/immutable-js/issues/203#issuecomment-165790502

and the gist here
https://gist.github.com/bouk/911b8d4993c19de3f98f

**Comment by runn1ng** [comment] 2016-01-03 21:09
Related to this issue
https://github.com/facebook/flow/issues/1189

but I put it as a separate issue, since I think it's different than using it in code itself. This is definitively a regression

**Comment by jeffmo** [comment] 2016-01-06 05:33
I followed up on the immutable issue, but these two situations aren't related. You can indeed extend a `declare `ed class

(In that issue someone is trying to extend an interface -- which can't be extended, only ` implement ` ed

**Comment by runn1ng** [comment] 2016-01-06 09:55
oh ok. I will try to edit that declaration file and will update. thanks a lot!

**Comment by samwgoldman** [comment] 2016-03-16 20:49
Hi @runn1ng. I'm going to close this, since it seems the issue is resolved. Let me know if there's something else actionable here. Thanks!

**Closed by samwgoldman** 2016-03-16 20:49 UTC
