### ISSUE TITLE
JSX elements with a period in the name don't type check

### ISSUE THREAD

**Issue by chrissnyder** [facebook/flow#3822] opened 2017-04-27 19:14 UTC
Not sure if this is a bug or just a design decision, but wanted to report it anyway. Components with names such as `Component.SubComponent` aren't properly typechecked.

Pseudo code setup:

```
class SectionHeader extends Component {
  props: {
    label: string
  };
}

class Section extends Component {
  static Header = SectionHeader;
}
```

In use:

```
import Section from 'somewhere';
const { Header } = Section;

class OtherComponent extends Component {
  render() {
    return (
      <Section>
        <Header foo="bar" /> // Works, type checks as expected
        <Section.Header foo="bar" /> // Doesn't work, no type checking happens
      </Section>
    );
  }
}
```

**Comment by vkurchatkin** [comment] 2017-05-01 20:02
Duplicate of https://github.com/facebook/flow/issues/1113

**Closed by vkurchatkin** 2017-05-01 20:02 UTC
