### ISSUE TITLE
Allow ignoring of certain modules

### ISSUE THREAD

**Issue by clayne11** [facebook/flow#1875] opened 2016-05-31 18:44 UTC
I'm using Meteor and Meteor has it's own package system that can't be resolved using the `node` resolver. I'd like to ignore all of the `meteor` imports in my project.

For example, have flow ignore the following: 
`import {Meteor} from 'meteor/meteor'`

I don't see a way to configure this right now. Would is be possible to add an option like `module.ignore_modules` and have it match RegEx?

**Comment by calebmer** [comment] 2017-07-26 22:18
Closing since this issue hasn’t seen a lot of activity. Sorry about that 😣

Please reopen with a reproduction on https://flow.org/try if you are still having issues!

**Closed by calebmer** 2017-07-26 22:18 UTC
