### ISSUE TITLE
Flow allows for invalid programs when using functions

### ISSUE THREAD

**Issue by danwang** [facebook/flow#3839] opened 2017-04-29 05:17 UTC
I'm having trouble trusting the output of Flow when it happily suggests that there are no errors because I've seen many cases where the checker allows for obviously incorrect programs.

Here's a minimal example I created [Flow try link](https://flow.org/try/#0PTAEDMEMBsGcFNQGMD2A7cBLAJvNT4AoACnAC5RiBKUAXgD5QA3FHKigW0wA95s7G4AHSRqQgEZikY7NQDcQA):

```
// false confidence
(f: () => void): mixed => f.a().b().c().d();
```

It appears that typing a variable as `() => void` ruins all type checks.

Did I make a bad assumption that led to my conclusion that this program should fail a type check?

**Comment by vkurchatkin** [comment] 2017-04-29 05:23
Duplicate of https://github.com/facebook/flow/issues/106

**Closed by vkurchatkin** 2017-04-29 05:23 UTC

**Comment by danwang** [comment] 2017-04-29 05:25
that issue is from 2014
