### ISSUE TITLE
Track whether a function is non-mutating

### ISSUE THREAD

**Issue by kevinbarabash** [facebook/flow#7988] opened 2019-08-04 23:04 UTC
## Proposal
Any function that we can guarantee is non-mutating can be called without invalidating type refinements.  Although the invalidation of type refinements can be worked around, the work arounds can be a bit awkward.  The most common work around is to destructure properties from the object we're refining.  This can get messy when refining multiple variables of the same type at the same time.  Also, invalidation of type refinements can be confusing to developers who are new to flow.

A function can be considered non-mutating if all of the following are true:
- All params are basic types, e.g. `boolean` | `number` | `string` | `null` | `void`
- The function shouldn't call `.exec()` on any `RegExp` params (it would be nice if `RegExp` was generic based on flags since only `g` and `y` cause a `RegExp` to be stateful)
- All params that aren't basic types, e.g. array, object, and class instances should be readonly
- The function shouldn't call any mutating function calls (this includes callbacks)

**Possible syntax**
We also need a way to declare library functions as non-mutating such as `console.log`.  This syntax could also be used in implementation files to assert that a function is non-mutating.  Here's one possible solution:
```js
declare var console: {
   log(...data: Array<any>): void %non_mutating,
}

function predicate(foo: $ReadOnly<Foo>): %checks, %non_mutating {
   return foo.type === "foo";
}
```

Marking `predicate` as `%non_mutating` is not needed to avoid invalidating type refinements, but if it did mutate `foo` then an error would be raising saying saying that "`predicate` is mutating even though it's marked as `%non_mutating`".

**Simple non-mutating**
```js
function add(a: number, b: number) {
  return a + b;
}
```

**Non-mutating with complex type params**
```js
type Node = {
  type: "leaf",
  value: number,
} | {
  type: "non-leaf",
  children: Node[],
};

// non-mutating even though it isn't explicitly marked with %non_mutating
function countChildren(node: $ReadOnly<Node>): number {
  switch (node.type) {
    case "leaf": return 0;
    case "non-leaf": return node.children.length;
  }
}

// non-mutating even though it isn't explicitly marked with %non_mutating
function traverse(node: $ReadOnly<Node>): void {
  switch (node.type) {
    case "leaf": return;
    case "non-leaf": {
      countChildren(node);
      // currently the next would cause an error, but shouldn't under the proposal
      node.children.forEach(traverse);
    }
  }
}
```

I think this could also be useful in being able to create read-only versions of class types by filtering out all mutating methods from the original class type.  When determining whether a method is non-mutating we'd do the same checks as for functions as well as these additional checks:
- Check that we're not setting or updating a value
- Check that we're not calling a method that mutates a instance variable

It might work something like:
```js
class Stack<T> {
  items: T[];
  constructor() {
    this.items = []; // it's okay to mutate in the constructor
  }
  // non-mutating
  peek(): T | void {
    return this.items[this.items.length - 1];
  }
  // mutating
  push(item: T) {
    this.items.push(item); // since push is a mutating method on Array
  }
  // mutating
  pop(item: T) {
    this.items.pop(); // since pop is a mutating method on Array
  }
}

type ReadOnlyStack = $ReadOnly<Stack>;
// this equivalent to
declare class ReadOnlyStack<T> {
  constructor(): void;
  peek(): T | void;
}
```

**Comment by kevinbarabash** [comment] 2019-08-04 23:25
It would also be cool if we could track what a function/method mutates.  This might not be possible in all cases, but for things like `stack.push(item)` we should be able to tell that it's only mutating the `stack` object so it shouldn't invalidate unrelated type refinements.  This would require different syntax, something like:
```
declare class Stack<T> {
  push(item: T): void %mutates(this);
  pop(item: T): void %mutates(this);
  peek(): T | void %non_mutating;
}
```
`%mutates` could be used with 0 or multiple args.  When used without an arg it will invalidate all type refinements.  When call with `this` it will only invalidate type refinements for the object the method is being called on.  Other possible things that could be passed to `%mutates` are parameters to the function/method, globals, or even any variables currently in scope.

If we had the immutable mode suggested in #5369 we could drop all `%non_mutating` markers from the code.

**Comment by goodmind** [comment] 2019-08-05 11:33
This looks more like algebraic effects?

**Comment by goodmind** [comment] 2019-08-05 11:43
Related https://github.com/facebook/flow/issues/2715

**Comment by kevinbarabash** [comment] 2019-08-06 03:59
@goodmind thanks for the links.  I read a little of https://www.microsoft.com/en-us/research/wp-content/uploads/2016/08/algeff-tr-2016-v3.pdf.  I don't have a background type theory so a fair amount of it was over my head, but I pick up that Koka tracks effects and has different rules for describing how effects flow through a program.

It might worth trying to create a list of effects the JavaScript code can produce and which effects mutate, what they mutate, and whether they mutate in a safe way.

An example of how an array may be mutated in safe way:
```
class Animal {};
class Cat extends Animal { meow() {} }
class Dog extends Animal { woof() {} }

function removeFirstAndLast(animals: Animal[]) {
  if (animals.length > 1) {
    animals.unshift();
    animals.pop();
  }
}

const cats: Cat[] = [new Cat, new Cat, new Cat];

removeFirstAndLast(cats);
```
This is safe because we're removing values from the cats array.  There's no way `Dog` instance can end up in the array.  This type of mutation is basically covariant safe mutation.  Originally I wrote this ticket with type refinements in mind, but it seems that tracking different kinds of effects has other benefits.

Getting back to type refinements, consider the following example:
```
type MaybeX = {
  x: ?number,
};

const foo: MaybeX = { x: null };
const bar: MaybeX = { x: null };

function updateFoo() {
  if (foo.x) {
    foo.x++;
  }
};

if (foo.x && bar.x) {
  updateFoo();
  (foo.x: number);
  (bar.x: number);
}
```
The call to `updateFoo()` shouldn't invalidate the type refinement of either `foo.x` or `bar.x`. The reason for `bar.x` is simple, `updateFoo` doesn't mutate `bar`.  We can only say this because `foo` and `bar` are both constants and initialized to different values.  The reason we can keep `foo.x`'s type refinement is that `updateFoo()` doesn't change the `foo.x`'s type.  We know this because in `updateFoo` the only mutation occurs inside a type refinement of `foo.x` and the mutation doesn't change the type.

Although we can define different types of mutations with different properties and use those properties to convince ourselves that certain mutations are safe, I do think that there are probably diminishing returns.  I do think that architecting things to support multiple effects is prudent, but we should probably start out with a single "mutation" effect that's a captures all of types of mutations.

**Comment by SamChou19815** [comment] 2023-02-22 20:11
Duplicate of #2715

**Closed by SamChou19815** 2023-02-22 20:11 UTC
Labels: Typing: refinements, discussion
