### ISSUE TITLE
Flow doesn't report if a non-voidable class property isn't defined at construction time

### ISSUE THREAD

**Issue by julienw** [facebook/flow#7696] opened 2019-05-02 18:03 UTC
Flow version: 0.98.0

## Expected behavior
```js
class SomeClass {
  foo: string;
}

const instance = new SomeClass();
if (instance.foo.startsWith("bar")) {
  // do something
}
```

Flow should warn that `foo` isn't defined at construction time. I understand this can be difficult when there's an actual constructor, but should be easy when no constructor is defined.

## Actual behavior

Flow doesn't warn about this issue.

* Link to Try-Flow or Github repo: https://flow.org/try/#0MYGwhgzhAEDKD2BbApgYXFaBvAUNaAZvPAFzQQAuATgJYB2A5gNw4C+OOw8dl09lYOsGTQAvNDrIA7nCRoMEABQBKFjQLRF-CoOEA6IvD0CqFCAHUaFABaKARACMwVO8uXY80APRfoAE3hyORt6BjYgA

**Comment by jbrown215** [comment] 2019-05-03 18:17
This is a KP, but we have no plans for it currently.

**Comment by SamChou19815** [comment] 2023-02-04 05:38
Duplicate of #650

**Closed by SamChou19815** 2023-02-04 05:38 UTC
Labels: bug, Typing: soundness
