### ISSUE TITLE
Spread breaks exact object types

### ISSUE THREAD

**Issue by ForbesLindesay** [facebook/flow#3608] opened 2017-03-29 14:01 UTC
The following example:

```js
/* @flow */

const x: {|a: number|} = {a: 10};
const y: {|a: number, b: number|} = {...x, b: 10};
```

Produces the error:

```
4: const y: {|a: number, b: number|} = {...x, b: 10};
                                       ^ object literal. Inexact type is incompatible with exact type
4: const y: {|a: number, b: number|} = {...x, b: 10};
            ^ exact type: object type
```

but it shouldn't produce an error because `x` is an exact object, so spreading it into an object literal should not prevent that object literal being exact.

**Comment by vkurchatkin** [comment] 2017-03-29 14:36
Duplicate of https://github.com/facebook/flow/issues/2405

**Closed by vkurchatkin** 2017-03-29 14:36 UTC
