### ISSUE TITLE
accessing an object with a string key should error

### ISSUE THREAD

**Issue by vicapow** [facebook/flow#7392] opened 2019-01-25 18:39 UTC
const a: {| m: number |} = { m: 1 }; // exact or not, doesn't matter.
const s: string = '???';
a[s].foo.bar; // Should error but a[s] is somehow `any`

**Comment by jbrown215** [comment] 2019-01-25 19:53
Here's the offending code:
https://github.com/facebook/flow/blob/master/src/typing/flow_js.ml#L5765-L5769 

This is a place where we were intentionally unsound. I can't speak to why we were, but @dsainati1 made some changes to Flow so that we can explicitly track our sources of unsoundness and how they propagate throughout the codebase. He should correct me if I'm wrong, but he plans to get rid of all of these sources of unsoundness.

**Comment by dsainati1** [comment] 2019-01-25 20:04
Yeah accessing object indexer properties with computed values is super unsound at the moment. We have a couple of ideas in the works to address both this case specifically as well as sources of unsoundness more generally. I'm gonna relabel this as an enhancement since it is technically intentional but we are working on getting rid of this behavior soon.

**Comment by wchargin** [comment] 2019-01-30 07:33
Related (duplicate of?): #6568.

**Comment by KlaraFickova** [comment] 2019-02-25 11:40
It's not just computed values. The problem goes way deeper:
https://github.com/facebook/flow/issues/4257

**Comment by SamChou19815** [comment] 2024-07-03 16:06
This is now banned

**Closed by SamChou19815** 2024-07-03 16:06 UTC
Labels: enhancement, Typing: soundness
