### ISSUE TITLE
Exact fails when doing es6 object spread

### ISSUE THREAD

**Issue by MarcoPolo** [facebook/flow#2405] opened 2016-09-06 21:59 UTC
This fails:

``` js
// @flow

type A = {|
  foo: number
|}

const foo: A = {foo: 3}
const bar: A = {...foo}
```

With error:

```
demo.js:8
  8: const bar: A = {...foo}
                    ^^^^^^^^ object literal. Inexact type is incompatible with exact type
  8: const bar: A = {...foo}
                ^ exact type: object type
```

This pattern is pretty common in redux style reducers where you return the old state merged with new values  (e.g.`{...foo, foo: 4}`)

**Comment by samwgoldman** [comment] 2016-09-06 22:41
Yeah, I think your expected behavior is reasonable here. There are quite a few issues surrounding object spread (which is why it has its own issues tag), so we should probably take another look at the entire spread implementation with this and other issues in mind.

Thanks for the report with simple repro code!

**Comment by pbomb** [comment] 2016-09-27 16:01
@samwgoldman I'm curious if I should expect any activity on this issue and what a good workaround in the meantime might be.

**Comment by jfmengels** [comment] 2016-09-28 13:20
I discovered the same problem and noticed the same error applies when using `Object.assign`

```js
type Foo = {
  a: string,
  b: string
};

const baseFoo: Foo = {
  a: 'a',
  b: 'b'
};

const extendedFoo: Foo = Object.assign(
  {},
  baseFoo,
  { a: 'c' }
);
```

**Comment by dchambers** [comment] 2016-09-30 22:16
> @samwgoldman I'm curious if I should expect any activity on this issue and what a good workaround in the meantime might be.

@pbomb, the work around I'm using is to not start making use of exact types until spread support improves. I rely heavily on object rest/spread so I can write pure functional JavaScript.

OTOH, exact types seem like more of a nice to have feature. For example, there's a good chance my app will work after doing a large refactor once Flow's happy, but the tests may still fail if I have some extra properties left round that would cause any deep object comparisons to fail. It would be great if Flow caught that stuff too, but it's not the end of the world if it doesn't.

At least that's how it's working out for me anyway...

**Comment by guicar** [comment] 2016-10-12 08:39
@pbomb A workaround we use:

```
type Foo_ = {
  a: string,
  b: string
};

type Foo = Foo_ & $Shape<Foo_>;
```

The type `$Shape<Foo_>` represents the objects which have a subset of the keys `{a, b}`. An object of type `Foo` cannot contain other fields than `a` and `b`, and the spread mechanism (seems to) works.

**Comment by dralletje** [comment] 2016-10-26 13:00
@guicar 's solution works perfect for me!
I now use `type Exact<T> = T & $Shape<T>;` everywhere and it works :o

**Comment by ivanmanolov90** [comment] 2016-11-22 02:50
is there currently any activity on resolving this issue?

**Comment by steida** [comment] 2016-12-06 19:23
As for custom Exact type, it breaks autocomplete in Atom. Just saying.

**Comment by ferrannp** [comment] 2016-12-12 18:23
This is quite a missing key feature when using `Redux` where you probably use spread operator everywhere in your reducers. If you define an exact state type, flow will report errors when using the spread operator (`Inexact type is incompatible with exact type`). If you do not define exact type for your state, then you're app state is not safe anymore. Example:

```
type TAppState = {|
  auth: TLoginState;
  ...
|}

type TLoginState = {|
  isLoading: string;
  token: string;
|}

...
// Login reducer:

...
return { ...state, isLoading: true }
// Flow error: object literal. Inexact type is incompatible with exact type

**Comment by dsimmons** [comment] 2016-12-15 21:43
Just echoing @ferrannp. Ran into this in the same exact context (Redux reducers).

Specifically, I have a function (reducer) that accepts a param of an exact object type (let's call it `SomeType`). `SomeType` has two attributes, each of type `AnotherType`. I've annotated the function to return `SomeType`. 

I'm attempting to do something like the following:

```Javascript
const (anotherType: AnotherType) = { k: v };

// Copy a `SomeType` with one of the two `AnotherType` fields changed.
return {
  ...(someType: SomeType),
  attrTwo: anotherType,
}
```

**Comment by torarnek** [comment] 2017-01-20 13:34
I have found this workaround to work quite well for our redux reducers:
```javascript
export type Foo = {
  a: string,
  b: string,
}

type Exact<T> = T & $Shape<T>;

function reducer(state: Foo = {}, action: any): Exact<Foo>{
  return {
    ...state,
    a: 'hello',
  }
}
```

Using the `Exact<Foo>` as returning type of the reducer allows us to use the spread operator. And then by referring to Foo elsewhere in the application gives use autocompletion of properties.

Thanks to @guicar for providing the Exact method.

**Comment by mull** [comment] 2017-02-14 08:28
Is this indeed considered a bug? An entry in the docs right around "Exact objects" would be helpful!

**Comment by tuff** [comment] 2017-05-23 18:54
@guicar  and @torarnek your workarounds do not feature exact object types, and so don't address this isssue.

No errors:
```
type Exact<T> = T & $Shape<T>;

type Foo = {
  a: string,
  b: string
};

const reducer = (state: Foo): Exact<Foo> => ({
  ...state
});
```

Now make `Foo` exact:
```
type Exact<T> = T & $Shape<T>;

type Foo = {|
  a: string,
  b: string
|};

const reducer = (state: Foo): Exact<Foo> => ({
  ...state
});
```

Error: `object literal. Inexact type is incompatible with exact type`

**Comment by steida** [comment] 2017-05-23 19:36
@tuff Impossible with Flow 46. Don't use exact types. It's bummer, I know.

**Comment by skovhus** [comment] 2017-06-16 09:48
@samwgoldman let us know if there is anything we can do to help on this... : )

Really missing this in redux, where you can misspell a state key.

**Comment by royrwood** [comment] 2017-06-29 17:53
Agreed-- I would really like to defined my Redux state object as exact and be able to use the spread operator in my reducer, though Flow does not like that.  I have not seen any reasonable work-arounds for this yet.

**Comment by skovhus** [comment] 2017-06-29 18:14
Does this work in TypeScript?

**Comment by royrwood** [comment] 2017-06-29 18:15
@skovhus -- I'm not sure if it works in TypeScript.  I haven't tried....

**Comment by aaronjensen** [comment] 2017-06-29 18:33
To my knowledge, [exact types are not expressable in typescript yet](https://github.com/Microsoft/TypeScript/issues/12936).

**Comment by disoul** [comment] 2017-07-19 03:35
Exact<T> can not work in Flow 0.50

**Comment by Leooonard** [comment] 2017-07-23 10:42
type Exact<T> = T & $Shape<T>;

this kind of exact type solve the problem with spread opertor. but it also create a new problem. this is a workground:

```javascript
type Obj = {
        a: {
            b: number
        }
    };
    type ExactObj = Exact<Obj>;

    const A: ExactObj = {
        a: {
            b: 1
        }
    };

    let {
        a: {
            c
        }
    } = A;
```

in this workground, no error will happen though c is not a key of type Obj and i think this new problem brings more hramness than can't use spread operator with exact type.

**Comment by klimashkin** [comment] 2017-07-28 03:02
Probably that issue need to be pinned to the top

**Comment by hackhat** [comment] 2017-08-03 14:40
@torarnek great solution! Did you incur into any problems with that?

**Comment by mrtnzlml** [comment] 2017-08-03 14:45
> @torarnek great solution! Did you incur into any problems with that?

Oh yes. It doesn't work with covariant (read-only) properties.

**Comment by barczaG** [comment] 2017-09-22 19:51
May I ask why this issue was closed? I would like to use exact type together with covariant properties in Redux. My current solution is to drop exact types, but I'm not happy about it.

**Comment by valscion** [comment] 2017-09-23 16:20
> May I ask why this issue was closed?

...it isn't closed, and hasn't ever been closed?

<img width="702" alt="screen shot 2017-09-23 at 19 19 29" src="https://user-images.githubusercontent.com/482561/30775015-338ce21c-a094-11e7-96c3-21cfaacb2166.png">

**Comment by ajhyndman** [comment] 2017-10-18 12:02
I think most of the descriptions in this issue slightly overstate it.

It seems to be very specifically that trying to pass the result of spreading an inexact and exact type to something *expecting an exact type* that will trigger an error.


```javascript
// @flow
type A = {| a: string |};
type B = { b: string };

declare var a: A;
declare var b: B;

const c = { ...a };
const d = { ...b };
const e = { ...a, ...b };
const f: { a: string, b: string } = { ...a, ...b };
// Only this case triggers an error:
const g: {| a: string, b: string |} = { ...a, ...b };
```

[Try Flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagIKgLygDeAPqAIYBcoAzsgE4CWAdgOagkC+A3ChtgCECxUACNqdJm1A9EiACaYAxtHL1sANzUVqOXopVrN28aAG9ES2MzqglwoqAB0L8jN5WbyUPIfOXou6W1rbYhI4uTuQANP5OgbKetpDUjlS0DCyssaaSWTJ+kTFxCbwgoAAqABaMNHbkNNiZrKyY9HXkzKBt9LD0lMFeoKypZOl5bDkSmdJcha6xkaWIQA)

However, I have also identified a couple other (unrelated?) behaviours that I believe to be bugs:

```javascript
// @flow
type A = {| a: string |};
type B = { b: string };

declare var a: { ...A, ...B };

// Why has b been inferred to be an optional property?
const x: string = a.b;
```

[Try Flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagIKgLygDeAPqAIYBcoAzsgE4CWAdgOagkC+A3ChtgCECxUACNqdJm1A9EiACaYAxtHL1sANzUVqRUADpDOADQHDQ2YhCgA6gAtUoO+RpixmTM1AtImeuvkKV3IvWHRkRlhmcmhQdHowvzQAfkQlKLpQAA8JBhZ2QnJ9UV4gA)

```javascript
// @flow
type A = {| a: string |};
type B = { b: string };

declare var a: { ...A, ...B };

// Why has b been inferred as an optional property?
const x: string = a.b;
```

[Try Flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagIKgLygDeAPqAIYBcoAzsgE4CWAdgOagkC+A3ChtgCECxUACNqdJm1A9EiACaYAxtHL1sANzUVqRUADpDOADQHDQ2YhCgA6gAtUoO+RpixmTM1AtImeuvkKV3IvWHRkRlhmcmhQdHowvzQAfkQlKLpQAA8JBhZ2QnJ9UV4gA)

**Comment by valscion** [comment] 2017-10-18 12:40
> It seems to be very specifically that trying to pass the result of spreading an inexact and exact type to something expecting an exact type that will trigger an error.

That is true :+1:

The thing that is broken seems to be spread of two exact object types not being exact anymore:

```js
// @flow
type A = {| a: string |};
type B = { b: string };
type C = {| c: string |};

declare var a: A;
declare var b: B;
declare var c: C;

const d = { ...a };
const e = { ...b };
const f = { ...a, ...b };
const g: { a: string, b: string } = { ...a, ...b };
// This case triggers an error, as it should:
const h: {| a: string, b: string |} = { ...a, ...b };
// This case should not trigger an error, but it does
const i: {| a: string, c: string |} = { ...a, ...c };
```

[Try Flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagIKgLygDeAPqAIYBcoAzsgE4CWAdgOagkC+A3ChtgCECxUACNqdJm1A8+WUAGFhpUAGMJDFuy69EAE0yro5etgBuJitRy8DRk+cvjQA24eOnQF+muoLdqrDMdKB6yqAAdFHkMryBwcig2IREkVGisYjxIZDhURHkADRpERmy2Yms1KlUtJpsxc6SWjJ50cX5ZbwgoAAqABaMNGrkNNiarKyY9MPkzEn09LD0xaOgjIk0-bAArtB6lFlBIf3VZLXNDWIaUtqcbQUd6Zk9A0MjY7Tbe2HMsIkTKY+OYLJYrMQ7RIbUKwTA0I4JdZnKx1W7FdSolpcB5FEqqTJAA)

**Comment by ajhyndman** [comment] 2017-10-18 14:17
Ah right.  Again, it's not the spreading itself that errors, but inferring that the result is exact that it fails to do.

```javascript
// @flow
type A = {| a: string |};
type B = { b: string };
type C = {| c: string |};

declare var a: A;
declare var b: B;
declare var c: C;

// Now this case doesn't trigger an error:
const i: { a: string, c: string } = { ...a, ...c };
```

[Try Flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagIKgLygDeAPqAIYBcoAzsgE4CWAdgOagkC+A3ChtgCECxUACNqdJm1A8+WUAGFhpUAGMJDFuy69EAE0yro5etgBuJitRy8DRk+cvjQA24eOnQF+muoLdIKAAKgAWjDRq5DTYNCGwAK7QeqDMsMigmqysmD7kzKA59LD0ADRi8emM6XqwmDSIqrDMdKCM1ERWtJpsZepdUuycyqAAdGPkZWMjqjK8QA)

**Comment by valscion** [comment] 2017-10-18 14:39
> Again, it's not the spreading itself that errors, but inferring that the result is exact that it fails to do.

Yeah, I get what you're saying. Maybe the issue title / description could be clarified to tell this story in a more clear way?

Maybe "ES6 object spread over exact object type incorrectly marks the resulting object as inexact" could be better?

**Comment by szagi3891** [comment] 2017-10-18 18:54
> Maybe "ES6 object spread over exact object type incorrectly marks the resulting object as inexact" could be better?

That is definitely bad behaviour.

**Comment by cprodescu** [comment] 2017-11-19 19:09
@samwgoldman Do you have any advice for someone trying to take a stab at this in the code-base? (files to start exploring, etc)

**Comment by vicapow** [comment] 2017-11-20 05:20
I would also appreciate any documentation on making it easier to contribute  to the flow codebase for this and other issues

**Comment by lloiser** [comment] 2017-11-30 09:50
In my project I have created a tiny helper function that looks like this:

```js
const assign = <T>(a: T, ...b: $Shape<T>[]): T => Object.assign({}, a, ...b)
```

You can see it in action here: [Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVATApgYxgQwCcswAXATwAcSAxOOAISLAF4wBvAH1TDCnoBcYAM6lCASwB2AcwA0PMACMiQ0RJmpOAX3Q44k0WHzDh46ZNZgAPABUAfAAp8Qm7LAA6T4qEASAMoAFvjUtnYA2gC6AJQurHZgAPKKAFa4pO7GpuYO7Fpu+G6e7opRuvqGUIoAjEJ0jMxs7HyCYABE-HCtbsqEQq09rWA6qMDAYAhwhADWwgCEqHoGpHyKAEy19EyElplmkg6VVW5NHX2SWEgdg1qlixWKAMwb9dtsu9mVq8dKKm3nSAMhrdystKgAWZ5bHYmPYHR7fU5-C7NOBgVZdH69JEA5jooELEErACskIaRhhH0UYOONwJSxWADZSa9yVl9pUiQiWq1-iiwA9rt8emdkT1+ddSiMxlB8OIYHM6fcAOzM6FsuGcjgooRVfF3UGKAAcqreFPZik1TWUAC8+jaJYqDQBOE2s2EcrlwEWXegYm12-DWh1AA)

**Comment by Emobe** [comment] 2017-12-11 14:20
What is the current workaround for this? Any progress?

**Comment by skovhus** [comment] 2017-12-13 22:05
@mroch @samwgoldman What can we do to help here? Should we just use exact types? Please advice.

**Comment by cprodescu** [comment] 2018-01-06 07:53
This is the top issue in terms of 👍s: https://github.com/facebook/flow/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

Looking forward to when it will be prioritized :)

**Comment by villesau** [comment] 2018-01-10 13:32
This is easily the most frustrating bug preventing us from using exact types and causing uncertainty around Flow.

**Comment by georggrubner** [comment] 2018-01-17 16:23
+1

**Comment by jdelStrother** [comment] 2018-02-01 16:25
@lloiser's workaround isn't workable with covariant properties, right?  https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwDK6AhuvgLxgDeAPqmGANRRxwBcYAzugE4CWAOwDmqGgF9UqKAFcBAY3R84Arujg9cACm6lcHIroCU+kmWr0wG9NJ4qA8gCMAVrgUA6Yp058hAzVTEAGlVdYKoWdjAAIgdiAC8osUNUCUlgYDAAQS8fFQALXBg8Hi5pISFcblwAEzBBMDz0dGxONnShPnQ86Qc3OTgAW2AoYjlcB1YAa2H4BGA+L2lK4AAmABYABgBWAGIFziX+gYHcAXQAWgBmNYAOAEZLgHY7u63UfoFuME9vXzBKAA8ABUAHyaYgcIHBNwwhwcAAkBDyxDwwJBAG0ALrGMBA-4gsCOFzuH65fxBb7Q2HJGTyRTKVTqXAAfQAbittKY9IQuTiDGYqBYrDYVKTfJzQtQIhwYvFEskxEA

**Comment by Dbuggerx** [comment] 2018-02-04 21:24
+1

**Comment by joshuawu** [comment] 2018-02-06 20:15
This workaround should work for all of you.
```javascript
function reduce<T: {}>(object: T, ...rest: Array<$Shape<T>>): T {
  return Object.assign((({}: any): T), object, ...rest);
}

const foo: {|a: number, b: number|} = {a: 0, b: 1};
const bar: {|a: number, b: number|} = reduce(foo, {b: 20}, {a: 10});  // no errors
console.log(bar);  // {a: 10, b: 20}
```

**Comment by jdelStrother** [comment] 2018-02-08 15:50
@joshuawu still no luck with covariant properties though :(
https://flow.org/try/#0GYVwdgxgLglg9mABAJwKYBMQVQHgCoBciA3gL4B8AFHAEYBWq0ReANIgHSdoDOURAgsmQBDAJ44AJAGUAFsIAOuPOXIBKZiQBQiFKighkSAPL1GUdsO7cYAczCUHZIsLCj1iPKra0G0Np3YeKFUAbk1STU0IBF5EYDg4ImIAHwBqYSIwEABbGlRkNlSaTJy85GTSRABeEgzEAAY2YsQARlIw6LBYmmFkJLS6rNz8wuahsorq3UxsSni4NmJmgCZ60kW6lrXQnQB6XcQwOER85DhkbiiYuAAbVHYbuBtKHuQdxH3aoi2molXSIA


```js
function reduce<T: {}>(object: T, ...rest: Array<$Shape<T>>): T {
  return Object.assign((({}: any): T), object, ...rest);
}

const foo: {|+a: number, +b: number|} = {a: 0, b: 1};
const bar: {|+a: number, +b: number|} = reduce(foo, {b: 20}, {a: 10});  // Covariant property `a` incompatible with contravariant use
console.log(bar);  // {a: 10, b: 20}
```

**Comment by ggregoire** [comment] 2018-02-08 16:44
@joshuawu I guess none of us here wants to replace object spread by a function wrapping `object.assign`.

We shouldn't have to change our code because of a bug in Flow's typechecking.

**Comment by denizdogan** [comment] 2018-02-12 15:21
Given that both Redux and Flow are Facebook projects and that this code pattern is so common, I'm surprised to see this hasn't been solved yet. It's been about 1.5 years since the issue was opened and while I have no choice but to continue using Flow for the project I'm working on, I can understand why people are moving away from Flow to other static type solutions.

**Comment by Andarist** [comment] 2018-02-12 15:59
@denizdogan redux is not facebook's project. In fact from what I know it's not even used inside facebook (at least not at scale).

**Comment by denizdogan** [comment] 2018-02-12 16:51
@Andarist My bad, I just assumed it was FB because it's reactjs/redux!

**Comment by TrySound** [comment] 2018-02-12 18:23
@denizdogan reactjs is community org

**Comment by MaxInMoon** [comment] 2018-03-10 17:06
**src/actions/index.js**

```js
/* @flow */
import * as formActions from './formActions';
import * as searchActions from './searchActions';

export default {
  ...formActions,
  ...searchActions,
};
```


** where action is used**

```js
```

**Comment by MaxInMoon** [comment] 2018-03-10 17:25
I'm facing the same problem exporting actions like written below (with spreaded imports in `actions/index.js`).
Do you think it is related to the issue?

Thanks

_______________

**`/src/actions/searchActions.js`**

```js
/* @flow */

type SearchChangeActionType = {
  +type: string,
  name: string,
  value?: string,
};

export const searchInputChange =
  ({ name, value }: SearchInputType): SearchChangeActionType => {
    return {
      type: actionsTypes.SEARCH_INPUT_CHANGE,
      name,
      value,
    };
  };


```

**`/src/actions/index`**

```js
/* @flow */
import * as formActions from './formActions';
import * as searchActions from './searchActions';

export default {
  ...formActions,
  ...searchActions,
};
```


**In a component**

```js
/* @flow */
import actions from '../../actions';
import type { DispatchType } from '../../types';


...
const mapDispatchToProps = (dispatch: DispatchType) => {
  return {
    onSearchChange: (value: string) => {
      dispatch(actions.searchChange({ // ---------> NO ERROR if i replace the arg by a number
        name: 'users',
        value: 'Tony',
        unWanted: 'foo', //----------------------> NO ERROR
      }));
    }
  };
};

```

**Comment by TrySound** [comment] 2018-03-10 18:08
@MaxInMoon Try this
```js
export * from './formActions';
export * from './searchActions';
```

**Comment by MaxInMoon** [comment] 2018-03-10 19:28
@TrySound thanks for the response. It's works perfecly but it force to import and use actions like so:

```js
import { myAction } from './actions';
```
But for actions I largely prefer:

```js
import actions from './actions';

// actions.myAction()

```

**Comment by TrySound** [comment] 2018-03-10 19:31
@MaxInMoon And this
```js
import * as actions from './actions';
// actions.myAction()
```

**Comment by MaxInMoon** [comment] 2018-03-10 19:37
@TrySound 👍 thanks!

Should we consider the use of `import * as actions from './actions';` instead of `import actions from './actions';` (to preserve actions type checking) as a bug? 
If no it could be good to add a note on the doc, no?

**Comment by TrySound** [comment] 2018-03-10 20:00
It's how you should use imports. Using spread operator with module namespaces is probably not considered case in flow. In any case it's a hack and should be avoided since you have a better tool.

**Comment by vjpr** [comment] 2018-03-10 20:40
Surely this is a showstopper for many people. Can't believe its >1 year old issue.

```
type Message = {| foo: number |}

const opts = {foo: 1}
const message: Message = {...opts, bar: 1}

// No error.
```

**Comment by vjpr** [comment] 2018-03-10 21:07
Also, if you spread with an untyped value (`flow weak`), it disables the exact check.

```
type Message = {| foo: number |}

function bar(): Message {
  const opts = somethingUntyped
  const message = {...opts, bar: 1}
  return message
}

// No error.
```

I would expect a warning at the very least...

**Comment by mandx** [comment] 2018-03-10 23:44
@vjpr Can you try running the `flow` command with the `--include-warnings` flag? Flow does have warnings for quite a few situations, but most of those warnings are disabled/silenced. For example, that snippet should trigger the `unclear-type` warning if you add this to your `.flowconfig`:
```
[lints]
; Triggers when you use any, Object, or Function as type annotations. These types are unsafe.
unclear-type=warn
```

**Comment by vjpr** [comment] 2018-03-11 09:38
@mandx Did not show any warnings.

**Comment by valscion** [comment] 2018-03-23 15:09
> I noticed that the trick mentioned [here](https://github.com/facebook/flow/issues/2386#issuecomment-351589094) seems to allow for spreading on an exact-ish type as well.

It works... somewhat. However, we lose the type safety when we spread an inext object type to the "exact-ish type", and then all bets of which extraneous keys there are, is off.

```js
// @flow

// Type A is an "exact-ish object type"
type A = { a: string, [any]: empty };
// Type B is our good ol' inexact object type
type B = { b: string };
// Type C is also an "exact-ish object type"
type C = { c: string, [any]: empty };

declare var a: A;
declare var b: B;
declare var c: C;

const d = { ...a };
const e = { ...b };
const f = { ...a, ...b };

// This case has always worked
const g: { a: string, b: string } = { ...a, ...b };

// This case SHOULD trigger an error -- We can't guarantee that the
// non-exact object `b` does not have other keys besides `b` set
const h: { a: string, b: string, [any]: empty } = { ...a, ...b };

// This case should not trigger an error, as both `a` and `c` have
// defined with the `[any]: empty` hack that they don't have other
// keys besides `a` and `c` set to strings.
const i: { a: string, c: string, [any]: empty } = { ...a, ...c };
```

[Try Flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQiSgCoE8AOBTUBBUASwGdQBDAO1ACIcAPcgYwBcBaUgC1FgCMArHK1AtsOGolG4CoALygA3hQBcoEiwBORSgHMANKADaVDAF1VOALZZRoAL4BuFGEzSAQsTKwArhtA7YWAATHmgAcmJKBmYWHgEhWKkcSTFQD3klXlV1LV17J1RXPABhTwpoElgKajpGVg4Sbj5BYSSJJNBSjNAmbM1tfSMTc1ArGwx85CChaHINPAA3OZUCJ2mmWfnQJb8stLWZucXl3s6nRCZYSnVQEO6AOkfyScvr2LwHx94Xq5vIOUUoEe93IBmB30cyEKnFIPXIJDwnHh5Xg5AwZHgsA0AGscEELr9YjpVEpyH1coM9jkBvYAUpgaCgV9Js50DCyEx4XgAMoACQA8gBVAAyABERFodDocH4qKMNBosaA2GxQAB1PCcyhhIneOZUFg4PAsJGJTjJVCUK5saLCZoJUAAA14jtusBwZCtsSRCzwsBNMtAuPRoF4HqI0zIztdCJYBLeoE4JJW1N0Bip-TTQ0oZgs1lsdjpTJBYOZkNZaHZcIRak4PmgIS9EqIUsDcplio0BmRvH93Ed5FdVBCjqYrp9FrA00g2jxoHgRBNInNTuMOZGY1E4+Y2OX5DNOAmQSuOsT5F9PADGlZwbIYZIEY9TsH1RHY7UOESVVTOhI93jNxEMmZJqJmgynD+Bhrrmoz5hMhafCWxZMJMQA)

**Comment by cprodescu** [comment] 2018-04-03 17:00
Another work-around for this (credit to #5551):
```
type Foo = {| a: number |};

const x: Foo = { a: 2 };

const x1: Foo = {...x};                              // error
const x2: Foo = Object.freeze({...x});               // works as expected
const x3: Foo = {...x, a: 23};                       // error
const x4: Foo = Object.freeze({...x, a: 23});        // works as expected
```
[Try](https://flow.org/try/#0C4TwDgpgBAYg9nKBeKBvAPlAhgLigOwFcBbAIwgCcp0BfAbgCgGBjOfAZ2CgA895EUqbHgBMUek1Ycu3AIx8EyNADpV3elE1btO3Xs0B6A1EoU4FFm048RCgVADypAFYRmwZQDMKECAC8IAApUVWV1AEo6fT0jKAB3cwBrdmwUiG5IdwgAE0tpHgBmOyUQtQAaYSgRAo1ouq1Y03M8624AFmKUJ1d3Lx9-INKwitwqmsj9WISKZNSTDLdgHKA)

**Comment by apolishch** [comment] 2018-04-04 14:07
Any progress on this issue?

**Comment by niieani** [comment] 2018-04-06 07:46
It's happening: https://github.com/facebook/flow/commit/1916b7d392feb254eb6ecdf392ad9c93651dd070!

![dancing](https://user-images.githubusercontent.com/563469/38408826-6f10c87e-397f-11e8-86be-6ca36e5808ae.gif)

**Comment by valscion** [comment] 2018-04-06 08:00
> It's happening: 1916b7d!

Super awesome! Unfortunately that is a bit too lax, though:

```js
// @flow
type A = {| a: string |};
type B = { b: string };
type C = {| c: string |};

declare var a: A;
declare var b: B;
declare var c: C;

var b: B = { b: 'foo', j: 'I am an extra property!' };

const d = { ...a };
const e = { ...b };
const f = { ...a, ...b };
const g: { a: string, b: string } = { ...a, ...b };
// This case SHOULD trigger an error, but it does not!!
const h: {| a: string, b: string |} = { ...a, ...b }; 
// This case should not trigger an error
const i: {| a: string, c: string |} = { ...a, ...c };
```

[Try Flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagIKgLygDeAPqAIYBcoAzsgE4CWAdgOagkC+A3ChtgCECxUACNqdJm1A8+WUAGFhpUAGMJDFuy69EAE0yro5etgBuJitRy8DRk+cvjQA24eOnQF+muoLd3mLUQoREQaAA5JCwsBEANKAAVtQRAJIUALYUzKCYAB4M5KDo9LBY9GgAhBEyuqqwzHSgesqgAHQdRbL1jci5rR1torWIPU2QA50Jg8PdDU2s1GFUtJpsCc6SWjKTbeTTHbO8IKAAKgAWjDRq5DTYAMoAEgDyAKoAMgAioJqsrJg+cg5AGlegbACufUYfT0sEw12YsGQlUqo3mfXOSzIKy263CuO0nF2+3ah1qoEQJwuVxud1o51g4OgLURfV+-0BwPooLRvVAjCxVlWUlYCXUwu2XGJBzaqlqQA)

**Comment by AlexanderShushunov** [comment] 2018-04-24 09:06
It does not work in JSX (

[Try](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdMAnmFnAArFjoC8cA3gB86ASBjAYAGywAuOKhhRgAOwDmdQQF8GzVnACiADxicI3OHyF04NuADoHp7gBprtlQBMshucoCuIABGWFAamvR0uBDKCihyTrwC4lKy5GTaUTHwgXJGJlyJ-A52yM5wnt5yAIyacAD0dXAAkvAA7tAA1qgAhAyZsQDCABbAkh4WcAAU3vlmqLnGCQCUFgB8cP6SkhH98OzIlMrwfJNgBfEFKzzrADzDo+NFDmdztRWGPPw19av0QA)

**Comment by TrySound** [comment] 2018-04-24 09:08
@AlexanderShushunov It should work in 0.71.
https://github.com/facebook/flow/commit/357ef4fe477978eebd9212a53fcc5e0de67cec08

**Closed** 2018-05-22 00:58 UTC
Labels: Typing: spread, bug

**Comment by 0x24a537r9** [comment] 2018-06-06 22:36
@mrkev Should this have been closed when @valscion raised a valid bug in the fix?

**Comment by mrkev** [comment] 2018-06-07 15:55
Ah, yeah, lets open a new one for that 👍

**Comment by rattrayalex-stripe** [comment] 2018-06-07 17:14
^ opened: https://github.com/facebook/flow/issues/6425

**Comment by dancrumb** [comment] 2018-09-06 17:43
I've opened https://github.com/facebook/flow/issues/6854 to address the fact that this is still a problem with interfaces
