### ISSUE TITLE
Regression since 0.89.0 (Maybe types for objects)

### ISSUE THREAD

**Issue by debel27** [facebook/flow#7463] opened 2019-02-10 15:24 UTC
Flow version: 0.89.0 and above

## Expected behavior

The doc on [_Maybe Types_](https://flow.org/en/docs/types/maybe/) states the following

> In the case of objects, a **missing** property is not the same thing as an explicitly `undefined` property.
> ```js
> // @flow
> function acceptsMaybeProp({ value }: { value: ?number }) {
>  // ...
> }
>
> acceptsMaybeProp({ value: undefined }); // Works!
> acceptsMaybeProp({});                   // Error!
> ```

I would therefore expect an error on `acceptsMaybeProp({});`

## Actual behavior

From [v0.89.0](https://github.com/facebook/flow/releases/tag/v0.89.0), Flow doesn't trigger an error for missing properties anymore.

```js
function acceptsMaybeProp({ value }: { value: ?number }) {
  // ...
}

// until v0.88.0 : KO (as expected)
// from v0.89.0 : OK (possible regression)
acceptsMaybeProp({});
```

[Try it out here](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoKBXAdgYwC4CWcWYAhjjgKYAOeAzgLKkCeARpQAoBOc1AFAG8wAN1IwMlMAF8AXGCGjxlOQH4sGALbsu0gJTzUYMMGBgAdBdRTUqclVqMW7br0EixEudgAmlKASxKbz0AbmNTAHU4LgBrOgBCWwoaeiY2Th5+ASldMKMjIA).

It seems that React elements [are not affected](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gFSgCGAzqAEoCmRAxnpFrKqAORbV0sDcikArgDs6yWANABZAJ4BhJpgGUBOABTpG6EgC5QAbxJNKABXXaA-AL6oARpSwBfAJS7EoUOxx8sYi9Gg87iCCgANIA8og0oiR4qDJyooo4AKLQoAC8oAA8UrIYCUqgwAB8XEA).

**Comment by vtereshyn** [comment] 2019-02-10 16:06
`someProp?: number` - says that you can not have your `someProp`, so it can be undefined
`someProp: ?number` - says that your `someProp` can be null. 

Maybe you need first case?

https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gFSgCGAzqAEoCmRAxnpFrKqAORbV0sDcikArgDs6yWANABZAJ4BhJpgGUBOABTpG6EgC5QAbxJNKABXUB+bQL6oARpSwBfAJS7EoUOxx8sYi9Gg87iCCgANIA8og0oiR4qDJyooo4AKLQoAC8oAA8UrIYCUqgwAB8XEA

**Comment by debel27** [comment] 2019-02-10 20:51
I was pointing out that `someProp: ?number` worked as expected, but I realize from your answer that my original post was misleading. 

I have updated my post to focus on the real issue, which is : 

```js
function acceptsMaybeProp({ value }: { value: ?number }) {
  // ...
}

// until v0.88.0 : KO (as expected)
// from v0.89.0 : OK (possible regression)
acceptsMaybeProp({});
```

**Comment by dsainati1** [comment] 2019-02-11 17:26
cc @avikchaudhuri

**Comment by dsainati1** [comment] 2019-02-11 17:27
I think this is a duplicate of #7456

**Closed by dsainati1** 2019-02-11 17:27 UTC
Labels: bug
