### ISSUE TITLE
Not supported: destructuring + union type + default 

### ISSUE THREAD

**Issue by mgtitimoli** [facebook/flow#4101] opened 2017-06-05 23:37 UTC
Hi there,

I've just tried to do what I described in the title, that's basically the following:

```javascript
// @flow

type Param = boolean | string;

const fn = ({param = true}: {param: Param}) => param;
``` 

And I got the following errors:

```
5: const fn = ({param = true}: {param: Param}) => param;
                ^ boolean. This type is incompatible with
5: const fn = ({param = true}: {param: Param}) => param;
                ^ string
5: const fn = ({param = true}: {param: Param}) => param;
                ^ string. This type is incompatible with
5: const fn = ({param = true}: {param: Param}) => param;
                ^ boolean
5: const fn = ({param = true}: {param: Param}) => param;
                        ^ boolean. This type is incompatible with
5: const fn = ({param = true}: {param: Param}) => param;
                ^ string
```

(you can try it by yourselves [here](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1ABQIYBO+AtqALygBGss0W+AdqAD6gDOKhAlowOYBuZAGNYjTqEjNKACgDeGIqQqguAVywBfAFygFSkroLESmgJQUAfKEUmBQA))

IMHO, this should work, or am I doing something wrong?

Thanks.

**Comment by goodmind** [comment] 2019-02-13 21:45
Duplicate of #2093

**Closed by goodmind** 2019-02-13 21:45 UTC
