### ISSUE TITLE
Flow does not infer type on spread

### ISSUE THREAD

**Issue by pronebird** [facebook/flow#7048] opened 2018-10-19 13:26 UTC
Flow is a little dumb when it comes to spread.

```
// @flow

const data = {
  event: ((): string => { return 'archive' })(),
  createdAt: +Date.now(),
  id: 1,
};

(data: {
 event: string,
 createdAt: number,
 id: number,
});

({
  ...data,
  event: 'archive',
  createdAt: new Date(data.createdAt),
}: {
  event: 'archive',
  createdAt: Date,
 id: number,
})
```

Gives the following output:

```
15: ({
     ^ Cannot cast object literal to object type because number [1] is incompatible with `Date` [2] in property `createdAt`.
References:
11:  createdAt: number,
                ^ [1]
21:   createdAt: Date,
                 ^ [2]
15: ({
     ^ Cannot cast object literal to object type because string [1] is incompatible with string literal `archive` [2] in property `event`.
References:
10:  event: string,
            ^ [1]
20:   event: 'archive',
             ^ [2]
```

Wat? 🤔

**Comment by wchargin** [comment] 2018-10-19 17:55
Duplicate of #6108.

**Closed** 2019-02-03 02:33 UTC
